# Read Selcen

In [1]:
### run 1

import pandas as pd
import numpy as np
import os
import re

selcen = pd.DataFrame()
for i in os.listdir('Settlement Project\Lazada\Seller Centre/'):
    print(i)
    if '$' not in i:
        if 'csv' in i:
            temp = pd.read_csv('Settlement Project\Lazada\Seller Centre/' + str(i), sep = ';')
        elif 'xlsx' in i:
            temp = pd.read_excel('Settlement Project\Lazada\Seller Centre/' + str(i))
            test = [' '.join(re.sub( r"([A-Z])", r" \1", x).split()).title() for x in temp.columns]
            test = [str(x).replace('Sku', 'SKU') for x in test]
            temp.columns = test
            temp = temp.rename(columns = {'Create Time' : 'Created at'})
            temp = temp[~temp['Order Item Id'].isin(selcen['Order Item Id'])]
        temp['Source'] = i
        true_col = ['Order Item Id', 'Order Type', 'Order Flag', 'Lazada Id', 'Seller SKU', 'Lazada SKU', 'Created at', 'Updated at', 'Order Number', 'Invoice Required', 'Customer Name', 
                    'Customer Email', 'National Registration Number', 'Shipping Name', 'Shipping Address', 'Shipping Address2', 'Shipping Address3', 'Shipping Address4', 'Shipping Address5', 
                    'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping City', 'Shipping Postcode', 'Shipping Country', 'Shipping Region', 'Billing Name', 'Billing Address', 
                    'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing City', 'Billing Postcode', 
                    'Billing Country', 'Payment Method', 'Paid Price', 'Unit Price', 'Shipping Fee', 'Wallet Credits', 'Item Name', 'Variation', 'CD Shipping Provider', 'Shipping Provider', 
                    'Shipment Type Name', 'Shipping Provider Type', 'CD Tracking Code', 'Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)',
                    'Tracking URL (first mile)', 'Promised shipping time', 'Premium', 'Status', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID', 'Bundle Discount',
                    'Refund Amount', 'Source']
        if temp.columns.to_list() == true_col :
            print('Column sama')
        else :
            true_col2 = ['Order Item Id', 'Order Type', 'Guarantee', 'Delivery Type','Lazada Id', 'Seller SKU', 'Lazada SKU', 'Ware House', 'Created at','Update Time', 
                         'Rts Sla', 'Tts Sla', 'Order Number', 'Invoice Required','Invoice Number', 'Delivered Date', 'Customer Name', 'Customer Email',
                         'National Registration Number', 'Shipping Name', 'Shipping Address','Shipping Address2', 'Shipping Address3', 'Shipping Address4','Shipping Address5', 
                         'Shipping Phone', 'Shipping Phone2', 'Shipping City', 'Shipping Post Code', 'Shipping Country','Shipping Region', 'Billing Name', 'Billing Addr', 
                         'Billing Addr2','Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone','Billing Phone2', 'Billing City', 'Billing Post Code',
                         'Billing Country', 'Tax Code', 'Branch Number', 'Tax Invoice Requested','Pay Method', 'Paid Price', 'Unit Price', 'Seller Discount Total',
                         'Shipping Fee', 'Wallet Credit', 'Item Name', 'Variation','Cd Shipping Provider', 'Shipping Provider', 'Shipment Type Name','Shipping Provider Type', 
                         'Cd Tracking Code', 'Tracking Code','Tracking Url', 'Shipping Provider F M', 'Tracking Code F M','Tracking Url F M', 'Promised Shipping Time', 
                         'Premium', 'Status','Buyer Failed Delivery Return Initiator','Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail',
                         'Buyer Failed Delivery User Name', 'Bundle Id', 'Bundle Discount','Refund Amount', 'Source']
            if temp.columns.to_list() == true_col2 :
                print('Column sama')
            else:
                print('Column beda')
                print([x for x in true_col if x not in temp.columns.to_list()])
                print([x for x in temp.columns.to_list() if x not in true_col])
        selcen = selcen.append(temp, ignore_index = True, sort = False)

01 Seller Centre-1-7 Jan Lazada.csv
Column sama
01 Seller Centre-15-21 Jan Lazada.csv
Column sama
01 Seller Centre-22-28 Jan Lazada.csv
Column sama
01 Seller Centre-29-31 Jan Lazada.csv
Column sama
01 Seller Centre-8-14 Jan Lazada.csv
Column sama
02 Seller Centre-1-7 Feb Lazada.csv
Column sama
02 Seller Centre-15-21 Feb Lazada.csv
Column sama
02 Seller Centre-22-28 Feb Lazada.csv
Column sama
02 Seller Centre-8-14 Feb Lazada.csv
Column sama
03 Seller Centre-1-7 Mar Lazada.csv
Column sama
03 Seller Centre-15-21 Mar Lazada.csv
Column sama
03 Seller Centre-22-28 Mar Lazada.csv
Column sama
03 Seller Centre-29-31 Mar Lazada.csv
Column sama
03 Seller Centre-8-14 Mar Lazada.csv
Column sama
04 Seller Centre-1-7 Apr Lazada.csv
Column sama
04 Seller Centre-15-21 Apr Lazada.csv
Column sama
04 Seller Centre-22-28 Apr Lazada.csv
Column sama
04 Seller Centre-29-30 Apr Lazada.csv
Column sama
04 Seller Centre-8-14 Apr Lazada.csv
Column sama
05. Seller Cemtre 29-31 Mei Lazada.csv
Column sama
05. Seller Centre 1-7 Mei Lazada.csv
Column sama
05. Seller Centre 15-21 Mei Lazada.csv
Column sama
05. Seller Centre 22-28 Mei Lazada.csv
Column sama
05. Seller Centre 8-14 Mei Lazada.csv
Column sama
06 Seller Centre-1-6 Jun Lazada.csv
Column sama
06 Seller Centre-14-20 Jun Lazada.csv
Column sama
06 Seller Centre-21-27 Jun Lazada.csv
Column sama
06 Seller Centre-28-30 Jun Lazada.csv
Column sama
06 Seller Centre-7-13 Jun Lazada.csv
Column sama
07 Seller Centre-1-7 Jul Lazada.csv
Column sama
07 Seller Centre-15-21 Jul Lazada.csv
Column sama
07 Seller Centre-22-29 Jul Lazada.csv
Column sama
07 Seller Centre-8-14 Jul Lazada.csv
Column sama
072ed5396b43e4a9a02045a5efbcc02d.xlsx
Column sama
0d7c287d37501a5c4b0c1babfbc50de8.xlsx
Column sama
11-0106-b81a79b5d5cd377255f02a99a92fe1ff.xlsx
Column sama
11-0713-a68716f868702a2ecd94510d20b8e492.xlsx
Column sama
11-1420-c469cfaa037f9b050ea005730be2b300.xlsx
Column sama
11-2127-61e64a85a42160f68c86b7bfd3d08ac9.xlsx
Column sama
11-2830-8ce085f48a2f834559161e112b05666c.xlsx
Column sama
12-0104-1a6975513a2d4e5c745c3fa5628a2436.xlsx
Column sama
12-0511-c204b8f66ca84193125f5921d2d0ceeb.xlsx
Column sama
12-1214-530ad9413a8dbb3839664f0d6e6738b9.xlsx
Column sama
12-1518-8602de216c78f8fa54692780a9c7cfae.xlsx
Column sama
12-1925-30492fe7907126d3c98046065671d835.xlsx
Column sama
12-2631-57cf4ae1b20233cfc0d8a5aa5625571d.xlsx
Column sama
132b2e43af1f7843f94e0130884aa531.xlsx
Column sama
2e5dfc48f43e793bca65f6cebb535b41.xlsx
Column sama
30f831349d3be58cc9345bc88738b1e8.xlsx
Column sama
35c923ddd483a4cbf417c6017672846d.xlsx
Column sama
41b65704ba6b7ae71eddbdff084ce208.xlsx
Column sama
54c46a1f072da1b79029314974760714.xlsx
Column sama
6ac70585036b6953c07e216337264562.xlsx
Column sama
7d7660b01a452d29ad6e1b6bcbdc9c76.xlsx
Column sama
9a054b447d0cb9e2ca550c4527a1f75e.xlsx
Column sama
9dd06223ed9e8e481adf614a2b6d5928.xlsx
Column sama
9f17233bc1649dfcb8c52b2f63e09c6f.xlsx
Column sama
a08394a2629c8b5f28ad735d451e8d7c.xlsx
Column sama
a3ad3eb8fbce4eb4390065ecf26885fd.xlsx
Column sama
ae7299a74876e5ee17043c265d1bbefb.xlsx
Column sama
af3afe6449a2c815f4473aa36801c54c.xlsx
Column sama
Apr 25-27 Apr.xlsx
Column sama
Apr 28-30 Apr.xlsx
Column sama
Aug 1-3 May.xlsx
Column sama
Aug 10-12 Aug.xlsx
Column sama
Aug 13-15 Aug.xlsx
Column sama
Aug 16-18 Aug.xlsx
Column sama
Aug 19-21 Aug.xlsx
Column sama
Aug 22-24 Aug.xlsx
Column sama
Aug 25-27 Aug.xlsx
Column sama
Aug 28-31 Aug.xlsx
Column sama
Aug 4-6 Aug.xlsx
Column sama
Aug 7-9 Aug.xlsx
Column sama
b65a556d55bdc75b4a6fded41f4dca1e.xlsx
Column sama
d8bac2b2074f150052f233df92a65a5e.xlsx
Column sama
dce7ec705fadbcc00ddd75c8d908c714.xlsx
Column sama
e14595919633e6189149b52dcf91f255.xlsx
Column sama
e3f3a3a7142acf093e577ff40ba29bf9.xlsx
Column sama
f076e3159d83a9e0453da8d24b52f98c.xlsx
Column sama
fdc75cb387fe1d9a4eb347dfa9512861.xlsx
Column sama
ffb97cb1c35c44bbb5cdc29e0f815015.xlsx
Column sama
Jul 1-3 Jul.xlsx
Column sama
Jul 10-12 Jul.xlsx
Column sama
Jul 13-15 Jul.xlsx
Column sama
Jul 16-18 Jul.xlsx
Column sama
Jul 19-21 Jul.xlsx
Column sama
Jul 22-24 Jul.xlsx
Column sama
Jul 25-27 Jul.xlsx
Column sama
Jul 28-31 Jul.xlsx
Column sama
Jul 4-6 Jul.xlsx
Column sama
Jul 7-9 Jul.xlsx
Column sama
Jun 1-3 Jun.xlsx
Column sama
Jun 10-12 Jun.xlsx
Column sama
Jun 13-15 Jun.xlsx
Column sama
Jun 16-18 Jun.xlsx
Column sama
Jun 19-21 Jun.xlsx
Column sama
Jun 22-24 Jun.xlsx
Column sama
Jun 25-27 Jun.xlsx
Column sama
Jun 28-30 Jun.xlsx
Column sama
Jun 4-6 Jun.xlsx
Column sama
Jun 7-9 Jun.xlsx
Column sama
Mar 11-13 Mar.xlsx
Column sama
Mar 14-16 Mar.xlsx
Column sama
Mar 8-10 Mar.xlsx
Column sama
May 11-13 May.xlsx
Column sama
May 14-16 May.xlsx
Column sama
May 17-19 May.xlsx
Column sama
May 20-22 May.xlsx
Column sama
May 23-25 May.xlsx
Column sama
May 26-28 May.xlsx
Column sama
May 29-31 May.xlsx
Column sama
May 8-10 May.xlsx
Column sama
Seller Center Lazada 20211201-06.xlsx
Column sama
Seller Center Lazada 20211207-12.xlsx
Column sama
Seller Center Lazada 20211213-18.xlsx
Column sama
Seller Center Lazada 20211219-25.xlsx
Column sama
Seller Center Lazada 20211226-31.xlsx
Column sama
Seller Center Lazada 20220101-07.xlsx
Column sama
Seller Center Lazada 20220108-14.xlsx
Column sama
Seller Center Lazada 20220115-21.xlsx
Column sama
Seller Center Lazada 20220122-25.xlsx
Column sama
Seller Center Lazada 20220122-28.xlsx
Column sama
Seller Center Lazada 20220129-31.xlsx
Column sama
Seller Center Lazada 20220201-05.xlsx
Column sama
Seller Center Lazada 20220206-10.xlsx
Column sama
Seller Center Lazada 20220211-15.xlsx
Column sama
Seller Center Lazada 20220216-20.xlsx
Column sama
Seller Center Lazada 20220216-23.xlsx
Column sama
Seller Center Lazada 20220221-25.xlsx
Column sama
Seller Center Lazada 20220225-28.xlsx
Column sama
Seller Center Lazada 20220301-05.xlsx
Column sama
Seller Center Lazada 20220306-10.xlsx
Column sama
Seller Center Lazada 20220311-15.xlsx
Column sama
Seller Center Lazada 20220316-20.xlsx
Column sama
Seller Center Lazada 20220321-25.xlsx
Column sama
Seller Center Lazada 20220326-28.xlsx
Column sama
Seller Center Lazada 20220329-31.xlsx
Column sama
Seller Center Lazada 20220401-05.xlsx
Column sama
Seller Center Lazada 20220406-10.xlsx
Column sama
Seller Center Lazada 20220411-15.xlsx
Column sama
Seller Center Lazada 20220416-20.xlsx
Column sama
Seller Center Lazada 20220421-25.xlsx
Column sama
Seller Center Lazada 20220426-30.xlsx
Column sama
Seller Center Lazada 20220501-05.xlsx
Column sama
Seller Center Lazada 20220506-10.xlsx
Column sama
Seller Center Lazada 20220511-15.xlsx
Column sama
Seller Center Lazada 20220516-20.xlsx
Column sama
Seller Center Lazada 20220521-24.xlsx
Column sama
Seller Center Lazada 20220525-31.xlsx
Column sama
Seller Center Lazada 20220601-05.xlsx
Column sama
Seller Center Lazada 20220606-10.xlsx
Column sama
Seller Center Lazada 20220611-15.xlsx
Column sama
Seller Center Lazada 20220616-20.xlsx
Column sama
Seller Center Lazada 20220621-26.xlsx
Column sama
Seller Center Lazada 20220627-30.xlsx
Column sama
Seller Center Lazada 20220701-05.xlsx
Column sama
Seller Center Lazada 20220706-10.xlsx
Column sama
Seller Center Lazada 20220711-15.xlsx
Column sama
Seller Center Lazada 20220716-20.xlsx
Column sama
Seller Center Lazada 20220721-22.xlsx
Column sama
Seller Center Lazada 20220723-27.xlsx
Column sama
Seller Center Lazada 20220728-31.xlsx
Column sama
Seller Center Lazada 20220801-05.xlsx
Column sama
Seller Center Lazada 20220806-10.xlsx
Column sama
Seller Center Lazada 20220811-15.xlsx
Column sama
Seller Center Lazada 20220816-20.xlsx
Column sama
Seller Center Lazada 20220821-23.xlsx
Column sama
Seller Center Lazada 20220824-31.xlsx
Column sama
Seller Center Lazada 20220901-08.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20220909-13.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20220914-21.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20220922-25.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20220926-30.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20221001-06.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20221007-12.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20221013-18.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20221019-24.xlsx
Column beda
['Order Flag', 'Updated at', 'Shipping Phone Number', 'Shipping Phone Number2', 'Shipping Postcode', 'Billing Address', 'Billing Address2', 'Billing Address3', 'Billing Address4', 'Billing Address5', 'Billing Phone Number', 'Billing Phone Number2', 'Billing Postcode', 'Payment Method', 'Wallet Credits', 'CD Shipping Provider', 'CD Tracking Code', 'Tracking URL', 'Shipping Provider (first mile)', 'Tracking Code (first mile)', 'Tracking URL (first mile)', 'Promised shipping time', 'Cancel / Return Initiator', 'Reason', 'Reason Detail', 'Editor', 'Bundle ID']
['Guarantee', 'Delivery Type', 'Ware House', 'Update Time', 'Rts Sla', 'Tts Sla', 'Invoice Number', 'Delivered Date', 'Shipping Phone', 'Shipping Phone2', 'Shipping Post Code', 'Billing Addr', 'Billing Addr2', 'Billing Addr3', 'Billing Addr4', 'Billing Addr5', 'Billing Phone', 'Billing Phone2', 'Billing Post Code', 'Tax Code', 'Branch Number', 'Tax Invoice Requested', 'Pay Method', 'Seller Discount Total', 'Wallet Credit', 'Cd Shipping Provider', 'Cd Tracking Code', 'Tracking Url', 'Shipping Provider F M', 'Tracking Code F M', 'Tracking Url F M', 'Promised Shipping Time', 'Buyer Failed Delivery Return Initiator', 'Buyer Failed Delivery Reason', 'Buyer Failed Delivery Detail', 'Buyer Failed Delivery User Name', 'Bundle Id', 'Seller Note']
Seller Center Lazada 20221024-25.xlsx
Column beda

In [2]:
### for backup
selcen_ori = selcen.copy()

In [2]:
## for backup
selcen = selcen_ori.copy()

NameError: name 'selcen_ori' is not defined

In [3]:
## for display
pd.options.display.max_columns = 150

In [4]:
## run 2
selcen = selcen.rename(columns = {'Seller SKU' : 'SKU'})
selcen['Qty. Invoiced'] = 1
# selcen['Total Pembayaran'] = selcen['Total Pembayaran'].astype(str).str.replace('Rp', '').str.replace('.', '', regex = False)

selcen['True datetime'] = pd.to_datetime(selcen['Created at'])

# indeks = selcen[selcen['True datetime'].isnull()].index.to_list()
# selcen['True datetime'][indeks] = pd.to_datetime(selcen['Created at'], format = '%Y %b %d %H:%M:%s', errors='coerce')


selcen['Year'] = selcen['True datetime'].dt.year.astype(int)
selcen['Month'] = selcen['True datetime'].dt.month_name()

In [5]:
## check sett month
selcen[['Year', 'Month']].drop_duplicates()

        Year      Month
0       2021    January
18076   2021   February
31716   2021      March
59009   2021      April
87948   2021        May
106992  2021       June
127921  2021       July
151997  2021   November
178127  2021   December
213145  2021     August
236015  2022    January
255206  2022   February
279962  2022      March
308180  2022      April
338973  2022        May
357886  2022       June
379432  2022       July
398668  2022     August
420275  2022  September
444166  2022    October
471522  2022   November
503714  2022   December
527901  2023    January
550153  2023   February
577450  2023      March
621307  2023      April
650649  2023        May
688718  2021  September
706118  2021    October

In [6]:
## run 3
selcen_new = selcen[selcen['Year'] > 2022]

In [7]:
## run 4
temp = selcen_new.groupby(['Order Item Id'], dropna = False)['Source'].nunique().gt(1).reset_index()
temp = temp[temp['Source'] == True]
# selcen_new[selcen_new['Order Item Id'].isin(temp['Order Item Id'])][['Order Item Id', 'SKU', 'Item Name', 'Qty. Invoiced', 'Source']].sort_values('Order Item Id')

In [8]:
## run 5 must null
selcen_new[selcen_new[['Order Item Id']].duplicated(keep = False)]

Empty DataFrame
Columns: [Order Item Id, Order Type, Order Flag, Lazada Id, SKU, Lazada SKU, Created at, Updated at, Order Number, Invoice Required, Customer Name, Customer Email, National Registration Number, Shipping Name, Shipping Address, Shipping Address2, Shipping Address3, Shipping Address4, Shipping Address5, Shipping Phone Number, Shipping Phone Number2, Shipping City, Shipping Postcode, Shipping Country, Shipping Region, Billing Name, Billing Address, Billing Address2, Billing Address3, Billing Address4, Billing Address5, Billing Phone Number, Billing Phone Number2, Billing City, Billing Postcode, Billing Country, Payment Method, Paid Price, Unit Price, Shipping Fee, Wallet Credits, Item Name, Variation, CD Shipping Provider, Shipping Provider, Shipment Type Name, Shipping Provider Type, CD Tracking Code, Tracking Code, Tracking URL, Shipping Provider (first mile), Tracking Code (first mile), Tracking URL (first mile), Promised shipping time, Premium, Status, Cancel / Return Initiator, Reason, Reason Detail, Editor, Bundle ID, Bundle Discount, Refund Amount, Source, Guarantee, Delivery Type, Ware House, Update Time, Rts Sla, Tts Sla, Invoice Number, Delivered Date, Shipping Phone, Shipping Phone2, Shipping Post Code, Billing Addr, Billing Addr2, Billing Addr3, Billing Addr4, Billing Addr5, Billing Phone, Billing Phone2, Billing Post Code, Tax Code, Branch Number, Tax Invoice Requested, Pay Method, Seller Discount Total, Wallet Credit, Cd Shipping Provider, Cd Tracking Code, Tracking Url, Shipping Provider F M, Tracking Code F M, Tracking Url F M, Promised Shipping Time, Buyer Failed Delivery Return Initiator, Buyer Failed Delivery Reason, Buyer Failed Delivery Detail, Buyer Failed Delivery User Name, ...]
Index: []

In [9]:
## check duplicate file
selcen_new[selcen_new['Order Item Id'].duplicated()]['Source'].unique()

array([], dtype=object)

In [10]:
## run 6 must null
cek_dups = selcen_new[(selcen_new[['Order Item Id', 'SKU']].duplicated(keep = False)) & (selcen_new['SKU'].notnull())].groupby('SKU')['Item Name'].unique().reset_index()
( cek_dups.join( pd.DataFrame(cek_dups['Item Name'].to_list())
                 .add_prefix('array_') )
        .drop('Item Name', axis = 1) ).values

array([], shape=(0, 1), dtype=object)

In [11]:
## run 7
indeks = selcen_new[selcen_new['Item Name'] == "(Free Gift) 3pcs L-Men Protein Crunch BBQ Beef 20g"].index.to_list()
selcen_new['SKU'][indeks] = '(B)2309005305P3'

indeks = selcen_new[selcen_new['Item Name'] == 'Buy 2 Get 2 – HiLo School Chocolate RTD UHT 200ml (ED 6 bulan)'].index.to_list()
selcen_new['SKU'][indeks] = '(E)2101492P4'

indeks = selcen_new[selcen_new['Item Name'] == 'Tropicana Slim White Coffee 4 Sachet x 3 pcs - Kopi Susu Nikmat Tanpa Gula Pasir'].index.to_list()
selcen_new['SKU'][indeks] = '2104170164P3'

indeks = selcen_new[selcen_new['SKU'] == '(B)2309005300'].index.to_list()
selcen_new['SKU'][indeks] = '(B)2309005305'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1061: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":

In [18]:
## run 8
temp2 = selcen_new.copy()

import time
import pandas as pd
import numpy as np
import math

import smtplib 
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys
import requests
import os
    
data_SKU = pd.read_excel(r"D:\1. Masterdata\SKU_File\data_SKU.xlsx")

s = requests.Session()
s.get("https://tatanama.pythonanywhere.com")
s.post("https://tatanama.pythonanywhere.com", data = {'username' : 'ecommerce', 'password' : 'ecommerce'})
r = s.get("https://tatanama.pythonanywhere.com/download")

with open(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx", 'wb') as output:
    output.write(r.content)

if os.path.isfile(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx") :    
    SKU_append = pd.read_excel(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx")
    SKU_append.columns = [x.replace('_', ' ') for x in SKU_append.columns]
    data_SKU = data_SKU[~data_SKU['SKU'].astype(str).isin(SKU_append['SKU'].astype(str))]
    data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)

to_excel = data_SKU.to_excel(r"D:\1. Masterdata\SKU_File\data_SKU.xlsx", index = False)

# data_SKU = SKU_append.copy()

data_SKU = SKU_append.append(data_SKU[data_SKU['SKU'].isin(temp2[~temp2['SKU'].isin(SKU_append['SKU'])]['SKU'].drop_duplicates().values)], ignore_index = True, sort = False)

In [19]:
### run 8.1
data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
dfalias=pd.DataFrame()
for i in [x for x in data_SKU if 'Alias SKU' in x]:
    dfaliastemp=data_SKU[data_SKU[i].notnull()][['Real SKU',i]].rename(columns={i:'SKU Alias'})
    # dfaliastemp['SKU Alias']=dfaliastemp['SKU Alias'].astype(str)
    dfalias=dfalias.append(dfaliastemp)
cek=temp2[~temp2['SKU'].isin(data_SKU['Real SKU'].unique())]['SKU'].unique()
# dfalias[dfalias['SKU Alias'].isin(cek)]
for i in cek:
    skualias=dfalias[dfalias['SKU Alias']==i]['Real SKU'].unique()[0]
    selcen_new.loc[selcen_new['SKU']==i,'SKU']=skualias
    # print(skualias)

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [21]:
## must null
# temp2[~temp2['SKU'].isin(data_SKU['SKU'])][['Order Number', 'Item Name', 'SKU']].drop_duplicates('SKU').values
## must null
selcen_new[~selcen_new['SKU'].isin(data_SKU['SKU'])][['Order Number', 'Item Name', 'SKU']].drop_duplicates('SKU').values

array([], shape=(0, 3), dtype=object)

In [22]:
## run 8.2

from datetime import datetime,timedelta
listjanjian=requests.get('http://event.l-men.com/apiv1?type=janjian')
for i in listjanjian.json():
    sku=i['realsku']
    print(sku)
    start=datetime.fromtimestamp(int(i['startdate']/1000)).replace(hour=0)
    end=datetime.fromtimestamp(int(i['enddate']/1000)).replace(hour=23)
    print(i['notes'])
    selcen_new.loc[(selcen_new['SKU']==sku)&(selcen_new['True datetime']>=start)&(selcen_new['True datetime']<end),'Pemilik Budget']=i['notes']
    print('=====')
    # print(str(datetime.fromtimestamp(int(i['enddate']/1000)).replace(hour=0)))

2T00803164
Launching tahap 2
=====
2T00803164P3
Launching tahap 2

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)

=====
2T02703229P2
Launching
=====
PT25T74
Launching
=====
2T02703229
Launching tahap 2
=====
2104115110
Launching tahap 2
=====
2104115110P2
Launching tahap 2
=====
2104148024
Launching tahap 2
=====
2104148024P2
Launching tahap 2
=====
1N01402250P24
Marketing
=====
1N01402250P4
Marketing
=====
2104010270
Marketing
=====
1101909331
Marketing
=====
2T00803164P2
Marketing
=====
2T00803164P3
Marketing
=====
2HF0114021
Launching tahap 2
=====
2101751112
Marketing
=====
2101751112P2
Marketing
=====
2101700166P2
Marketing
=====
2101700166
Marketing
=====
2101384106
Internal
=====
2101384106P3
Internal
=====
2105055180P2
Internal
=====
2104523105P3
Internal
=====
2104508105P3
Internal
=====
2104543105P3
Internal
=====
2104589105P3
Internal
=====
2104241210P2
Internal
=====
2106386249P24
Internal
=====
2101000195
Internal
=====
2101151180
Internal
=====
2101150180
Internal
=====
2101200180
Internal
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102500125P2
Internal
=====
2102500130P2
Internal
=====
2102900125
Internal
=====
2102900130
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2309005305P20
Marketing
=====
2T01813126P2
Launching
=====
PH22T17
Marketing
=====
PH22T41
Marketing
=====
PH19H22
Launching
=====
PH22H95G277
Marketing
=====
1101685360
Marketing
=====
1101656360
Marketing
=====
2101847360
Marketing
=====
2101845360
Marketing
=====
2101819360
Marketing
=====
2101888360
Marketing
=====
PH19H103
Launching
=====
PH35H103
Launching
=====
2305551028
Launching
=====
2HF0113021
Launching tahap 2
=====
2HF0112021
Launching tahap 2
=====
1N01402250P4
Internal
=====
1N01402250P24
Internal
=====
2T00803164
Internal
=====
2T00803164P2
Internal
=====
2T00803164P3
Internal
=====
1101686318
Marketing
=====
1101694318
Marketing
=====
1N01402250P4
Marketing
=====
2T00803164
Marketing
=====
1N01402250P24
Marketing
=====
2T00803164P2
Marketing
=====
2T00803164P3
Marketing
=====
1101618318P2
Marketing
=====
1101618318
Marketing
=====
2309005305
Marketing
=====
2309005305P5
Marketing
=====
2309005305P10
Marketing
=====
2101700166
Marketing
=====
2101700166
Marketing
=====
2101700166P2
Marketing
=====
2101700166P2
Marketing
=====
2309005305P20
Marketing
=====
2309005305P20
Marketing
=====
(E)2101469180
Marketing
=====
1N01402250P4
Marketing
=====
1N01402250P24
Marketing
=====
2T01402249P4
Launching
=====
2T01402249P24
Launching
=====
1100534034
Launching
=====
2HC0109021
Launching tahap 2
=====
2305551028
Launching tahap 2
=====
PH19H22
Marketing
=====
PH22T41
Marketing
=====
PH22T17
Marketing
=====
(E)2101487148
Marketing
=====
(E)2101487148
Marketing
=====
2T01813126
Launching tahap 2
=====
2T01813126P2
Launching tahap 2
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102500125P2
Internal
=====
2102900125
Internal
=====
2102500130P2
Internal
=====
2102900130
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2101150180
Internal
=====
2101151180
Internal
=====
2101200180
Internal
=====
2101000195
Internal
=====
2101000195P2
Internal
=====
2101150180P2
Internal
=====
2101151180P2
Internal
=====
2101200180P2
Internal
=====
2304097159
Internal
=====
2104394210P2
Internal
=====
2104394210
Internal
=====
PT26T54
Internal
=====
2T01705164P2
Launching
=====
2305551028
Launching tahap 2
=====
PH22H95G277
Marketing
=====
1101665318
Marketing
=====
1101677318
Marketing
=====
1101653318
Marketing
=====
1101618318
Marketing
=====
2HH0813443P2
Launching
=====
2HF0114021P2
Marketing
=====
2LL1402249P4
Launching
=====
2LL1402249P24
Launching
=====
2LM0801029
Launching
=====
PL32L33
Launching
=====
2HF0114021
Marketing
=====
2101651195
Marketing
=====
2101651195P2
Marketing
=====
2101453195
Marketing
=====
2305551028
Internal
=====
2101453195P2
Marketing
=====
2101486195
Marketing
=====
2101486195P2
Marketing
=====
2309005305P20
Marketing
=====
(E)1101505453
Internal
=====
2304051180
Internal
=====
2LD0905181
Internal
=====
2304008180
Internal
=====
2TA0102180
Launching tahap 2
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102900125
Internal
=====
2102000180
Internal
=====
2102500125P2
Internal
=====
2102500130P2
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2102000180P2
Internal
=====
2102900130
Internal
=====
2304558112
Internal
=====
2304515112
Internal
=====
2304576112
Internal
=====
2304558112P2
Internal
=====
2304515112C2
Internal
=====
2304576112P2
Internal
=====
2304051180P2
Internal
=====
2LD0905181P2
Internal
=====
2304008180P2
Internal
=====
1N03301456
Launching
=====
2T01402249P24
Launching tahap 2
=====
2LM0801029
Launching tahap 2
=====
1101685360
Marketing
=====
1101656360
Marketing
=====
2T01402249P24
Internal
=====
2106386249P24
Internal
=====
2106386249P12
Internal
=====
2101888360
Marketing
=====
2101819360
Marketing
=====
2101845360
Marketing
=====
2101847360
Marketing
=====
2305551028P3
Internal
=====
2305551028
Internal
=====
2305507288
Internal
=====
2305545288
Internal
=====
2305559288
Internal
=====
2305584288
Internal
=====
2105028180P2
Internal
=====
1N01402250P24
Internal
=====
2LM0801029P2
Marketing
=====
PT25T41
Internal
=====
2104228230P2
Internal
=====
2104251230P2
Internal
=====
2T01402249P12
Internal
=====

In [23]:
## run 9
temp2 = selcen_new.copy()

temp2 = temp2.rename(columns = {'Nama Produk' : 'Item Name'})

data_SKU.loc[data_SKU['Price List NFI'].isin(['-']), 'Price List NFI'] = 0
data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')

data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)

list_col = ['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand']

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)
for i in list_col:
    temp2[i] = temp_merge[str(i)]
    
list_col = ['SKU'] + data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Cost 7')+1].to_list()
temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU').set_index(temp2.index)
list_pcs = [x for x in temp_merge.columns if 'PCS' in x]
for i in list_pcs:
    temp_merge[i] = temp_merge[i] * temp_merge['Qty. Invoiced']

list_col = data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Cost 7')+1].to_list()    
for i in list_col:
    temp2[i] = temp_merge[str(i)]
    
list_col = ['Real SKU', 'Price List NFI', 'Harga Cost']

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)
for i in list_col:
    if i == 'Real SKU':
        temp2[i] = temp_merge[str(i) + '_y']
    else :
        temp2[i] = temp_merge[str(i)]
    
temp2['Price List NFI'] = pd.to_numeric(temp2['Price List NFI']).astype(int)
temp2['Harga Cost'] = pd.to_numeric(temp2['Harga Cost']).astype(int)
temp2['Qty. Invoiced'] = pd.to_numeric(temp2['Qty. Invoiced']).astype(int)

temp2['Total Net'] = temp2['Price List NFI'] * temp2['Qty. Invoiced']
temp2['Total Harga Cost'] = temp2['Harga Cost'] * temp2['Qty. Invoiced']
temp2['Total Net Before PPN'] = temp2['Total Net']/1.11

print("Unbundling")
data_bundle1 = temp2[~temp2['Produk 1'].isnull()]
data_bundle1['Bundle Name'] = data_bundle1['Item Name']
data_bundle1['Item Name'] = data_bundle1['Produk 1']
data_bundle1['SKU'] = data_bundle1['SKU Produk 1']
data_bundle1['Qty. Invoiced'] = data_bundle1['PCS Produk 1']
data_bundle1['Price List NFI'] = data_bundle1['Price List NFI 1']
data_bundle1['Total Net'] = data_bundle1['Price List NFI 1']
data_bundle1['Bundle Flag'] = np.nan

data_bundle2 = temp2[~temp2['Produk 2'].isnull()]
data_bundle2['Bundle Name'] = data_bundle2['Item Name']
data_bundle2['Item Name'] = data_bundle2['Produk 2']
data_bundle2['SKU'] = data_bundle2['SKU Produk 2']
data_bundle2['Qty. Invoiced'] = data_bundle2['PCS Produk 2']
data_bundle2['Price List NFI'] = data_bundle2['Price List NFI 2']
data_bundle2['Total Net'] = data_bundle2['Price List NFI 2'] 
data_bundle2['Bundle Flag'] = np.nan

data_bundle3 = temp2[~temp2['Produk 3'].isnull()]
data_bundle3['Bundle Name'] = data_bundle3['Item Name']
data_bundle3['Item Name'] = data_bundle3['Produk 3']
data_bundle3['SKU'] = data_bundle3['SKU Produk 3']
data_bundle3['Qty. Invoiced'] = data_bundle3['PCS Produk 3']
data_bundle3['Price List NFI'] = data_bundle3['Price List NFI 3']
data_bundle3['Total Net'] = data_bundle3['Price List NFI 3'] 
data_bundle3['Bundle Flag'] = np.nan

data_bundle4 = temp2[~temp2['Produk 4'].isnull()]
data_bundle4['Bundle Name'] = data_bundle4['Item Name']
data_bundle4['Item Name'] = data_bundle4['Produk 4']
data_bundle4['SKU'] = data_bundle4['SKU Produk 4']
data_bundle4['Qty. Invoiced'] = data_bundle4['PCS Produk 4']
data_bundle4['Price List NFI'] = data_bundle4['Price List NFI 4']
data_bundle4['Total Net'] = data_bundle4['Price List NFI 4'] 
data_bundle4['Bundle Flag'] = np.nan

data_bundle5 = temp2[~temp2['Produk 5'].isnull()]
data_bundle5['Bundle Name'] = data_bundle5['Item Name']
data_bundle5['Item Name'] = data_bundle5['Produk 5']
data_bundle5['SKU'] = data_bundle5['SKU Produk 5']
data_bundle5['Qty. Invoiced'] = data_bundle5['PCS Produk 5']
data_bundle5['Price List NFI'] = data_bundle5['Price List NFI 5']
data_bundle5['Total Net'] = data_bundle5['Price List NFI 5']
data_bundle5['Bundle Flag'] = np.nan

data_bundle6 = temp2[~temp2['Produk 6'].isnull()]
data_bundle6['Bundle Name'] = data_bundle6['Item Name']
data_bundle6['Item Name'] = data_bundle6['Produk 6']
data_bundle6['SKU'] = data_bundle6['SKU Produk 6']
data_bundle6['Qty. Invoiced'] = data_bundle6['PCS Produk 6']
data_bundle6['Price List NFI'] = data_bundle6['Price List NFI 6']
data_bundle6['Total Net'] = data_bundle6['Price List NFI 6']
data_bundle6['Bundle Flag'] = np.nan

data_bundle7 = temp2[~temp2['Produk 7'].isnull()]
data_bundle7['Bundle Name'] = data_bundle7['Item Name']
data_bundle7['Item Name'] = data_bundle7['Produk 7']
data_bundle7['SKU'] = data_bundle7['SKU Produk 7']
data_bundle7['Qty. Invoiced'] = data_bundle7['PCS Produk 7']
data_bundle7['Price List NFI'] = data_bundle7['Price List NFI 7']
data_bundle7['Total Net'] = data_bundle7['Price List NFI 7']
data_bundle7['Bundle Flag'] = np.nan

data_bundle = data_bundle1.append([data_bundle2, data_bundle3, data_bundle4, data_bundle5, data_bundle6, data_bundle7], ignore_index = True, sort = False)
data_bundle['SKU'] = data_bundle['SKU'].astype(str)
data_bundle['SKU'] = data_bundle['SKU'].str.replace('\.0$', '', regex = True)
data_bundle[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']] = data_bundle.merge(data_SKU[['Real SKU', 'Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU')[['Real SKU_y', 'Nama Produk', 'Brand_y', 'Sub Brand_y', 'Parent Item', 'Parent SKU']]

list_col = ['Real SKU', 'Price List NFI', 'Harga Cost']

data_bundle = data_bundle.drop(['Price List NFI', 'Harga Cost'], axis = 1)

temp_merge = data_bundle.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(data_bundle.index)
for i in list_col:
    if i == 'Real SKU':
        data_bundle[i] = temp_merge[str(i) + '_y']
    else :
        data_bundle[i] = temp_merge[str(i)]

data_bundle['Price List NFI'] = pd.to_numeric(data_bundle['Price List NFI']).astype(int)
data_bundle['Harga Cost'] = pd.to_numeric(data_bundle['Harga Cost']).astype(int)
data_bundle['Qty. Invoiced'] = pd.to_numeric(data_bundle['Qty. Invoiced']).astype(int)

data_bundle['Total Net'] = data_bundle['Price List NFI'] * data_bundle['Qty. Invoiced']
data_bundle['Total Harga Cost'] = data_bundle['Harga Cost'] * data_bundle['Qty. Invoiced']
data_bundle['Total Net Before PPN'] = data_bundle['Total Net']/1.11

for i in ['Unit Price', 'Paid Price', 'Shipping Fee']:
    data_bundle[i] = data_bundle[i].fillna(0) * data_bundle['Total Net Before PPN']/data_bundle.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')

print("Pricing")
temp2 = temp2.append(data_bundle, ignore_index = True, sort = False)

temp2['Price List NFI'] = pd.to_numeric(temp2['Price List NFI']).astype(int)
temp2['Harga Cost'] = pd.to_numeric(temp2['Harga Cost']).astype(int)
temp2['Qty. Invoiced'] = pd.to_numeric(temp2['Qty. Invoiced']).astype(int)

temp2['Total Net'] = temp2['Price List NFI'] * temp2['Qty. Invoiced']
temp2['Total Harga Cost'] = temp2['Harga Cost'] * temp2['Qty. Invoiced']
temp2['Total Net Before PPN'] = temp2['Total Net']/1.11

Unbundling

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:97: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:101: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Pricing

In [24]:
## run 10
selcen_sku = temp2.copy()

In [25]:
## run 11
j_conv = pd.read_excel("Settlement Project\Rumus Realisasi.xlsx", sheet_name = 'Paket Brand')
j_conv = j_conv.iloc[:,:5]
j_conv = j_conv.rename(columns = {'SKU' : 'Real SKU', 'SKU.1' : 'SKU Produk'})
j_conv = j_conv[j_conv['Real SKU'].notnull()]
j_conv['SKU Produk'] = j_conv['SKU Produk'].astype(str).str.replace('.0', '',regex = False)

temp_all = selcen_sku.copy()

temp_all['Real SKU'] = temp_all['Real SKU'].astype(str)
j_conv['Real SKU'] = j_conv['Real SKU'].astype(str)

temp_all = temp_all.merge(j_conv, how = 'left', on = 'Real SKU')

paket_j = temp_all[temp_all['SKU Produk'].notnull()]

paket_j['Bundle Name'] = paket_j['Item Name']
paket_j['Item Name'] = paket_j['Name']
paket_j['SKU'] = paket_j['SKU Produk']
paket_j['Qty. Invoiced'] = paket_j['Qty. Invoiced'] * paket_j['Konversi ke UOM'].astype(float)
paket_j['Bundle Flag'] = np.nan

import time
import pandas as pd
import numpy as np
import math

import smtplib 
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys
import requests
import os
    

print('A')
data_SKU = pd.read_excel(r'D:\1. Masterdata\SKU_File\data_SKU.xlsx')
print('A')
s = requests.Session()
s.get("https://tatanama.pythonanywhere.com")
s.post("https://tatanama.pythonanywhere.com", data = {'username' : 'ecommerce', 'password' : 'ecommerce'})
r = s.get("https://tatanama.pythonanywhere.com/download")

with open(r'D:\1. Masterdata\SKU_File\Master tatanama.xlsx', 'wb') as output:
    output.write(r.content)

if os.path.isfile(r'D:\1. Masterdata\SKU_File\Master tatanama.xlsx') :    
    SKU_append = pd.read_excel(r'D:\1. Masterdata\SKU_File\Master tatanama.xlsx')
    SKU_append.columns = [x.replace('_', ' ') for x in SKU_append.columns]
    data_SKU = data_SKU[~data_SKU['SKU'].astype(str).isin(SKU_append['SKU'].astype(str))]
    data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)
    
data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)
if 'Real SKU_y' in paket_j.columns:
    paket_j = paket_j.drop('Real SKU_y', axis = 1)
paket_j['SKU'] = paket_j['SKU'].astype(str)
paket_j[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU', 'Price List NFI']] = paket_j.merge(data_SKU[['Real SKU', 'Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU', 'Price List NFI']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(paket_j.index)[['Real SKU_y', 'Nama Produk', 'Brand_y', 'Sub Brand_y', 'Parent Item_y', 'Parent SKU_y', 'Price List NFI_y']]

paket_j['Price List NFI']=paket_j['Price List NFI'].astype(int)
paket_j['Total Net'] = paket_j['Price List NFI'] * paket_j['Qty. Invoiced']

for i in ['Unit Price', 'Paid Price', 'Shipping Fee']:
    paket_j[i] = paket_j[i] * paket_j['Total Net']/paket_j.groupby(['Order Number', 'Bundle Name'])['Total Net'].transform('sum')

paket_j = paket_j.drop(['Nama Paket', 'SKU Produk', 'Name', 'Konversi ke UOM'], axis = 1)
selcen_sku = selcen_sku.append(paket_j, ignore_index = True, sort = False)
indeks = selcen_sku[selcen_sku['Item Name'].isin(paket_j['Bundle Name'])].index.to_list()
selcen_sku['Brand'][indeks] = 'Bundle'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A
A

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [27]:
## run for check, jika ingin di unbundling isi rumus realisasi xlsx sheet paket brand
selcen_sku[(selcen_sku['Real SKU'].str.contains('J'))&~(selcen_sku['Real SKU'].isin(j_conv['Real SKU'].unique()))][['Real SKU','Real Nama Produk']].drop_duplicates()

Empty DataFrame
Columns: [Real SKU, Real Nama Produk]
Index: []

In [26]:
## run 12
indeks = selcen_sku[(selcen_sku['Real SKU'].astype(str).str.contains('^\(B\)', regex = True)) &
      (~selcen_sku['Brand'].isin(['Bonus Produk', 'Gimmick']))].index.to_list()

selcen_sku['Brand'][indeks] = 'Bonus Produk'

indeks = selcen_sku[(selcen_sku['Real SKU'].astype(str).str.contains('^\(U\)', regex = True)) &
      (~selcen_sku['Brand'].isin(['Bonus Produk', 'Gimmick']))].index.to_list()

selcen_sku['Brand'][indeks] = 'Bonus Produk'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

# Old NFI

In [28]:
## run 13
# source = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Realisasi Januari 2022\Final Result\Runningan Lazada Jan 2021 - Jan 2022 Real.csv", sep = ';')
source = pd.read_csv(r"Settlement Project\Backup\Realisasi Jan 2022\Runningan Lazada Jan 2021 - Jan 2022 Real.csv", sep = ';')

source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021) & (source['True datetime']<'2022-02-01')]

selcen_sku['Order Number'] = selcen_sku['Order Number'].astype(str).str.replace('.0', '', regex = False)
source['Order #'] = source['Order #'].astype(str).str.replace('.0', '', regex = False)

selcen_old = selcen_sku[selcen_sku['Order Number'].isin(source['Order #'])]

indeks = selcen_old[(selcen_old['Bundle Name'].astype(str).str.contains('-Rasa', regex = False)) & ~(selcen_old['Bundle Name'].astype(str).str.contains(' -Rasa', regex = False))].index.to_list()
selcen_old['Bundle Name'][indeks] = selcen_old['Bundle Name'].astype(str).str.replace('-Rasa', ' - Rasa', regex = False)

indeks = selcen_old[(selcen_old['Bundle Name'].astype(str).str.contains('-Flavor', regex = False)) & ~(selcen_old['Bundle Name'].astype(str).str.contains(' -Flavor', regex = False))].index.to_list()
selcen_old['Bundle Name'][indeks] = selcen_old['Bundle Name'].astype(str).str.replace('-Flavor', ' - Flavor', regex = False)

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

selcen_old_merge = selcen_old.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Price List NFI', 'Qty. Invoiced']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']) 

selcen_old_null = selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()]

selcen_old_null = selcen_old_null.drop(['Order #', 'Price List NFI_y'], axis = 1)
selcen_old_null = selcen_old_null.rename(columns = {'Price List NFI_x' : 'Price List NFI'})

selcen_old_null = selcen_old_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Price List NFI']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name', 'Price List NFI']), how = 'left', left_on = ['Order Number', 'Item Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(selcen_old_null.index) 
selcen_old_merge['Price List NFI_y'][selcen_old_null.index] = selcen_old_null['Price List NFI_y']

selcen_old_null = selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()]

selcen_old_null = selcen_old_null.drop(['Order #', 'Price List NFI_y'], axis = 1)
selcen_old_null = selcen_old_null.rename(columns = {'Price List NFI_x' : 'Price List NFI'})

selcen_old_null = selcen_old_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Price List NFI']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name', 'Price List NFI']), how = 'left', left_on = ['Order Number', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(selcen_old_null.index) 
selcen_old_merge['Price List NFI_y'][selcen_old_null.index] = selcen_old_null['Price List NFI_y']

# selcen_old_null = selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()]

# source2 = source.copy()

# # source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# # indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# # source2['Real SKU'][indeks] = '(U)2101809250'

# # indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# # source2['Real SKU'][indeks] = '2101941250P4'

# # indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# # source2['Real SKU'][indeks] = '2101809250P4'

# selcen_old_null = selcen_old_null.drop(['Order #', 'Price List NFI_y'], axis = 1)
# selcen_old_null = selcen_old_null.rename(columns = {'Price List NFI_x' : 'Price List NFI'})

# selcen_old_null = selcen_old_null.merge(source2[['Order #', 'Real SKU', 'Bundle Name', 'Price List NFI']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(selcen_old_null.index) 

# selcen_old_merge['Price List NFI_y'][selcen_old_null.index] = selcen_old_null['Price List NFI_y']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (14,22,23,24) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [29]:
## run 14
selcen_old_merge[(selcen_old_merge['Price List NFI_y'].isnull()) & (selcen_old_merge['Status'] != 'canceled')][['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Status']]['Bundle Name'].unique()

array([], dtype=object)

In [30]:
## run 15
selcen_old_merge = selcen_old_merge.drop(['Price List NFI_x', 'Order #'], axis = 1)
selcen_old_merge = selcen_old_merge.rename(columns = {'Price List NFI_y' : 'Price List NFI'})

selcen_old_merge['Price List NFI'] = pd.to_numeric(selcen_old_merge['Price List NFI']).astype(float)
selcen_old_merge['Qty. Invoiced'] = pd.to_numeric(selcen_old_merge['Qty. Invoiced']).astype(float)

selcen_old_merge['Total Net'] = selcen_old_merge['Price List NFI'] * selcen_old_merge['Qty. Invoiced']

selcen_sku = selcen_sku[~selcen_sku['Order Number'].isin(selcen_old_merge['Order Number'])]
selcen_sku = selcen_sku.append(selcen_old_merge, ignore_index = True, sort = False)

selcen_sku['Total Net Before PPN'] = selcen_sku['Total Net']/1.11

In [31]:
## run 16
indeks = selcen_sku[(selcen_sku['Item Name'].astype(str).str.contains('-Flavor', regex = False)) & ~(selcen_sku['Item Name'].astype(str).str.contains(' -Flavor', regex = False))].index.to_list()
selcen_sku['Item Name'][indeks] = selcen_sku['Item Name'].astype(str).str.replace('-Flavor', ' - Flavor', regex = False)

indeks = selcen_sku[(selcen_sku['Item Name'].astype(str).str.contains('-Rasa', regex = False)) & ~(selcen_sku['Item Name'].astype(str).str.contains(' -Rasa', regex = False))].index.to_list()
selcen_sku['Item Name'][indeks] = selcen_sku['Item Name'].astype(str).str.replace('-Rasa', ' - Rasa', regex = False)

indeks = selcen_sku[(selcen_sku['Bundle Name'].astype(str).str.contains('-Rasa', regex = False)) & ~(selcen_sku['Bundle Name'].astype(str).str.contains(' -Rasa', regex = False))].index.to_list()
selcen_sku['Bundle Name'][indeks] = selcen_sku['Bundle Name'].astype(str).str.replace('-Rasa', ' - Rasa', regex = False)

indeks = selcen_sku[(selcen_sku['Bundle Name'].astype(str).str.contains('-Flavor', regex = False)) & ~(selcen_sku['Bundle Name'].astype(str).str.contains(' -Flavor', regex = False))].index.to_list()
selcen_sku['Bundle Name'][indeks] = selcen_sku['Bundle Name'].astype(str).str.replace('-Flavor', ' - Flavor', regex = False)

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":

# Fulfillment

In [32]:
## run 17
wms = pd.DataFrame()
rencol=pd.read_excel("Settlement Project\Lazada\dict_col_fulfiment.xlsx")
for i in os.listdir('Settlement Project\Lazada\Fulfillment/'):
    print(i)
    temp = pd.read_excel('Settlement Project\Lazada\Fulfillment/' + str(i))
    if 'datareport/Customer Order No.' in temp.columns:
        temp=temp.rename(columns=dict(rencol.values)) 
    temp['Source'] = i
    true_col = ['Customer Order No.', 'Order Time', 'Update Time', 'Number of SKUs', 'Platform SKU', 'Seller SKU', 'Platform SKU Name', 'Number of Items', 'Delivery Type', 
                'Update Time.1', 'Status', 'Platform', 'Source']
    if 'Customer Order No.' in wms.columns:
        temp = temp[~temp['Customer Order No.'].isin(wms['Customer Order No.'])]
    if temp.columns.to_list() == true_col :
        print('Column sama')
    else:
        print('Column beda')
        
        print([x for x in true_col if x not in temp.columns.to_list()])
        print([x for x in temp.columns.to_list() if x not in true_col])
    wms = wms.append(temp, ignore_index = True, sort = False)

fulfillment-sales-report-export-202204 16 sd end.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export-202205.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export-202206.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export-202207.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202101.xlsx
Column sama
fulfillment-sales-report-export202102.xlsx
Column sama
fulfillment-sales-report-export202103.xlsx
Column sama
fulfillment-sales-report-export202104.xlsx
Column sama
fulfillment-sales-report-export202105.xlsx
Column sama
fulfillment-sales-report-export202106.xlsx
Column sama
fulfillment-sales-report-export202107.xlsx
Column sama
fulfillment-sales-report-export202108.xlsx
Column sama
fulfillment-sales-report-export202109.xlsx
Column sama
fulfillment-sales-report-export202110.xlsx
Column sama
fulfillment-sales-report-export202112.xlsx
Column sama
fulfillment-sales-report-export202201.xlsx
Column sama
fulfillment-sales-report-export202202 1-15 Feb.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202202 1-24 Feb.xlsx
Column sama
fulfillment-sales-report-export202202 16-28 Feb.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202203.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202204 1 sd 15 Apr.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202207.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202208.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202209.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202210.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202211.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202212.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202301.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202302.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202303.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202304.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export202305.xlsx
Column beda
['Number of SKUs']
[]
fulfillment-sales-report-export2112312250091409402-11-0113.xlsx
Column sama
fulfillment-sales-report-export2112312252318785810-11-1430.xlsx
Column sama

In [33]:
## run 18
temp = wms.groupby(['Customer Order No.'], dropna = False)['Source'].nunique().gt(1).reset_index()
temp = temp[temp['Source'] == True]
wms[wms['Customer Order No.'].isin(temp['Customer Order No.'])].sort_values('Customer Order No.')
# temp

Empty DataFrame
Columns: [Customer Order No., Order Time, Update Time, Platform SKU, Seller SKU, Platform SKU Name, Number of Items, Delivery Type, Update Time.1, Status, Platform, Source, Number of SKUs]
Index: []

In [34]:
## for backup
wms_ori = wms.copy()
wms_ori2 = wms.copy()

In [135]:
## for backup
wms = wms_ori.copy()

In [35]:
## run 19
wms = wms.rename(columns = {'Seller SKU' : 'Real SKU'})

In [36]:
# wms[(wms['Real SKU'] == 'NON DATA') & (wms['Number of Items'] > 1)].sort_values('Order Time').drop_duplicates('Platform SKU Name')

In [37]:
# wms[(wms['Real SKU'].astype(str).str.contains('P')) & (wms['Customer Order No.'].isin(selcen_sku['Order Number']))& (wms['Number of Items'] > 1)].sort_values('Order Time')

In [38]:
## run 20
wms_non = wms[(wms['Real SKU'] == 'NON DATA') | (wms['Real SKU'].isnull())]
wms_data = wms[wms['Real SKU'] != 'NON DATA']

indeks = wms_data[wms_data['Real SKU'] == '(E)1101984453-1'].index.to_list()
wms_data['Real SKU'][indeks] = '(E)1101984453'
indeks = wms_data[wms_data['Real SKU'] == '2104148164PX'].index.to_list()
wms_data['Real SKU'][indeks] = '2104148164P2'
wms_data[~wms_data['Real SKU'].isin(data_SKU['SKU'])]

### yang non akan di handle belakangan dont panic wkwkw

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1061: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Customer Order No.,Order Time,Update Time,Platform SKU,Real SKU,Platform SKU Name,Number of Items,Delivery Type,Update Time.1,Status,Platform,Source,Number of SKUs
72,863087785020441,2022-04-30 20:59:26,2022-05-04 15:25:37,5578964799_ID-11033026847,NaN,L-Men Hi Protein Daily Popcorn Caramel 250g - ...,1,STANDARD,2022-05-04 15:25:37,Delivered,LAZADA,fulfillment-sales-report-export-202204 16 sd e...,NaN
1314,854262459457438,2022-04-27 12:50:28,2022-04-28 22:17:56,5578964799_ID-11033026847,NaN,L-Men Hi Protein Daily Popcorn Caramel 250g - ...,1,STANDARD,2022-04-28 22:17:56,Delivered,LAZADA,fulfillment-sales-report-export-202204 16 sd e...,NaN
1703,860437378435912,2022-04-26 05:41:32,2022-04-27 23:13:17,5368828718_ID-10584378308,NaN,HiLo Teen Popcorn Caramel 500g - Susu Tinggi K...,1,STANDARD,2022-04-27 23:13:17,Delivered,LAZADA,fulfillment-sales-report-export-202204 16 sd e...,NaN
2089,859726768086154,2022-04-25 11:59:22,2022-04-29 15:37:16,5578964799_ID-11033026847,NaN,L-Men Hi Protein Daily Popcorn Caramel 250g - ...,1,STANDARD,2022-04-29 15:37:16,Delivered,LAZADA,fulfillment-sales-report-export-202204 16 sd e...,NaN
2604,857270365617590,2022-04-23 21:24:08,2022-04-24 15:09:30,5786410177_ID-11243280024,NaN,HiLo Teen Strawberry Milkshake 500g - Susu Tin...,1,STANDARD,2022-04-24 15:09:30,Delivered,LAZADA,fulfillment-sales-report-export-202204 16 sd e...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
313890,1145569855382813,2023-05-01 17:33:27,2023-05-03 12:38:18,5368828718_ID-10584378308,NaN,HiLo Teen Popcorn Caramel 500g - Susu Tinggi K...,2,STANDARD,2023-05-03 12:38:18,Delivered,LAZADA,fulfillment-sales-report-export202305.xlsx,NaN
314032,1145619262923856,2023-05-01 10:24:55,2023-05-04 15:24:51,7240400466_ID-13572370602,NaN,[GIFT] Botol Minum Lock & Lock 1.5 L,1,STANDARD,2023-05-04 15:24:51,Delivered,LAZADA,fulfillment-sales-report-export202305.xlsx,NaN
314055,1145619262923856,2023-05-01 10:24:55,2023-05-04 15:24:51,6904130555_ID-13084370607,NaN,HiLo Platinum Original 360g (12 Sachet) - Susu...,1,STANDARD,2023-05-04 15:24:51,Delivered,LAZADA,fulfillment-sales-report-export202305.xlsx,NaN
314066,1145619262923856,2023-05-01 10:24:55,2023-05-04 15:24:51,HI108OTBGOO8ANID-1473943,NaN,HiLo Platinum Susu Tinggi Kalsium - 420 g,1,STANDARD,2023-05-04 15:24:51,Delivered,LAZADA,fulfillment-sales-report-export202305.xlsx,NaN
314114,1155828360511198,2023-05-01 04:03:05,2023-05-03 19:07:32,HI108TBAA2NZ2BANID-4911183,NaN,HiLo Teen Yoghurt Banana 250gr - Susu Tinggi K...,2,STANDARD,2023-05-03 19:07:32,Delivered,LAZADA,fulfillment-sales-report-export202305.xlsx,NaN

In [39]:
## run 21
import time
import pandas as pd
import numpy as np
import math

import smtplib 
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys
import requests
import os
    

list_col = ['SKU'] + data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Cost 7')+1].to_list()
wms_data = wms_data.merge(data_SKU[list_col].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU')
list_pcs = [x for x in wms_data.columns if 'PCS' in x]
for i in list_pcs:
    wms_data[i] = wms_data[i] * wms_data['Number of Items']

print("Unbundling")
data_bundle1 = wms_data[~wms_data['Produk 1'].isnull()]
data_bundle1['Real SKU'] = data_bundle1['SKU Produk 1']
data_bundle1['Number of Items'] = data_bundle1['PCS Produk 1']

data_bundle2 = wms_data[~wms_data['Produk 2'].isnull()]
data_bundle2['Real SKU'] = data_bundle2['SKU Produk 2']
data_bundle2['Number of Items'] = data_bundle2['PCS Produk 2']

data_bundle3 = wms_data[~wms_data['Produk 3'].isnull()]
data_bundle3['Real SKU'] = data_bundle3['SKU Produk 3']
data_bundle3['Number of Items'] = data_bundle3['PCS Produk 3']

data_bundle4 = wms_data[~wms_data['Produk 4'].isnull()]
data_bundle4['Real SKU'] = data_bundle4['SKU Produk 4']
data_bundle4['Number of Items'] = data_bundle4['PCS Produk 4']

data_bundle5 = wms_data[~wms_data['Produk 5'].isnull()]
data_bundle5['Real SKU'] = data_bundle5['SKU Produk 5']
data_bundle5['Number of Items'] = data_bundle5['PCS Produk 5']

data_bundle6 = wms_data[~wms_data['Produk 6'].isnull()]
data_bundle6['Real SKU'] = data_bundle6['SKU Produk 6']
data_bundle6['Number of Items'] = data_bundle6['PCS Produk 6']

data_bundle7 = wms_data[~wms_data['Produk 7'].isnull()]
data_bundle7['Real SKU'] = data_bundle7['SKU Produk 7']
data_bundle7['Number of Items'] = data_bundle7['PCS Produk 7']

data_bundle = data_bundle1.append([data_bundle2, data_bundle3, data_bundle4, data_bundle5, data_bundle6, data_bundle7], ignore_index = True, sort = False)

Unbundling

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [40]:
## run 22
fbl_merge = selcen_sku[selcen_sku['Shipment Type Name'] == 'own_warehouse']
lzd_merge = selcen_sku[selcen_sku['Shipment Type Name'] == 'dropshipping']

lzd_merge = lzd_merge.reset_index(drop = True)
wms_data['Customer Order No.'] = wms_data['Customer Order No.'].astype(str)

bundle_wms_data = fbl_merge[fbl_merge['Bundle Name'].notnull()]
lazada_wms_data = fbl_merge[fbl_merge['Bundle Name'].isnull()]

wms_data = wms_data.groupby(['Customer Order No.', 'Platform SKU']).agg({'Status' : 'first', 'Number of Items' : 'sum'}).reset_index()
wms_data['WH'] = 'Lazada Warehouse'
wms_data = wms_data.rename(columns = {'Number of Items' : 'Warehouse Quantity'})

lazada_wms_data = lazada_wms_data.merge(wms_data.drop_duplicates(['Customer Order No.', 'Platform SKU']), how = 'left', left_on = ['Order Number', 'Lazada SKU'], right_on = ['Customer Order No.', 'Platform SKU'])
lazada_wms_data['Warehouse Quantity'] = lazada_wms_data['Warehouse Quantity'] * lazada_wms_data['Qty. Invoiced']/lazada_wms_data.groupby(['Order Number', 'Real SKU'])['Qty. Invoiced'].transform('sum')


data_bundle = data_bundle.rename(columns = {'Number of Items' : 'Warehouse Quantity', 'Customer Order No.' : 'Order Number', 'Platform SKU Name' : 'Bundle Name'})
bundle_wms_data['Order Number'] = bundle_wms_data['Order Number'].astype(str)
bundle_wms_data['Real SKU'] = bundle_wms_data['Real SKU'].astype(str)
data_bundle['Order Number'] = data_bundle['Order Number'].astype(str)
data_bundle['Real SKU'] = data_bundle['Real SKU'].astype(str)

# data_bundle['Bundle Name'] = data_bundle['Bundle Name'].astype(str).str.replace('-Rasa:Lainnya', '', regex = False)
# bundle_wms_data['Bundle Name'] = bundle_wms_data['Bundle Name'].astype(str).str.replace('-Rasa:Lainnya', '', regex = False)

bundle_wms_data_merge = bundle_wms_data.merge(data_bundle[['Order Number', 'Real SKU', 'Platform SKU', 'Status', 'Warehouse Quantity']].drop_duplicates(['Order Number', 'Real SKU', 'Platform SKU']), how = 'left', left_on = ['Order Number', 'Real SKU', 'Lazada SKU'], right_on = ['Order Number', 'Real SKU', 'Platform SKU'])
bundle_wms_data_merge = bundle_wms_data_merge.rename(columns = {'Product Name_x' : 'Product Name'})

bundle_duplicate = bundle_wms_data_merge[bundle_wms_data_merge[['Order Number', 'Real SKU', 'Bundle Name']].duplicated(keep = False)]
bundle_notduplicate = bundle_wms_data_merge[~bundle_wms_data_merge.index.isin(bundle_duplicate.index)]

bundle_duplicate['Warehouse Quantity'] = bundle_duplicate['Warehouse Quantity'] * bundle_duplicate['Qty. Invoiced']/bundle_duplicate.groupby(['Order Number', 'Bundle Name', 'Real SKU'])['Qty. Invoiced'].transform('sum')

bundle_wms_data_merge = bundle_notduplicate.append(bundle_duplicate, ignore_index = True, sort = False)
# bundle_wms_data_merge = bundle_wms_data_merge.drop('Product Name_y', axis = 1)

lazada_wms_data = lazada_wms_data.append(bundle_wms_data_merge, ignore_index = True, sort = False)

# lazada_wms_data_null = lazada_wms_data[(lazada_wms_data['Order Number'].isin(wms_data['Customer Order No.'])) & (lazada_wms_data['Status'].isnull())]

# wms_data_ori['Customer Order No.'] = wms_data_ori['Customer Order No.'].astype(str)
# wms_data_ori = wms_data_ori.groupby(['Customer Order No.', 'Seller SKU']).agg({'Status' : 'first', 'Number of Items' : 'sum'}).reset_index()
# wms_data_ori['WH'] = 'Lazada Warehouse'
# wms_data_ori = wms_data_ori.rename(columns = {'Number of Items' : 'Warehouse Quantity'})

# lazada_wms_data_null = lazada_wms_data_null.merge(wms_data_ori.drop_duplicates(['Customer Order No.', 'Seller SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Customer Order No.', 'Seller SKU']).set_index(lazada_wms_data_null.index)

# lazada_wms_data_null_bundle = lazada_wms_data_null[lazada_wms_data_null['Brand'] == 'Bundle']
# lazada_wms_data_null_real = lazada_wms_data_null[lazada_wms_data_null['Brand'] != 'Bundle']

# data_bundle['WH'] = 'Lazada Warehouse'
# # lazada_wms_data_null_real = lazada_wms_data_null_real.rename(columns = {'WH_y' : 'WH', 'Status_y' : 'Status'})
# buat_bundle = data_bundle.groupby(['Order Number', 'Real SKU']).agg({'WH' : 'first', 'Status' : 'first', 'Warehouse Quantity' : 'sum'}).reset_index()
# lazada_wms_data_null_bundle = lazada_wms_data_null_bundle.drop(['WH_y', 'Status_y'], axis = 1)
# temp_lzd_bundle = lazada_wms_data_null_bundle.merge(data_bundle.drop_duplicates(['Order Number', 'Real SKU']), how = 'left', on = ['Order Number', 'Real SKU']).set_index(lazada_wms_data_null_bundle.index)

# lazada_wms_data_null['Status_y'][temp_lzd_bundle.index] = temp_lzd_bundle['Status']
# lazada_wms_data_null['WH_y'][temp_lzd_bundle.index] = temp_lzd_bundle['WH']

# lazada_wms_data['Status'][lazada_wms_data_null.index] = lazada_wms_data_null['Status_y']
# lazada_wms_data['WH'][lazada_wms_data_null.index] = lazada_wms_data_null['WH_y']
# lazada_wms_data['Warehouse Quantity'][lazada_wms_data_null.index] = lazada_wms_data_null['Warehouse Quantity_y']

fbl_wms_data = lazada_wms_data.copy()
del(lazada_wms_data)

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [41]:
# wms_non = wms[wms['Real SKU'] == 'NON DATA']

In [42]:
## run 23
wms_non = wms[(wms['Real SKU'] == 'NON DATA') | (wms['Real SKU'].isnull())]

wms_non = wms_non.merge(selcen_sku[['Real SKU', 'Lazada SKU', 'Brand']].drop_duplicates('Lazada SKU'), how = 'left', left_on = ['Platform SKU'], right_on = ['Lazada SKU'])
wms_non['Real SKU'] = wms_non['Real SKU_y']
wms_non = wms_non.drop(['Real SKU_x', 'Real SKU_y', 'Lazada SKU'], axis = 1)

# temp = wms_non[wms_non['Customer Order No.'] == 751321202119191]
# wms_non = wms_non[pd.to_datetime(wms_non['Order Time']).dt.year > 2021]
# wms_non = wms_non.append(temp, ignore_index = True, sort = False)

wms_non[wms_non['Real SKU'].isnull()].drop_duplicates('Platform SKU Name')

,Customer Order No.,Order Time,Update Time,Platform SKU,Platform SKU Name,Number of Items,Delivery Type,Update Time.1,Status,Platform,Source,Number of SKUs,Brand,Real SKU
90,694665873082033,2021-09-30 22:58:22,2021-10-03 14:29:07,501840290_ID-636752737,Paket Coffee Time - Tropicana Slim Cafe Latte ...,1,standard,2021-10-03 14:29:07,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
124,694585006815621,2021-09-30 20:16:36,2021-10-02 17:35:02,670212837_ID-930410013,[Bundling HiLo Active] - Chocolate 500gr dan V...,1,standard,2021-10-02 17:35:02,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
153,700082989575144,2021-09-30 17:25:47,2021-10-01 16:55:39,5119512958_ID-9516878900,Paket Es Tinggi Kalsium - HiLo Es Teler 10 Sac...,1,standard,2021-10-01 16:55:39,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
164,700039953595773,2021-09-30 16:02:59,2021-10-01 20:37:29,5012950797_ID-9294406237,L-Men Gain Mass Mangga 500g - Suplemen Penamba...,1,standard,2021-10-01 20:37:29,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
259,699722164773600,2021-09-30 08:02:19,2021-10-01 18:53:37,2172012529_ID-4163638059,Triple Pack - 2 HiLo School Chocolate Gusset 3...,1,standard,2021-10-01 18:53:37,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
260,694105629732298,2021-09-30 07:57:56,2021-10-01 14:24:18,4473130393_ID-7674574244,W'Dank Empon Empon 10 Sachet - Minuman Tradisi...,2,standard,2021-10-01 14:24:18,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
264,693591026743638,2021-09-30 07:35:04,2021-10-01 17:44:29,5664220291_ID-11108728291,Free Gift - Tropicana Slim Santan 10 Sachet - ...,1,standard,2021-10-01 17:44:29,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
317,693882286914062,2021-09-29 20:50:06,2021-10-01 16:53:50,1328830144_ID-2364290587,Twin Pack - Tropicana Slim Sweetener I-Sweet ...,1,standard,2021-10-01 16:53:50,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
333,699486321608157,2021-09-29 19:46:41,2021-10-01 15:52:23,1185976786_ID-1890392745,Paket Cookies: Tropicana Slim Nutty Cookies Ch...,3,standard,2021-10-01 15:52:23,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
407,693581248848477,2021-09-29 13:07:03,2021-09-30 20:11:02,5093314227_ID-9441088630,HiLo Active Es Teler 175g - Susu Tinggi Kalsiu...,1,standard,2021-09-30 20:11:02,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
466,693410053332294,2021-09-29 08:52:33,2021-09-30 16:12:40,5148728169_ID-9579024021,Twin Pack - Tropicana Slim Sweetener Rose Vani...,1,standard,2021-09-30 16:12:40,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
689,698835122706484,2021-09-28 21:21:47,2021-10-02 11:56:27,4684042357_ID-8338090319,Paket Imun Nutrisari W’dank,1,standard,2021-10-02 11:56:27,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
744,698767140581289,2021-09-28 19:41:01,2021-09-29 17:01:50,4870020996_ID-8997322455,HiLo Es Teler 20 Sachet,1,standard,2021-09-29 17:01:50,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
759,698753908595089,2021-09-28 19:16:21,2021-10-01 18:47:03,4850206367_ID-8969782646,Paket Cookies - Tropicana Slim Korean Garlic B...,1,standard,2021-10-01 18:47:03,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
821,693004684278982,2021-09-28 16:26:32,2021-10-02 15:53:23,568784362_ID-806100440,Tropicana Slim Goldenmil with Manuka Honey 180...,5,standard,2021-10-02 15:53:23,Delivered,LAZADA,fulfillment-sales-report-export202109.xlsx,1.0,NaN,NaN
1862,1060292727386091,2023-01-29 18:26:38,2023-01-30 20:07:07,7228430534_ID-13558384057,[GIFT] Tropicana Slim Orange Cocoa 4 Sachet - ...,1,STANDARD,2023-01-30 20:07:07,Delivered,LAZADA,fulfillment-sales-report-export202301.xlsx,NaN,NaN,NaN
1867,1058510133502745,2023-01-28 20:07:16,2023-01-31 19:10:34,7240400466_ID-13572370602,[GIFT] Botol Minum Lock & Lock 1.5 L,1,STANDARD,2023-01-31 19:10:34,Delivered,LAZADA,fulfillment-sales-report-export202301.xlsx,NaN,NaN,NaN

In [43]:
## run 24
list_col = ['SKU'] + data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Cost 7')+1].to_list()
wms_non = wms_non.merge(data_SKU[list_col].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU')
list_pcs = [x for x in wms_non.columns if 'PCS' in x]
for i in list_pcs:
    wms_non[i] = wms_non[i] * wms_non['Number of Items']

print("Unbundling")
data_bundle1 = wms_non[~wms_non['Produk 1'].isnull()]
data_bundle1['Real SKU'] = data_bundle1['SKU Produk 1']
data_bundle1['Number of Items'] = data_bundle1['PCS Produk 1']

data_bundle2 = wms_non[~wms_non['Produk 2'].isnull()]
data_bundle2['Real SKU'] = data_bundle2['SKU Produk 2']
data_bundle2['Number of Items'] = data_bundle2['PCS Produk 2']

data_bundle3 = wms_non[~wms_non['Produk 3'].isnull()]
data_bundle3['Real SKU'] = data_bundle3['SKU Produk 3']
data_bundle3['Number of Items'] = data_bundle3['PCS Produk 3']

data_bundle4 = wms_non[~wms_non['Produk 4'].isnull()]
data_bundle4['Real SKU'] = data_bundle4['SKU Produk 4']
data_bundle4['Number of Items'] = data_bundle4['PCS Produk 4']

data_bundle5 = wms_non[~wms_non['Produk 5'].isnull()]
data_bundle5['Real SKU'] = data_bundle5['SKU Produk 5']
data_bundle5['Number of Items'] = data_bundle5['PCS Produk 5']

data_bundle6 = wms_non[~wms_non['Produk 6'].isnull()]
data_bundle6['Real SKU'] = data_bundle6['SKU Produk 6']
data_bundle6['Number of Items'] = data_bundle6['PCS Produk 6']

data_bundle7 = wms_non[~wms_non['Produk 7'].isnull()]
data_bundle7['Real SKU'] = data_bundle7['SKU Produk 7']
data_bundle7['Number of Items'] = data_bundle7['PCS Produk 7']

data_bundle = data_bundle1.append([data_bundle2, data_bundle3, data_bundle4, data_bundle5, data_bundle6, data_bundle7], ignore_index = True, sort = False)

Unbundling

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [44]:
## run 25
wms_non = wms_non.append(data_bundle, ignore_index = True, sort = False)
wms_non = wms_non.groupby(['Customer Order No.', 'Real SKU']).agg({'Status' : 'first', 'Number of Items' : 'sum'}).reset_index()
wms_non['WH'] = 'Lazada Warehouse'
wms_non = wms_non.rename(columns = {'Number of Items' : 'Warehouse Quantity'})

In [45]:
## run 26
wms_non['Customer Order No.'] = wms_non['Customer Order No.'].astype(str).str.replace('.0', '',regex = False)

In [46]:
## run 27
fbl_null = fbl_wms_data[(fbl_wms_data['Order Number'].isin(wms_non['Customer Order No.'])) & (fbl_wms_data['Warehouse Quantity'].isnull())].copy()

fbl_null = fbl_null.drop(['Status_y', 'Warehouse Quantity', 'WH'],axis = 1)

fbl_null = fbl_null.merge(wms_non.drop_duplicates(['Customer Order No.', 'Real SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Customer Order No.', 'Real SKU']).set_index(fbl_null.index)
fbl_null['Warehouse Quantity'] = fbl_null['Warehouse Quantity'] * fbl_null['Qty. Invoiced']/fbl_null.groupby(['Order Number', 'Real SKU'])['Qty. Invoiced'].transform('sum')

fbl_null_bundle = fbl_null[fbl_null['Brand'] == 'Bundle']

temp_buat_bundle = fbl_null.groupby(['Order Number', 'Bundle Name']).agg({'WH' : 'first', 'Status' : 'first', 'Warehouse Quantity' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Warehouse Quantity'] = temp_buat_bundle['Warehouse Quantity']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

fbl_null_bundle = fbl_null_bundle.merge(temp_buat_bundle.drop_duplicates(['Order Number', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Item Name'], right_on = ['Order Number', 'Bundle Name']).set_index(fbl_null_bundle.index)
fbl_null_bundle['Warehouse Quantity_y'] = fbl_null_bundle['Warehouse Quantity_y']*fbl_null_bundle['Qty. Invoiced']

fbl_null['Status'][fbl_null_bundle.index] = fbl_null_bundle['Status_y']
fbl_null['WH'][fbl_null_bundle.index] = fbl_null_bundle['WH_y']
fbl_null['Warehouse Quantity'][fbl_null_bundle.index] = fbl_null_bundle['Warehouse Quantity_y']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [47]:
## run 28
fbl_wms_data['Status_y'][fbl_null.index] = fbl_null['Status']
fbl_wms_data['WH'][fbl_null.index] = fbl_null['WH']
fbl_wms_data['Warehouse Quantity'][fbl_null.index] = fbl_null['Warehouse Quantity']

fbl_wms_data = fbl_wms_data.rename(columns = {'Status_x' : 'Order Status', 'Status_y' : 'Status'})

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [48]:
## run 29
fbl_null = fbl_wms_data[(fbl_wms_data['Order Number'].isin(wms_non['Customer Order No.'])) & (fbl_wms_data['Warehouse Quantity'].isnull())].copy()

fbl_null = fbl_null.drop(['Status', 'Warehouse Quantity', 'WH'],axis = 1)

wms_non2 = wms_non.copy()
wms_non2['Real SKU'] = wms_non2['Real SKU'].astype(str).str.replace('(U)2309005305','(B)2309005305', regex = False)

fbl_null = fbl_null.merge(wms_non2.drop_duplicates(['Customer Order No.', 'Real SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Customer Order No.', 'Real SKU']).set_index(fbl_null.index)
fbl_null['Warehouse Quantity'] = fbl_null['Warehouse Quantity'] * fbl_null['Qty. Invoiced']/fbl_null.groupby(['Order Number', 'Real SKU'])['Qty. Invoiced'].transform('sum')

fbl_null_bundle = fbl_null[fbl_null['Brand'] == 'Bundle']

temp_buat_bundle = fbl_null.groupby(['Order Number', 'Bundle Name']).agg({'WH' : 'first', 'Status' : 'first', 'Warehouse Quantity' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Warehouse Quantity'] = temp_buat_bundle['Warehouse Quantity']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

fbl_null_bundle = fbl_null_bundle.merge(temp_buat_bundle.drop_duplicates(['Order Number', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Item Name'], right_on = ['Order Number', 'Bundle Name']).set_index(fbl_null_bundle.index)
fbl_null_bundle['Warehouse Quantity_y'] = fbl_null_bundle['Warehouse Quantity_y']*fbl_null_bundle['Qty. Invoiced']

fbl_null['Status'][fbl_null_bundle.index] = fbl_null_bundle['Status_y']
fbl_null['WH'][fbl_null_bundle.index] = fbl_null_bundle['WH_y']
fbl_null['Warehouse Quantity'][fbl_null_bundle.index] = fbl_null_bundle['Warehouse Quantity_y']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [49]:
## run 30
fbl_wms_data['Status'][fbl_null.index] = fbl_null['Status']
fbl_wms_data['WH'][fbl_null.index] = fbl_null['WH']
fbl_wms_data['Warehouse Quantity'][fbl_null.index] = fbl_null['Warehouse Quantity']

# fbl_wms_data = fbl_wms_data.rename(columns = {'Status_x' : 'Order Status', 'Status_y' : 'Status'})

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [50]:
## run 31
import pandas as pd
import numpy as np
import pypyodbc

conn = pypyodbc.connect('Driver={SQL Server};'
                        'Server=NFI-DB-01;'
                        'Database=gudang;'
                        # 'UID=andra.miftah;'
                        # 'PWD=24nutrifoodindonesia21;'
                        'Trusted_Connection=yes;'
                       )

cursor = conn.cursor()
wms_telkom = pd.read_sql(r"""SELECT t1.id, t1.order_id,t1.status, t1.quantity, t1.product_id, t2.id,  t2.order_number, t2.invoice_number, t2.channel, t2.order_date, t3.id, t3.sku, t3.name
  FROM [gudang].[dbo].[outbound_items] as t1
  left join orders as t2
  on t1.order_id = t2.id
  left join products as t3
  on t1.product_id = t3.id
  where t2.channel = 'FBL' or t2.channel = 'Lazada'""", conn)


# wms_telkom=pd.read_excel(r"D:\Downloads\Data Gudang 20221122 (1).xlsx")
# wms_telkom=wms_telkom[wms_telkom['channel']=='Lazada']

wms_telkom_copy=wms_telkom.copy()

In [51]:
## for backup
wms_telkom_copy=wms_telkom.copy()

In [151]:
## for backup
wms_telkom=wms_telkom_copy.copy()

In [52]:
## run 32

# outbound_items = pd.read_csv(r'Backup Gudang 4 Sept 2021 Gudang Baru/outbound_items.csv', sep = ';')
# orders = pd.read_csv(r'Backup Gudang 4 Sept 2021 Gudang Baru/orders.csv', sep = ';')
# products = pd.read_csv(r'Backup Gudang 4 Sept 2021 Gudang Baru/products.csv', sep = ';')

# wms_telkom2 = outbound_items[['id', 'order_id','status', 'quantity', 'product_id']].merge(
#     orders[['id',  'order_number', 'invoice_number', 'channel', 'order_date']], how = 'left', left_on = 'order_id', right_on = 'id'
# ).merge(
#     products[['id', 'sku', 'name']], how = 'left', left_on = 'product_id', right_on = 'id'
# )
# wms_telkom2 = wms_telkom2[wms_telkom2['channel'].isin(['Lazada', 'FBL'])]
if 'STATUS' in wms_telkom.columns:
    wms_telkom = wms_telkom.rename(columns = {'STATUS':'status'})
wms_telkom = wms_telkom[['order_number', 'sku', 'status', 'quantity']].drop_duplicates()
# wms_telkom2 = wms_telkom2[['invoice_number', 'sku', 'status', 'quantity']].drop_duplicates()
# wms_telkom = wms_telkom.append(wms_telkom2, ignore_index = True, sort = False)

wms_telkom['WH'] = 'Telkom'
wms_telkom = wms_telkom.rename(columns = {'order_number' : 'Customer Order No.', 'status':'Status', 'sku' : 'Platform SKU', 'quantity' : 'Warehouse Quantity'})

colname = wms_telkom.columns.to_list()
wms_telkom_all = wms_telkom.merge(j_conv, how = 'left', left_on = ['Platform SKU'], right_on = ['Real SKU'])
wms_j = wms_telkom_all[wms_telkom_all['SKU Produk'].notnull()]

wms_j['Platform SKU'] = wms_j['SKU Produk']
wms_j['Warehouse Quantity'] = wms_j['Warehouse Quantity'] * wms_j['Konversi ke UOM'].astype(float)

wms_telkom = wms_telkom.append(wms_j, ignore_index = True, sort = False)
wms_telkom = wms_telkom[colname]

lzd_merge = selcen_sku[selcen_sku['Shipment Type Name'] == 'dropshipping'].reset_index(drop = True)

indeks = lzd_merge[(lzd_merge['Real SKU'].isin(['(B)2309005305P3', '(B)2309005300P3']))].index.to_list()
lzd_merge['Brand'][indeks] = 'Bundle'

lzd_merge['Order Number'] = lzd_merge['Order Number'].astype(str)
wms_telkom['Customer Order No.'] = wms_telkom['Customer Order No.'].astype(str)

wms_telkom = wms_telkom.groupby(['Customer Order No.', 'Platform SKU', 'Status',
       'WH'])['Warehouse Quantity'].sum().reset_index()

lzd_merge['Real SKU'] = lzd_merge['Real SKU'].astype(str).str.replace('.0', '', regex = False)
lzd_merge = lzd_merge.rename(columns = {'Status' : 'Order Status'})
wms_telkom['Platform SKU'] = wms_telkom['Platform SKU'].astype(str)

temp_cek_telkom = lzd_merge.merge(wms_telkom[['Customer Order No.', 'Platform SKU']].drop_duplicates(), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Customer Order No.', 'Platform SKU']).set_index(lzd_merge.index)
temp_cek_telkom = temp_cek_telkom[temp_cek_telkom['Order Number'].isin(wms_telkom['Customer Order No.'])]
temp_telkom = lzd_merge.iloc[temp_cek_telkom.index]

temp_telkom['Order Number'] = temp_telkom['Order Number'].astype(str)
wms_telkom['Customer Order No.'] = wms_telkom['Customer Order No.'].astype(str)

temp_telkom['Real SKU'] = temp_telkom['Real SKU'].astype(str).str.replace('.0', '', regex = False)
wms_telkom['Platform SKU'] = wms_telkom['Platform SKU'].astype(str)

temp_telkom = temp_telkom.merge(wms_telkom.drop_duplicates(['Customer Order No.', 'Platform SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Customer Order No.', 'Platform SKU'])

temp_telkom['Warehouse Quantity'] = temp_telkom['Warehouse Quantity'] * temp_telkom['Qty. Invoiced']/temp_telkom.groupby(['Order Number', 'Real SKU'])['Qty. Invoiced'].transform('sum')


indeks = temp_telkom[(temp_telkom['Item Name'].astype(str).str.contains('-Rasa', regex = False)) & ~(temp_telkom['Item Name'].astype(str).str.contains(' -Rasa', regex = False))].index.to_list()
temp_telkom['Item Name'][indeks] = temp_telkom['Item Name'].astype(str).str.replace('-Rasa', ' - Rasa', regex = False)

indeks = temp_telkom[(temp_telkom['Item Name'].astype(str).str.contains('-Flavor', regex = False)) & ~(temp_telkom['Item Name'].astype(str).str.contains(' -Flavor', regex = False))].index.to_list()
temp_telkom['Item Name'][indeks] = temp_telkom['Item Name'].astype(str).str.replace('-Flavor', ' - Flavor', regex = False)

indeks = temp_telkom[(temp_telkom['Bundle Name'].astype(str).str.contains('-Rasa', regex = False)) & ~(temp_telkom['Bundle Name'].astype(str).str.contains(' -Rasa', regex = False))].index.to_list()
temp_telkom['Bundle Name'][indeks] = temp_telkom['Bundle Name'].astype(str).str.replace('-Rasa', ' - Rasa', regex = False)

indeks = temp_telkom[(temp_telkom['Bundle Name'].astype(str).str.contains('-Flavor', regex = False)) & ~(temp_telkom['Bundle Name'].astype(str).str.contains(' -Flavor', regex = False))].index.to_list()
temp_telkom['Bundle Name'][indeks] = temp_telkom['Bundle Name'].astype(str).str.replace('-Flavor', ' - Flavor', regex = False)


temp_telkom_bundle = temp_telkom[temp_telkom['Brand'] == 'Bundle']

temp_buat_bundle = temp_telkom.groupby(['Order Number', 'Bundle Name']).agg({'WH' : 'first', 'Status' : 'first', 'Warehouse Quantity' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Warehouse Quantity'] = temp_buat_bundle['Warehouse Quantity']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

temp_telkom_bundle = temp_telkom_bundle.merge(temp_buat_bundle.drop_duplicates(['Order Number', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Item Name'], right_on = ['Order Number', 'Bundle Name']).set_index(temp_telkom_bundle.index)
temp_telkom_bundle['Warehouse Quantity_y'] = temp_telkom_bundle['Warehouse Quantity_y']*temp_telkom_bundle['Qty. Invoiced']

temp_telkom['Status'][temp_telkom_bundle.index] = temp_telkom_bundle['Status_y']
temp_telkom['WH'][temp_telkom_bundle.index] = temp_telkom_bundle['WH_y']
temp_telkom['Warehouse Quantity'][temp_telkom_bundle.index] = temp_telkom_bundle['Warehouse Quantity_y']

lzd_merge = lzd_merge.drop(temp_cek_telkom.index, axis = 0)
lzd_merge = lzd_merge.append(temp_telkom, ignore_index = True, sort = False)

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [53]:
## run 33
lzd_merge_null = lzd_merge[(lzd_merge['Order Number'].isin(wms_telkom['Customer Order No.'])) & 
        (lzd_merge['Status'].isnull())]

temp_telkom = lzd_merge_null[lzd_merge_null['Order Number'].isin(wms_telkom['Customer Order No.'])]
wms_telkom2 = wms_telkom.copy()

indeks = wms_telkom2[wms_telkom2['Platform SKU'] == '2101809250'].index.to_list()
wms_telkom2['Platform SKU'][indeks] = '(E)2101809250'

indeks = wms_telkom2[wms_telkom2['Platform SKU'] == '1101996453'].index.to_list()
wms_telkom2['Platform SKU'][indeks] = '(E)1101996453'

indeks = wms_telkom2[wms_telkom2['Platform SKU'] == '2101947250'].index.to_list()
wms_telkom2['Platform SKU'][indeks] = '(E)2101947250'

wms_telkom2['Platform SKU'] = wms_telkom2['Platform SKU'].astype(str).str.replace('2309005305', '2309005300')

temp_telkom = temp_telkom.drop(['WH', 'Customer Order No.', 'Status', 'Platform SKU', 'Warehouse Quantity'], axis = 1)
temp_telkom['Order Number'] = temp_telkom['Order Number'].astype(str)
wms_telkom2['Customer Order No.'] = wms_telkom2['Customer Order No.'].astype(str)

temp_telkom['Real SKU'] = temp_telkom['Real SKU'].astype(str).str.replace('.0', '', regex = False)
wms_telkom2['Platform SKU'] = wms_telkom2['Platform SKU'].astype(str)

temp_telkom = temp_telkom.merge(wms_telkom2.drop_duplicates(['Customer Order No.', 'Platform SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Customer Order No.', 'Platform SKU']).set_index(temp_telkom.index)
temp_telkom['Warehouse Quantity'] = temp_telkom['Warehouse Quantity'] * temp_telkom['Qty. Invoiced']/temp_telkom.groupby(['Order Number', 'Real SKU'])['Qty. Invoiced'].transform('sum')

temp_telkom_bundle = temp_telkom[temp_telkom['Brand'] == 'Bundle']

temp_buat_bundle = temp_telkom.groupby(['Order Number', 'Bundle Name']).agg({'WH' : 'first', 'Status' : 'first', 'Warehouse Quantity' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Warehouse Quantity'] = temp_buat_bundle['Warehouse Quantity']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

temp_telkom_bundle = temp_telkom_bundle.merge(temp_buat_bundle.drop_duplicates(['Order Number', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Item Name'], right_on = ['Order Number', 'Bundle Name']).set_index(temp_telkom_bundle.index)
temp_telkom_bundle['Warehouse Quantity_y'] = temp_telkom_bundle['Warehouse Quantity_y']*temp_telkom_bundle['Qty. Invoiced']

temp_telkom['Status'][temp_telkom_bundle.index] = temp_telkom_bundle['Status_y']
temp_telkom['WH'][temp_telkom_bundle.index] = temp_telkom_bundle['WH_y']
temp_telkom['Warehouse Quantity'][temp_telkom_bundle.index] = temp_telkom_bundle['Warehouse Quantity_y']

lzd_merge['Status'][temp_telkom.index] = temp_telkom['Status']
lzd_merge['WH'][temp_telkom.index] = temp_telkom['WH']
lzd_merge['Warehouse Quantity'][temp_telkom.index] = temp_telkom['Warehouse Quantity']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [54]:
## run 34 # kemuingkinan tidak terkriim dr gudang NFI
lzd_merge[(lzd_merge['Status'].isnull()) &
          (lzd_merge['Order Number'].isin(wms_telkom['Customer Order No.'])) &
          (lzd_merge['Bundle Name'].isnull())].groupby(['Real SKU', 'Real Nama Produk', 'Platform SKU', 'Lazada SKU', 'Item Name'], dropna = False)['Order Number'].first().reset_index()

,Real SKU,Real Nama Produk,Platform SKU,Lazada SKU,Item Name,Order Number
0,(E)1101692318,(Near ED) Lokalate Kopi Pisang Bakar Epe 10 sch,NaN,7361450804_ID-13767048937,LIMITED DEALS : Lokalate Kopi Pisang Bakar Epe...,1117537134399026
1,(E)1101693318,(Near ED) Lokalate Kopi Tape Ketan 10's,NaN,7361498194_ID-13767106316,LIMITED DEALS : Lokalate Kopi Tape Ketan 10 Sa...,1117537134399026
2,1101534453,NutriSari Sweet Mango (40 sch),NaN,1464740088_ID-2722932186,NutriSari Sweet Mango 40 Sachet - Minuman Buah...,1155280045426870
3,1101569326P4,NutriSari Jeruk Peras (160 Sch),NaN,670762151_ID-931748448,NutriSari Jeruk Peras 160 sachet - Minuman Bua...,1125459241101668
4,1101686318,Lokalate Kopi Kawista 10 Sachet Polos,NaN,1575086373_ID-3022088904,Lokalate Kopi Kawista 10 Sachet - Kopi Sachet ...,1161529158754744
5,1101976453,NutriSari Markisa (40 Sch),NaN,882894083_ID-1299222299,NutriSari Markisa 40 Sachet - Minuman Buah Vit...,1155280045426870
6,21014281P24,Hilo School Vanilla Vegiberi Ready To Drink Su...,NaN,1018838036_ID-1526392133,HiLo School Vanilla Vegiberi Ready To Drink 20...,1113966265536726
7,21014281P4,Hilo School Vanilla Vegiberi Ready To Drink Su...,NaN,6600098298_ID-12549308394,HiLo School Vanilla Vegiberi Ready To Drink 20...,1056351518674015
8,2101808450,Hilo Chocolate Taro (10 sch),NaN,6424006520_ID-12186314276,HiLo Chocolate Taro 10 sachet - Minuman Cokela...,1106641941816632
9,2102900130P2,Twin Pack: Tropicana Slim Diabtx 100s,NaN,1640072770_ID-3172162308,Twin Pack - Tropicana Slim Sweetener Diabtx 10...,1093726380316331
10,2309005305,L-Men Protein Crunch BBQ Beef (20gr),NaN,4607124026_ID-8028636853,L-Men Protein Crunch BBQ Beef 20g (12g protein...,1096690676501833

In [55]:
# lzd_merge[['Status','Order Number','Bundle Name','Real SKU', 'Real Nama Produk', 'Platform SKU', 'Lazada SKU', 'Item Name']]
wms_telkom[wms_telkom['Customer Order No.']=='1096690676501833']

      Customer Order No.   Platform SKU     Status      WH  Warehouse Quantity
20950   1096690676501833  (E)2101888360  confirmed  Telkom                 1.0

In [56]:
## run 35
lazada_wms = fbl_wms_data.append(lzd_merge, ignore_index = True, sort = False)

In [57]:
## run 36
lazada_wms = lazada_wms.rename(columns = {'Shipping Fee' : 'Selcen Shipping Fee'})

In [49]:
## SKIP THIS

import os
import pandas as pd
import numpy as np

settlement = pd.DataFrame()
for i in os.listdir('Settlement Project\Lazada\Settlement/'):
    print(i)
    if 'finance' in i:
        if '2021-08-02' in i or '2021-08-09' in i or '2021-08-16' in i or '2021-08-23' in i:
            temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i), sep = ';')
        else :
            temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i))
    else :
        temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i), sep = ';')
    temp['Source'] = i
    true_col = ['Transaction Date', 'Transaction Type', 'Fee Name', 'Transaction Number', 'Details', 'Seller SKU', 'Lazada SKU', 'Amount', 'VAT in Amount', 'WHT Amount', 
                'WHT included in Amount', 'Statement', 'Paid Status', 'Order No.', 'Order Item No.', 'Order Item Status', 'Shipping Provider', 'Shipping Speed', 
                'Shipment Type', 'Reference', 'Comment', 'PaymentRefId', 'Source']
    if temp.columns.to_list() == true_col :
        print('Column sama')
    else:
        print('Column beda')
        print([x for x in true_col if x not in temp.columns.to_list()])
        print([x for x in temp.columns.to_list() if x not in true_col])
    settlement = settlement.append(temp, ignore_index = True, sort = False)
    
list_cat = pd.read_excel(r'Settlement Project\Lazada/Converter Settlement.xlsx')
settlement_cat = settlement.merge(list_cat, how = 'left', left_on = settlement['Fee Name'].str.lower(), right_on = list_cat['Fee Name'].str.lower())
settlement_cat['Order No.'] = settlement_cat['Order No.'].astype(str).str.replace('.0', '', regex = False)

display(settlement_cat[(settlement_cat['Kategori'].isnull()) & (settlement_cat['Statement'].astype(str).str.contains('2022'))].drop_duplicates('Fee Name_x'))

settlement_cat = settlement_cat.drop_duplicates(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Order Item No.'])
settlement_cat = settlement_cat.groupby(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Lazada SKU', 'Kategori'], dropna = False)['Amount'].sum().reset_index()


set_pivot = pd.pivot_table(settlement_cat, values = 'Amount', index = ['Order No.', 'Seller SKU'], columns = 'Kategori', aggfunc=np.sum).reset_index()

051f777d8476cb03b83de06b20ee2867.csv
Column sama
05ec6740ce1c9863706444fd94571534.csv
Column sama
06359794492a90fa9a5448a2b5349d59.csv
Column sama
08f7db7b701aefdb27d7603078059531.csv
Column sama
0c8103f161469f057e726a5a27eb6fb1.csv
Column sama
182cafdc91948090f90646b92e1f07ff.csv
Column sama
18b814eaeffdacdb8f662792367dc833.csv
Column sama
1e1ec864ae4f6f31f2819c8de779b717.csv
Column sama
20d971e9e622a902ad43ef06ee858096.csv
Column sama
23ff3061e197e0a76e546540a5e8176c.csv
Column sama
244b8cb51abf377d50536f0dcd5fd5d3.csv
Column sama
25368e6d8f61f888744fd23db8d76c33.csv

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Column sama
27b80084349d17ae97ad45fa9b572fb9.csv
Column sama
28a47e2268d75afcd72e2c3507c1b470.csv
Column sama
28e4273cc23eb20fe93415550d5288fb.csv
Column sama
2b68b25924b08cdbe5af54dd329382df.csv
Column sama
2f18dea4ee4391fe78cd2bba6f21bc40.csv
Column sama
31d3a9a2962fb129f7178d8a9e3d5051.csv
Column sama
320015fa79e352c0c14229f97c112adc.csv
Column sama
354f985c81a7176f9bd69dfd5925582f.csv
Column sama
371af7983ef02c7f59301418dc178cd9.csv
Column sama
4571049e2005ec66a4bb7364a5d23521.csv
Column sama
45e1c318369d1ad3b16850c69ed2f11e.csv
Column sama
463a9eb1d7a575f5db9175502b7cd253.csv
Column sama
46bf21ca890564acb7ca17bfe305d8a4.csv
Column sama
4d0bbafd438f19b9cebc740c3b8a81da.csv
Column sama
4f0384a67a750edef4e2c0fda1279ca8.csv
Column sama
53dcdb8fa093faf4dcad4e33e479ec8f.csv
Column sama
55e02cfa0609e15018de6d7cf1418016.csv
Column sama
562c29ff3561227170bd3c12af1b87e8.csv
Column sama
565c5521f1eaff7f634dd44052f8f58c.csv
Column sama
638942d1766efe6023dc274329e8e4bf.csv
Column sama
7141d7a454731bdbec0a8a08581dd8b9.csv
Column sama
71cf5b04661d19be253be400326a5b10.csv
Column sama
72dfbd59bfe0125e40b073581321f233.csv
Column sama
746b86fdc0e7f451f7db32f16177ca52.csv
Column sama
7488b49aa1428322e77222da43993e4d.csv
Column sama
791bbf8649302b22b0f0f550d4c466ba.csv
Column sama
7a65cbb427d8c6537e95f8a96d944d72.csv
Column sama
7f46847a7437f754c35b38121f7c0745.csv
Column sama
810afc65ba7df7c999d9aaef68ac3d33.csv
Column sama
817b856beba36f4a68fac4ec4529a4f7.csv
Column sama
81a59406471d6590963e2b17e4f32a79.csv
Column sama
83a88ccb29159abf1d5e1f7b0002c5cd.csv
Column sama
83b0caacb801f68f0be845eb712fdba3.csv
Column sama
89ccadc9bd8b33e4fd992f69e787c82e.csv
Column sama
8a9db88f9565a621b807a084ff9842f8.csv
Column sama
8c65996613c0809fd6798ffb68436402.csv
Column sama
8f821d3bcfa467c8b777a7a6008a3f1c.csv
Column sama
911e61a9367194ba80f1ca60c2d4e974.csv
Column sama
926dfc29f69e2ffca9f3072bc26e690d.csv
Column sama
9291c7582c0f8d99a2f68557f347dd53.csv
Column sama
95a05a5c862c97bbc54fde4cc982fe32.csv
Column sama
9637d7bb4e7ce7ebcf7b3eb203ec4a01.csv
Column sama
96411b3d5d71c55f9934fb3f7ceeaa46.csv
Column sama
9d409d86b38b717ac9efd5918178be52.csv
Column sama
9d7daab7c8bbb69eb0baef9db560587d.csv
Column sama
a1b7b60a728413efcfdedf3b27d4ba2e.csv
Column sama
a4a0a7695d8ce7bba927c6192d042ae0.csv
Column sama
a686019c3f9e55a2d558482af82c324c.csv
Column sama
ab465575845455bc45d86c6396d51fc4.csv
Column sama
ae12f2d2ab8cfafc8e7caeeb4a3eb949.csv
Column sama
b52685c6e3bec74272b037e62893ae04.csv
Column sama
b8223c3fb727592ab3bbae04cfcb75dd.csv
Column sama
bea800ffd1e3b72a6f142226607c5444.csv
Column sama
bf409f7b7e9193b78f38d14bf913bbd7.csv
Column sama
bf78c15451b777af39c17da2915a2748.csv
Column sama
c3a607beadc94ebeff59a843b00afcd4.csv
Column sama
ca88072f158d1df0f491d28eedf6f5b0.csv
Column sama
cb3feaddef4b112903c378cc4f19b465.csv
Column sama
d177e1cdc93775b70ce5e16619449a3e.csv
Column sama
d3ca833712faa4c7e0baf6c34bcc659a.csv
Column sama
d4098be76d122cc0959418229dd63797.csv
Column sama
d79c4d91ae08121510146d09f9505792.csv
Column sama
d7d1881e8bb5eaf94926378b3f20b5ed.csv
Column sama
dca5c168b1bd64d45a7d8d5810abe40f.csv
Column sama
dcb1bdb6da23c32f0efe44cc868746c3.csv
Column sama
dd6586dc67a7e75289a28357b19e5ee1.csv
Column sama
e048400d1d29d6e708019ed5413f9936.csv
Column sama
e29427e5f34a4637596882668460db0d.csv
Column sama
e4901960c30de2dc7225c395c64def59.csv
Column sama
e90a927b09e66c7134b97bbe3e61003a.csv
Column sama
f23a03cff43d3f317e50841fbd000838.csv
Column sama
f56a1678becd0bc229330bf690587588.csv
Column sama
f81cea868711b6869d6bc45bf85b90ff.csv
Column sama
f8cc0c624a14d67ec7a535356dc0051d.csv
Column sama
fc7acd5820374c898fbb046c2216fa2e.csv
Column sama
finance.export.transaction 2021-01-06.csv
Column sama
finance.export.transaction 2021-01-14.csv
Column sama
finance.export.transaction 2021-01-20.csv
Column sama
finance.export.transaction 2021-01-27.csv
Column sama
finance.export.transaction 2021-02-05.csv
Column sama
finance.export.transaction 2021-02-10.csv
Column sama
finance.export.transaction 2021-02-24 (1).csv
Column sama
finance.export.transaction 2021-02-24.csv
Column sama
finance.export.transaction 2021-03-03.csv
Column sama
finance.export.transaction 2021-03-10.csv
Column sama
finance.export.transaction 2021-03-17.csv
Column sama
finance.export.transaction 2021-03-25.csv
Column sama
finance.export.transaction 2021-03-30.csv
Column sama
finance.export.transaction 2021-04-07.csv
Column sama
finance.export.transaction 2021-04-14.csv
Column sama
finance.export.transaction 2021-04-21.csv
Column sama
finance.export.transaction 2021-04-28.csv
Column sama
finance.export.transaction 2021-05-19 (2).csv
Column sama
finance.export.transaction 2021-05-19.csv

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (3,21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Column sama
finance.export.transaction 2021-05-20.csv
Column sama
finance.export.transaction 2021-05-28.csv
Column sama
finance.export.transaction 2021-06-02.csv
Column sama
finance.export.transaction 2021-06-09.csv
Column sama
finance.export.transaction 2021-06-16.csv
Column sama
finance.export.transaction 2021-06-23.csv
Column sama
finance.export.transaction 2021-06-30.csv
Column sama
finance.export.transaction 2021-07-07.csv
Column sama
finance.export.transaction 2021-07-13.csv
Column sama
finance.export.transaction 2021-07-21.csv
Column sama
finance.export.transaction 2021-07-30.csv
Column sama
finance.export.transaction 2021-08-02.csv
Column sama
finance.export.transaction 2021-08-04.csv
Column sama
finance.export.transaction 2021-08-09.csv
Column sama
finance.export.transaction 2021-08-16.csv
Column sama
finance.export.transaction 2021-08-23.csv
Column sama
settlement 1.csv
Column sama
settlement 5.csv

KeyboardInterrupt:

In [ ]:
list_cat = pd.read_excel(r'Settlement Project\Lazada/Converter Settlement.xlsx')
settlement_cat = settlement.merge(list_cat, how = 'left', left_on = settlement['Fee Name'].str.lower(), right_on = list_cat['Fee Name'].str.lower())
settlement_cat['Order No.'] = settlement_cat['Order No.'].astype(str).str.replace('.0', '', regex = False)

display(settlement_cat[(settlement_cat['Kategori'].isnull()) & (settlement_cat['Statement'].astype(str).str.contains('2022'))].drop_duplicates('Fee Name_x'))

settlement_cat = settlement_cat.drop_duplicates(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Order Item No.'])

In [10]:
settlement_cat.to_csv('Rekap Settlement Lazada 2021-2022.csv',sep=";",index=False)

In [58]:
## run 37
import os
import pandas as pd

settlement = pd.DataFrame()
for i in os.listdir('Settlement Project\Lazada\Settlement/'):
    print(i)
    if 'finance' in i:
        if '2021-08-02' in i or '2021-08-09' in i or '2021-08-16' in i or '2021-08-23' in i:
            temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i), sep = ';')
        else :
            temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i))
    else :
        temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i), sep = ';')
    temp['Source'] = i
    true_col = ['Transaction Date', 'Transaction Type', 'Fee Name', 'Transaction Number', 'Details', 'Seller SKU', 'Lazada SKU', 'Amount', 'VAT in Amount', 'WHT Amount', 
                'WHT included in Amount', 'Statement', 'Paid Status', 'Order No.', 'Order Item No.', 'Order Item Status', 'Shipping Provider', 'Shipping Speed', 
                'Shipment Type', 'Reference', 'Comment', 'PaymentRefId', 'Source']
    if temp.columns.to_list() == true_col :
        print('Column sama')
    else:
        print('Column beda')
        print([x for x in true_col if x not in temp.columns.to_list()])
        print([x for x in temp.columns.to_list() if x not in true_col])
    settlement = settlement.append(temp, ignore_index = True, sort = False)

0118e4649624f5da67abea1627f8094c.csv
Column sama
04402c11aa89e293037975d0d0f01792.csv
Column sama
051f777d8476cb03b83de06b20ee2867.csv
Column sama
05ec6740ce1c9863706444fd94571534.csv
Column sama
06359794492a90fa9a5448a2b5349d59.csv
Column sama
08f7db7b701aefdb27d7603078059531.csv
Column sama
0bd3d7eaa70facffdbac788e41eca109.csv
Column sama
0c8103f161469f057e726a5a27eb6fb1.csv
Column sama
150ca316c163487c9c30866b6a8f1140.csv
Column sama
182cafdc91948090f90646b92e1f07ff.csv
Column sama
18b814eaeffdacdb8f662792367dc833.csv
Column sama
1a10817a2fdc1bbe71397ab4ef2d084f.csv
Column sama
1e1ec864ae4f6f31f2819c8de779b717.csv
Column sama
20d971e9e622a902ad43ef06ee858096.csv
Column sama
23ff3061e197e0a76e546540a5e8176c.csv
Column sama
244b8cb51abf377d50536f0dcd5fd5d3.csv
Column sama
25368e6d8f61f888744fd23db8d76c33.csv

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Column sama
27b80084349d17ae97ad45fa9b572fb9.csv
Column sama
28a47e2268d75afcd72e2c3507c1b470.csv
Column sama
28e4273cc23eb20fe93415550d5288fb.csv
Column sama
2b68b25924b08cdbe5af54dd329382df.csv
Column sama
2f18dea4ee4391fe78cd2bba6f21bc40.csv
Column sama
31d3a9a2962fb129f7178d8a9e3d5051.csv
Column sama
320015fa79e352c0c14229f97c112adc.csv
Column sama
354f985c81a7176f9bd69dfd5925582f.csv
Column sama
371af7983ef02c7f59301418dc178cd9.csv
Column sama
4571049e2005ec66a4bb7364a5d23521.csv
Column sama
45e1c318369d1ad3b16850c69ed2f11e.csv
Column sama
463a9eb1d7a575f5db9175502b7cd253.csv
Column sama
46bf21ca890564acb7ca17bfe305d8a4.csv
Column sama
4d0bbafd438f19b9cebc740c3b8a81da.csv
Column sama
4f0384a67a750edef4e2c0fda1279ca8.csv
Column sama
53dcdb8fa093faf4dcad4e33e479ec8f.csv
Column sama
55e02cfa0609e15018de6d7cf1418016.csv
Column sama
562c29ff3561227170bd3c12af1b87e8.csv
Column sama
565c5521f1eaff7f634dd44052f8f58c.csv
Column sama
638942d1766efe6023dc274329e8e4bf.csv
Column sama
6ba34dae524317df6f25f48bbf5766aa.csv
Column sama
7141d7a454731bdbec0a8a08581dd8b9.csv
Column sama
71cf5b04661d19be253be400326a5b10.csv
Column sama
72dfbd59bfe0125e40b073581321f233.csv
Column sama
746b86fdc0e7f451f7db32f16177ca52.csv
Column sama
7488b49aa1428322e77222da43993e4d.csv
Column sama
78623ecdc52b79c80e720261d8a2e742.csv
Column sama
791bbf8649302b22b0f0f550d4c466ba.csv
Column sama
7a65cbb427d8c6537e95f8a96d944d72.csv
Column sama
7f46847a7437f754c35b38121f7c0745.csv
Column sama
810afc65ba7df7c999d9aaef68ac3d33.csv
Column sama
817b856beba36f4a68fac4ec4529a4f7.csv
Column sama
81a59406471d6590963e2b17e4f32a79.csv
Column sama
83a88ccb29159abf1d5e1f7b0002c5cd.csv
Column sama
83b0caacb801f68f0be845eb712fdba3.csv
Column sama
8758ed7ab34489057c70c98861a00d87.csv
Column sama
89ccadc9bd8b33e4fd992f69e787c82e.csv
Column sama
8a9db88f9565a621b807a084ff9842f8.csv
Column sama
8c65996613c0809fd6798ffb68436402.csv
Column sama
8f821d3bcfa467c8b777a7a6008a3f1c.csv
Column sama
9003aefdd4dcccb9534e8ac6e1e54a49.csv
Column sama
911e61a9367194ba80f1ca60c2d4e974.csv
Column sama
914be656bf4ca410410bc41e24055029.csv
Column sama
926dfc29f69e2ffca9f3072bc26e690d.csv
Column sama
9291c7582c0f8d99a2f68557f347dd53.csv
Column sama
95a05a5c862c97bbc54fde4cc982fe32.csv
Column sama
9637d7bb4e7ce7ebcf7b3eb203ec4a01.csv
Column sama
96411b3d5d71c55f9934fb3f7ceeaa46.csv
Column sama
9d409d86b38b717ac9efd5918178be52.csv
Column sama
9d7daab7c8bbb69eb0baef9db560587d.csv
Column sama
a1b7b60a728413efcfdedf3b27d4ba2e.csv
Column sama
a4a0a7695d8ce7bba927c6192d042ae0.csv
Column sama
a686019c3f9e55a2d558482af82c324c.csv
Column sama
ab465575845455bc45d86c6396d51fc4.csv
Column sama
ae12f2d2ab8cfafc8e7caeeb4a3eb949.csv
Column sama
b52685c6e3bec74272b037e62893ae04.csv
Column sama
b8223c3fb727592ab3bbae04cfcb75dd.csv
Column sama
bb86fc52206698623ea8714f86d9e4fb.csv
Column sama
bea800ffd1e3b72a6f142226607c5444.csv
Column sama
bf409f7b7e9193b78f38d14bf913bbd7.csv
Column sama
bf78c15451b777af39c17da2915a2748.csv
Column sama
c3a607beadc94ebeff59a843b00afcd4.csv
Column sama
c45e68018d600bc7be3b4011009eba5a.csv
Column sama
c5e79637e601413471b7f8e731b60291.csv
Column sama
ca88072f158d1df0f491d28eedf6f5b0.csv
Column sama
cb3feaddef4b112903c378cc4f19b465.csv
Column sama
d177e1cdc93775b70ce5e16619449a3e.csv
Column sama
d3ca833712faa4c7e0baf6c34bcc659a.csv
Column sama
d4098be76d122cc0959418229dd63797.csv
Column sama
d79c4d91ae08121510146d09f9505792.csv
Column sama
d7d1881e8bb5eaf94926378b3f20b5ed.csv
Column sama
dca5c168b1bd64d45a7d8d5810abe40f.csv
Column sama
dcb1bdb6da23c32f0efe44cc868746c3.csv
Column sama
dd337a6097460d04f52b3d83b9930b35.csv
Column sama
dd6586dc67a7e75289a28357b19e5ee1.csv
Column sama
e048400d1d29d6e708019ed5413f9936.csv
Column sama
e29427e5f34a4637596882668460db0d.csv
Column sama
e4901960c30de2dc7225c395c64def59.csv
Column sama
e90a927b09e66c7134b97bbe3e61003a.csv
Column sama
f07398f6b0c1e6ef0cfbe11fa1cf13eb.csv
Column sama
f23a03cff43d3f317e50841fbd000838.csv
Column sama
f56a1678becd0bc229330bf690587588.csv
Column sama
f81cea868711b6869d6bc45bf85b90ff.csv
Column sama
f8cc0c624a14d67ec7a535356dc0051d.csv
Column sama
fc7acd5820374c898fbb046c2216fa2e.csv
Column sama
finance.export.transaction 2021-01-06.csv
Column sama
finance.export.transaction 2021-01-14.csv
Column sama
finance.export.transaction 2021-01-20.csv
Column sama
finance.export.transaction 2021-01-27.csv
Column sama
finance.export.transaction 2021-02-05.csv
Column sama
finance.export.transaction 2021-02-10.csv
Column sama
finance.export.transaction 2021-02-24 (1).csv
Column sama
finance.export.transaction 2021-02-24.csv
Column sama
finance.export.transaction 2021-03-03.csv
Column sama
finance.export.transaction 2021-03-10.csv
Column sama
finance.export.transaction 2021-03-17.csv
Column sama
finance.export.transaction 2021-03-25.csv
Column sama
finance.export.transaction 2021-03-30.csv
Column sama
finance.export.transaction 2021-04-07.csv
Column sama
finance.export.transaction 2021-04-14.csv
Column sama
finance.export.transaction 2021-04-21.csv
Column sama
finance.export.transaction 2021-04-28.csv
Column sama
finance.export.transaction 2021-05-19 (2).csv
Column sama
finance.export.transaction 2021-05-19.csv

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (3,21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Column sama
finance.export.transaction 2021-05-20.csv
Column sama
finance.export.transaction 2021-05-28.csv
Column sama
finance.export.transaction 2021-06-02.csv
Column sama
finance.export.transaction 2021-06-09.csv
Column sama
finance.export.transaction 2021-06-16.csv
Column sama
finance.export.transaction 2021-06-23.csv
Column sama
finance.export.transaction 2021-06-30.csv
Column sama
finance.export.transaction 2021-07-07.csv
Column sama
finance.export.transaction 2021-07-13.csv
Column sama
finance.export.transaction 2021-07-21.csv
Column sama
finance.export.transaction 2021-07-30.csv
Column sama
finance.export.transaction 2021-08-02.csv
Column sama
finance.export.transaction 2021-08-04.csv
Column sama
finance.export.transaction 2021-08-09.csv
Column sama
finance.export.transaction 2021-08-16.csv
Column sama
finance.export.transaction 2021-08-23.csv
Column sama
settlement 1.csv
Column sama
settlement 5.csv
Column sama
settlement2.csv
Column sama
settlement3.csv
Column sama
settlement4.csv
Column sama
settlement6.csv
Column sama
settlement7.csv
Column sama
settlement8.csv
Column sama

In [59]:
## for backup
settlement_copy=settlement.copy()

In [157]:
## for backup
settlement=settlement_copy.copy()

In [60]:
##Run 37.1
list_cat = pd.read_excel(r'Settlement Project\Lazada/Converter Settlement.xlsx')
settlement_cat = settlement.merge(list_cat, how = 'left', left_on = settlement['Fee Name'].str.lower(), right_on = list_cat['Fee Name'].str.lower())
settlement_cat['Order No.'] = settlement_cat['Order No.'].astype(str).str.replace('.0', '', regex = False)

display(settlement_cat[(settlement_cat['Kategori'].isnull()) & (settlement_cat['Statement'].astype(str).str.contains('2023'))].drop_duplicates('Fee Name_x'))

settlement_cat = settlement_cat.drop_duplicates(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Order Item No.'])
settlement_cat = settlement_cat.groupby(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Lazada SKU', 'Kategori'], dropna = False)['Amount'].sum().reset_index()


set_pivot = pd.pivot_table(settlement_cat, values = 'Amount', index = ['Order No.', 'Seller SKU'], columns = 'Kategori', aggfunc=np.sum).reset_index()


# indeks = lazada_wms[(lazada_wms['Order Number'].isin(['559843140940047', '570053517364893', '575957908200754',
#        '577436614667847', '581773151953393', '580784173888189',
#        '579252087390821', '583280309680693', '584406184163482',
#        '588374178583373', '593364733555669', '588645498508270',
#        '594172356552868', '589503459931050', '594020923234251',
#        '589428225222831', '593962925532162', '589367060015532',
#        '593877586114364', '593864327866052', '593837547275614',
#        '593305539632042', '593345977890705', '593756924841819',
#        '593731525177823', '593702979642006', '593694337695107',
#        '593680923404018', '588995293082147', '593555385780987',
#        '593293552996555', '588965810091534', '588954206670966',
#        '593491929312305', '593401902198461', '588819489968863',
#        '593249764268270', '593185587440558', '593129198674005',
#        '593107598461876', '588539419232974', '593104986085405',
#        '593092994762343', '593073368079777', '590367025213685',
#        '590358640068270', '594913320926038', '594884156934733',
#        '594869579365652', '590258088924976', '590234288354116',
#        '590254608264809', '594793350250446', '590199653348313',
#        '594718779068892', '594725942611774', '590119219895375',
#        '594661371334535', '594621183568903', '590054248795184',
#        '590013674417216', '590053015915262', '594577173324152',
#        '594561965181950', '589966062726742', '594527372175614',
#        '589927810658895', '589865638770513', '589856040817448',
#        '589825854186704', '589771800551067', '594284550997184',
#        '589706807705424', '594261317584967', '594199931063036',
#        '595939384524081', '595929398398589', '595904587150546',
#        '595830789026275', '591134298798589', '595780535198589',
#        '591094215398589', '595762388498589', '591153013325708',
#        '595750941320645', '595654931855706', '595684122674005',
#        '591035295324258', '595638902189716', '595617318036237',
#        '595582345878430', '590978824279055', '595457520058163',
#        '590827657814707', '590804894081596', '590791025107124',
#        '595377128277618', '595376915530919', '595234116430750',
#        '590644410151423', '595179186328420', '595157561508697',
#        '590536471216064', '600802357828790', '596112234729713',
#        '596012073162610', '595908480071136', '595877888916064',
#        '600582582342683', '595876035754794', '600510709997379',
#        '595776012117106', '595730202237782', '595582410941333',
#        '595521094823473', '595041632796594', '594991806324076',
#        '599604199324530', '599583760458961', '594935671784084',
#        '599577115751594', '594902865242113', '599556918276104',
#        '599544718368129', '594790437300144', '594752630645222',
#        '599357309627724', '599294380026506', '599182571538223',
#        '599112726973387', '594477412023933', '598899572856620',
#        '594224465085127', '594196086344168', '598784949947209',
#        '598711795152111', '594083495533791', '593993894924689',
#        '593920238449841', '593889617803385', '593865053092399',
#        '598063766922849', '593817088095184', '598401164078318',
#        '593783046561716', '598348315439422', '593731216980820',
#        '593693880837137', '593683844664323', '598067311522492',
#        '593440016191958', '598027924989819', '593361297377935',
#        '593300093127907', '593328627600361', '597194072187590',
#        '601862391003411', '596959259188060', '596948269606644',
#        '601622114150736', '596896672440727', '596850884618023',
#        '601374998521519', '601425527089233', '596754622322755',
#        '596710658162799', '601236119027872', '602944935032754',
#        '602945731602975', '598201876696064', '602890912032824',
#        '602700501288223', '598002235480992', '602647362437495',
#        '602665902282685', '602591538164879', '597916028988860',
#        '602583125588451', '597905018609822', '597869053377392',
#        '602519558256799', '597824057268488', '602467746523267',
#        '602382330971431', '602359924639337', '602340706687825',
#        '602307957414034', '597344417954512', '601965346879402',
#        '603778367893693', '603735704477524', '598876237481883',
#        '603430962325847', '598744855716768', '598735288226863',
#        '598741473840500', '603316134465448', '603322317613372',
#        '598651479420102', '603244518842123', '598499685419970',
#        '598482092634877', '603134945969772', '598466236693023',
#        '598455639149416', '598432061497459', '599637452132800',
#        '599612035376841', '604162768072064', '604158531241374',
#        '599364833007914', '603950566489370', '603943948217185',
#        '603895127652459', '606081301072062', '606010105343029',
#        '601234631674671', '601209255605424', '605718700173135',
#        '600931421886752', '605537906427543', '600671605813389',
#        '605293965672243', '605284158010790', '605205995065167',
#        '605052548095184', '604969186516768', '604695317327158',
#        '604671397611645', '604661196994892', '601793824281742',
#        '606452707196321', '601716056421857', '602072032874148',
#        '606675172494148', '602011296948313', '601981852693595',
#        '607081541959909', '602274011161069', '609265912710790',
#        '609162585439503', '609178510485567', '604032038469420',
#        '608593756577486', '603730818024267', '608102558873387',
#        '603402256711078', '603363812810866', '603160081407487',
#        '610106182769178', '609989532190676', '605001864235652',
#        '609602399145526', '609587357293108', '604823886767992',
#        '610701155545775', '605791698895484', '610200544132538',
#        '611234981563429', '606249450081272', '606115899390720',
#        '611824116558135', '611779194588223', '611793103063246',
#        '607015245183311', '613791139290373', '608935248776162',
#        '608906255379668', '613661328981358', '608749062894551',
#        '607532848220093', '609674051400474', '609593271342019',
#        '609499009318865', '609211614978639', '615055360901433',
#        '614848523561978', '614765992993023', '615322732997379',
#        '611736898514328', '611245260542025', '618164168220507',
#        '613226069177192', '617684719984473', '617324982915475',
#        '611984865482003', '616764349229865', '616695142439870',
#        '611901851728349', '645374694477695', '645373896877695',
#        '651866515266131', '578611062239848'])) &
#                    (lazada_wms['Item Name'] == 'Tropicana Slim Sirup Cocopandan 750ml - Sirup Bebas Gula')].index.to_list()
# lazada_wms['Lazada SKU'][indeks] = 'TR086WNAACKQ4RANID-28082439'

# indeks = set_pivot[set_pivot['Seller SKU'].astype(str) == 'PE14E23H63B61'].index.to_list()
# set_pivot['Seller SKU'][indeks] = 'PE23H63B18B61'

# indeks = set_pivot[set_pivot['Seller SKU'].astype(str) == 'PE14E23H63B61'].index.to_list()
# set_pivot['Seller SKU'][indeks] = 'PE23H63B18B61'

# indeks = set_pivot[set_pivot['Seller SKU'].astype(str) == '(B)2101813443P4'].index.to_list()
# set_pivot['Seller SKU'][indeks] = 'PH63(2)B61(2)'

# indeks = set_pivot[set_pivot['Seller SKU'].astype(str) == '2101813443P4'].index.to_list()
# set_pivot['Seller SKU'][indeks] = 'PH63(2)B61(2)'

# indeks = set_pivot[set_pivot['Seller SKU'].astype(str) == '(B)2101845443P4'].index.to_list()
# set_pivot['Seller SKU'][indeks] = '2101845443P4'

# index = lazada_wms[lazada_wms['SKU'].astype(str) == '2101845443P4'].index.to_list()
# lazada_wms['Brand'][index] = 'Bundle'
# lazada_wms['Bundle Flag'][index] = 'Bundle'
# lazada_wms['Parent Item'][index] = 'HiLo Ketan Hitam 40 Sch'

set_pivot['Order No.'] = set_pivot['Order No.'].astype(str)
set_pivot['Seller SKU'] = set_pivot['Seller SKU'].astype(str)


### tambahan timo jan 23
set_pivot.loc[set_pivot['Seller SKU']=='(E)2101492P04','Seller SKU']='(E)2101492P4'

lazada_wms['Order Number'] = lazada_wms['Order Number'].astype(str)
lazada_wms['Real SKU'] = lazada_wms['Real SKU'].astype(str)

no_prop = lazada_wms[lazada_wms['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]
lazada_prop = lazada_wms[~lazada_wms['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]

bundle_wms = lazada_prop[lazada_prop['Bundle Name'].notnull()]
lazada_set = lazada_prop[lazada_prop['Bundle Name'].isnull()]

lazada_set = lazada_set.merge(set_pivot.drop_duplicates(['Order No.', 'Seller SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Order No.', 'Seller SKU'])
lazada_set['BTL Cost'] = lazada_set['BTL Cost'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number', 'Item Name'])['Total Net Before PPN'].transform('sum')
lazada_set['ComFee'] = lazada_set['ComFee'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number', 'Item Name'])['Total Net Before PPN'].transform('sum')
lazada_set['FullFee'] = lazada_set['FullFee'].fillna(0) * lazada_set['Qty. Invoiced']/lazada_set.groupby(['Order Number', 'Item Name'])['Qty. Invoiced'].transform('sum')
lazada_set['Payment Fee'] = lazada_set['Payment Fee'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number', 'Item Name'])['Total Net Before PPN'].transform('sum')
lazada_set['Shipping Fee'] = lazada_set['Shipping Fee'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number', 'Item Name'])['Total Net Before PPN'].transform('sum')
lazada_set['Total Transfer'] = lazada_set['Total Transfer'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number', 'Item Name'])['Total Net Before PPN'].transform('sum')

bundle_set = bundle_wms.merge(lazada_set.groupby(['Order Number', 'Item Name'])[['BTL Cost', 'ComFee', 'FullFee','Payment Fee', 'Shipping Fee', 'Total Transfer']].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Bundle Name'], right_on = ['Order Number', 'Item Name'])
display(bundle_set[['BTL Cost']].head(5))
bundle_set = bundle_set.rename(columns = {'Item Name_x' : 'Item Name'})
bundle_set = bundle_set.drop('Item Name_y', axis = 1)

bundle_set['BTL Cost'] = bundle_set['BTL Cost'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundle_set['ComFee'] = bundle_set['ComFee'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundle_set['FullFee'] = bundle_set['FullFee'].fillna(0) * bundle_set['Qty. Invoiced']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Qty. Invoiced'].transform('sum')
bundle_set['Payment Fee'] = bundle_set['Payment Fee'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundle_set['Shipping Fee'] = bundle_set['Shipping Fee'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundle_set['Total Transfer'] = bundle_set['Total Transfer'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')

lazada_set = lazada_set.append(bundle_set, ignore_index = True, sort = False)
lazada_set = lazada_set.append(no_prop, ignore_index = True, sort = False)

no_details = settlement[(settlement['Details'].isnull()) & (settlement['Order No.'].notnull())]
no_details_cat = no_details.merge(list_cat, how = 'left', left_on = no_details['Fee Name'].str.lower(), right_on = list_cat['Fee Name'].str.lower())
no_details_cat['Order No.'] = no_details_cat['Order No.'].astype(str).str.replace('.0', '', regex = False)
no_details_cat = no_details_cat.drop_duplicates(['key_0', 'Fee Name_x', 'Order No.', 'Transaction Number'])
no_details_cat = no_details_cat.groupby(['key_0', 'Fee Name_x', 'Order No.', 'Kategori'])['Amount'].sum().reset_index()
no_details_cat = no_details_cat[no_details_cat['Order No.'] != '0']

no_details_pivot = pd.pivot_table(no_details_cat, values = 'Amount', index = ['Order No.'], columns = 'Kategori', aggfunc=np.sum).reset_index()

no_prop = lazada_set[lazada_set['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]
lazada_prop = lazada_set[~lazada_set['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]

bundle_wms = lazada_prop[lazada_prop['Bundle Name'].notnull()]
lazada_set = lazada_prop[lazada_prop['Bundle Name'].isnull()]

lazada_set = lazada_set.merge(no_details_pivot, how = 'left', left_on = ['Order Number'], right_on = ['Order No.'])
if 'BTL Cost_x' in lazada_set.columns: ## timo Mar 23
    lazada_set['BTL Cost'] = lazada_set['BTL Cost_x'] + (lazada_set['BTL Cost_y'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number'])['Total Net Before PPN'].transform('sum'))
# lazada_set['ComFee'] = lazada_set['ComFee_x'] + (lazada_set['ComFee_y'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number'])['Total Net Before PPN'].transform('sum'))
# lazada_set['FullFee'] = lazada_set['FullFee_x'] + (lazada_set['FullFee_y'].fillna(0) * lazada_set['Qty. Invoiced']/lazada_set.groupby(['Order Number'])['Qty. Invoiced'].transform('sum'))
# lazada_set['Payment Fee'] = lazada_set['Payment Fee_x'] + (lazada_set['Payment Fee_y'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number'])['Total Net Before PPN'].transform('sum'))
# lazada_set['Shipping Fee'] = lazada_set['Shipping Fee_x'] + (lazada_set['Shipping Fee_y'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number'])['Total Net Before PPN'].transform('sum'))
# lazada_set['Total Transfer'] = lazada_set['Total Transfer_x'] + (lazada_set['Total Transfer_y'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number'])['Total Net Before PPN'].transform('sum'))

bundle_wms = bundle_wms.drop(['BTL Cost'], axis = 1)
bundle_set = bundle_wms.merge(lazada_set.groupby(['Order Number', 'Item Name'])[['BTL Cost']].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Bundle Name'], right_on = ['Order Number', 'Item Name'])
bundle_set = bundle_set.rename(columns = {'Item Name_x' : 'Item Name'})
bundle_set = bundle_set.drop('Item Name_y', axis = 1)

bundle_set['BTL Cost'] = bundle_set['BTL Cost'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')

lazada_set = lazada_set.append(bundle_set, ignore_index = True, sort = False)
lazada_set = lazada_set.append(no_prop, ignore_index = True, sort = False)

no_details['Order No.'] = no_details['Order No.'].astype(str).str.replace('.0', '', regex = False)

# settlement_cat = settlement.merge(list_cat, how = 'left', left_on = settlement['Fee Name'].str.lower(), right_on = list_cat['Fee Name'].str.lower())
# settlement_cat['Order No.'] = settlement_cat['Order No.'].astype(str).str.replace('.0', '', regex = False)

set_refund = settlement_cat[settlement_cat['Fee Name_x'] == 'Reversal Item Price'][['Order No.', 'Seller SKU']]

bundle_payment = lazada_set[lazada_set['Bundle Name'].notnull()]
lazada_payment = lazada_set[lazada_set['Bundle Name'].isnull()]

indeks = lazada_payment[lazada_payment['Order No._x'].notnull()].index.to_list()
lazada_payment['Paid'] = np.nan
lazada_payment['Paid'][indeks] = 'Paid'
lazada_payment['Paid'] = lazada_payment['Paid'].fillna('Unpaid')

indeks = lazada_payment[(lazada_payment['Paid'] == 'Paid') & (lazada_payment['Total Transfer'] == 0)].index.to_list()
lazada_payment['Paid'][indeks] = 'Refund'

lazada_payment = lazada_payment.drop('Order No._y', axis = 1)

gimmick_tapi_bundle = ['(B)2309005305P3', '(B)2309005300P3']

paid_order = lazada_payment[(lazada_payment['Paid'] == 'Paid') & (lazada_payment['Brand'] == 'L-Men')]['Order Number'].unique()
indeks = lazada_payment[(lazada_payment['Real SKU'].isin(gimmick_tapi_bundle)) &
                       (lazada_payment['Order Number'].isin(paid_order))].index.to_list()
lazada_payment['Paid'][indeks] = 'Paid'

temp = lazada_payment.merge(set_refund.drop_duplicates(['Order No.', 'Seller SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Order No.', 'Seller SKU']).set_index(lazada_payment.index)
indeks = temp[temp['Order No._y'].notnull()].index.to_list()
lazada_payment['Paid'][indeks] = 'Half Paid'

indeks = lazada_payment[(lazada_payment['Paid'] == 'Half Paid') & (lazada_payment['Total Transfer'] == 0)].index.to_list()
lazada_payment['Paid'][indeks] = 'Refund'

temp_status = lazada_payment.drop_duplicates(['Order Number', 'Paid']).sort_values(['Paid']).groupby('Order Number')['Paid'].agg(lambda x: ','.join(x)).reset_index()
temp_status = temp_status.rename(columns = {'Paid' : 'Order Paid'})

lazada_payment = lazada_payment.merge(temp_status, how = 'left', on = 'Order Number')

# order_nol = lazada_payment[lazada_payment['Paid Order'] == 'Paid'].groupby('Order Number')['Total Transfer'].sum().reset_index()
# half_nol = order_nol[(order_nol['Total Transfer'] != 0)]['Order Number'].unique()
# full_nol = order_nol[(order_nol['Total Transfer'] == 0) ]['Order Number'].unique()
# orderitem_nol = lazada_payment[(lazada_payment['Total Transfer'] == 0)]['Order Number'].unique()

# indeks = lazada_payment[(lazada_payment['Order Number'].isin(orderitem_nol)) & (lazada_payment['Order Number'].isin(full_nol) & (lazada_payment['Paid'] == 'Paid'))].index.to_list()
# lazada_payment['Order Paid'][indeks] = 'Full Nol'

# indeks = lazada_payment[(lazada_payment['Order Number'].isin(orderitem_nol)) & (lazada_payment['Order Number'].isin(half_nol) & (lazada_payment['Paid'] == 'Paid'))].index.to_list()
# lazada_payment['Order Paid'][indeks] = 'Half Nol'


bundle_payment = bundle_payment.merge(lazada_payment.groupby(['Order Number', 'Item Name'])[['Paid', 'Order Paid']].first().reset_index(), how = 'left', left_on = ['Order Number', 'Bundle Name'], right_on = ['Order Number', 'Item Name'])
bundle_payment = bundle_payment.rename(columns = {'Item Name_x' : 'Item Name'})
bundle_payment = bundle_payment.drop('Item Name_y', axis = 1)

lazada_payment = lazada_payment.append(bundle_payment, ignore_index = True, sort = False)

,key_0,Transaction Date,Transaction Type,Fee Name_x,Transaction Number,Details,Seller SKU,Lazada SKU,Amount,VAT in Amount,WHT Amount,WHT included in Amount,Statement,Paid Status,Order No.,Order Item No.,Order Item Status,Shipping Provider,Shipping Speed,Shipment Type,Reference,Comment,PaymentRefId,Source,Unnamed: 0,Fee Name_y,Kategori,Note
0,fbl item handling fee,30-Apr-2023,3P Services-Logistics,FBL Item Handling Fee,FO069615167366496,Tropicana Slim Sweetener Classic 100 sachet - ...,2102500130,TR086WNAADWPB2ANID-30660761,-2997.0,0.0,0.0,No,30 Apr 2023 - 30 Apr 2023,paid,1155703924262264,1.1557e+15,Delivered,NaN,standard,Own Warehouse,1.1557e+15,NaN,NaN,0118e4649624f5da67abea1627f8094c.csv,NaN,NaN,NaN,NaN
26731,lazflash extra/everyday below $9.99 subsidy,27-Apr-2023,Orders-Lazada Fees,LazFlash Extra/Everyday Below $9.99 Subsidy,1150511771120038,NutriSari American Sweet Orange 160 sachet - M...,1101909331P4,670676200_ID-931444373,25000.0,0.0,0.0,No,27 Apr 2023 - 27 Apr 2023,paid,1150511771020038,1.15051e+15,Delivered,NaN,standard,Own Warehouse,1.15051e+15,NaN,NaN,0118e4649624f5da67abea1627f8094c.csv,NaN,NaN,NaN,NaN
1776969,seller incentive,03-Apr-2023,Other Services-Sales,Seller Incentive,ID109XE-ZQQX2F2-230403,NaN,NaN,NaN,1652520.0,0.0,0.0,No,03 Apr 2023 - 03 Apr 2023,paid,0,NaN,NaN,NaN,NaN,NaN,0,Jan'23 - FS Max & EDC Program Rebate,NaN,78623ecdc52b79c80e720261d8a2e742.csv,NaN,NaN,NaN,NaN
2216378,shipping fee claims,19-Apr-2023,Orders-Claims,Shipping Fee Claims,1139915946578008,NutriSari Jeruk Nipis 40 Sachet - Minuman Buah...,1101558453,1040214653_ID-1580494324,5.0,0.0,0.0,No,19 Apr 2023 - 19 Apr 2023,paid,1139915946378008,1.13992e+15,Delivered,Rara,express,Dropshipping,1.13992e+15,Reimbursement for Shipping fee-Incorrect packa...,NaN,914be656bf4ca410410bc41e24055029.csv,NaN,NaN,NaN,NaN
3050055,fbl item handling fee discount,02-Apr-2023,3P Services-Logistics,FBL Item Handling Fee Discount,FO017515001124701,Twin Pack - Tropicana Slim Sweetener Diabtx 10...,2102900130P2,1640072770_ID-3172162308,222.0,0.0,0.0,No,02 Apr 2023 - 02 Apr 2023,paid,1114625602303279,1.11463e+15,Delivered,NaN,standard,Own Warehouse,1.11463e+15,NaN,NaN,c45e68018d600bc7be3b4011009eba5a.csv,NaN,NaN,NaN,NaN

   BTL Cost
0    -324.0
1    -324.0
2       0.0
3   -4750.0
4  -10530.0

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:209: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:220: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:221: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1061: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:222: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:225: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1061: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:241: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [61]:
### no details -> apa ada btl cost nya?

In [62]:
no_details['Fee Name'].unique()#_cat['Kategori'].unique()

array(['Wrong Weight Adjustment', 'Sponsored Affiliates',
       'FBL Relabeling Fee', 'FBL Bundling Fee', 'Storage Fee',
       'Sponsored Affiliates Refund', 'Seller Incentive',
       'Sponsored Discovery - Top up',
       'FBL Handling fee refund - correction for overcharge'],
      dtype=object)

In [63]:
### run 38

# import os
# import pandas as pd

# settlement = pd.DataFrame()
# for i in os.listdir('Settlement Project\Lazada\Settlement/'):
#     print(i)
#     if 'finance' in i:
#         if '2021-08-02' in i or '2021-08-09' in i or '2021-08-16' in i or '2021-08-23' in i:
#             temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i), sep = ';')
#         else :
#             temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i))
#     else :
#         temp = pd.read_csv('Settlement Project\Lazada\Settlement/' + str(i), sep = ';')
#     temp['Source'] = i
#     true_col = ['Transaction Date', 'Transaction Type', 'Fee Name', 'Transaction Number', 'Details', 'Seller SKU', 'Lazada SKU', 'Amount', 'VAT in Amount', 'WHT Amount', 
#                 'WHT included in Amount', 'Statement', 'Paid Status', 'Order No.', 'Order Item No.', 'Order Item Status', 'Shipping Provider', 'Shipping Speed', 
#                 'Shipment Type', 'Reference', 'Comment', 'PaymentRefId', 'Source']
#     if temp.columns.to_list() == true_col :
#         print('Column sama')
#     else:
#         print('Column beda')
#         print([x for x in true_col if x not in temp.columns.to_list()])
#         print([x for x in temp.columns.to_list() if x not in true_col])
#     settlement = settlement.append(temp, ignore_index = True, sort = False)
    
list_cat = pd.read_excel(r'Settlement Project\Lazada/Converter Settlement.xlsx')
settlement_cat = settlement.merge(list_cat, how = 'left', left_on = settlement['Fee Name'].str.lower(), right_on = list_cat['Fee Name'].str.lower())
settlement_cat['Order No.'] = settlement_cat['Order No.'].astype(str).str.replace('.0', '', regex = False)
settlement_cat = settlement_cat.drop_duplicates(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Order Item No.'])
settlement_cat = settlement_cat.groupby(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Lazada SKU', 'Kategori'], dropna = False)['Amount'].sum().reset_index()

settlement_cat[settlement_cat['Kategori'].isnull()]['Fee Name_x'].unique()

array(['FBL Item Handling Fee', 'FBL Item Handling Fee Discount',
       'LazFlash Extra/Everyday Below $9.99 Subsidy', 'Seller Incentive',
       'Shipping Fee Claims', 'Sponsored Discovery - Top up', nan],
      dtype=object)

In [64]:
### run 39
settlement_cat = settlement.merge(list_cat, how = 'left', left_on = settlement['Fee Name'].str.lower(), right_on = list_cat['Fee Name'].str.lower())
settlement_cat['Order No.'] = settlement_cat['Order No.'].astype(str).str.replace('.0', '', regex = False)

display(settlement_cat[(settlement_cat['Kategori'].isnull()) &
              (settlement_cat['Statement'].astype(str).str.contains('2022'))].drop_duplicates('Fee Name_x')
       )
settlement_cat = settlement_cat.drop_duplicates(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Order Item No.'])
settlement_cat = settlement_cat.groupby(['key_0', 'Fee Name_x', 'Order No.', 'Seller SKU', 'Lazada SKU', 'Kategori'], dropna = False)['Amount'].sum().reset_index()

Empty DataFrame
Columns: [key_0, Transaction Date, Transaction Type, Fee Name_x, Transaction Number, Details, Seller SKU, Lazada SKU, Amount, VAT in Amount, WHT Amount, WHT included in Amount, Statement, Paid Status, Order No., Order Item No., Order Item Status, Shipping Provider, Shipping Speed, Shipment Type, Reference, Comment, PaymentRefId, Source, Unnamed: 0, Fee Name_y, Kategori, Note]
Index: []

In [65]:
settlement[settlement['Fee Name'].isnull()]['Statement'].unique()
# settlement['Fee Name'].unique()

array(['20 Sep 2021 - 26 Sep 2021'], dtype=object)

In [67]:
### run 40
gimmick_tapi_bundle = ['(B)2309005305P3', '(B)2309005300P3']

paid_order = lazada_payment[(lazada_payment['Paid'] == 'Paid') & (lazada_payment['Brand'] == 'L-Men')]['Order Number'].unique()
indeks = lazada_payment[(lazada_payment['Real SKU'].isin(gimmick_tapi_bundle)) &
                       (lazada_payment['Order Number'].isin(paid_order))].index.to_list()
lazada_payment['Paid'][indeks] = 'Paid'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [68]:
## run 41

# indeks = lazada_payment[(lazada_payment['Paid'] == 'Paid') &
#       (lazada_payment['Shipment Type Name'] == 'dropshipping') &
#       (lazada_payment['Status'].isnull()) &
#       (pd.to_datetimelazada_payment['True datetime'] > '2021-07-28') &
#        (lazada_payment['True datetime'] < '2021-09-06')
#       ].index.to_list()
# lazada_payment['Status'][indeks] = 'confirmed'
# lazada_payment['Warehouse Quantity'][indeks] = lazada_payment['Qty. Invoiced'][indeks]

tambah_unpaid = pd.read_excel(r'Settlement Project/unpaid order to Andra.xlsx', sheet_name = 'Unpaid to cancel or not found')
tambah_unpaid2 = pd.read_excel(r'Settlement Project/Unpaid Mar.xlsx', sheet_name = 'lazada')

tambah_unpaid['Order Number'] = tambah_unpaid['Order #'].astype(str)
tambah_unpaid = tambah_unpaid.append(tambah_unpaid2, ignore_index = True, sort = False)
indeks = lazada_payment[(lazada_payment['Order Number'].isin(tambah_unpaid['Order Number'])) & (lazada_payment['Shipment Type Name'] == 'dropshipping')].index.to_list()
print(len(indeks))
lazada_payment['Order Status'][indeks] = 'Cancel'
lazada_payment['Paid'][indeks] = 'Cancel'

rumus_status = pd.read_excel(r'Settlement Project/Rumus Status.xlsx', sheet_name = 'lazada')
if len(rumus_status != 0):
    for i in range(len(rumus_status)):
        stat = rumus_status['Order Status'][i]
        indeks = lazada_payment[(lazada_payment['Paid'] == 'Unpaid') &
                             (lazada_payment['Order Status'].str.lower() == stat.lower())].index.to_list()
        lazada_payment['Order Status'][indeks] = 'Cancel'
        lazada_payment['Paid'][indeks] = 'Cancel'


unpaid = lazada_payment[lazada_payment['Paid'] == 'Unpaid']
paid = lazada_payment[lazada_payment['Paid'] != 'Unpaid']

unpaid['Total Transfer'] = unpaid['Paid Price']
unpaid['BTL Cost'] = 0

no_prop = unpaid[unpaid['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]
unpaid_prop = unpaid[~unpaid['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]

unpaid_real = unpaid_prop[unpaid_prop['Bundle Name'].isnull()]
unpaid_bundle = unpaid_prop[unpaid_prop['Bundle Name'].notnull()]

unpaid_real['FullFee'] = unpaid_real['Qty. Invoiced'] * 3000

temp_unpaid_real = unpaid_real.groupby(['Order Number', 'Item Name'])['FullFee'].sum().reset_index()
unpaid_bundle['FullFee'] = unpaid_bundle.merge(temp_unpaid_real.drop_duplicates(['Order Number', 'Item Name']), how = 'left', left_on = ['Order Number', 'Bundle Name'], right_on = ['Order Number', 'Item Name']).set_index(unpaid_bundle.index)['FullFee_y']
unpaid_bundle['FullFee'] = unpaid_bundle['FullFee'].fillna(0) * unpaid_bundle['Qty. Invoiced']/unpaid_bundle.groupby(['Order Number', 'Bundle Name'])['Qty. Invoiced'].transform('sum')

indeks = unpaid_real[(unpaid_real['Brand'] != 'Bundle') & (unpaid_real['Brand'] != 'L-Men')].index.to_list()
unpaid_real['ComFee'][indeks] = unpaid_real['Paid Price'] * 4.95 / 100

indeks = unpaid_real[(unpaid_real['Brand'] == 'L-Men')].index.to_list()
unpaid_real['ComFee'][indeks] = unpaid_real['Paid Price'] * 0.99 / 100

indeks = unpaid_real[(unpaid_real['Brand'] == 'Bundle') & 
                     (unpaid_real['Real SKU'].astype(str).str.contains('^P', regex = True))].index.to_list()
unpaid_real['ComFee'][indeks] = unpaid_real['Paid Price'] * 4.95 / 100

indeks = unpaid_real[(unpaid_real['Brand'] == 'Bundle') & 
                     (unpaid_real['Real SKU'].astype(str).str.contains('^P', regex = True)) &
                    (unpaid_real['Real SKU'].astype(str).str.contains('^[^NHTE]+$', regex = True))].index.to_list()
unpaid_real['ComFee'][indeks] = unpaid_real['Paid Price'] * 0.99 / 100

sku_lmen = lazada_set[lazada_set['Brand'] == 'L-Men']['Real SKU'].unique()

indeks = unpaid_real[(unpaid_real['Brand'] == 'Bundle') & 
                     (~unpaid_real['Real SKU'].astype(str).str.contains('^P', regex = True)) &
                    (~unpaid_real['SKU Produk 1'].isin(sku_lmen))].index.to_list()
unpaid_real['ComFee'][indeks] = unpaid_real['Paid Price'] * 4.95 / 100

indeks = unpaid_real[(unpaid_real['Brand'] == 'Bundle') & 
                     (~unpaid_real['Real SKU'].astype(str).str.contains('^P', regex = True)) &
                    (unpaid_real['SKU Produk 1'].isin(sku_lmen))].index.to_list()
unpaid_real['ComFee'][indeks] = unpaid_real['Paid Price'] * 0.99 / 100

temp_unpaid_real = unpaid_real.groupby(['Order Number', 'Item Name'])['ComFee'].sum().reset_index()
unpaid_bundle['ComFee'] = unpaid_bundle.merge(temp_unpaid_real.drop_duplicates(['Order Number', 'Item Name']), how = 'left', left_on = ['Order Number', 'Bundle Name'], right_on = ['Order Number', 'Item Name']).set_index(unpaid_bundle.index)['ComFee_y']
unpaid_bundle['ComFee'] = unpaid_bundle['ComFee'].fillna(0) * unpaid_bundle['Total Net Before PPN']/unpaid_bundle.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')

unpaid_prop = unpaid_real.append(unpaid_bundle, ignore_index = True, sort = False)
unpaid = unpaid_prop.append(no_prop, ignore_index = True, sort = False)

unpaid['Payment Fee'] = 0
unpaid['Shipping Fee'] = 0

lazada_set = paid.append(unpaid, ignore_index = True, sort = False)

lazada_set['Bi Produk'] = lazada_set['BTL Cost'] + lazada_set['Total Transfer']
lazada_set['Real BTL Cost'] = lazada_set['Bi Produk'] - lazada_set['Total Net Before PPN']

0

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1061: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
lazada_set[(lazada_set['Total Transfer'].isnull()) & (lazada_set['Order Number'].isin(settlement_cat['Order No.'])) & (~lazada_set['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])) &
          (lazada_set['Bundle Name'].isnull())].groupby(['Item Name','Real SKU', 'Real Nama Produk', 'Bundle Name'], dropna = False)['Order Number'].first().reset_index()

In [70]:
## for display only
pd.options.display.max_columns = 150

In [69]:
## run 42
indeks = lazada_set[(lazada_set['Paid'] == 'Paid') & (lazada_set['WH'] == 'Telkom')].index.to_list()
lazada_set['Status'][indeks] = 'confirmed'

indeks = lazada_set[lazada_set['Paid'] == 'Paid-0'].index.to_list()
lazada_set['Paid'][indeks] = 'Refund'

indeks = lazada_set[(lazada_set['Paid'] == 'Unpaid') & (lazada_set['Status'].isin(['Delivery Failed', 'Out of stock',
       'Cancelled']))].index.to_list()
lazada_set['Paid'][indeks] = 'Cancel'

lazada_set_gimmick = lazada_set[lazada_set['Brand'].isin(['Gimmick', 'Bonus Produk'])]
paid = lazada_set[lazada_set['Paid'] == 'Paid']['Order Number'].unique()

indeks = lazada_set_gimmick[lazada_set_gimmick['Order Number'].isin(paid)].index.to_list()
lazada_set['Paid'][indeks] = 'Paid'

total_trx = lazada_set.drop('BTL Cost', axis = 1)

total_trx = total_trx.rename(columns = {
    'Lazada SKU' : 'Product ID',
    'Paid Price' : 'Total Selcen',
    'Status Seller Centre' : 'Order Status_y',
    'Shipment Type Name' : 'Warehouse Origin',
    'Status' : 'SO STATUS',
    'Bi Produk' : 'Total Produk Prop',
    'FullFee' : 'Fullfee Prop',
    'ComFee' : 'Comfee Prop',
    'Real BTL Cost' : 'BTL Cost',
    'Created at' : 'Order Date Seller Centre'
})

total_trx_full = total_trx.copy()

total_trx_full = total_trx_full.rename(columns = {
    'Total Selcen' : 'Total Seller Centre', 
    'Order Status_y' : 'Order Status Seller Centre',
    'SO STATUS' : 'Status Gudang'
})

total_trx_full['Total Produk Prop Adj'] = total_trx_full['Total Produk Prop']/1.11
total_trx_full['BTL Cost'] = total_trx_full['Total Produk Prop Adj'] - total_trx_full['Total Net Before PPN']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [57]:
total_trx_full[total_trx_full['Order Item Id']==842781336962656][['Order Number','Order Item Id','Paid']].drop_duplicates()
# settlement[settlement['Order No.']==]

           Order Number    Order Item Id  Paid
215734  842781336662656  842781336962656  Paid

In [70]:
## run 43
import numpy as np

temp_order = total_trx_full.groupby(['Order Number', 'Paid'])['Fullfee Prop'].sum().reset_index()
orders = temp_order[(temp_order['Paid'] == 'Paid') & (temp_order['Fullfee Prop'] == 0)]['Order Number'].unique()

sept_total = total_trx_full[(total_trx_full['Order Number'].isin(orders)) & 
                           (total_trx_full['Warehouse Origin'] == 'own_warehouse')]
print(len(sept_total))
nonsept_trx = total_trx_full[~total_trx_full.index.isin(sept_total.index)]

sept_trx = sept_total[sept_total['Paid'].isin(['Paid', 'Half Paid'])]
sept_notpaid = sept_total[~sept_total['Paid'].isin(['Paid', 'Half Paid'])]

no_prop = sept_trx[sept_trx['Brand'].isin(['Bonus Produk', 'Gimmick'])]
sept_prop = sept_trx[~sept_trx['Brand'].isin(['Bonus Produk', 'Gimmick'])]

total_trx_real = sept_prop[sept_prop['Bundle Name'].isnull()]
total_trx_bundle = sept_prop[sept_prop['Bundle Name'].notnull()]

total_trx_real['Fullfee Prop'] = total_trx_real['Qty. Invoiced'] * -2750

indeks = total_trx_real[(total_trx_real['Brand'] == 'Bundle')].index.to_list()
total_trx_real['Fullfee Prop'][indeks] = total_trx_real['Fullfee Prop'][indeks] - 1200

# total_trx_bundle = total_trx_bundle.drop('Fullfee Prop', axis = 1)
total_trx_bundle['Fullfee Prop'] = total_trx_bundle.merge(total_trx_real[['Order Number', 'Item Name', 'Fullfee Prop']].drop_duplicates(['Order Number', 'Item Name']), how = 'left', left_on = ['Order Number', 'Bundle Name'], right_on = ['Order Number', 'Item Name']).set_index(total_trx_bundle.index)['Fullfee Prop_y']
total_trx_bundle['Fullfee Prop'] = total_trx_bundle['Fullfee Prop'].fillna(0) * total_trx_bundle['Qty. Invoiced']/total_trx_bundle.groupby(['Order Number', 'Bundle Name'])['Qty. Invoiced'].transform('sum')

total_trx_final = total_trx_real.append(total_trx_bundle, ignore_index = True, sort = False)

indeks = no_prop[no_prop['Bundle Name'].isnull()].index.to_list()
no_prop['Fullfee Prop'] = no_prop['Qty. Invoiced'] * -2750

total_trx_final = total_trx_final.append(no_prop, ignore_index = True, sort = False)

sept_total = total_trx_final.append(sept_notpaid, ignore_index = True, sort = False)

indeks = sept_total[(sept_total['WH'] == 'Telkom')].index.to_list()
sept_total['Fullfee Prop'][indeks] = np.nan

total_trx_full = nonsept_trx.append(sept_total, ignore_index = True, sort = False)
total_trx_full

42997

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\series.py:1061: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Order Item Id,Order Type,Order Flag,Lazada Id,SKU,Product ID,Order Date Seller Centre,Updated at,Order Number,Invoice Required,Customer Name,Customer Email,National Registration Number,Shipping Name,Shipping Address,Shipping Address2,Shipping Address3,Shipping Address4,Shipping Address5,Shipping Phone Number,Shipping Phone Number2,Shipping City,Shipping Postcode,Shipping Country,Shipping Region,Billing Name,Billing Address,Billing Address2,Billing Address3,Billing Address4,Billing Address5,Billing Phone Number,Billing Phone Number2,Billing City,Billing Postcode,Billing Country,Payment Method,Total Seller Centre,Unit Price,Selcen Shipping Fee,Wallet Credits,Item Name,Variation,CD Shipping Provider,Shipping Provider,Warehouse Origin,Shipping Provider Type,CD Tracking Code,Tracking Code,Tracking URL,Shipping Provider (first mile),Tracking Code (first mile),Tracking URL (first mile),Promised shipping time,Premium,Order Status,Cancel / Return Initiator,Reason,Reason Detail,Editor,Bundle ID,Bundle Discount,Refund Amount,Source,Guarantee,Delivery Type,Ware House,Update Time,Rts Sla,Tts Sla,Invoice Number,Delivered Date,Shipping Phone,Shipping Phone2,Shipping Post Code,...,Subtotal Produk 1,Harga Display 1,Harga Cost 1,Produk 2,SKU Produk 2,PCS Produk 2,Price List NFI 2,Subtotal Produk 2,Harga Display 2,Harga Cost 2,Produk 3,SKU Produk 3,PCS Produk 3,Price List NFI 3,Subtotal Produk 3,Harga Display 3,Harga Cost 3,Produk 4,SKU Produk 4,PCS Produk 4,Price List NFI 4,Subtotal Produk 4,Harga Display 4,Harga Cost 4,Produk 5,SKU Produk 5,PCS Produk 5,Price List NFI 5,Subtotal Produk 5,Harga Display 5,Harga Cost 5,Produk 6,SKU Produk 6,PCS Produk 6,Price List NFI 6,Subtotal Produk 6,Harga Display 6,Harga Cost 6,Produk 7,SKU Produk 7,PCS Produk 7,Price List NFI 7,Subtotal Produk 7,Harga Display 7,Harga Cost 7,Price List NFI,Harga Cost,Total Net,Total Harga Cost,Total Net Before PPN,Bundle Name,Bundle Flag,Parent Item,Parent SKU,Customer Order No.,Platform SKU,Status Gudang,Warehouse Quantity,WH,Order No._x,Seller SKU,Comfee Prop,Fullfee Prop,Payment Fee_x,Shipping Fee,Total Transfer,Payment Fee_y,Order No.,Payment Fee,Paid,Order Paid,Order No._y,Total Produk Prop,BTL Cost,Total Produk Prop Adj
0,1056706380859385,NORMAL,NaN,1056706380859385,2104405,LM705WNAAXLBFYANID-76087554,25 Jan 2023 23:57,NaN,1056706380759385,No,dila yulika,NaN,NaN,Dila yulika,Pamulang permai 1 blok c19 no.7 jl.jambu kel. ...,NaN,Banten,Kota Tangerang Selatan,Pamulang,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,Dila yulika,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,61350.000000,61500.000000,0.000,NaN,Tropicana Slim Minyak Kanola 946ml - 100% Pur...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-8001357283,NaN,NaN,NaN,NaN,NaN,No,shipped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20221221-25.xlsx,non-Guarantee,STANDARD,NaN,27 Jan 2023 06:01,NaN,NaN,NaN,NaN,NaN,NaN,15417,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,77700.0,77700,77700.0,77700,70000.0,NaN,NaN,NaN,NaN,1056706380759385,LM705WNAAXLBFYANID-76087554,Delivered,1.0,Lazada Warehouse,1056706380759385,2104405,-2451.00000,-2775.0,-1117.0,-7000.0,68500.0,NaN,NaN,NaN,Paid,Paid,NaN,68350.0,-8423.423423,61576.576577
1,1056706380959385,NORMAL,NaN,1056706380959385,2104405,LM705WNAAXLBFYANID-76087554,25 Jan 2023 23:57,NaN,1056706380759385,No,dila yulika,NaN,NaN,Dila yulika,Pamulang permai 1 blok c19 no.7 jl.jambu kel. ...,NaN,Banten,Kota Tangerang Selatan,Pamulang,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,Dila yulika,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,61350.000000,61500.000000,0.000,NaN,Tropicana Slim Minyak Kanola 946ml - 100% Pur...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-8001357283,NaN,NaN,NaN,NaN,NaN,No,shipped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20221221-25.xlsx,non-Guarantee,STANDARD,NaN,27 Jan 2023 06:01,NaN,NaN,NaN,NaN,NaN,NaN,15417,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,77700.0,77700,77700.0,77700,70000.0,NaN,NaN,NaN,NaN,1056706380759385,LM705WNAAXLBFYANID-76087554,Delivered,1.0,Lazada Warehouse,1056706380759385,2104405,-2451.00000,-2775.0,-1117.0,-7000.0,68500.0,NaN,NaN,NaN,Paid,Paid,NaN,68350.0,-8423.423423,61576.576577
2,1056706381059385,NORMAL,NaN,1056706381059385,2104405,LM705WNAAXLBFYANID-76087554,25 Jan 2023 23:57,NaN,1056706380759385,No,dila yulika,NaN,NaN,Dila yulika,Pamulang permai 1 blok c19 no.7 jl.jambu kel. ...,NaN,Banten,Kota Tangerang Selatan,Pamulang,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,Dila yulika,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,61350.000000,61500.000000,0.000,NaN,Tropicana Slim Minyak Kanola 946ml - 100% Pur...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-8001357283,NaN,NaN,NaN,NaN,NaN,No,shipped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20221221-25.xlsx,non-Guarantee,STANDARD,NaN,27 Jan 2023 06:01,NaN,NaN,NaN,NaN,NaN,NaN,15417,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,77700.0,77700,77700.0,77700,70000.0,NaN,NaN,NaN,NaN,1056706380759385,LM705WNAAXLBFYANID-76087554,Delivered,1.0,Lazada Warehouse,1056706380759385,2104405,-2451.00000,-2775.0,-1117.0,-7000.0,68500.0,NaN,NaN,NaN,Paid,Paid,NaN,68350.0,-8423.423423,61576.576577
3,1056706381159385,NORMAL,NaN,1056706381159385,2104405,LM705WNAAXLBFYANID-76087554,25 Jan 2023 23:57,NaN,1056706380759385,No,dila yulika,NaN,NaN,Dila yulika,Pamulang permai 1 blok c19 no.7 jl.jambu kel. ...,NaN,Banten,Kota Tangerang Selatan,Pamulang,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,Dila yulika,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,61350.000000,61500.000000,0.000,NaN,Tropicana Slim Minyak Kanola 946ml - 100% Pur...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-8001357283,NaN,NaN,NaN,NaN,NaN,No,shipped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20221221-25.xlsx,non-Guarantee,STANDARD,NaN,27 Jan 2023 06:01,NaN,NaN,NaN,NaN,NaN,NaN,15417,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,77700.0,77700,77700.0,77700,70000.0,NaN,NaN,NaN,NaN,1056706380759385,LM705WNAAXLBFYANID-76087554,Delivered,1.0,Lazada Warehouse,1056706380759385,2104405,-2451.00000,-2775.0,-1117.0,-7000.0,68500.0,NaN,NaN,NaN,Paid,Paid,NaN,68350.0,-8423.423423,61576.576577
4,1056706381259385,NORMAL,NaN,1056706381259385,2104405,LM705WNAAXLBFYANID-76087554,25 Jan 2023 23:57,NaN,1056706380759385,No,dila yulika,NaN,NaN,Dila yulika,Pamulang permai 1 blok c19 no.7 jl.jambu kel. ...,NaN,Banten,Kota Tangerang Selatan,Pamulang,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,Dila yulika,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Tangerang Selatan,NaN,Indonesia,NaN,61350.000000,61500.000000,0.000,NaN,Tropicana Slim Minyak Kanola 946ml - 100% Pur...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-8001357283,NaN,NaN,NaN,NaN,NaN,No,shipped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20221221-25.xlsx,non-Guarantee,STANDARD,NaN,27 Jan 2023 06:01,NaN,NaN,NaN,NaN,NaN,NaN,15417,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,77700.0,77700,77700.0,77700,70000.0,NaN,NaN,NaN,NaN,1056706380759385,LM705WNAAXLBFYANID-76087554,Delivered,1.0,Lazada Warehouse,1056706380759385,2104405,-2451.00000,-2775.0,-1117.0,-7000.0,68500.0,NaN,NaN,NaN,Paid,Paid,NaN,68350.0,-8423.423423,61576.576577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202281,1152950534831319,NORMAL,NaN,1152950534831319,2104393210,4584476547_ID-7941382071,27 Apr 2023 06:48,NaN,1152950534631319,No,Wina,NaN,NaN,w*a,l*k,NaN,J*t,K*i,C*k,NaN,NaN,K*i,NaN,Indonesia,NaN,w*a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K*i,NaN,Indonesia,NaN,24629.166667,24629.166667,733.125,NaN,Tropicana Slim Kecap Asin 200 ml,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-1004924764,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20230424-28.xlsx,non-Guarantee,STANDARD,NaN,02 May 2023 21:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27750.0,39000.0,27750.0,Tropicana Slim Kecap Asin 200 ml,2104393210,1.0,25530.0,25530.0,30400.0,25530.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25530.0,25530,25530.0,25530,23000.0,Duo Kecap - Tropicana Slim Kecap Asin dan Keca...,NaN,Tropicana Slim Kecap Asin 200 ml,NaN,NaN,4584476547_ID-7941382071,Delivery Failed,1.0,NaN,NaN,NaN,0.00000,0.0,NaN,0.0,0.0,NaN,NaN,0.0,Cancel,"Paid,Unpaid",NaN,0.0,-23000.000000,0.000000
202282,1173926321716432,NORMAL,NaN,1173926321716432,1102110453,5337754001_ID-10471214091,25 May 2023 12:18,NaN,1173926321116432,No,Andi Tris,NaN,NaN,andi widianto,toko ciki Tris depan pasar gembong · Balaraja,NaN,Banten,Kab. Tangerang,Balaraja,NaN,NaN,Kab. Tangerang,NaN,Indonesia,NaN,andi widianto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Tangerang,NaN,Indonesia,NaN,46900.000000,46900.000000,0.000,NaN,NutriSari NUTRI-C1000 Jeruk 40 Sachet - Minuma...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-1005320505,NaN,NaN,NaN,NaN,NaN,No,shipped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20230521_25.xlsx,non-Guarantee,STANDARD,NaN,25 May 2023 21:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45510.0,45510,45510.0,45510,41000.0,NaN,NaN,NaN,NaN,1173926321116432,5337754001_ID-10471214091,Ready to Ship,1.0,Lazada Warehouse,NaN,NaN,2321.55000,3000.0,0.0,0.0,46900.0,NaN,NaN,0.0,Unpaid,"Paid,Unpaid",NaN,46900.0,1252.252252,42252.252252
202283,1162051869748106,NORMAL,NaN,1162051869748106,PL1L23,5851250985_ID-11312106253,23 May 2023 18:34,NaN,1162051869548106,No,Made Dika Diatmika,NaN,NaN,M*a,J*n,NaN,D*a,K*n,S*i,NaN,NaN,K*n,NaN,Indonesia,NaN,M*a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K*n,NaN,Indonesia,NaN,119795.000000,123500.000000,1555.000,NaN,Daily Package - L-Men Daily Chocolate 250gr & ...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20230521_25.xlsx,non-Guarantee,STANDARD,NaN,24 May 2023 12:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63270.0,75600.0,63270.0,L-Men Daily Popcorn Caramel 250gr,2300542155,1.0,63270.0,63270.0,75600.0,63270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126540.0,126540,126540.0,126540,114000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1185.97050,3000.0,0.0,0.0,119795.0,NaN,NaN,0.0,Unpaid,"Paid,Unpaid",NaN,119795.0,-6076.576577,107923.423423
202284,1162051869748106,NORMAL,NaN,1162051869748106,2300551155,5851250985_ID-11312106253,23 May 2023 18:34,NaN,1162051869548106,No,Made Dika Diatmika,NaN,NaN,M*a,J*n,NaN,D*a,K*n,S*i,NaN,NaN,K*n,NaN,Indonesia,NaN,M*a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K*n,NaN,Indonesia,NaN,59897.500000,61750.000000,777.500,NaN,L-Men Whey Daily Dark Chocolate 250gr,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20230521_25.xlsx,non-Guarantee,STANDARD,NaN,24 May 2023 12:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63270.0,75600.0,63270.0,L-Men Daily Popcorn Caramel 250gr,2300542155,1.0,63270.0,63270.0,75600.0,63270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63270.0,63270,63270.0,63270,57000.0,Daily Package - L-Men Daily Chocolate 250gr & ...,NaN,L-Men Whey Daily Dark Chocolate 250gr,2300551155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,592.98525,1500.0,NaN,0.0,59897.5,NaN,NaN,0.0,Unpaid,"Paid,Unpaid",NaN,59897.5,-3038.288288,53961.711712
202285,1162051869748106,NORMAL,NaN,1162051869748106,2300542155,5851250985_ID-11312106253,23 May 2023 18:34,NaN,1162051869548106,No,Made Dika Diatmika,NaN,NaN,M*a,J*n,NaN,D*a,K*n,S*i,NaN,NaN,K*n,NaN,Indonesia,NaN,M*a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K*n,NaN,Indonesia,NaN,59897.500000,61750.000000,777.500,NaN,L-Men Daily Popcorn Caramel 250gr,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20230521_25.xlsx,non-Guarantee,STANDARD,NaN,24 May 2023 12:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63270.0,75600.0,63270.0,L-Men Daily Popcorn Caramel 250gr,2300542155,1.0,63270.0,63270.0,75600.0,63270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63270.0,63270,63270.0,63270,57000.0,Daily Package - L-Men Daily Chocolate 250gr & ...,NaN,L-Men Daily Popcorn Caramel 250gr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,592.98525,1500.0,NaN,0.0,59897.5,NaN,NaN,0.0,Unpaid,"Paid,Unpaid",NaN,59897.5,-3038.288288,53961.711712

In [71]:
### run 44
total_trx_full.to_csv(r"Settlement Project\Backup\Realisasi May 2023\Final Result\Before Compare\Lazada Testing by Selcen Compare v8.csv",sep=';')

In [62]:
# total_trx_fullcp=total_trx_full.copy()

In [73]:
## run 45
import pandas as pd
import numpy as np
import os

# total_trx = pd.read_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v8.csv', sep = ';')
# total_trx_full=pd.read_csv(r"Settlement Project\Backup\Realisasi Apr 2023\Final Result\Before Compare\Lazada Testing by Selcen Compare v8.csv",sep=';')
total_trx_full = total_trx_full.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})

# total_trx_full=total_trx_full[total_trx_full['Order Item Id']==885185568741700]
# total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
#        'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
#        'Delta Comfee Prop'], axis = 1)

source = pd.read_csv(r"D:\6. settlement\Code\Settlement Project\Backup\Realisasi Apr 2023\Final Result\Raw Unpivoted\CSV\Running Lazada By Selcen Jan 2022 - Apr 2023.csv", sep = ';')
# source=sourcecp.copy()
# source['Order Number']=source['Order Number'].astype(str)
# source = pd.read_excel(r"D:\settlement\Code\Settlement Project\Backup\Realisasi Juni 2022\Final Result\Raw Unpivoted\Excel\Running Lazada By Selcen Jan 2022 - Jun 2022.xlsx")
# source=source[source['Order Item Id']==885185568741700]


source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021)]

# selcen_sku['OrderId'] = selcen_sku['OrderId'].astype(str)
source['Order #'] = source['Order Number'].astype(str)
source['Real SKU'] = source['Real SKU'].astype(str)

# selcen_old = selcen_sku[selcen_sku['OrderId'].isin(source['Order #'])]

source['Product Name'] = source['Item Name'].fillna(source['Real Nama Produk'])

total_trx_full['Order Number'] = total_trx_full['Order Number'].astype(str)

total_trx_merge = total_trx_full.merge(source.groupby(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid April'])['Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])
cek=total_trx_merge.copy()
# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# display(total_trx_null[total_trx_null['Order Number']=='829299019029418'][['Real Nama Produk','Real SKU','Paid','Paid June']])
total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid April'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source.groupby(['Order #', 'Product Name', 'Bundle Name', 'Paid April'])['Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Item Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 

cek2=total_trx_null.copy()

total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid April'][total_trx_null.index] = total_trx_null['Paid April']


# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# display(total_trx_null[total_trx_null['Order Number']=='829299019029418'][['Real Nama Produk','Real SKU','Paid','Paid June']])


total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid April'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Total Net', 'Total Produk Prop',
                                              'Comfee Prop', 'Paid April']].drop_duplicates(['Order #', 'Real SKU',
                                                                                            'Bundle Name']), how = 'left', left_on = ['Order Number',
                                                                                                                                      'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
cek3=total_trx_null.copy()


total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid April'][total_trx_null.index] = total_trx_null['Paid April']

total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')


# # total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# # source2 = source.copy()

# # source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# # indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# # source2['Real SKU'][indeks] = '(U)2101809250'

# # indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# # source2['Real SKU'][indeks] = '2101941250P4'

# # indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# # source2['Real SKU'][indeks] = '2101809250P4'

# # total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# # total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
# #                                                   'Total Produk Prop_x' : 'Total Produk Prop',
# #                                                   'Comfee Prop_x' : 'Comfee Prop'})

# # total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
# # total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# # total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# # total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_merge = total_trx_merge.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_merge.loc[(total_trx_merge['Paid']=='Unpaid')&(total_trx_merge['Paid April']=='Cancel'),'Paid']='Cancel' ### add cancel
# total_trx_merge.loc[(total_trx_merge['Paid'].isnull())&(total_trx_merge['Paid July']=='Cancel'),'Paid']='Cancel' ### add cancel
# total_trx_merge.loc[(total_trx_merge['Paid'].isnull())&(total_trx_merge['Paid July']=='Paid'),'Paid']='Paid' ### add cancel
# total_trx_merge.loc[(total_trx_merge['Paid'].isnull())&(total_trx_merge['Paid July']=='Refund'),'Paid']='Refund' ### add cancel
total_trx_merge['Paid Beda'] = np.nan

indeks = total_trx_merge[total_trx_merge['Paid'] != total_trx_merge['Paid April']].index.to_list()
total_trx_merge['Paid Beda'][indeks] = 'Beda'

total_trx_merge['Paid Beda'] = total_trx_merge['Paid Beda'].fillna('Sama')
# total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'][['Order #','Brand','Real SKU','Month', 'Paid_x', 'Paid_y', 'Paid Beda']]
total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'].groupby(['Month', 'Paid', 'Paid April'], dropna  = False)['Order Number'].nunique()

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (4,42,68,69,80,92,105,106,111,117,118,124,125,131,132,138,139,145,146,152,164,166,167,169,170,172,173,185) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:38: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:51: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Month  Paid       Paid April
April  Cancel     Unpaid           37
                  NaN             496
       Paid       Unpaid          808
                  NaN            3659
       Refund     Paid              1
                  NaN               3
       Unpaid     NaN               4
March  Paid       Refund            5
May    Cancel     NaN            2887
       Half Paid  NaN               2
       Paid       NaN           15421
       Refund     NaN               4
       Unpaid     NaN             226
Name: Order Number, dtype: int64

In [ ]:
import pandas as pd
import numpy as np
import os

# total_trx = pd.read_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v8.csv', sep = ';')
total_trx_full=pd.read_csv(r"D:\settlement\Code\Settlement Project\Backup\Realisasi Sept 2022\Final Result\Before Compare\Lazada Testing by Selcen Compare v8.csv",sep=';')
total_trx_full = total_trx_full.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})

# total_trx_full=total_trx_full[total_trx_full['Order Item Id']==885185568741700]
total_trx_full['Real SKU'] = total_trx_full['Real SKU'].astype(str)
# total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
#        'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
#        'Delta Comfee Prop'], axis = 1)

source = pd.read_csv(r"D:\settlement\Code\Settlement Project\Backup\Realisasi Aug 2022\Final Result\Raw Unpivoted\CSV\Running Lazada By Selcen Jan 2022 - Aug 2022 rev 1.csv", sep = ';')
# source=sourcecp.copy()
# source['Order Number']=source['Order Number'].astype(str)
# source = pd.read_excel(r"D:\settlement\Code\Settlement Project\Backup\Realisasi Juni 2022\Final Result\Raw Unpivoted\Excel\Running Lazada By Selcen Jan 2022 - Jun 2022.xlsx")
# source=source[source['Order Item Id']==885185568741700]


source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021)]

# selcen_sku['OrderId'] = selcen_sku['OrderId'].astype(str)
source['Order #'] = source['Order Number'].astype(str)
source['Real SKU'] = source['Real SKU'].astype(str)


# selcen_old = selcen_sku[selcen_sku['OrderId'].isin(source['Order #'])]

source['Product Name'] = source['Item Name'].fillna(source['Real Nama Produk'])

total_trx_full['Order Number'] = total_trx_full['Order Number'].astype(str)

total_trx_merge = total_trx_full.merge(source.groupby(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid August'])['Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])
cek=total_trx_merge.copy()
# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# display(total_trx_null[total_trx_null['Order Number']=='829299019029418'][['Real Nama Produk','Real SKU','Paid','Paid June']])
total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid August'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source.groupby(['Order #', 'Product Name', 'Bundle Name', 'Paid August'])['Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Item Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 

cek2=total_trx_null.copy()

total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid August'][total_trx_null.index] = total_trx_null['Paid August']


total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid August'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})
a=total_trx_null.copy()
b=source.copy()
total_trx_null = total_trx_null.merge(source[['Order Item Id', 'Real SKU', 'Bundle Name', 'Total Net', 'Total Produk Prop',
                                              'Comfee Prop', 'Paid August']].drop_duplicates(['Order Item Id', 'Real SKU',
                                                                                            'Bundle Name']), how = 'left', left_on = ['Order Item Id',
                                                                                                                                      'Real SKU'], right_on = ['Order Item Id', 'Real SKU']).set_index(total_trx_null.index) 
cek3=total_trx_null.copy()


total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid August'][total_trx_null.index] = total_trx_null['Paid August']

total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')




total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_merge = total_trx_merge.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_merge.loc[(total_trx_merge['Paid']=='Unpaid')&(total_trx_merge['Paid August']=='Cancel'),'Paid']='Cancel' ### add cancel
# total_trx_merge.loc[(total_trx_merge['Paid'].isnull())&(total_trx_merge['Paid July']=='Cancel'),'Paid']='Cancel' ### add cancel
# total_trx_merge.loc[(total_trx_merge['Paid'].isnull())&(total_trx_merge['Paid July']=='Paid'),'Paid']='Paid' ### add cancel
# total_trx_merge.loc[(total_trx_merge['Paid'].isnull())&(total_trx_merge['Paid July']=='Refund'),'Paid']='Refund' ### add cancel
total_trx_merge['Paid Beda'] = np.nan

indeks = total_trx_merge[total_trx_merge['Paid'] != total_trx_merge['Paid August']].index.to_list()
total_trx_merge['Paid Beda'][indeks] = 'Beda'

total_trx_merge['Paid Beda'] = total_trx_merge['Paid Beda'].fillna('Sama')
# total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'][['Order #','Brand','Real SKU','Month', 'Paid_x', 'Paid_y', 'Paid Beda']]
total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'].groupby(['Month', 'Paid', 'Paid August'], dropna  = False)['Order Number'].nunique()

In [74]:
cek=source[source['Paid April']=='Paid']['Order Item Id'].unique()
total_trx_merge[(total_trx_merge['Paid'].isnull())&(total_trx_merge['Order Item Id'].isin(cek))]
# ini harus null

Empty DataFrame
Columns: [Order Item Id, Order Type, Order Flag, Lazada Id, SKU, Product ID, Order Date Seller Centre, Updated at, Order Number, Invoice Required, Customer Name, Customer Email, National Registration Number, Shipping Name, Shipping Address, Shipping Address2, Shipping Address3, Shipping Address4, Shipping Address5, Shipping Phone Number, Shipping Phone Number2, Shipping City, Shipping Postcode, Shipping Country, Shipping Region, Billing Name, Billing Address, Billing Address2, Billing Address3, Billing Address4, Billing Address5, Billing Phone Number, Billing Phone Number2, Billing City, Billing Postcode, Billing Country, Payment Method, Total Seller Centre, Unit Price, Selcen Shipping Fee, Wallet Credits, Item Name, Variation, CD Shipping Provider, Shipping Provider, Warehouse Origin, Shipping Provider Type, CD Tracking Code, Tracking Code, Tracking URL, Shipping Provider (first mile), Tracking Code (first mile), Tracking URL (first mile), Promised shipping time, Premium, Order Status, Cancel / Return Initiator, Reason, Reason Detail, Editor, Bundle ID, Bundle Discount, Refund Amount, Source, Guarantee, Delivery Type, Ware House, Update Time, Rts Sla, Tts Sla, Invoice Number, Delivered Date, Shipping Phone, Shipping Phone2, Shipping Post Code, Billing Addr, Billing Addr2, Billing Addr3, Billing Addr4, Billing Addr5, Billing Phone, Billing Phone2, Billing Post Code, Tax Code, Branch Number, Tax Invoice Requested, Pay Method, Seller Discount Total, Wallet Credit, Cd Shipping Provider, Cd Tracking Code, Tracking Url, Shipping Provider F M, Tracking Code F M, Tracking Url F M, Promised Shipping Time, Buyer Failed Delivery Return Initiator, Buyer Failed Delivery Reason, Buyer Failed Delivery Detail, Buyer Failed Delivery User Name, ...]
Index: []

[0 rows x 192 columns]

In [75]:
## run 46
total_trx_merge = total_trx_merge.rename(columns = {'Paid' : 'Paid May'})

In [76]:
## run 47
# finres=pd.read_excel("Settlement Project\Backup\Realisasi April 2022\Final Result\Ke Mbak May\Running Lazada By Selcen Jan 22 - Apr 22 With LazSub and Free Ship Rev 1.xlsx",sheet_name='Running Lazada')
finres=pd.read_csv("Settlement Project\Backup\Realisasi April 2022\Final Result\Raw Unpivoted\CSV\Running Lazada By Selcen Jan 2022 - Apr 2022 With LazSub and Free Ship Rev 1.csv",sep=';')

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (42,69,80,92,110,117,123,124,130,131,137,144,145,163,165,166,182) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [77]:
## run 48
finres=finres.rename(columns={'Paid April':'Paid May'})
finres=finres.rename(columns={'Paid March':'Paid April'})

# finres=finres.rename(columns={'Paid March':'Paid January'})
# finres=finres.head(0).append(total_trx_merge)

finres['Pemilik Budget']=np.nan

In [78]:
## run 48.1
finres=total_trx_merge[[x for x in total_trx_merge.columns if x in finres.columns]]

In [79]:
## run 49
finres[finres['Year']>2022].to_excel(r'Settlement Project\Backup\Realisasi May 2023\Final Result\Raw Unpivoted\Excel/Running Lazada By Selcen Jan 2023 - May 2023.xlsx', index = False)
print('excel sdh')
finres.to_csv(r'Settlement Project\Backup\Realisasi May 2023\Final Result\Raw Unpivoted\CSV/Running Lazada By Selcen Jan 2022 - Apr 2023.csv', sep = ';', index = False)

excel sdh

In [ ]:
### lazada Selesai ####

In [293]:
source
cek=pd.read_excel("D:\Downloads\status lazada.xlsx")
total_trx_merge[(total_trx_merge['Order Item Id'].isin(cek['Order Item Id']))&
                (total_trx_merge['Paid Beda']=='Beda')][['Paid Beda','Paid','Paid June']]
# source[source['Order Item Id']==891304426530421]#.groupby(['Order Item Id'])[['Bundle Name']].nunique().reset_index().sort_values('Order Item Id',ascending=False)

       Paid Beda  Paid Paid June
118419      Beda  Paid    Unpaid
118420      Beda  Paid    Unpaid
147724      Beda  Paid    Unpaid
147725      Beda  Paid    Unpaid

In [ ]:
for i in cek['Order Item Id'].unique():
    print(i)
    bundlebener=source[(source['Order Item Id']==i)&
                       (source['Bundle Name'].notnull())]['Bundle Name'].unique()
    total_trx_full.loc[(total_trx_full['Order Item Id']==i)&
                       (total_trx_full['Bundle Name'].notnull()),'Bundle Name']=bundlebener[0]

In [290]:
bundlebener[0]

'Free Tumbler - HiLo School Bubble Gum 500g - Susu Tinggi Kalsium Lebih Rendah Lemak'

In [96]:
total_trx_merge = total_trx_merge.drop([x for x in total_trx_merge.columns if '_x' in x or '_y' in x], axis = 1)

In [97]:
set_pivot = pd.pivot_table(settlement_cat[settlement_cat['Fee Name_x'].isin(['LazSubsidy','Free Shipping Max Fee'])], values = 'Amount', index = ['Order No.', 'Seller SKU'], columns = 'Fee Name_x', aggfunc=np.sum).reset_index()

set_pivot['Order No.'] = set_pivot['Order No.'].astype(str)
set_pivot['Seller SKU'] = set_pivot['Seller SKU'].astype(str)
total_trx_merge['Order Number'] = total_trx_merge['Order Number'].astype(str)
total_trx_merge['Real SKU'] = total_trx_merge['Real SKU'].astype(str)

no_prop = total_trx_merge[total_trx_merge['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]
lazada_prop = total_trx_merge[~total_trx_merge['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]

bundle_wms = lazada_prop[lazada_prop['Bundle Name'].notnull()]
lazada_set = lazada_prop[lazada_prop['Bundle Name'].isnull()]

lazada_set = lazada_set.merge(set_pivot.drop_duplicates(['Order No.', 'Seller SKU']), how = 'left', left_on = ['Order Number', 'Real SKU'], right_on = ['Order No.', 'Seller SKU'])
lazada_set['LazSubsidy'] = lazada_set['LazSubsidy'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number', 'Item Name'])['Total Net Before PPN'].transform('sum')
lazada_set['Free Shipping Max Fee'] = lazada_set['Free Shipping Max Fee'].fillna(0) * lazada_set['Total Net Before PPN']/lazada_set.groupby(['Order Number', 'Item Name'])['Total Net Before PPN'].transform('sum')

bundle_set = bundle_wms.merge(lazada_set.groupby(['Order Number', 'Item Name'])[['LazSubsidy', 'Free Shipping Max Fee']].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Bundle Name'], right_on = ['Order Number', 'Item Name'])
bundle_set = bundle_set.rename(columns = {'Item Name_x' : 'Item Name'})
bundle_set = bundle_set.drop('Item Name_y', axis = 1)

bundle_set['LazSubsidy'] = bundle_set['LazSubsidy'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundle_set['Free Shipping Max Fee'] = bundle_set['Free Shipping Max Fee'].fillna(0) * bundle_set['Total Net Before PPN']/bundle_set.groupby(['Order Number', 'Bundle Name'])['Total Net Before PPN'].transform('sum')

lazada_set = lazada_set.append(bundle_set, ignore_index = True, sort = False)
lazada_set = lazada_set.append(no_prop, ignore_index = True, sort = False)

In [98]:
lazada_set = lazada_set.drop([x for x in lazada_set.columns if '_x' in x or '_y' in x], axis = 1)
lazada_set[lazada_set['Free Shipping Max Fee'] != 0]

,Order Item Id,Order Type,Order Flag,Lazada Id,SKU,Product ID,Order Date Seller Centre,Updated at,Order Number,Invoice Required,Customer Name,Customer Email,National Registration Number,Shipping Name,Shipping Address,Shipping Address2,Shipping Address3,Shipping Address4,Shipping Address5,Shipping Phone Number,Shipping Phone Number2,Shipping City,Shipping Postcode,Shipping Country,Shipping Region,Billing Name,Billing Address,Billing Address2,Billing Address3,Billing Address4,Billing Address5,Billing Phone Number,Billing Phone Number2,Billing City,Billing Postcode,Billing Country,Payment Method,Total Seller Centre,Unit Price,Selcen Shipping Fee,Wallet Credits,Item Name,Variation,CD Shipping Provider,Shipping Provider,Warehouse Origin,Shipping Provider Type,CD Tracking Code,Tracking Code,Tracking URL,Shipping Provider (first mile),Tracking Code (first mile),Tracking URL (first mile),Promised shipping time,Premium,Order Status,Cancel / Return Initiator,Reason,Reason Detail,Editor,Bundle ID,Bundle Discount,Refund Amount,Source,Guarantee,Delivery Type,Ware House,Update Time,Rts Sla,Tts Sla,Invoice Number,Delivered Date,Shipping Phone,Shipping Phone2,Shipping Post Code,...,Subtotal Produk 1,Harga Display 1,Harga Cost 1,Produk 2,SKU Produk 2,PCS Produk 2,Price List NFI 2,Subtotal Produk 2,Harga Display 2,Harga Cost 2,Produk 3,SKU Produk 3,PCS Produk 3,Price List NFI 3,Subtotal Produk 3,Harga Display 3,Harga Cost 3,Produk 4,SKU Produk 4,PCS Produk 4,Price List NFI 4,Subtotal Produk 4,Harga Display 4,Harga Cost 4,Produk 5,SKU Produk 5,PCS Produk 5,Price List NFI 5,Subtotal Produk 5,Harga Display 5,Harga Cost 5,Produk 6,SKU Produk 6,PCS Produk 6,Price List NFI 6,Subtotal Produk 6,Harga Display 6,Harga Cost 6,Produk 7,SKU Produk 7,PCS Produk 7,Price List NFI 7,Subtotal Produk 7,Harga Display 7,Harga Cost 7,Price List NFI,Harga Cost,Total Net,Total Harga Cost,Total Net Before PPN,Bundle Name,Bundle Flag,Parent Item,Parent SKU,Customer Order No.,Platform SKU,Status Gudang,Warehouse Quantity,WH,Comfee Prop,Fullfee Prop,Payment Fee,Shipping Fee,Total Transfer,Paid May,Order Paid,Total Produk Prop,BTL Cost,Total Produk Prop Adj,Paid April,Paid Beda,Free Shipping Max Fee,LazSubsidy,Seller SKU,Order No.
525,789194165105927,NORMAL,NaN,789194165105927,2104589105P3,5972504646_ID-11450758558,28 Jan 2022 23:49,NaN,789194164705927,No,Henny Puspayanti,NaN,NaN,henny puspa,taman kebon jeruk intercon blok G1 no 2 · Kemb...,NaN,DKI Jakarta,Kota Jakarta Barat,Kembangan,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,henny puspa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,56792.0,58600.0,0.0,NaN,Triple Pack - Tropicana Slim Klepon Cookies (5...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0017939550,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220122-28.xlsx,Guarantee,STANDARD,NaN,31 Jan 2022 11:01,NaN,NaN,NaN,31 Jan 2022 11:01,NaN,NaN,NaN,...,64935.0,80400.0,64935.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64935.0,64935,64935.0,64935,58500.000000,NaN,NaN,NaN,NaN,789194164705927,5972504646_ID-11450758558,Delivered,1.0,Lazada Warehouse,-2811.0,-2750.0,-1025.0,-1137.0,58600.0,Paid,Paid,56792.00000,-7336.036036,51163.963964,Paid,Sama,-1137.0,0.0,NaN,NaN
526,789194165205927,NORMAL,NaN,789194165205927,2101150180,TR086WNABLBRA8ANID-130399110,28 Jan 2022 23:49,NaN,789194164705927,No,Henny Puspayanti,NaN,NaN,henny puspa,taman kebon jeruk intercon blok G1 no 2 · Kemb...,NaN,DKI Jakarta,Kota Jakarta Barat,Kembangan,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,henny puspa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,100308.0,103500.0,0.0,NaN,Tropicana Slim Susu Skim Coffee 500g - Bantu T...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0017939550,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220122-28.xlsx,Guarantee,STANDARD,NaN,31 Jan 2022 11:01,NaN,NaN,NaN,31 Jan 2022 11:01,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,113220.0,113220,113220.0,113220,102000.000000,NaN,NaN,NaN,NaN,789194164705927,TR086WNABLBRA8ANID-130399110,Delivered,1.0,Lazada Warehouse,-4965.0,-2750.0,-1810.0,-2009.0,103500.0,Paid,Paid,100308.00000,-11632.432432,90367.567568,Paid,Sama,-2009.0,0.0,NaN,NaN
527,789196958414721,NORMAL,NaN,789196958414721,2104406,1879828815_ID-3693538825,28 Jan 2022 23:47,NaN,789196958314721,No,Fitri Junai H.Arbih,NaN,NaN,Fitri Junai H. Arbi,jl. Mesjid Nurul Iman Gg. H.Mair no.81 rt. 09/...,NaN,DKI Jakarta,Kota Jakarta Barat,Kalideres,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,Fitri Junai H. Arbi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,58543.0,60400.0,1900.0,NaN,Tropicana Slim Minyak Sunflower 946ml - Minyak...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0017939827,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220122-28.xlsx,Guarantee,STANDARD,NaN,29 Jan 2022 11:12,NaN,NaN,NaN,29 Jan 2022 11:11,NaN,NaN,Kalideres,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76691.0,76691,76691.0,76691,69090.990991,NaN,NaN,NaN,NaN,789196958314721,1879828815_ID-3693538825,Delivered,1.0,Lazada Warehouse,-580.0,-2750.0,-1056.0,-1172.0,60400.0,Paid,Paid,57704.19931,-17105.225846,51985.765145,Paid,Sama,-1172.0,0.0,NaN,NaN
528,789196958514721,NORMAL,NaN,789196958514721,2102500125,331035989_ID-337881610,28 Jan 2022 23:47,NaN,789196958314721,No,Fitri Junai H.Arbih,NaN,NaN,Fitri Junai H. Arbi,jl. Mesjid Nurul Iman Gg. H.Mair no.81 rt. 09/...,NaN,DKI Jakarta,Kota Jakarta Barat,Kalideres,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,Fitri Junai H. Arbi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Barat,NaN,Indonesia,NaN,36057.0,37200.0,1900.0,NaN,Tropicana Slim Sweetener Classic 50 Sachet - P...,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0017939748,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220122-28.xlsx,Guarantee,STANDARD,NaN,30 Jan 2022 16:11,NaN,NaN,NaN,30 Jan 2022 16:11,NaN,NaN,Kalideres,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,41070.0,41070,41070.0,41070,37000.000000,NaN,NaN,NaN,NaN,789196958314721,331035989_ID-337881610,Delivered,1.0,Lazada Warehouse,-357.0,-2750.0,-650.0,-722.0,37200.0,Paid,Paid,35607.80069,-4920.900280,32079.099720,Paid,Sama,-722.0,0.0,NaN,NaN
529,782545468133631,NORMAL,NaN,782545468133631,2102500130,TR086WNAADWPB2ANID-30660761,28 Jan 2022 23:47,NaN,782545468033631,No,endah nurdiati,NaN,NaN,Endah Nurdiati,jl martadireja 2 no 42 utara RS sinar kasi · P...,NaN,Jawa Tengah,Kab. Banyumas,Purwokerto Timur,NaN,NaN,Kab. Banyumas,NaN,Indonesia,NaN,Endah Nurdiati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Banyumas,NaN,Indonesia,NaN,64000.0,67000.0,0.0,NaN,Tropicana Slim Sweetener Classic 100 sachet - ...,NaN,NaN,JNE,own_warehouse,STANDARD,NaN,JNAT-0003426241,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220122-28.xlsx,non-Guarantee,STANDARD,NaN,02 Feb 2022 09:34,NaN,NaN,NaN,02 Feb 2022 09:34,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,74370.0,74370,74370.0,74370,67000.000000,NaN,NaN,NaN,NaN,782545468033631,TR086WNAADWPB2ANID-30660761,Delivered,1.0,Lazada Warehouse,-634.0,-2750.0,-1155.0,-1282.0,67000.0,Paid,Paid,64000.00000,-9342.342342,57657.657658,Paid,Sama,-1282.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142820,865583258345668,NORMAL,NaN,865583258345668,(G)71210225,6306140214_ID-11981038020,17 May 2022 02:34,NaN,865583258045668,No,Azki Maulana,NaN,NaN,Azki Desi,Linggapura Kel. RT.04 / RW.02 ( LINGGAPURA POR...,NaN,Jawa Tengah,Kab. Brebes,Tonjong,NaN,NaN,Kab. Brebes,NaN,Indonesia,NaN,Azki Desi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Brebes,NaN,Indonesia,NaN,0.0,0.0,255.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,JNE,own_warehouse,STANDARD,NaN,JNAT-0004005942,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,non-Guarantee,STANDARD,NaN,20 May 2022 13:51,NaN,NaN,NaN,19 May 2022 09:45,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.000000,NaN,NaN,NaN,NaN,865583258045668,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.00000,0.000000,0.000000,NaN,Beda,NaN,NaN,NaN,NaN
142821,872933754307174,NORMAL,NaN,872933754307174,(B)71210026,6294350528_ID-11966466335,17 May 2022 01:59,NaN,872933754007174,No,85266179919,NaN,NaN,Anis wati,jl. Krakatau · Mentawak Baru,NaN,Jambi,Kab. Sarolangun,Air Hitam,NaN,NaN,Kab. Sarolangun,NaN,Indonesia,NaN,Anis wati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Sarolangun,NaN,Indonesia,NaN,0.0,0.0,7299.0,NaN,[Gift] Spider Bottle Shaker,NaN,NaN,NinjaVanID,own_warehouse,STANDARD,NaN,NLIDAT0003815444,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,non-Guarantee,STANDARD,NaN,22 May 2022 20:42,NaN,NaN,NaN,22 May 2022 20:35,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,36000,0.0,36000,0.000000,NaN,NaN,NaN,NaN,872933754007174,6294350528_ID-11966466335,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.00000,0.000000,0.000000,NaN,Beda,NaN,NaN,NaN,NaN
142822,865401202625317,NORMAL,NaN,865401202625317,(G)71210225,6306140214_ID-11981038020,16 May 2022 19:07,NaN,865401202125317,No,Lusia Chris,NaN,NaN,Lusia Chris,Villa Nusa Indah 5 blok SB 10/9 Cluster Kasuar...,NaN,Jawa Barat,Kab. Bogor,Gunung Putri,NaN,NaN,Kab. Bogor,NaN,Indonesia,NaN,Lusia Chris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bogor,NaN,Indonesia,NaN,0.0,0.0,714.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0020357760,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,Guarantee,STANDARD,NaN,19 May 2022 20:52,NaN,NaN,NaN,18 May 2022 17:38,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.000000,NaN,NaN,NaN,NaN,865401202125317,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.00000,0.000000,0.000000,NaN,Beda,NaN,NaN,NaN,NaN
142823,865054631142870,NORMAL,NaN,865054631142870,(G)71210225,6306140214_ID-11981038020,16 May 2022 09:25,NaN,865054630842870,No,Teguh,NaN,NaN,Teguh,Demak 59581 rt6/rw1 · Jatisono,NaN,Jawa Tengah,Kab. Demak,Gajah,NaN,NaN,Kab. Demak,NaN,Indonesia,NaN,Teguh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Demak,NaN,Indonesia,NaN,0.0,0.0,2000.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,JNE,own_warehouse,STANDARD,NaN,JNAT-0004003174,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,non-Guarantee,STANDARD,NaN,20 May 2022 12:43,NaN,NaN,NaN,19 May 2022 14:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.000000,NaN,NaN,NaN,NaN,865054630842870,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.00000,0.000000,0.000000,NaN,Beda,NaN,NaN,NaN,NaN
142824,875932195836521,NORMAL,NaN,875932195836521,(G)71210225,6306140214_ID-11981038020,21 May 2022 16:55,NaN,875932195636521,No,Ade Fatonah,NaN,NaN,ade fatonah,Toko Abadi. jalan pasar talagasari los depan d...,NaN,Jawa Barat,Kab. Karawang,Talagasari,NaN,NaN,Kab. Karawang,NaN,Indonesia,NaN,ade fatonah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Karawang,NaN,Indonesia,NaN,0.0,0.0,143.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0020445960,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220521-24.xlsx,Guarantee,STANDARD,NaN,24 May 2022 11:56,NaN,NaN,NaN,22 May 2022 17:18,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.000000,NaN,NaN,NaN,NaN,875932195636521,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.00000,0.000000,0.000000,NaN,Beda,NaN,NaN,NaN,NaN

In [108]:
finres=pd.read_excel("D:\settlement\Code\Settlement Project\Backup\Realisasi April 2022\Final Result\Ke Mbak May\Running Lazada By Selcen Jan 22 - Apr 22 With LazSub and Free Ship Rev 1.xlsx",sheet_name='Running Lazada')

In [110]:
finres=finres.rename(columns={'Paid April':'Paid May'})
finres=finres.rename(columns={'Paid March':'Paid April'})
finres=finres.head(0)
finres

Empty DataFrame
Columns: [Order Item Id, Order Type, Order Flag, Lazada Id, SKU, Product ID, Order Date Seller Centre, Updated at, Order Number, Invoice Required, Customer Name, Customer Email, National Registration Number, Shipping Name, Shipping Address, Shipping Address2, Shipping Address3, Shipping Address4, Shipping Address5, Shipping Phone Number, Shipping Phone Number2, Shipping City, Shipping Postcode, Shipping Country, Shipping Region, Billing Name, Billing Address, Billing Address2, Billing Address3, Billing Address4, Billing Address5, Billing Phone Number, Billing Phone Number2, Billing City, Billing Postcode, Billing Country, Payment Method, Total Seller Centre, Unit Price, Selcen Shipping Fee, Wallet Credits, Item Name, Variation, CD Shipping Provider, Shipping Provider, Warehouse Origin, Shipping Provider Type, CD Tracking Code, Tracking Code, Tracking URL, Shipping Provider (first mile), Tracking Code (first mile), Tracking URL (first mile), Promised shipping time, Premium, Order Status, Cancel / Return Initiator, Reason, Reason Detail, Editor, Bundle ID, Bundle Discount, Refund Amount, Source, Guarantee, Delivery Type, Ware House, Update Time, Rts Sla, Tts Sla, Invoice Number, Delivered Date, Shipping Phone, Shipping Phone2, Shipping Post Code, Billing Addr, Billing Addr2, Billing Addr3, Billing Addr4, Billing Addr5, Billing Phone, Billing Phone2, Billing Post Code, Tax Code, Branch Number, Tax Invoice Requested, Pay Method, Seller Discount Total, Wallet Credit, Cd Shipping Provider, Cd Tracking Code, Tracking Url, Shipping Provider F M, Tracking Code F M, Tracking Url F M, Promised Shipping Time, Buyer Failed Delivery Return Initiator, Buyer Failed Delivery Reason, Buyer Failed Delivery Detail, Buyer Failed Delivery User Name, ...]
Index: []

[0 rows x 188 columns]

In [111]:
finres2=finres.append(lazada_set)

In [113]:
finres2.to_csv(r'D:\settlement\Code\Settlement Project\Backup\Realisasi Mei 2022\Final Result\Raw Unpivoted\CSV/Running Lazada By Selcen Jan 2022 - Mei 2022 v2.csv', sep = ';', index = False)

In [114]:
finres2.to_excel(r'D:\settlement\Code\Settlement Project\Backup\Realisasi Mei 2022\Final Result\Raw Unpivoted\Excel/Running Lazada By Selcen Jan 2022 - Mei 2022 v2.xlsx', index = False)

In [67]:
lazada_set.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Realisasi April 2022/Final Result/Running Lazada By Selcen Jan 2022 - Apr 2022 With LazSub and Free Ship Rev 1.csv', sep = ';', index = False)

In [112]:
lazada_set ##142825 
finres2 ##142825

,Order Item Id,Order Type,Order Flag,Lazada Id,SKU,Product ID,Order Date Seller Centre,Updated at,Order Number,Invoice Required,Customer Name,Customer Email,National Registration Number,Shipping Name,Shipping Address,Shipping Address2,Shipping Address3,Shipping Address4,Shipping Address5,Shipping Phone Number,Shipping Phone Number2,Shipping City,Shipping Postcode,Shipping Country,Shipping Region,Billing Name,Billing Address,Billing Address2,Billing Address3,Billing Address4,Billing Address5,Billing Phone Number,Billing Phone Number2,Billing City,Billing Postcode,Billing Country,Payment Method,Total Seller Centre,Unit Price,Selcen Shipping Fee,Wallet Credits,Item Name,Variation,CD Shipping Provider,Shipping Provider,Warehouse Origin,Shipping Provider Type,CD Tracking Code,Tracking Code,Tracking URL,Shipping Provider (first mile),Tracking Code (first mile),Tracking URL (first mile),Promised shipping time,Premium,Order Status,Cancel / Return Initiator,Reason,Reason Detail,Editor,Bundle ID,Bundle Discount,Refund Amount,Source,Guarantee,Delivery Type,Ware House,Update Time,Rts Sla,Tts Sla,Invoice Number,Delivered Date,Shipping Phone,Shipping Phone2,Shipping Post Code,...,Subtotal Produk 1,Harga Display 1,Harga Cost 1,Produk 2,SKU Produk 2,PCS Produk 2,Price List NFI 2,Subtotal Produk 2,Harga Display 2,Harga Cost 2,Produk 3,SKU Produk 3,PCS Produk 3,Price List NFI 3,Subtotal Produk 3,Harga Display 3,Harga Cost 3,Produk 4,SKU Produk 4,PCS Produk 4,Price List NFI 4,Subtotal Produk 4,Harga Display 4,Harga Cost 4,Produk 5,SKU Produk 5,PCS Produk 5,Price List NFI 5,Subtotal Produk 5,Harga Display 5,Harga Cost 5,Produk 6,SKU Produk 6,PCS Produk 6,Price List NFI 6,Subtotal Produk 6,Harga Display 6,Harga Cost 6,Produk 7,SKU Produk 7,PCS Produk 7,Price List NFI 7,Subtotal Produk 7,Harga Display 7,Harga Cost 7,Price List NFI,Harga Cost,Total Net,Total Harga Cost,Total Net Before PPN,Bundle Name,Bundle Flag,Parent Item,Parent SKU,Customer Order No.,Platform SKU,Status Gudang,Warehouse Quantity,WH,Comfee Prop,Fullfee Prop,Payment Fee,Shipping Fee,Total Transfer,Paid May,Order Paid,Total Produk Prop,BTL Cost,Total Produk Prop Adj,Paid April,Paid Beda,Free Shipping Max Fee,LazSubsidy,Seller SKU,Order No.
0,768518467283259,NORMAL,NaN,768518467283259,2101651195,3192634665_ID-5588762098,07 Jan 2022 22:15,NaN,768518467183259,No,85752452418,NaN,NaN,destia,eplasmen keluwin rayon 2 jangkit jangkit · Air...,NaN,Kalimantan Barat,Kab. Ketapang,Air Upas,NaN,NaN,Kab. Ketapang,NaN,Indonesia,NaN,destia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Ketapang,NaN,Indonesia,NaN,132000.0,132000.0,29500.0,NaN,HiLo Teen Chocolate 1000g - Susu Tinggi Kalsiu...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,07 Jan 2022 22:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144300.0,144300,144300.0,144300,130000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,Cancel,Unpaid,0.0,-130000.0,0.0,Cancel,Sama,0.0,0.0,NaN,NaN
1,768434658315354,NORMAL,NaN,768434658315354,2101751112,HI108OTBGOO8ANID-1473943,07 Jan 2022 20:05,NaN,768434658215354,No,Umi,NaN,NaN,Masfufah,jl Brawijaya 179 · Prajuritkulon (Prajurit Kulon),NaN,Jawa Timur,Kota Mojokerto,Prajurit Kulon,NaN,NaN,Kota Mojokerto,NaN,Indonesia,NaN,Umik,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Lamongan,NaN,Indonesia,NaN,86000.0,86000.0,2000.0,NaN,HiLo Platinum 420g - Susu Tinggi Kalsium Renda...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,08 Jan 2022 20:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,91020.0,91020,91020.0,91020,82000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,Cancel,Unpaid,0.0,-82000.0,0.0,Cancel,Sama,0.0,0.0,NaN,NaN
2,774864588802959,NORMAL,NaN,774864588802959,2101751112,HI108OTBGOO8ANID-1473943,07 Jan 2022 20:00,NaN,774864588702959,No,mala hayati,NaN,NaN,Mala hayati,kp. bojongwarna ds. mekarsari kec. carenang Rt...,NaN,Banten,Kab. Serang,Carenang,NaN,NaN,Kab. Serang,NaN,Indonesia,NaN,Mala hayati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Serang,NaN,Indonesia,NaN,86000.0,86000.0,0.0,NaN,HiLo Platinum 420g - Susu Tinggi Kalsium Renda...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,07 Jan 2022 20:02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,91020.0,91020,91020.0,91020,82000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,Cancel,Unpaid,0.0,-82000.0,0.0,Cancel,Sama,0.0,0.0,NaN,NaN
3,768427407133765,NORMAL,NaN,768427407133765,2305545288,5049956253_ID-9382424569,07 Jan 2022 19:44,NaN,768427407033765,No,Hisnudin lutpi,NaN,NaN,Hisnudin lutfi,jalan. pasirsalam kampung legok heas Rt 04 Rw ...,NaN,Jawa Barat,Kab. Bandung,Soreang,NaN,NaN,Kab. Bandung,NaN,Indonesia,NaN,Hisnudin lutfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bandung,NaN,Indonesia,NaN,252200.0,260000.0,7000.0,NaN,L-Men Platinum Ketan Hitam 800g (25g protein) ...,Rasa Nutrisi:Ketan Hitam,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,07 Jan 2022 19:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305250.0,305250,305250.0,305250,275000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,Cancel,Unpaid,0.0,-275000.0,0.0,Cancel,Sama,0.0,0.0,NaN,NaN
4,774789710106450,NORMAL,NaN,774789710106450,2101150180,TR086WNABLBRA8ANID-130399110,07 Jan 2022 17:47,NaN,774789710006450,No,luh liandriani sulistias,NaN,NaN,luh liandriani sulistias,PT Buana Amanah Karya Jl. melati 23K Rawabadak...,NaN,DKI Jakarta,Kota Jakarta Utara,Koja,NaN,NaN,Kota Jakarta Utara,NaN,Indonesia,NaN,luh liandriani sulistias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Utara,NaN,Indonesia,NaN,103500.0,103500.0,6900.0,NaN,Tropicana Slim Susu Skim Coffee 500g - Bantu T...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,Guarantee,STANDARD,NaN,08 Jan 2022 17:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,113220.0,113220,113220.0,113220,102000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,Cancel,Unpaid,0.0,-102000.0,0.0,Cancel,Sama,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142820,865583258345668,NORMAL,NaN,865583258345668,(G)71210225,6306140214_ID-11981038020,17 May 2022 02:34,NaN,865583258045668,No,Azki Maulana,NaN,NaN,Azki Desi,Linggapura Kel. RT.04 / RW.02 ( LINGGAPURA POR...,NaN,Jawa Tengah,Kab. Brebes,Tonjong,NaN,NaN,Kab. Brebes,NaN,Indonesia,NaN,Azki Desi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Brebes,NaN,Indonesia,NaN,0.0,0.0,255.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,JNE,own_warehouse,STANDARD,NaN,JNAT-0004005942,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,non-Guarantee,STANDARD,NaN,20 May 2022 13:51,NaN,NaN,NaN,19 May 2022 09:45,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.0,NaN,NaN,NaN,NaN,865583258045668,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.0,0.0,0.0,NaN,Beda,NaN,NaN,NaN,NaN
142821,872933754307174,NORMAL,NaN,872933754307174,(B)71210026,6294350528_ID-11966466335,17 May 2022 01:59,NaN,872933754007174,No,85266179919,NaN,NaN,Anis wati,jl. Krakatau · Mentawak Baru,NaN,Jambi,Kab. Sarolangun,Air Hitam,NaN,NaN,Kab. Sarolangun,NaN,Indonesia,NaN,Anis wati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Sarolangun,NaN,Indonesia,NaN,0.0,0.0,7299.0,NaN,[Gift] Spider Bottle Shaker,NaN,NaN,NinjaVanID,own_warehouse,STANDARD,NaN,NLIDAT0003815444,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,non-Guarantee,STANDARD,NaN,22 May 2022 20:42,NaN,NaN,NaN,22 May 2022 20:35,NaN,NaN,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,36000,0.0,36000,0.0,NaN,NaN,NaN,NaN,872933754007174,6294350528_ID-11966466335,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.0,0.0,0.0,NaN,Beda,NaN,NaN,NaN,NaN
142822,865401202625317,NORMAL,NaN,865401202625317,(G)71210225,6306140214_ID-11981038020,16 May 2022 19:07,NaN,865401202125317,No,Lusia Chris,NaN,NaN,Lusia Chris,Villa Nusa Indah 5 blok SB 10/9 Cluster Kasuar...,NaN,Jawa Barat,Kab. Bogor,Gunung Putri,NaN,NaN,Kab. Bogor,NaN,Indonesia,NaN,Lusia Chris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bogor,NaN,Indonesia,NaN,0.0,0.0,714.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0020357760,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,Guarantee,STANDARD,NaN,19 May 2022 20:52,NaN,NaN,NaN,18 May 2022 17:38,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.0,NaN,NaN,NaN,NaN,865401202125317,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.0,0.0,0.0,NaN,Beda,NaN,NaN,NaN,NaN
142823,865054631142870,NORMAL,NaN,865054631142870,(G)71210225,6306140214_ID-11981038020,16 May 2022 09:25,NaN,865054630842870,No,Teguh,NaN,NaN,Teguh,Demak 59581 rt6/rw1 · Jatisono,NaN,Jawa Tengah,Kab. Demak,Gajah,NaN,NaN,Kab. Demak,NaN,Indonesia,NaN,Teguh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Demak,NaN,Indonesia,NaN,0.0,0.0,2000.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,JNE,own_warehouse,STANDARD,NaN,JNAT-0004003174,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220516-20.xlsx,non-Guarantee,STANDARD,NaN,20 May 2022 12:43,NaN,NaN,NaN,19 May 2022 14:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.0,NaN,NaN,NaN,NaN,865054630842870,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.0,0.0,0.0,NaN,Beda,NaN,NaN,NaN,NaN
142824,875932195836521,NORMAL,NaN,875932195836521,(G)71210225,6306140214_ID-11981038020,21 May 2022 16:55,NaN,875932195636521,No,Ade Fatonah,NaN,NaN,ade fatonah,Toko Abadi. jalan pasar talagasari los depan d...,NaN,Jawa Barat,Kab. Karawang,Talagasari,NaN,NaN,Kab. Karawang,NaN,Indonesia,NaN,ade fatonah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Karawang,NaN,Indonesia,NaN,0.0,0.0,143.0,NaN,[Gift] Tumbler HiLo Teen - Warna Random,NaN,NaN,LEX ID,own_warehouse,STANDARD,NaN,LXAT-0020445960,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220521-24.xlsx,Guarantee,STANDARD,NaN,24 May 2022 11:56,NaN,NaN,NaN,22 May 2022 17:18,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0,0,0.0,NaN,NaN,NaN,NaN,875932195636521,6306140214_ID-11981038020,Delivered,1.0,Lazada Warehouse,NaN,-2750.0,0.0,0.0,0.0,Paid,"Paid,Unpaid",0.0,0.0,0.0,NaN,Beda,NaN,NaN,NaN,NaN

In [72]:
set_pivot = pd.pivot_table(settlement_cat[settlement_cat['Fee Name_x'].isin(['LazSubsidy','Free Shipping Max Fee'])], values = 'Amount', index = ['Order No.', 'Seller SKU'], columns = 'Fee Name_x', aggfunc=np.sum).reset_index()

set_pivot['Order No.'] = set_pivot['Order No.'].astype(str)
set_pivot['Seller SKU'] = set_pivot['Seller SKU'].astype(str)
total_trx_merge['Order Number'] = total_trx_merge['Order Number'].astype(str)
total_trx_merge['Real SKU'] = total_trx_merge['Real SKU'].astype(str)

no_prop = total_trx_merge[total_trx_merge['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]
lazada_prop = total_trx_merge[~total_trx_merge['Brand'].isin(['Bonus Produk', 'Gimmick', 'Partnership'])]

bundle_wms = lazada_prop[lazada_prop['Bundle Name'].notnull()]
lazada_set = lazada_prop[lazada_prop['Bundle Name'].isnull()]

lazada_set

,Order Item Id,Order Type,Order Flag,Lazada Id,SKU,Product ID,Order Date Seller Centre,Updated at,Order Number,Invoice Required,Customer Name,Customer Email,National Registration Number,Shipping Name,Shipping Address,Shipping Address2,Shipping Address3,Shipping Address4,Shipping Address5,Shipping Phone Number,Shipping Phone Number2,Shipping City,Shipping Postcode,Shipping Country,Shipping Region,Billing Name,Billing Address,Billing Address2,Billing Address3,Billing Address4,Billing Address5,Billing Phone Number,Billing Phone Number2,Billing City,Billing Postcode,Billing Country,Payment Method,Total Seller Centre,Unit Price,Selcen Shipping Fee,Wallet Credits,Item Name,Variation,CD Shipping Provider,Shipping Provider,Warehouse Origin,Shipping Provider Type,CD Tracking Code,Tracking Code,Tracking URL,Shipping Provider (first mile),Tracking Code (first mile),Tracking URL (first mile),Promised shipping time,Premium,Order Status,Cancel / Return Initiator,Reason,Reason Detail,Editor,Bundle ID,Bundle Discount,Refund Amount,Source,Guarantee,Delivery Type,Ware House,Update Time,Rts Sla,Tts Sla,Invoice Number,Delivered Date,Shipping Phone,Shipping Phone2,Shipping Post Code,...,Harga Cost 1,Produk 2,SKU Produk 2,PCS Produk 2,Price List NFI 2,Subtotal Produk 2,Harga Display 2,Harga Cost 2,Produk 3,SKU Produk 3,PCS Produk 3,Price List NFI 3,Subtotal Produk 3,Harga Display 3,Harga Cost 3,Produk 4,SKU Produk 4,PCS Produk 4,Price List NFI 4,Subtotal Produk 4,Harga Display 4,Harga Cost 4,Produk 5,SKU Produk 5,PCS Produk 5,Price List NFI 5,Subtotal Produk 5,Harga Display 5,Harga Cost 5,Produk 6,SKU Produk 6,PCS Produk 6,Price List NFI 6,Subtotal Produk 6,Harga Display 6,Harga Cost 6,Produk 7,SKU Produk 7,PCS Produk 7,Price List NFI 7,Subtotal Produk 7,Harga Display 7,Harga Cost 7,Price List NFI,Harga Cost,Total Net,Total Harga Cost,Total Net Before PPN,Bundle Name,Bundle Flag,Parent Item,Parent SKU,Customer Order No.,Platform SKU,Status Gudang,Warehouse Quantity,WH,Order No._x,Seller SKU,BTL Cost_x,Comfee Prop,Fullfee Prop,Payment Fee,Shipping Fee,Total Transfer,BTL Cost_y,Order No.,Paid April,Order Paid,Order No._y,Total Produk Prop,BTL Cost,Total Produk Prop Adj,Paid March,Paid Beda
0,768518467283259,NORMAL,NaN,768518467283259,2101651195,3192634665_ID-5588762098,07 Jan 2022 22:15,NaN,768518467183259,No,85752452418,NaN,NaN,destia,eplasmen keluwin rayon 2 jangkit jangkit · Air...,NaN,Kalimantan Barat,Kab. Ketapang,Air Upas,NaN,NaN,Kab. Ketapang,NaN,Indonesia,NaN,destia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Ketapang,NaN,Indonesia,NaN,132000.0,132000.0,29500.0,NaN,HiLo Teen Chocolate 1000g - Susu Tinggi Kalsiu...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,07 Jan 2022 22:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144300.0,144300,144300.0,144300,130000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,Cancel,Unpaid,NaN,0.0,-130000.000000,0.000000,Unpaid,Beda
1,768434658315354,NORMAL,NaN,768434658315354,2101751112,HI108OTBGOO8ANID-1473943,07 Jan 2022 20:05,NaN,768434658215354,No,Umi,NaN,NaN,Masfufah,jl Brawijaya 179 · Prajuritkulon (Prajurit Kulon),NaN,Jawa Timur,Kota Mojokerto,Prajurit Kulon,NaN,NaN,Kota Mojokerto,NaN,Indonesia,NaN,Umik,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Lamongan,NaN,Indonesia,NaN,86000.0,86000.0,2000.0,NaN,HiLo Platinum 420g - Susu Tinggi Kalsium Renda...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,08 Jan 2022 20:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,91020.0,91020,91020.0,91020,82000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,Cancel,Unpaid,NaN,0.0,-82000.000000,0.000000,Unpaid,Beda
2,774864588802959,NORMAL,NaN,774864588802959,2101751112,HI108OTBGOO8ANID-1473943,07 Jan 2022 20:00,NaN,774864588702959,No,mala hayati,NaN,NaN,Mala hayati,kp. bojongwarna ds. mekarsari kec. carenang Rt...,NaN,Banten,Kab. Serang,Carenang,NaN,NaN,Kab. Serang,NaN,Indonesia,NaN,Mala hayati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Serang,NaN,Indonesia,NaN,86000.0,86000.0,0.0,NaN,HiLo Platinum 420g - Susu Tinggi Kalsium Renda...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,07 Jan 2022 20:02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,91020.0,91020,91020.0,91020,82000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,Cancel,Unpaid,NaN,0.0,-82000.000000,0.000000,Unpaid,Beda
3,768427407133765,NORMAL,NaN,768427407133765,2305545288,5049956253_ID-9382424569,07 Jan 2022 19:44,NaN,768427407033765,No,Hisnudin lutpi,NaN,NaN,Hisnudin lutfi,jalan. pasirsalam kampung legok heas Rt 04 Rw ...,NaN,Jawa Barat,Kab. Bandung,Soreang,NaN,NaN,Kab. Bandung,NaN,Indonesia,NaN,Hisnudin lutfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bandung,NaN,Indonesia,NaN,252200.0,260000.0,7000.0,NaN,L-Men Platinum Ketan Hitam 800g (25g protein) ...,Rasa Nutrisi:Ketan Hitam,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,non-Guarantee,STANDARD,NaN,07 Jan 2022 19:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305250.0,305250,305250.0,305250,275000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,Cancel,Unpaid,NaN,0.0,-275000.000000,0.000000,Unpaid,Beda
4,774789710106450,NORMAL,NaN,774789710106450,2101150180,TR086WNABLBRA8ANID-130399110,07 Jan 2022 17:47,NaN,774789710006450,No,luh liandriani sulistias,NaN,NaN,luh liandriani sulistias,PT Buana Amanah Karya Jl. melati 23K Rawabadak...,NaN,DKI Jakarta,Kota Jakarta Utara,Koja,NaN,NaN,Kota Jakarta Utara,NaN,Indonesia,NaN,luh liandriani sulistias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Utara,NaN,Indonesia,NaN,103500.0,103500.0,6900.0,NaN,Tropicana Slim Susu Skim Coffee 500g - Bantu T...,NaN,NaN,NaN,own_warehouse,STANDARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Cancel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220101-07.xlsx,Guarantee,STANDARD,NaN,08 Jan 2022 17:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,113220.0,113220,113220.0,113220,102000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,Cancel,Unpaid,NaN,0.0,-102000.000000,0.000000,Unpaid,Beda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120889,850476433768455,NORMAL,NaN,850476433768455,PT26T54,6233252095_ID-11846486590,23 Apr 2022 10:34,NaN,850476432968455,No,Serta Pane,NaN,NaN,Serta Pane,Jalan Percetakan Negara 4B no.23 · Johar Baru,NaN,DKI Jakarta,Kota Jakarta Pusat,Johar Baru,NaN,NaN,Kota Jakarta Pusat,NaN,Indonesia,NaN,serta pane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Utara,NaN,Indonesia,NaN,34105.0,35900.0,2113.0,NaN,Paket Dapur Sehat - Tropicana Slim Kecap Manis...,NaN,NaN,LEX ID,dropshipping,STANDARD,NaN,LXAD-2569589256,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220421-25.xlsx,non-Guarantee,STANDARD,NaN,26 Apr 2022 21:01,NaN,29 Apr 2022 23:59,150471.0,26 Apr 2022 21:01,NaN,NaN,NaN,...,27750.0,Tropicana Slim Saus Tiram 200ml,2104394210,1.0,26640.0,26640.0,33000.0,26640.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54390.0,54390,54390.0,54390,49000.0,NaN,NaN,NaN,NaN,NaN,NaN,confirmed,1.0,Telkom,NaN,NaN,0.0,1688.1975,NaN,0.0,0.0,34105.0,NaN,NaN,Unpaid,"Paid,Unpaid",NaN,34105.0,-18274.774775,30725.225225,NaN,Beda
120890,850476433868455,NORMAL,NaN,850476433868455,PT26T54,6233252095_ID-11846486590,23 Apr 2022 10:34,NaN,850476432968455,No,Serta Pane,NaN,NaN,Serta Pane,Jalan Percetakan Negara 4B no.23 · Johar Baru,NaN,DKI Jakarta,Kota Jakarta Pusat,Johar Baru,NaN,NaN,Kota Jakarta Pusat,NaN,Indonesia,NaN,serta pane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kota Jakarta Utara,NaN,Indonesia,NaN,34105.0,35900.0,2113.0,NaN,Paket Dapur Sehat - Tropicana Slim Kecap Manis...,NaN,NaN,LEX ID,dropshipping,STANDARD,NaN,LXAD-2569589256,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220421-25.xlsx,non-Guarantee,STANDARD,NaN,26 Apr 2022 21:01,NaN,29 Apr 2022 23:59,150471.0,26 Apr 2022 21:01,NaN,NaN,NaN,...,27750.0,Tropicana Slim Saus Tiram 200ml,2104394210,1.0,26640.0,26640.0,33000.0,26640.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54390.0,54390,54390.0,54390,49000.0,NaN,NaN,NaN,NaN,NaN,NaN,confirmed,1.0,Telkom,NaN,NaN,0.0,1688.1975,NaN,0.0,0.0,34105.0,NaN,NaN,Unpaid,"Paid,Unpaid",NaN,34105.0,-18274.774775,30725.225225,NaN,Beda
120891,857555554280888,NORMAL,NaN,857555554280888,PT23T51,5843072295_ID-11303288541,23 Apr 2022 09:35,NaN,857555553980888,No,Shishi Anindita,NaN,NaN,shishi,the breeze 2 no. 22 sentul nirwana residence ·...,NaN,Jawa Barat,Kab. Bogor,Babakan Madang,NaN,NaN,Kab. Bogor,NaN,Indonesia,NaN,Shishi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bogor,NaN,Indonesia,NaN,39000.0,39000.0,0.0,NaN,Paket Coffee Time - Tropicana Slim Avocado Cof...,NaN,NaN,LEX ID,dropshipping,STANDARD,NaN,LXAD-2569589324,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220421-25.xlsx,non-Guarantee,STANDARD,NaN,26 Apr 2022 22:29,NaN,29 Apr 2022 23:59,150461.0,26 Apr 2022 22:29,NaN,NaN,NaN,...,13320.0,Tropicana Slim Cafe Latte (10 sch),2104153110,1.0,29415.0,29415.0,39000.0,29415.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42735.0,42735,42735.0,42735,38500.0,NaN,NaN,NaN,NaN,NaN,NaN,confirmed,1.0,Telkom,NaN,NaN,0.0,1930.5000,NaN,0.0,0.0,39000.0,NaN,NaN,Unpaid,"Paid,Unpaid",NaN,39000.0,-3364.864865,35135.135135,NaN,Beda
120892,850318657255457,NORMAL,NaN,850318657255457,2104407,1940418273_ID-3810342748,23 Apr 2022 07:24,NaN,850318655355457,No,*********245,NaN,NaN,Neni oktarin,perumahan Mustika Media Residence jl.salak 9 B...,NaN,Jawa Barat,Kab. Bekasi,Setu,NaN,NaN,Kab. Bekasi,NaN,Indonesia,NaN,Neni oktarin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bekasi,NaN,Indonesia,NaN,83200.0,83200.0,8129.0,NaN,Tropicana Slim Extra Virgin Olive Oil 500ml - ...,NaN,NaN,LEX ID,dropshipping,STANDARD,NaN,LXAD-2569589112,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220421-25.xlsx,non-Guarantee,STANDARD,NaN,26 Apr 2022 18:25,NaN,29 Apr 2022 23:59,150442.0,26 Apr 2022 18:25,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86580.0,86580,86580.0,86580,78000.0,NaN,NaN,NaN,NaN,850318655355457,2104407,confirmed,1.0,Telkom,NaN,NaN,0.0,4118.4000,NaN,0.0,0.0,83200.0,NaN,NaN,Unpaid,"Paid,Unpaid",NaN,83200.0,-3045.045045,74954.954955,NaN,Beda
120893,850318657355457,NORMAL,NaN,850318657355457,PT26T54,6233252095_ID-11846486590,23 Apr 2022 07:24,NaN,850318655355457,No,*********245,NaN,NaN,Neni oktarin,perumahan Mustika Media Residence jl.salak 9 B...,NaN,Jawa Barat,Kab. Bekasi,Setu,NaN,NaN,Kab. Bekasi,NaN,Indonesia,NaN,Neni oktarin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bekasi,NaN,Indonesia,NaN,35900.0,35900.0,3871.0,NaN,Paket Dapur Sehat - Tropicana Slim Kecap Manis...,NaN,NaN,LEX ID,dropshipping,STANDARD,NaN,LXAD-2569589112,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220421-25.xlsx,non-Guarantee,STANDARD,NaN,26 Apr 2022 18:25,NaN,29 Apr 2022 23:59,150442.0,26 Apr 2022 18:25,NaN,NaN,NaN,...,27750.0,Tropicana Slim Saus Tiram 200ml,2104394210,1.0,26640.0,26640.0,33000.0,26640.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54390.0,54390,54390.0,54390,49000.0,NaN,NaN,NaN,NaN,NaN,NaN,confirmed,1.0,Telkom,NaN,NaN,0.0,1777.0500,NaN,0.0,0.0,35900.0,NaN,NaN,Unpaid,"Paid,Unpaid",NaN,35900.0,-16657.657658,32342.342342,NaN,Beda

In [88]:
settlement_cat[settlement_cat['Order No.'] == '789194164705927']

,key_0,Fee Name_x,Order No.,Seller SKU,Lazada SKU,Kategori,Amount
287515,commission,Commission,789194164705927,2101150180,TR086WNABLBRA8ANID-130399110,ComFee,-4965.0
287516,commission,Commission,789194164705927,2104589105P3,5972504646_ID-11450758558,ComFee,-2811.0
522956,fbl handling fee,FBL Handling Fee,789194164705927,2101150180,TR086WNABLBRA8ANID-130399110,FullFee,-2750.0
522957,fbl handling fee,FBL Handling Fee,789194164705927,2104589105P3,5972504646_ID-11450758558,FullFee,-2750.0
627105,free shipping max fee,Free Shipping Max Fee,789194164705927,2101150180,TR086WNABLBRA8ANID-130399110,BTL Cost,-2009.0
627106,free shipping max fee,Free Shipping Max Fee,789194164705927,2104589105P3,5972504646_ID-11450758558,BTL Cost,-1137.0
888088,item price credit,Item Price Credit,789194164705927,2101150180,TR086WNABLBRA8ANID-130399110,Total Transfer,103500.0
888089,item price credit,Item Price Credit,789194164705927,2104589105P3,5972504646_ID-11450758558,Total Transfer,58600.0
1249689,payment fee,Payment Fee,789194164705927,2101150180,TR086WNABLBRA8ANID-130399110,Payment Fee,-1810.0
1249690,payment fee,Payment Fee,789194164705927,2104589105P3,5972504646_ID-11450758558,Payment Fee,-1025.0
1368869,promotional charges vouchers,Promotional Charges Vouchers,789194164705927,2101150180,TR086WNABLBRA8ANID-130399110,BTL Cost,-3192.0
1368870,promotional charges vouchers,Promotional Charges Vouchers,789194164705927,2104589105P3,5972504646_ID-11450758558,BTL Cost,-1808.0

In [48]:
# total_trx_merge = total_trx_full.merge(source.groupby(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name'])['Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

# # total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# # total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# # total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')

# total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
#                                                   'Total Produk Prop_x' : 'Total Produk Prop',
#                                                   'Comfee Prop_x' : 'Comfee Prop'})

# total_trx_null = total_trx_null.merge(source.groupby(['Order #', 'Product Name', 'Bundle Name'])['Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Item Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
# total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

# # total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# # total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# # total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')

# total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
#                                                   'Total Produk Prop_x' : 'Total Produk Prop',
#                                                   'Comfee Prop_x' : 'Comfee Prop'})

# total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
# total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')

# # # total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# # # source2 = source.copy()

# # # source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# # # indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# # # source2['Real SKU'][indeks] = '(U)2101809250'

# # # indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# # # source2['Real SKU'][indeks] = '2101941250P4'

# # # indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# # # source2['Real SKU'][indeks] = '2101809250P4'

# # # total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# # # total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
# # #                                                   'Total Produk Prop_x' : 'Total Produk Prop',
# # #                                                   'Comfee Prop_x' : 'Comfee Prop'})

# # # total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
# # # total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# # # total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# # # total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [36]:
total_trx_merge[total_trx_merge['Total Net_y'].notnull()]

,Order Item Id,Order Type,Order Flag,Lazada Id,SKU,Product ID,Order Date Seller Centre,Updated at,Order Number,Invoice Required,...,Paid,Order Paid,Order No._y,Total Produk Prop_x,BTL Cost,Total Produk Prop Adj,Order #,Total Net_y,Total Produk Prop_y,Comfee Prop_y
14443,768509484025365,NORMAL,NaN,768509484025365,2104405,1946174577_ID-3820002565,07 Jan 2022 22:07,NaN,768509483925365,No,...,Paid,Paid,NaN,171800.000000,-14818.181818,156181.818182,7.685095e+14,188100.0,171800.000000,-1701.000000
14444,768461897346810,NORMAL,NaN,768461897346810,2304558112,4343962728_ID-7448464302,07 Jan 2022 20:53,NaN,768461897246810,No,...,Paid,Paid,NaN,401095.000000,-35368.181818,364631.818182,7.684619e+14,440000.0,401095.000000,-3971.000000
14445,774830167537911,NORMAL,NaN,774830167537911,2104402,1416074372_ID-2591268238,07 Jan 2022 19:04,NaN,774830167437911,No,...,Paid,Paid,NaN,148000.000000,-5454.545455,134545.454545,7.748302e+14,154000.0,148000.000000,-1465.000000
14446,768386231728760,NORMAL,NaN,768386231728760,2304558112,LM705WNAB5UDZGANID-94564946,07 Jan 2022 18:48,NaN,768386231628760,No,...,Paid,Paid,NaN,206000.000000,-12727.272727,187272.727273,7.683862e+14,220000.0,206000.000000,-2039.000000
14447,774802136226969,NORMAL,NaN,774802136226969,2102900125,1328800045_ID-2364118252,07 Jan 2022 18:12,NaN,774802136126969,No,...,Paid,Paid,NaN,77260.000000,-3763.636364,70236.363636,7.748021e+14,81400.0,77260.000000,-782.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46403,764828490764003,NORMAL,NaN,764828490764003,2104543105,5691008596_ID-11140142464,02 Jan 2022 21:29,NaN,764828490664003,No,...,Paid,Paid,NaN,18500.000000,-1681.818182,16818.181818,7.648285e+14,20350.0,18500.000000,-915.666667
46404,771792116572037,NORMAL,NaN,771792116572037,2106386249,5911748889_ID-11382014904,03 Jan 2022 15:04,NaN,771792116272037,No,...,Paid,Paid,NaN,16567.883212,2061.712011,15061.712011,7.717921e+14,14300.0,16567.883212,-163.970803
46405,771792116572037,NORMAL,NaN,771792116572037,2104589105,5911748889_ID-11382014904,03 Jan 2022 15:04,NaN,771792116272037,No,...,Paid,Paid,NaN,23577.372263,2933.974784,21433.974784,7.717921e+14,20350.0,23577.372263,-233.343066
46406,771792116572037,NORMAL,NaN,771792116572037,2106395308,5911748889_ID-11382014904,03 Jan 2022 15:04,NaN,771792116272037,No,...,Paid,Paid,NaN,33135.766423,4123.424021,30123.424021,7.717921e+14,28600.0,33135.766423,-327.941606
46407,771792116572037,NORMAL,NaN,771792116572037,2104115163,5911748889_ID-11382014904,03 Jan 2022 15:04,NaN,771792116272037,No,...,Paid,Paid,NaN,14018.978102,1744.525547,12744.525547,7.717921e+14,12100.0,14018.978102,-138.744526

In [71]:
temp = total_trx_merge[total_trx_merge['Order Number'] == 779791057355840][['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Total Net Before PPN', 'Total Net_x', 'Total Net_y']].copy()

In [72]:
temp

,Order Number,Real SKU,Real Nama Produk,Bundle Name,Qty. Invoiced,Total Net Before PPN,Total Net_x,Total Net_y
11832,779791057355840,1101909331P4,NutriSari American Sweet Orange (160 Sch),NaN,1.0,148800.0,163680.0,163680.0
11833,779791057355840,1101909331P4,NutriSari American Sweet Orange (160 Sch),NaN,1.0,148800.0,163680.0,163680.0
11834,779791057355840,1101909331P4,NutriSari American Sweet Orange (160 Sch),NaN,1.0,148800.0,163680.0,163680.0
11835,779791057355840,1101534453,NutriSari Sweet Mango (40 sch),NaN,1.0,37200.0,40920.0,40920.0
11836,779791057355840,1101534453,NutriSari Sweet Mango (40 sch),NaN,1.0,37200.0,40920.0,40920.0
15942,779791057355840,1101909331,Nutrisari American Sweet Orange (40 Sch),NutriSari American Sweet Orange 160 sachet - M...,4.0,148800.0,163680.0,163680.0
15943,779791057355840,1101909331,Nutrisari American Sweet Orange (40 Sch),NutriSari American Sweet Orange 160 sachet - M...,4.0,148800.0,163680.0,163680.0
15944,779791057355840,1101909331,Nutrisari American Sweet Orange (40 Sch),NutriSari American Sweet Orange 160 sachet - M...,4.0,148800.0,163680.0,163680.0

In [58]:
temp['Total Net_y'] * temp['Total Net Before PPN']/temp.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')

11832    163680.0
11833    163680.0
11834    163680.0
11835     40920.0
11836     40920.0
15942    163680.0
15943    163680.0
15944    163680.0
dtype: float64

In [46]:
source[source['Order #'] == 779791057355840][['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Total Net']]

,Order #,Real SKU,Real Nama Produk,Bundle Name,Qty. Invoiced,Total Net
7846,779791057355840,1101909331P4,NutriSari American Sweet Orange (160 Sch),NaN,3.0,491040.0
7847,779791057355840,1101534453,NutriSari Sweet Mango (40 sch),NaN,2.0,81840.0
7848,779791057355840,1101909331,Nutrisari American Sweet Orange (40 Sch),NutriSari American Sweet Orange 160 sachet - M...,12.0,491040.0

In [49]:
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

In [50]:
total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

In [51]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v8.csv', sep = ';', index = False)

In [137]:
total_trx_merge[total_trx_merge['Order Number'].isin(source_cp[source_cp['Paid January'] == 'Paid']['Order #'])].to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v3.csv', sep = ';', index = False)

In [153]:
total_trx_merge_cp = total_trx_merge.copy()

In [137]:
total_trx_merge[total_trx_merge['Order Number'].isin(source_cp[source_cp['Paid January'] == 'Paid']['Order #'])].to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v3.csv', sep = ';', index = False)

In [137]:
total_trx_merge[total_trx_merge['Order Number'].isin(source_cp[source_cp['Paid January'] == 'Paid']['Order #'])].to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v3.csv', sep = ';', index = False)

In [75]:
total_trx_merge[total_trx_merge['Order Number'] == 777552216072041][['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Price List NFI', 'Total Net by Selcen', 'Total Net Real Jan', 'Delta Total Net']]

,Order Number,Real SKU,Real Nama Produk,Bundle Name,Qty. Invoiced,Price List NFI,Total Net by Selcen,Total Net Real Jan,Delta Total Net
7854,777552216072041,2101428190P2,HiLo School Vanilla Vegiberi [750g x 2 pcs],NaN,1.0,213400.0,213400.0,213400.0,0.0
7855,777552216072041,2101428190P2,HiLo School Vanilla Vegiberi [750g x 2 pcs],NaN,1.0,213400.0,213400.0,213400.0,0.0
7856,777552216072041,2101428190,HiLo School Vanilla Vegiberi 750gr,NaN,1.0,106700.0,106700.0,106700.0,0.0
15764,777552216072041,2101428190,HiLo School Vanilla Vegiberi 750gr,Twin Pack - HiLo School Vanilla Vegiberi 750gr...,2.0,106700.0,213400.0,213400.0,0.0
15765,777552216072041,2101428190,HiLo School Vanilla Vegiberi 750gr,Twin Pack - HiLo School Vanilla Vegiberi 750gr...,2.0,106700.0,213400.0,213400.0,0.0

In [66]:
source[source['Order #'] == 777552216072041][['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Total Net']]

,Order #,Real SKU,Real Nama Produk,Bundle Name,Qty. Invoiced,Total Net
5777,777552216072041,2101428190,HiLo School Vanilla Vegiberi 750gr,Twin Pack - HiLo School Vanilla Vegiberi 750gr...,4.0,426800.0
5778,777552216072041,2101428190,HiLo School Vanilla Vegiberi 750gr,NaN,1.0,106700.0
5779,777552216072041,2101428190P2,HiLo School Vanilla Vegiberi [750g x 2 pcs],NaN,2.0,426800.0

In [386]:
total_trx_merge[total_trx_merge['Order Number'] == '783629138765346'][['Order Number', 'Paid','Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Price List NFI', 'Total Net Before PPN','Total Transfer', 'BTL Cost','Total Produk Prop by Selcen', 'Total Produk Prop Real Jan', 'Delta Total Produk Prop']]

,Order Number,Paid,Real SKU,Real Nama Produk,Bundle Name,Qty. Invoiced,Price List NFI,Total Net Before PPN,Total Transfer,BTL Cost,Total Produk Prop by Selcen,Total Produk Prop Real Jan,Delta Total Produk Prop
8296,783629138765346,Paid,2300551155P2,L-Men Daily Chocolate 250gr x2,NaN,1.0,99000.0,90000.0,94100.0,-7181.818182,91100.0,87092.0,4008.0
14928,783629138765346,Paid,2300551155,L-Men Whey Daily Dark Chocolate 250gr,Twin Pack - L-Men Hi Protein Whey Daily Dark C...,2.0,49500.0,90000.0,94100.0,-7181.818182,91100.0,87092.0,4008.0

In [382]:
source_cp[source_cp['Order #'] == '777908654992873'][['Order #' ,'Paid January','Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced','Total Produk Prop', 'Total Net Before PPN', 'Total Produk Prop Adj']]

,Order #,Paid January,Real SKU,Real Nama Produk,Bundle Name,Qty. Invoiced,Total Produk Prop,Total Net Before PPN,Total Produk Prop Adj
217395,777908654992873,Paid,2300542155P2,Twin Pack: L-Men Daily Popcorn Caramel 250gr x 2,NaN,1.0,92000.0,90000.0,83636.363636
258182,777908654992873,Paid,2300542155,L-Men Daily Popcorn Caramel 250gr,Twin Pack - L-Men Hi Protein Daily Popcorn Car...,2.0,92000.0,90000.0,83636.363636

In [125]:
(133700.0 - 120929.938931)

12770.061069000003

In [127]:
(133700.0 -127221.0)

6479.0

In [108]:
8640 * 146300/(146300.0 + 146300.0 + 133700.0)

2965.1231527093596

In [126]:
9978+2965.1231527093596

12943.123152709359

In [129]:
9978 - 2965

7013

In [94]:
set_pivot['Bi Produk'] = set_pivot['Total Transfer'] + set_pivot['BTL Cost']

In [387]:
set_pivot[set_pivot['Order No.'] == '783629138765346']

Kategori,Order No.,Seller SKU,BTL Cost,ComFee,FullFee,Payment Fee,Shipping Fee,Total Transfer
244432,783629138765346,2300551155P2,-3000.0,-902.0,-2750.0,-1643.0,NaN,94100.0

In [388]:
no_details_pivot[no_details_pivot['Order No.'] == '783629138765346']

Kategori        Order No.  BTL Cost
9151      783629138765346       0.0

In [1]:
import pandas as pd
import numpy as np
import os

In [154]:
total_trx = pd.read_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v7.csv', sep = ';')

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (69,80,92,110,118,126,170,172,173,180) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [106]:
source_cp.columns[-25:]

Index(['Store Type', 'Region Group', 'PL Before PPN', 'Total Net Before PPN',
       'Category Baru', 'Exported Parent Item', 'Order Date Seller Centre',
       'Product ID', 'Total Seller Centre', 'Order Status Seller Centre',
       'Warehouse Origin', 'Paid January', 'Order Paid', 'Status Gudang', 'WH',
       'Warehouse Quantity', 'Total Produk Prop', 'Fullfee Prop',
       'Comfee Prop', 'BTL Cost', 'Payment Fee', 'Shipping Fee',
       'Total Produk Prop Adj', 'Paid December', 'Paid Beda'],
      dtype='object')

In [155]:
total_trx_full = total_trx.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

In [1]:
import pandas as pd

In [2]:
total_trx = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Lazada Testing by Selcen Compare v5.csv", sep = ';')

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (69,80,92,110,118,126,170,172,173,180) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
total_trx_full = total_trx.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_full['Order Number'] = total_trx_full['Order Number'].astype(str)

In [156]:
source = pd.read_csv(r"D:\Backup\Backup 26 Mei\Settlement Project Backup\Realisasi Februari 2022\Final Result\Runningan Lazada Jan 2021 - Feb 2022 Real.csv", sep = ';')

source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021)]

# selcen_sku['OrderId'] = selcen_sku['OrderId'].astype(str)
source['Order #'] = source['Order #'].astype(str)
source['Real SKU'] = source['Real SKU'].astype(str)

# selcen_old = selcen_sku[selcen_sku['OrderId'].isin(source['Order #'])]

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (14,22,23,24) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [157]:
total_trx_full['Order Number'] = total_trx_full['Order Number'].astype(str)

In [158]:
total_trx_merge = total_trx_full.merge(source.groupby(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid February'])['Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid February'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source.groupby(['Order #', 'Product Name', 'Bundle Name', 'Paid February'])['Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Item Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']

# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid February'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop', 'Paid February']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']

total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')


# # total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# # source2 = source.copy()

# # source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# # indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# # source2['Real SKU'][indeks] = '(U)2101809250'

# # indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# # source2['Real SKU'][indeks] = '2101941250P4'

# # indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# # source2['Real SKU'][indeks] = '2101809250P4'

# # total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# # total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
# #                                                   'Total Produk Prop_x' : 'Total Produk Prop',
# #                                                   'Comfee Prop_x' : 'Comfee Prop'})

# # total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
# # total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# # total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# # total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [127]:
len(total_trx_full)

47530

In [128]:
len(total_trx_merge)

47530

In [159]:
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

In [160]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare vPaid 2.csv', sep = ';', index = False)

In [131]:
total_trx_merge[total_trx_merge['Order Number'] == '789032345413430'][['Order Number','Item Name','Paid', 'Paid February', 'Bundle Name', 'Qty. Invoiced']].values

array([['789032345413430',
        'Twin Pack - L-Men Gain Mass Taro 225g - Suplemen Penambah Massa Otot Tinggi Whey Protein-Rasa Nutrisi:Taro',
        'Paid', 'Paid', nan, 1.0],
       ['789032345413430', 'L-MEN Gain Mass Taro 225 gr', nan, 'Paid',
        'Twin Pack - L-Men Gain Mass Taro 225g - Suplemen Penambah Massa Otot Tinggi Whey Protein - Rasa Nutrisi:Taro',
        2.0]], dtype=object)

In [13]:
source[source['Order #'] == '768056645215186'][['Order #','Real Nama Produk','Paid February', 'Bundle Name', 'Qty. Invoiced']]

,Order #,Real Nama Produk,Paid February,Bundle Name,Qty. Invoiced
141370,768056645215186,Paket Cookies - Tropicana Slim Korean Garlic B...,Paid,NaN,1.0
161575,768056645215186,HiLo Chocolate Taro RTD 200ml x 2pcs - Near ED,Paid,NaN,1.0
161576,768056645215186,Hilo RTD Thai Tea 200ml x 2 pcs - Near ED,Paid,NaN,1.0
202909,768056645215186,Tropicana Slim Hokkaido Cheese Cookies,Paid,Paket Cookies - Tropicana Slim Korean Garlic B...,1.0
202910,768056645215186,Tropicana Slim Korean Garlic Butter Cookies 5 Sch,Paid,Paket Cookies - Tropicana Slim Korean Garlic B...,1.0
210041,768056645215186,Hilo RTD Thai Tea 200ml - Near ED,Paid,CRAZY DEALS - HiLo Thai Tea Ready To Drink 200...,2.0
210042,768056645215186,HiLo Chocolate Taro RTD 200ml - Near ED,Paid,CRAZY DEALS - HiLo Chocolate Taro Ready To Dri...,2.0

In [53]:
import pandas as pd
import numpy as np
import os

total_trx = pd.read_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare v8.csv', sep = ';')

total_trx_full = total_trx.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

source = pd.read_csv(r"D:\Backup\Backup 26 Mei\Settlement Project Backup\Realisasi Januari 2022\Final Result\Runningan Lazada Jan 2021 - Jan 2022 Real.csv", sep = ';')

source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021)]

# selcen_sku['OrderId'] = selcen_sku['OrderId'].astype(str)
source['Order #'] = source['Order #'].astype(str)
source['Real SKU'] = source['Real SKU'].astype(str)

# selcen_old = selcen_sku[selcen_sku['OrderId'].isin(source['Order #'])]

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

total_trx_full['Order Number'] = total_trx_full['Order Number'].astype(str)

total_trx_merge = total_trx_full.merge(source.groupby(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid January'])['Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid January'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source.groupby(['Order #', 'Product Name', 'Bundle Name', 'Paid January'])['Total Net', 'Total Produk Prop', 'Comfee Prop'].sum().reset_index(), how = 'left', left_on = ['Order Number', 'Item Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid January'][total_trx_null.index] = total_trx_null['Paid January']

# total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')
# total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', ])['Total Net Before PPN'].transform('sum')

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y', 'Paid January'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop', 'Paid January']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid January'][total_trx_null.index] = total_trx_null['Paid January']

total_trx_merge['Total Net_y'] = total_trx_merge['Total Net_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Total Produk Prop_y'] = total_trx_merge['Total Produk Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')
total_trx_merge['Comfee Prop_y'] = total_trx_merge['Comfee Prop_y'] * total_trx_merge['Total Net Before PPN']/total_trx_merge.groupby(['Order Number', 'Real SKU', 'Bundle Name'], dropna = False)['Total Net Before PPN'].transform('sum')


# # total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# # source2 = source.copy()

# # source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# # indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# # source2['Real SKU'][indeks] = '(U)2101809250'

# # indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# # source2['Real SKU'][indeks] = '2101941250P4'

# # indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# # source2['Real SKU'][indeks] = '2101809250P4'

# # total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# # total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
# #                                                   'Total Produk Prop_x' : 'Total Produk Prop',
# #                                                   'Comfee Prop_x' : 'Comfee Prop'})

# # total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Order Number', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
# # total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# # total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# # total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_merge = total_trx_merge.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_merge['Paid Beda'] = np.nan

indeks = total_trx_merge[total_trx_merge['Paid'] != total_trx_merge['Paid January']].index.to_list()
total_trx_merge['Paid Beda'][indeks] = 'Beda'

total_trx_merge['Paid Beda'] = total_trx_merge['Paid Beda'].fillna('Sama')
# total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'][['Order #','Brand','Real SKU','Month', 'Paid_x', 'Paid_y', 'Paid Beda']]
total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'].groupby(['Month', 'Paid', 'Paid January'], dropna  = False)['Order Number'].nunique()

C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (69,80,92,110,118,126,170,172,173,180) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (14,22,23,24) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:32: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:45: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\andra.miftah\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:124: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Month     Paid    Paid January
February  Cancel  NaN                34
          Paid    NaN             13372
          Refund  NaN                 2
          Unpaid  NaN              3213
January   Cancel  Unpaid              5
                  NaN                 3
          Paid    Cancel              6
                  Unpaid           2765
                  NaN              4593
          Refund  Cancel             25
                  Unpaid             51
                  NaN                 7
          Unpaid  NaN               678
Name: Order Number, dtype: int64

In [54]:
total_trx_merge = total_trx_merge.rename(columns = {'Paid' : 'Paid February'})

In [55]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Lazada Testing by Selcen Compare vPaid Beda.csv', sep = ';', index = False)

In [82]:
# mei=pd.read_csv("D:\settlement\Code\Settlement Project\Backup\Realisasi Mei 2022\Final Result\Raw Unpivoted\CSV\Running Lazada By Selcen Jan 2022 - Mei 2022 v2.csv",sep=';')
# jun=pd.read_csv("D:\settlement\Code\Settlement Project\Backup\Realisasi Juni 2022\Final Result\Raw Unpivoted\CSV\Running Lazada By Selcen Jan 2022 - Jun 2022.csv",sep=';')
sourcejun = pd.read_csv(r"D:\settlement\Code\Settlement Project\Backup\Realisasi Juni 2022\Final Result\Raw Unpivoted\CSV\Running Lazada By Selcen Jan 2022 - Jun 2022.csv", sep = ';')

In [ ]:
mei[mei['Order Item Id'].isin(jun['Order Item Id'].unique())].rename(columns={'Paid May':'Paid June','Paid April':'Paid May'})
sourcejun

In [ ]:
jun

In [ ]:
mei

In [138]:
cek=pd.read_excel("D:\settlement\Code\Settlement Project\Backup\Realisasi Juli 2022\Final Result\Raw Unpivoted\Excel\Running Lazada By Selcen Jan 2022 - Jul 2022 rev2.xlsx")

In [105]:
case=pd.read_excel("D:\Downloads\case lazada.xlsx")

In [130]:
# cek[cek['']]

In [139]:
cek[cek['Order Item Id']==885185568741700]
# cek.columns

,Order Item Id,Order Type,Order Flag,Lazada Id,SKU,Product ID,Order Date Seller Centre,Updated at,Order Number,Invoice Required,Customer Name,Customer Email,National Registration Number,Shipping Name,Shipping Address,Shipping Address2,Shipping Address3,Shipping Address4,Shipping Address5,Shipping Phone Number,Shipping Phone Number2,Shipping City,Shipping Postcode,Shipping Country,Shipping Region,Billing Name,Billing Address,Billing Address2,Billing Address3,Billing Address4,Billing Address5,Billing Phone Number,Billing Phone Number2,Billing City,Billing Postcode,Billing Country,Payment Method,Total Seller Centre,Unit Price,Selcen Shipping Fee,Wallet Credits,Item Name,Variation,CD Shipping Provider,Shipping Provider,Warehouse Origin,Shipping Provider Type,CD Tracking Code,Tracking Code,Tracking URL,Shipping Provider (first mile),Tracking Code (first mile),Tracking URL (first mile),Promised shipping time,Premium,Order Status,Cancel / Return Initiator,Reason,Reason Detail,Editor,Bundle ID,Bundle Discount,Refund Amount,Source,Guarantee,Delivery Type,Ware House,Update Time,Rts Sla,Tts Sla,Invoice Number,Delivered Date,Shipping Phone,Shipping Phone2,Shipping Post Code,...,SKU Produk 2,PCS Produk 2,Price List NFI 2,Subtotal Produk 2,Harga Display 2,Harga Cost 2,Produk 3,SKU Produk 3,PCS Produk 3,Price List NFI 3,Subtotal Produk 3,Harga Display 3,Harga Cost 3,Produk 4,SKU Produk 4,PCS Produk 4,Price List NFI 4,Subtotal Produk 4,Harga Display 4,Harga Cost 4,Produk 5,SKU Produk 5,PCS Produk 5,Price List NFI 5,Subtotal Produk 5,Harga Display 5,Harga Cost 5,Produk 6,SKU Produk 6,PCS Produk 6,Price List NFI 6,Subtotal Produk 6,Harga Display 6,Harga Cost 6,Produk 7,SKU Produk 7,PCS Produk 7,Price List NFI 7,Subtotal Produk 7,Harga Display 7,Harga Cost 7,Price List NFI,Harga Cost,Total Net,Total Harga Cost,Total Net Before PPN,Bundle Name,Bundle Flag,Parent Item,Parent SKU,Customer Order No.,Platform SKU,Status Gudang,Warehouse Quantity,WH,Comfee Prop,Fullfee Prop,Payment Fee,Shipping Fee,Total Transfer,Paid July,Order Paid,Total Produk Prop,BTL Cost,Total Produk Prop Adj,Paid June,Paid Beda,Free Shipping Max Fee,LazSubsidy,Seller SKU,Order No.,Order No._x,BTL Cost_x,BTL Cost_y,Order No._y
54862,885185568741700,NORMAL,NaN,885185568741700,2304008151P2,695028002_ID-963450677,04 Jun 2022 07:29,NaN,885185568641700,No,Andry Gunawan,NaN,NaN,Andry,jalan tanjung kalian indah No 01 depan masjid ...,NaN,Bangka Belitung,Kab. Bangka Barat,Mentok (Muntok),NaN,NaN,Kab. Bangka Barat,NaN,Indonesia,NaN,Andry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bangka Barat,NaN,Indonesia,NaN,110900.0,110900.0,31000.0,NaN,Twin Pack - L-Men Gain Mass Taro 225g - Suplem...,Rasa Nutrisi:Taro,NaN,NinjaVanID,own_warehouse,STANDARD,NaN,NLIDAT0003871378,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220601-05.xlsx,non-Guarantee,STANDARD,NaN,22 Jun 2022 10:35,NaN,NaN,NaN,07 Jun 2022 10:26,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,133200.0,133200,133200.0,133200,120000.0,NaN,NaN,NaN,NaN,8.851856e+14,695028002_ID-963450677,Delivered,1.0,Lazada Warehouse,-1108.0,-2775.0,-2019.0,-2240.0,110900.0,Paid,Paid,110900.0,-20090.09009,99909.90991,Paid,Sama,NaN,NaN,2304008151P2,NaN,8.851856e+14,0.0,NaN,NaN
131498,885185568741700,NORMAL,NaN,885185568741700,2304008151,695028002_ID-963450677,04 Jun 2022 07:29,NaN,885185568641700,No,Andry Gunawan,NaN,NaN,Andry,jalan tanjung kalian indah No 01 depan masjid ...,NaN,Bangka Belitung,Kab. Bangka Barat,Mentok (Muntok),NaN,NaN,Kab. Bangka Barat,NaN,Indonesia,NaN,Andry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kab. Bangka Barat,NaN,Indonesia,NaN,110900.0,110900.0,31000.0,NaN,L-MEN Gain Mass Taro 225 gr,Rasa Nutrisi:Taro,NaN,NinjaVanID,own_warehouse,STANDARD,NaN,NLIDAT0003871378,NaN,NaN,NaN,NaN,NaN,No,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seller Center Lazada 20220601-05.xlsx,non-Guarantee,STANDARD,NaN,22 Jun 2022 10:35,NaN,NaN,NaN,07 Jun 2022 10:26,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,66600.0,66600,133200.0,133200,120000.0,Twin Pack - L-Men Gain Mass Taro 225g - Suplem...,NaN,L-Men Gainmass Taro 225gr,NaN,NaN,695028002_ID-963450677,Delivered,2.0,NaN,-1108.0,-2775.0,-2019.0,-2240.0,110900.0,Paid,Paid,110900.0,-20090.09009,99909.90991,Paid,Sama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN