In [1]:
### run 1

import pandas as pd
import os
import numpy as np
import time
import math
import requests
import glob

pd.options.display.max_columns = 150
pd.options.mode.chained_assignment = None

selcen = pd.DataFrame()

folder = 'Settlement Project/Tokopedia/Seller Centre/'
for i in os.listdir(folder):
    print(i)
    if r'$' not in i:
        temp = pd.read_excel(folder + str(i), header = 3)
        if 'Order ID' not in temp.columns:
            for j in temp.index:
                if temp['Unnamed: 1'][j] == 'Order ID':
                    jenis = 'Order ID'
                    row_number = j
                    break;
                elif  temp['Unnamed: 1'][j] == 'Nomor Invoice':
                    jenis = 'Nomor Invoice'
                    row_number = j
                    break;
            if jenis == 'Order ID' :
                temp = pd.read_excel(folder + str(i), header = row_number + 1 + 3)
            elif jenis == 'Nomor Invoice':
                temp = pd.read_excel(folder + str(i), header = row_number + 1 + 3)
                # temp = temp.drop(['Tanggal Pesanan Selesai',
                #  'Waktu Pesanan Selesai',
                #  'Tanggal Pesanan Dibatalkan',
                #  'Waktu Pesanan Dibatalkan','Catatan penjual','Harga Satuan Bundling (IDR)', 'Harga Jual (IDR)','Nilai Voucher Toko Terpakai (IDR)',
                #  'Jenis Voucher Toko Terpakai',
                #  'Kode Voucher Toko yang digunakan','Kota',
                #  'Provinsi','Tanggal Pengiriman Barang',
                #  'Waktu Pengiriman Barang','Paket Bundling',
                #  'COD'], axis = 1)
                temp = temp.drop([x for x in ['Tanggal Pesanan Selesai',
                                                'Waktu Pesanan Selesai',
                                                'Tanggal Pesanan Dibatalkan',
                                                'Waktu Pesanan Dibatalkan','Catatan penjual','Catatan Produk Penjual','Harga Satuan Bundling (IDR)', 'Harga Jual (IDR)','Nilai Voucher Toko Terpakai (IDR)',
                                                'Jenis Voucher Toko Terpakai',
                                                'Kode Voucher Toko yang digunakan','Kode Voucher Toko Yang Digunakan','Kota',
                                                'Provinsi','Tanggal Pengiriman Barang',
                                                'Waktu Pengiriman Barang','Paket Bundling',
                                                'COD', 'Tipe Produk', 'Nama Bundling', 'Bebas Ongkir'] if x in temp.columns], axis = 1)
                # temp = temp.drop([x for x in ['Tanggal Pesanan Selesai','Waktu Pesanan Selesai','Tanggal Pesanan Dibatalkan',
                #                               'Waktu Pesanan Dibatalkan','Catatan penjual','Harga Satuan Bundling (IDR)', 'Harga Jual (IDR)','Nilai Voucher Toko Terpakai (IDR)',
                #                               'Jenis Voucher Toko Terpakai','Kode Voucher Toko yang digunakan','Kota',
                #                               'Provinsi','Tanggal Pengiriman Barang','Waktu Pengiriman Barang','Paket Bundling','COD'] if x in temp.columns], axis = 1)

                temp.columns = ['Count', 'Invoice', 'Payment Date', 'Order Status', 'Product Name', 'Stock Keeping Unit (SKU)', 'Notes', 'Quantity', 
                                'Price (Rp.)', 'Discount Amount (Rp.)', 'Subsidi Amount (Rp.)','Shipping Price + fee (Rp.)','Insurance (Rp.)','Total Shipping Fee (Rp.)','Total Amount (Rp.)',
                                'Customer Name', 'Customer Phone', 'Recipient', 'Recipient Number',
                                'Recipient Address', 'Courier', 'Jenis Layanan','AWB', 'Warehouse Origin','Campaign Name']
                for i in temp.columns :
                    temp[i] = temp[i].fillna(method = 'ffill')
                    
        if 'Price (Rp.)' not in temp.columns:
            if 'Harga Jual (Rp.)' in temp.columns:
                temp = temp.rename(columns = {'Harga Jual (Rp.)' : 'Price (Rp.)'})
            else :
                temp = temp.rename(columns = {'Harga Awal (Rp.)' : 'Price (Rp.)'})
        true_col = ['Count', 'Order ID', 'Invoice', 'Payment Date', 'Order Status',
                    'Product ID', 'Product Name', 'Quantity', 'Stock Keeping Unit (SKU)',
                    'Notes', 'Price (Rp.)', 'Discount Amount (Rp.)', 'Subsidi Amount (Rp.)',
                    'Customer Name', 'Customer Phone', 'Recipient', 'Recipient Number',
                    'Recipient Address', 'Courier', 'Shipping Price + fee (Rp.)',
                    'Insurance (Rp.)', 'Total Shipping Fee (Rp.)', 'Total Amount (Rp.)',
                    'AWB', 'Jenis Layanan', 'Bebas Ongkir', 'Warehouse Origin',
                    'Campaign Name']
        
        if temp.columns.to_list() == true_col :
            print('Column sama')
        else:
            print('Column beda')
            print([x for x in true_col if x not in temp.columns.to_list()])
            print([x for x in temp.columns.to_list() if x not in true_col])
        temp['Source'] = i
        if 'Invoice' in selcen.columns:
            temp=temp[~temp['Invoice'].isin(selcen['Invoice'].unique())]
        selcen = selcen.append(temp, ignore_index = True, sort = False)

Tokopedia_Order_20210101-20210131.xlsx
Column sama
Tokopedia_Order_20221226-20221231.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230101-20230105.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230106-20230110.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230111-20230115.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230116-20230120.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230121-20230125.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230126-20230130.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230131-20230131.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230201-20230205.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230206-20230210.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230211-20230215.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230216-20230220.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230221-20230223.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230224-20230228.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230301-20230305.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230306-20230310.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230311-20230315.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230316-20230320.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230321-20230323.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230324-20230326.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230327-20230328.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230329-20230331.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230401-20230405.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230406-20230410.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230411-20230415.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230416-20230420.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
Tokopedia_Order_20230421-20230423.xlsx
Column beda
['Order ID', 'Product ID', 'Bebas Ongkir']
[]
~$Tokopedia_Order_20210101-20210131.xlsx
~$Tokopedia_Order_20210601-20210627.xlsx
~$Tokopedia_Order_20211022-20211028.xlsx

In [ ]:
pd.read_excel("Settlement Project\Tokopedia\Seller Centre\Tokopedia_Order_20230324-20230328.xlsx")

# Process Seller Centre

In [2]:
## for backup
selcen_cp = selcen.copy()

In [35]:
### for backup
selcen = selcen_cp.copy()

In [3]:
## run 2
# Renaming Columns
print('== Renaming Columns ==')
selcen = selcen.rename(columns = {'Stock Keeping Unit (SKU)' : 'SKU', 'Quantity' : 'Qty. Invoiced'})
selcen = selcen.drop('Count', axis = 1)

# Formatting Date
print('== Formatting Date ==')
selcen['Date'] = np.nan
selcen['Month'] = np.nan
selcen['Year'] = np.nan

### tambahan timo April 23
selcen['true datetime']=np.nan

indeks = selcen[pd.to_datetime(selcen['Payment Date']).dt.strftime('%d').astype(int) <= 12].index.to_list()
selcen['Date'][indeks] = pd.to_datetime(pd.to_datetime(selcen['Payment Date'][indeks]).dt.strftime('%Y-%d-%m %H:%M')).dt.day
selcen['Month'][indeks] = pd.to_datetime(pd.to_datetime(selcen['Payment Date'][indeks]).dt.strftime('%Y-%d-%m %H:%M')).dt.month_name()
selcen['Year'][indeks] = pd.to_datetime(pd.to_datetime(selcen['Payment Date'][indeks]).dt.strftime('%Y-%d-%m %H:%M')).dt.year

### tambahan timo April 23
selcen['true datetime'][indeks] = pd.to_datetime(pd.to_datetime(selcen['Payment Date'][indeks]).dt.strftime('%Y-%d-%m %H:%M'))

non_indeks = selcen[~selcen.index.isin(indeks)].index.to_list()
selcen['Date'][non_indeks] = pd.to_datetime(selcen['Payment Date'][non_indeks]).dt.day
selcen['Month'][non_indeks] = pd.to_datetime(selcen['Payment Date'][non_indeks]).dt.month_name()
selcen['Year'][non_indeks] = pd.to_datetime(selcen['Payment Date'][non_indeks]).dt.year

### tambahan timo April 23
selcen['true datetime'][non_indeks] = pd.to_datetime(selcen['Payment Date'][non_indeks])

selcen = selcen[selcen['Year'] > 2022]

# Filling Product ID
print('== Filling Product ID ==')

prod_id = pd.read_excel(r"Settlement Project\Tokopedia\data base product ID.xlsx")
selcen['SKU'] = selcen['SKU'].astype(str)
prod_id['SKU'] = prod_id['SKU'].astype(str)
prod_id = prod_id.rename(columns = {'Nama Produk' : 'Product Name'})

selcen = selcen.merge(prod_id[['SKU', 'ID Produk', 'Product Name']].drop_duplicates(['SKU', 'Product Name']), how = 'left', on = ['SKU', 'Product Name'])

temp = prod_id[prod_id['Product Name'] == 'Free L-Men 2 Go - L-Men Gain Mass Chocolate 500g']
temp['Product Name'] = 'Free L-Men 2 Go - L-Men Gain Mass Chocolate 500gr'
prod_id = prod_id.append(temp, ignore_index = True, sort = False)

selcen_null = selcen[selcen['ID Produk'].isnull()]
selcen_null = selcen_null.drop('ID Produk', axis = 1)
selcen_null = selcen_null.merge(prod_id[['SKU', 'ID Produk']].drop_duplicates('SKU'), how = 'left', on = 'SKU').set_index(selcen_null.index)
selcen['ID Produk'][selcen_null.index] = selcen_null['ID Produk']

selcen_null = selcen[selcen['ID Produk'].isnull()]
selcen_null = selcen_null.drop('ID Produk', axis = 1)

selcen_null = selcen_null.merge(prod_id[['Product Name', 'ID Produk']].drop_duplicates('Product Name'), how = 'left', on = 'Product Name').set_index(selcen_null.index)
selcen['ID Produk'][selcen_null.index] = selcen_null['ID Produk']
selcen['Product ID'] = selcen['ID Produk']
selcen = selcen.drop('ID Produk', axis = 1)

# Distributing Value
print('== Distributing Value ==')

indeks = selcen[selcen['Shipping Price + fee (Rp.)'] != 'Non Tunai'].index.to_list()
if len(indeks) != 0:
    selcen['Shipping Price + fee (Rp.)'][indeks] = selcen['Shipping Price + fee (Rp.)'][indeks] * selcen['Price (Rp.)'][indeks]/selcen.iloc[indeks].groupby(['Invoice'])['Price (Rp.)'].transform('sum')

indeks = selcen[selcen['Total Shipping Fee (Rp.)'] != 'Non Tunai'].index.to_list()
if len(indeks) != 0:    
    selcen['Total Shipping Fee (Rp.)'][indeks] = selcen['Total Shipping Fee (Rp.)'][indeks] * selcen['Price (Rp.)'][indeks]/selcen.iloc[indeks].groupby(['Invoice'])['Price (Rp.)'].transform('sum')

selcen['Total Amount (Rp.)'] = selcen['Total Amount (Rp.)'] * selcen['Price (Rp.)']/selcen.groupby(['Invoice'])['Price (Rp.)'].transform('sum')

# Drop duplicates
print('== Drop duplicates ==')
selcen = selcen.drop_duplicates(['Order ID',
 'Invoice',
 'Payment Date',
 'Order Status',
 'Product ID',
 'Product Name',
 'Qty. Invoiced',
 'SKU',
 'Notes',
 'Customer Name',
 'Customer Phone',
 'Recipient',
 'Recipient Number',
 'Recipient Address',
 'Courier',
 'AWB', 'Jenis Layanan',
 'Bebas Ongkir',
 'Warehouse Origin',
 'Campaign Name',
 'Source']).reset_index(drop = True)

# Check with SKU NFI


print('== Check with SKU NFI ==')
temp2 = selcen.copy()

indeks = temp2[(temp2['Product Name'] == 'Free 2 Pcs L-Men 2 Go - L-Men Lose Weight Avocado Coffee 300gr') & (selcen['Year'] == 2022) & (selcen['Month'].isin(['January', 'February','March']))].index.to_list()
temp2['SKU'][indeks] = 'PL25B103(2)'
indeks = temp2[(temp2['Product Name'] == 'Buy 1 Get 1 FREE L-Men Lose Weight Mango Sticky Rice 300gr') & (selcen['Year'] == 2022) & (selcen['Month'].isin(['January', 'February','March']))].index.to_list()
temp2['SKU'][indeks] = '2304576112P2'
temp2.loc[temp2['SKU']=='2300551155PL1B102','SKU']='PL1B102'



data_SKU = pd.read_excel(r"D:\1. Masterdata\SKU_File\data_SKU.xlsx")

s = requests.Session()
s.get("https://tatanama.pythonanywhere.com")
s.post("https://tatanama.pythonanywhere.com", data = {'username' : 'ecommerce', 'password' : 'ecommerce'})
r = s.get("https://tatanama.pythonanywhere.com/download")

with open(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx", 'wb') as output:
    output.write(r.content)

if os.path.isfile(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx") :    
    SKU_append = pd.read_excel(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx")
    SKU_append.columns = [x.replace('_', ' ') for x in SKU_append.columns]
    data_SKU = data_SKU[~data_SKU['SKU'].astype(str).isin(SKU_append['SKU'].astype(str))]
    data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)

to_excel = data_SKU.to_excel(r"D:\1. Masterdata\SKU_File\data_SKU.xlsx", index = False)

# Check Null SKU
print('== Check Null SKU ==')
temp2[~temp2['SKU'].isin(data_SKU['SKU'])][['Invoice', 'Product Name', 'SKU']].drop_duplicates('SKU').values

== Renaming Columns ==
== Formatting Date ==
== Filling Product ID ==
== Distributing Value ==
== Drop duplicates ==
== Check with SKU NFI ==
== Check Null SKU ==

array([], shape=(0, 3), dtype=object)

In [4]:
## run 3
selcen=selcen[~selcen['Product Name'].isin(['Kartu Ucapan & Kemasan - Kirim sebagai Hadiah','Kartu Ucapan & Kemasan - Kemasan & Kartu Ucapan'])]

In [5]:
## run 3.1 

from datetime import datetime,timedelta
listjanjian=requests.get('http://event.l-men.com/apiv1?type=janjian')
for i in listjanjian.json():
    sku=i['realsku']
    print(sku)
    start=datetime.fromtimestamp(int(i['startdate']/1000)).replace(hour=0)
    end=datetime.fromtimestamp(int(i['enddate']/1000)).replace(hour=23)
    print(i['notes'])
    selcen.loc[(selcen['SKU']==sku)&(selcen['true datetime']>=start)&(selcen['true datetime']<end),'Pemilik Budget']=i['notes']
    print('=====')
    # print(str(datetime.fromtimestamp(int(i['enddate']/1000)).replace(hour=0)))

2T00803164
Launching tahap 2
=====
2T00803164P3
Launching tahap 2
=====
2T02703229P2
Launching
=====
PT25T74
Launching
=====
2T02703229
Launching tahap 2
=====
2104115110
Launching tahap 2
=====
2104115110P2
Launching tahap 2
=====
2104148024
Launching tahap 2
=====
2104148024P2
Launching tahap 2
=====
1N01402250P24
Marketing
=====
1N01402250P4
Marketing
=====
2104010270
Marketing
=====
1101909331
Marketing
=====
2T00803164P2
Marketing
=====
2T00803164P3
Marketing
=====
2HF0114021
Launching tahap 2
=====
2101751112
Marketing
=====
2101751112P2
Marketing
=====
2101700166P2
Marketing
=====
2101700166
Marketing
=====
2101384106
Internal
=====
2101384106P3
Internal
=====
2105055180P2
Internal
=====
2104523105P3
Internal
=====
2104508105P3
Internal
=====
2104543105P3
Internal
=====
2104589105P3
Internal
=====
2104241210P2
Internal
=====
2106386249P24
Internal
=====
2101000195
Internal
=====
2101151180
Internal
=====
2101150180
Internal
=====
2101200180
Internal
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102500125P2
Internal
=====
2102500130P2
Internal
=====
2102900125
Internal
=====
2102900130
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2309005305P20
Marketing
=====
2T01813126P2
Launching
=====
PH22T17
Marketing
=====
PH22T41
Marketing
=====
PH19H22
Launching
=====
PH22H95G277
Marketing
=====
1101685360
Marketing
=====
1101656360
Marketing
=====
2101847360
Marketing
=====
2101845360
Marketing
=====
2101819360
Marketing
=====
2101888360
Marketing
=====
PH19H103
Launching
=====
PH35H103
Launching
=====
2305551028
Launching
=====
2HF0113021
Launching tahap 2
=====
2HF0112021
Launching tahap 2
=====
1N01402250P4
Internal
=====
1N01402250P24
Internal
=====
2T00803164
Internal
=====
2T00803164P2
Internal
=====
2T00803164P3
Internal
=====
1101686318
Marketing
=====
1101694318
Marketing
=====
1N01402250P4
Marketing
=====
2T00803164
Marketing
=====
1N01402250P24
Marketing
=====
2T00803164P2
Marketing
=====
2T00803164P3
Marketing
=====
1101618318P2
Marketing
=====
1101618318
Marketing
=====
2309005305
Marketing
=====
2309005305P5
Marketing
=====
2309005305P10
Marketing
=====
2101700166
Marketing
=====
2101700166
Marketing
=====
2101700166P2
Marketing
=====
2101700166P2
Marketing
=====
2309005305P20
Marketing
=====
2309005305P20
Marketing
=====
(E)2101469180
Marketing
=====
1N01402250P4
Marketing
=====
1N01402250P24
Marketing
=====
2T01402249P4
Launching
=====
2T01402249P24
Launching
=====
1100534034
Launching
=====
2HC0109021
Launching tahap 2
=====
2305551028
Launching tahap 2
=====
PH19H22
Marketing
=====
PH22T41
Marketing
=====
PH22T17
Marketing
=====
(E)2101487148
Marketing
=====
(E)2101487148
Marketing
=====
2T01813126
Launching tahap 2
=====
2T01813126P2
Launching tahap 2
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102500125P2
Internal
=====
2102900125
Internal
=====
2102500130P2
Internal
=====
2102900130
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2101150180
Internal
=====
2101151180
Internal
=====
2101200180
Internal
=====
2101000195
Internal
=====
2101000195P2
Internal
=====
2101150180P2
Internal
=====
2101151180P2
Internal
=====
2101200180P2
Internal
=====
2304097159
Internal
=====
2104394210P2
Internal
=====
2104394210
Internal
=====
PT26T54
Internal
=====
2T01705164P2
Launching
=====
2305551028
Launching tahap 2
=====
PH22H95G277
Marketing
=====
1101665318
Marketing
=====
1101677318
Marketing
=====
1101653318
Marketing
=====
1101618318
Marketing
=====
2HH0813443P2
Launching
=====
2HF0114021P2
Marketing
=====
2LL1402249P4
Launching
=====
2LL1402249P24
Launching
=====
2LM0801029
Launching
=====
PL32L33
Launching
=====
2HF0114021
Marketing
=====
2101651195
Marketing
=====
2101651195P2
Marketing
=====
2101453195
Marketing
=====
2305551028
Internal
=====
2101453195P2
Marketing
=====
2101486195
Marketing
=====
2101486195P2
Marketing
=====
2309005305P20
Marketing
=====
(E)1101505453
Internal
=====
2304051180
Internal
=====
2LD0905181
Internal
=====
2304008180
Internal
=====
2TA0102180
Launching tahap 2
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102900125
Internal
=====
2102000180
Internal
=====
2102500125P2
Internal
=====
2102500130P2
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2102000180P2
Internal
=====
2102900130
Internal
=====
2304558112
Internal
=====
2304515112
Internal
=====
2304576112
Internal
=====
2304558112P2
Internal
=====
2304515112C2
Internal
=====
2304576112P2
Internal
=====
2304051180P2
Internal
=====
2LD0905181P2
Internal
=====
2304008180P2
Internal
=====

In [6]:
### run 4

print('== Merging with SKU Attributes ==')

temp2 = selcen.copy()

indeks = temp2[(temp2['Product Name'] == 'Free 2 Pcs L-Men 2 Go - L-Men Lose Weight Avocado Coffee 300gr') & (selcen['Year'] == 2022) & (selcen['Month'].isin(['January', 'February','March']))].index.to_list()
temp2['SKU'][indeks] = 'PL25B103(2)'
indeks = temp2[(temp2['Product Name'] == 'Buy 1 Get 1 FREE L-Men Lose Weight Mango Sticky Rice 300gr') & (selcen['Year'] == 2022) & (selcen['Month'].isin(['January', 'February','March']))].index.to_list()
temp2['SKU'][indeks] = '2304576112P2'
temp2.loc[temp2['SKU']=='2300551155PL1B102','SKU']='PL1B102'

data_SKU.loc[data_SKU['Price List NFI'].isin(['-']), 'Price List NFI'] = 0
data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')
# data_SKU['Price List NFI']=data_SKU['Price List NFI']/1.11
data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)#.str.replace('(S)', '', regex = False)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)
list_col = ['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand']

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)
for i in list_col:
    temp2[i] = temp_merge[str(i)]

list_col = ['SKU'] + data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Organik 7')+1].to_list()
temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU').set_index(temp2.index)
list_pcs = [x for x in temp_merge.columns if 'PCS' in x]
for i in list_pcs:
    temp_merge[i] = temp_merge[i] * temp_merge['Qty. Invoiced']

list_col = data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Organik 7')+1].to_list()    
for i in list_col:
    temp2[i] = temp_merge[str(i)]
    
print('== Unbundling ==')
data_bundle1 = temp2[~temp2['Produk 1'].isnull()]
data_bundle1['Bundle Name'] = data_bundle1['Product Name']
data_bundle1['Product Name'] = data_bundle1['Produk 1']
data_bundle1['SKU'] = data_bundle1['SKU Produk 1']
data_bundle1['Qty. Invoiced'] = data_bundle1['PCS Produk 1']
data_bundle1['Price List NFI'] = data_bundle1['Price List NFI 1']
data_bundle1['Total Net'] = data_bundle1['Price List NFI 1']
data_bundle1['Bundle Flag'] = np.nan

data_bundle2 = temp2[~temp2['Produk 2'].isnull()]
data_bundle2['Bundle Name'] = data_bundle2['Product Name']
data_bundle2['Product Name'] = data_bundle2['Produk 2']
data_bundle2['SKU'] = data_bundle2['SKU Produk 2']
data_bundle2['Qty. Invoiced'] = data_bundle2['PCS Produk 2']
data_bundle2['Price List NFI'] = data_bundle2['Price List NFI 2']
data_bundle2['Total Net'] = data_bundle2['Price List NFI 2'] 
data_bundle2['Bundle Flag'] = np.nan

data_bundle3 = temp2[~temp2['Produk 3'].isnull()]
data_bundle3['Bundle Name'] = data_bundle3['Product Name']
data_bundle3['Product Name'] = data_bundle3['Produk 3']
data_bundle3['SKU'] = data_bundle3['SKU Produk 3']
data_bundle3['Qty. Invoiced'] = data_bundle3['PCS Produk 3']
data_bundle3['Price List NFI'] = data_bundle3['Price List NFI 3']
data_bundle3['Total Net'] = data_bundle3['Price List NFI 3'] 
data_bundle3['Bundle Flag'] = np.nan

data_bundle4 = temp2[~temp2['Produk 4'].isnull()]
data_bundle4['Bundle Name'] = data_bundle4['Product Name']
data_bundle4['Product Name'] = data_bundle4['Produk 4']
data_bundle4['SKU'] = data_bundle4['SKU Produk 4']
data_bundle4['Qty. Invoiced'] = data_bundle4['PCS Produk 4']
data_bundle4['Price List NFI'] = data_bundle4['Price List NFI 4']
data_bundle4['Total Net'] = data_bundle4['Price List NFI 4'] 
data_bundle4['Bundle Flag'] = np.nan

data_bundle5 = temp2[~temp2['Produk 5'].isnull()]
data_bundle5['Bundle Name'] = data_bundle5['Product Name']
data_bundle5['Product Name'] = data_bundle5['Produk 5']
data_bundle5['SKU'] = data_bundle5['SKU Produk 5']
data_bundle5['Qty. Invoiced'] = data_bundle5['PCS Produk 5']
data_bundle5['Price List NFI'] = data_bundle5['Price List NFI 5']
data_bundle5['Total Net'] = data_bundle5['Price List NFI 5']
data_bundle5['Bundle Flag'] = np.nan

data_bundle6 = temp2[~temp2['Produk 6'].isnull()]
data_bundle6['Bundle Name'] = data_bundle6['Product Name']
data_bundle6['Product Name'] = data_bundle6['Produk 6']
data_bundle6['SKU'] = data_bundle6['SKU Produk 6']
data_bundle6['Qty. Invoiced'] = data_bundle6['PCS Produk 6']
data_bundle6['Price List NFI'] = data_bundle6['Price List NFI 6']
data_bundle6['Total Net'] = data_bundle6['Price List NFI 6']
data_bundle6['Bundle Flag'] = np.nan

data_bundle7 = temp2[~temp2['Produk 7'].isnull()]
data_bundle7['Bundle Name'] = data_bundle7['Product Name']
data_bundle7['Product Name'] = data_bundle7['Produk 7']
data_bundle7['SKU'] = data_bundle7['SKU Produk 7']
data_bundle7['Qty. Invoiced'] = data_bundle7['PCS Produk 7']
data_bundle7['Price List NFI'] = data_bundle7['Price List NFI 7']
data_bundle7['Total Net'] = data_bundle7['Price List NFI 7']
data_bundle7['Bundle Flag'] = np.nan

data_bundle = data_bundle1.append([data_bundle2, data_bundle3, data_bundle4, data_bundle5, data_bundle6, data_bundle7], ignore_index = True, sort = False)
data_bundle['SKU'] = data_bundle['SKU'].astype(str)
data_bundle['SKU'] = data_bundle['SKU'].str.replace('\.0$', '', regex = True)
data_bundle[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']] = data_bundle.merge(data_SKU[['Real SKU', 'Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU')[['Real SKU_y', 'Nama Produk', 'Brand_y', 'Sub Brand_y', 'Parent Item', 'Parent SKU']]

print("== Pricing ==")
temp2 = temp2.append(data_bundle, ignore_index = True, sort = False)
list_col = ['Real SKU', 'Price List NFI', 'Harga Cost']

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)
for i in list_col:
    if i == 'Real SKU' or i == 'Price List NFI':
        temp2[i] = temp_merge[str(i) + '_y']
    else :
        temp2[i] = temp_merge[str(i)]
    
temp2['Price List NFI'] = pd.to_numeric(temp2['Price List NFI']).astype(int)
temp2['Harga Cost'] = pd.to_numeric(temp2['Harga Cost']).astype(int)
temp2['Qty. Invoiced'] = pd.to_numeric(temp2['Qty. Invoiced']).astype(int)

temp2['Total Net'] = temp2['Price List NFI'] * temp2['Qty. Invoiced']
temp2['Total Harga Cost'] = temp2['Harga Cost'] * temp2['Qty. Invoiced']

selcen_sku = temp2.copy()

# Merging with J Converter
print('== Merging with J Converter ==')
j_conv = pd.read_excel("Settlement Project\Rumus Realisasi.xlsx", sheet_name = 'Paket Brand')
j_conv = j_conv.iloc[:,:5]
j_conv = j_conv.rename(columns = {'SKU' : 'Real SKU', 'SKU.1' : 'SKU Produk'})
j_conv = j_conv[j_conv['Real SKU'].notnull()]
j_conv['SKU Produk'] = j_conv['SKU Produk'].astype(str).str.replace('.0', '',regex = False)

temp_all = selcen_sku.copy()

temp_all['Real SKU'] = temp_all['Real SKU'].astype(str)
j_conv['Real SKU'] = j_conv['Real SKU'].astype(str)

temp_all = temp_all.merge(j_conv, how = 'left', on = 'Real SKU')

paket_j = temp_all[temp_all['SKU Produk'].notnull()]

paket_j['Bundle Name'] = paket_j['Product Name']
paket_j['Product Name'] = paket_j['Name']
paket_j['SKU'] = paket_j['SKU Produk']
paket_j['Qty. Invoiced'] = paket_j['Qty. Invoiced'] * paket_j['Konversi ke UOM'].astype(float)
paket_j['Bundle Flag'] = np.nan
    
data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)
if 'Real SKU_y' in paket_j.columns:
    paket_j = paket_j.drop('Real SKU_y', axis = 1)
paket_j['SKU'] = paket_j['SKU'].astype(str)
paket_j[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU', 'Price List NFI']] = paket_j.merge(data_SKU[['Real SKU', 'Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU', 'Price List NFI']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(paket_j.index)[['Real SKU_y', 'Nama Produk', 'Brand_y', 'Sub Brand_y', 'Parent Item_y', 'Parent SKU_y', 'Price List NFI_y']]

paket_j['Total Net'] = paket_j['Price List NFI'] * paket_j['Qty. Invoiced']

paket_j['Price (Rp.)'] = paket_j['Price (Rp.)'] * paket_j['Total Net']/paket_j.groupby(['Invoice', 'Bundle Name'])['Total Net'].transform('sum')
paket_j['Discount Amount (Rp.)'] = paket_j['Discount Amount (Rp.)'] * paket_j['Total Net']/paket_j.groupby(['Invoice', 'Bundle Name'])['Total Net'].transform('sum')

indeks = paket_j[paket_j['Shipping Price + fee (Rp.)'] != 'Non Tunai'].index.to_list()
if len(indeks) != 0:
    paket_j['Shipping Price + fee (Rp.)'][indeks] = paket_j['Shipping Price + fee (Rp.)'][indeks] * paket_j['Total Net'][indeks]/paket_j.iloc[indeks].groupby(['Invoice', 'Bundle Name'])['Total Net'].transform('sum')

indeks = paket_j[paket_j['Insurance (Rp.)'] != 'Non Tunai'].index.to_list()
if len(indeks) != 0:
    paket_j['Insurance (Rp.)'][indeks] = paket_j['Insurance (Rp.)'][indeks] * paket_j['Total Net'][indeks]/paket_j.iloc[indeks].groupby(['Invoice', 'Bundle Name'])['Total Net'].transform('sum')


indeks = paket_j[paket_j['Total Shipping Fee (Rp.)'] != 'Non Tunai'].index.to_list()
if len(indeks) != 0:
    paket_j['Total Shipping Fee (Rp.)'][indeks]  = paket_j['Total Shipping Fee (Rp.)'][indeks]  * paket_j['Total Net'][indeks] /paket_j.iloc[indeks].groupby(['Invoice', 'Bundle Name'])['Total Net'].transform('sum')

paket_j['Total Amount (Rp.)'] = paket_j['Total Amount (Rp.)'] * paket_j['Total Net']/paket_j.groupby(['Invoice', 'Bundle Name'])['Total Net'].transform('sum')

paket_j = paket_j.drop(['Nama Paket', 'SKU Produk', 'Name', 'Konversi ke UOM'], axis = 1)
selcen_sku = selcen_sku.append(paket_j, ignore_index = True, sort = False)
indeks = selcen_sku[selcen_sku['Product Name'].isin(paket_j['Bundle Name'])].index.to_list()
selcen_sku['Brand'][indeks] = 'Bundle'

indeks = selcen_sku[(selcen_sku['Real SKU'].astype(str).str.contains('^\(B\)', regex = True)) &
      (~selcen_sku['Brand'].isin(['Bonus Produk', 'Gimmick']))].index.to_list()

selcen_sku['Brand'][indeks] = 'Bonus Produk'

indeks = selcen_sku[(selcen_sku['Real SKU'].astype(str).str.contains('^\(U\)', regex = True)) &
      (~selcen_sku['Brand'].isin(['Bonus Produk', 'Gimmick']))].index.to_list()

selcen_sku['Brand'][indeks] = 'Bonus Produk'

# Selcen Done
print('== Selcen Done ==')

== Merging with SKU Attributes ==
== Unbundling ==
== Pricing ==
== Merging with J Converter ==
== Selcen Done ==

In [7]:
### checking must null
temp2[temp2['Price List NFI'].isnull()]

Empty DataFrame
Columns: [Order ID, Invoice, Payment Date, Order Status, Product ID, Product Name, Qty. Invoiced, SKU, Notes, Price (Rp.), Discount Amount (Rp.), Subsidi Amount (Rp.), Customer Name, Customer Phone, Recipient, Recipient Number, Recipient Address, Courier, Shipping Price + fee (Rp.), Insurance (Rp.), Total Shipping Fee (Rp.), Total Amount (Rp.), AWB, Jenis Layanan, Bebas Ongkir, Warehouse Origin, Campaign Name, Source, Date, Month, Year, true datetime, Pemilik Budget, Real SKU, Real Nama Produk, Brand, Sub Brand, Produk 1, SKU Produk 1, PCS Produk 1, Price List NFI 1, Subtotal Produk 1, Harga Display 1, Harga Cost 1, Harga Organik 1, Produk 2, SKU Produk 2, PCS Produk 2, Price List NFI 2, Subtotal Produk 2, Harga Display 2, Harga Cost 2, Harga Organik 2, Produk 3, SKU Produk 3, PCS Produk 3, Price List NFI 3, Subtotal Produk 3, Harga Display 3, Harga Cost 3, Harga Organik 3, Produk 4, SKU Produk 4, PCS Produk 4, Price List NFI 4, Subtotal Produk 4, Harga Display 4, Harga Cost 4, Harga Organik 4, Produk 5, SKU Produk 5, PCS Produk 5, Price List NFI 5, Subtotal Produk 5, Harga Display 5, Harga Cost 5, Harga Organik 5, Produk 6, SKU Produk 6, PCS Produk 6, Price List NFI 6, Subtotal Produk 6, Harga Display 6, Harga Cost 6, Harga Organik 6, Produk 7, SKU Produk 7, PCS Produk 7, Price List NFI 7, Subtotal Produk 7, Harga Display 7, Harga Cost 7, Harga Organik 7, Bundle Name, Price List NFI, Total Net, Bundle Flag, Parent Item, Parent SKU, Harga Cost, ...]
Index: []

# Old NFI

In [8]:
## run 5

# Confirming January 2022 PL NFI Not Changed with Old Realisation
print('== Confirming January 2022 PL NFI Not Changed with Old Realisation ==')
source = pd.read_csv(r"Settlement Project\Backup\Realisasi Jan 2022\Runningan Tokped Jan 2021 - Jan 2022 Real Rev 1.csv", sep = ';')

source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021) & (source['True datetime']<'2022-02-01')]
selcen_old = selcen_sku[selcen_sku['Invoice'].isin(source['Order #'])]
source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])
selcen_old_merge = selcen_old.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Price List NFI', 'Qty. Invoiced']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['Invoice', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']) 

selcen_old_null = selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()]
selcen_old_null = selcen_old_null.drop(['Order #', 'Price List NFI_y'], axis = 1)
selcen_old_null = selcen_old_null.rename(columns = {'Price List NFI_x' : 'Price List NFI'})
selcen_old_null = selcen_old_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Price List NFI']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name', 'Price List NFI']), how = 'left', left_on = ['Invoice', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(selcen_old_null.index) 
selcen_old_merge['Price List NFI_y'][selcen_old_null.index] = selcen_old_null['Price List NFI_y']

selcen_old_null = selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()]

source2 = source.copy()
source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')
indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
source2['Real SKU'][indeks] = '(U)2101809250'

selcen_old_null = selcen_old_null.drop(['Order #', 'Price List NFI_y'], axis = 1)
selcen_old_null = selcen_old_null.rename(columns = {'Price List NFI_x' : 'Price List NFI'})
selcen_old_null = selcen_old_null.merge(source2[['Order #', 'Real SKU', 'Bundle Name', 'Price List NFI']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(selcen_old_null.index) 
selcen_old_merge['Price List NFI_y'][selcen_old_null.index] = selcen_old_null['Price List NFI_y']

# Check
print('== Check ==')
selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()][['Invoice','Product Name','Real Nama Produk', 'Real SKU','Bundle Name', 'Price List NFI_x', 'Price List NFI_y','Qty. Invoiced']].drop_duplicates('Real SKU')

== Confirming January 2022 PL NFI Not Changed with Old Realisation ==

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (11,13,14,19,22,23) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

== Check ==

Empty DataFrame
Columns: [Invoice, Product Name, Real Nama Produk, Real SKU, Bundle Name, Price List NFI_x, Price List NFI_y, Qty. Invoiced]
Index: []

In [9]:
## run 6

# Continue if Blank
print('== Continue if Blank ==')
selcen_old_merge = selcen_old_merge.drop(['Price List NFI_x', 'Order #'], axis = 1)
selcen_old_merge = selcen_old_merge.rename(columns = {'Price List NFI_y' : 'Price List NFI'})

selcen_old_merge['Price List NFI'] = pd.to_numeric(selcen_old_merge['Price List NFI']).astype(float)
selcen_old_merge['Qty. Invoiced'] = pd.to_numeric(selcen_old_merge['Qty. Invoiced']).astype(float)

selcen_old_merge['Total Net'] = selcen_old_merge['Price List NFI'] * selcen_old_merge['Qty. Invoiced']

selcen_sku = selcen_sku[~selcen_sku['Invoice'].isin(selcen_old_merge['Invoice'])]
selcen_sku = selcen_sku.append(selcen_old_merge, ignore_index = True, sort = False)

selcen_sku['Total Net Before PPN'] = selcen_sku['Total Net']/1.11

== Continue if Blank ==

# Fulfillment

In [10]:
## run 7

# Read Fulfilment MP Data
print('== Read Fulfilment MP Data ==')

wms_tokped = pd.DataFrame()
wms_tokped2 = pd.DataFrame()
wms_tokped3 = pd.DataFrame()

folder = 'Settlement Project/Tokopedia/WMS Titip Aja/'
for i in os.listdir(folder):
    print(i)
    if r'$' not in i and '$' not in i:
        if 'new' not in i and 'Nutrimart' not in i and 'Swift' not in i:
            temp = pd.read_excel(folder + str(i))
            temp['Source'] = i
            temp = temp.drop_duplicates()
            wms_tokped = wms_tokped.append(temp, ignore_index = True, sort = False)
            true_col = ['WAREHOUSE ID', 'CUSTOMER NAME', 'CUSTOMER ID', 'ORDER TIME', 'PAYMENT TIME', 'TTLAMOUNT', 'ORDER NO', 'ORDER TYPE NAME', 'SO LINE NO', 'SO STATUS', 
                        'CLOSED TIME', 'CONSIGNEE ID', 'CONSIGNEE NAME', 'CONSIGNEE ADRESS', 'CONSIGNEE PHONE', 'SKU', 'SKU DESCRIPTION', 'SOREFERENCE1', 'SOREFERENCE2', 
                        'SOREFERENCE5', 'LOCATION', 'PACK UOM', 'PACK ID', 'QTY ORDERED', 'QTY SHIPPED', 'CUBIC', 'GROSS WEIGHT', 'WAREHOUSING DATE', 'INVENTORY TYPE', 
                        'SERVICETYP', 'COMMODITY STATUS', 'COURIER', 'SALESMAN CODE', 'Source']
            print('Tokped 1')
            if temp.columns.to_list() == true_col :
                print('Column sama')
            else:
                print('Column beda')
                print([x for x in true_col if x not in temp.columns.to_list()])
                print([x for x in temp.columns.to_list() if x not in true_col])
        elif 'new' in i:
            temp = pd.read_excel(folder + str(i), sheet_name = 'Query result')
            temp['Source'] = i
            temp = temp.drop_duplicates()
            wms_tokped2 = wms_tokped2.append(temp, ignore_index = True, sort = False)
            print('Tokped 2')
        elif 'Nutrimart' in i or 'Swift' in i:
            temp = pd.read_excel(folder + str(i))
            temp['Source'] = i
            temp = temp.drop_duplicates()
            temp.columns = [str(x).replace('_',' ').title().replace('Sku','SKU').replace('Wms','WMS') for x in temp.columns]
            for j in temp.columns:
                temp[j] = temp[j].replace("'", "", regex = False)
            temp = temp.drop_duplicates()
            print('Tokped 3')
            true_col = ['Tenant', 'Provider Awb Last Mile', 'Last Mile 3Pl', 'Sales Order', 'WMS Order Status', 'Channel', 'Reason', 'Product Id', 'Title', 'Item SKU', 
                        'Customer Name', 'Phone Number', 'Address', 'Payment', 'Pick Up Date', 'Order Date', 'Picking Date', 'Packing Date', 'Waitingintransit Date', 
                        'Bookingcargo Date', 'Stidest Date', 'Delivered Date', 'Last Update', 'Packaging', 'Tot Item', 'Source']
            if temp.columns.to_list() == true_col :
                print('Column sama')
            else:
                print('Column beda')
                print([x for x in true_col if x not in temp.columns.to_list()])
                print([x for x in temp.columns.to_list() if x not in true_col])
            wms_tokped3 = wms_tokped3.append(temp, ignore_index = True, sort = False)

== Read Fulfilment MP Data ==
Outbound Report Jkt_202204.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report Jkt_202205.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'SOREFERENCE3', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report Jkt_202206.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PICK TIME', 'PICKER', 'SOREFERENCE3', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo', 'Consignee ZIP']
Outbound Report Jkt_202207.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'SOREFERENCE3', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report Jkt_202208.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PICK TIME', 'PICKER', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo', 'Consignee ZIP']
Outbound Report Jkt_202209.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'PICK TIME', 'PICKER', 'PACKED TIME', 'PACKER', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'Consignee ZIP']
Outbound Report Jkt_202210.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound Report Jkt_202211.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound Report Jkt_202212.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound Report Jkt_202301.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound Report Jkt_202302.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound Report Jkt_202303.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound Report Jkt_202304.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound Report _202203.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report_202101 (start 20 Jan).xlsx
Tokped 1
Column sama
Outbound Report_202102.xlsx
Tokped 1
Column sama
Outbound Report_202103.xlsx
Tokped 1
Column beda
[]
['PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3']
Outbound Report_202104.xlsx
Tokped 1
Column beda
[]
['PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3']
Outbound Report_202105.xlsx
Tokped 1
Column beda
[]
['PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound Report_202106.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'WAREHOUSING DATE']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound Report_202107.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'WAREHOUSING DATE']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound Report_202108.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'WAREHOUSING DATE']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound Report_202109.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound Report_202110.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound Report_202111.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound Report_202112.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report_202201.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report_202202 1-24 Feb.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report_202202.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound Report_202203.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound TC Swift SBY 202106.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202107.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202108.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202109.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202110.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202111.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202112.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202201.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202202 1-24 Feb.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202202.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202203.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202204.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202205.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202206.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202207.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202208.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202209.xlsx
Tokped 3
Column sama
Outbound TC Swift SBY 202210.xlsx
Tokped 3
Column sama
Outbound+Report Bdg_202203.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Bdg_202204.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Bdg_202205.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'SOREFERENCE3', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Bdg_202206.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PICK TIME', 'PICKER', 'SOREFERENCE3', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo', 'Consignee ZIP']
Outbound+Report Bdg_202207.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'SOREFERENCE3', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Bdg_202208.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PICK TIME', 'PICKER', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo', 'Consignee ZIP']
Outbound+Report Bdg_202209.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'QTY PICKED']
Outbound+Report Bdg_202210.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'PICK TIME', 'PICKER', 'PACKED TIME', 'PACKER', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'Consignee ZIP', 'TS Location']
Outbound+Report Bdg_202211.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Bdg_202212.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Bdg_202301.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Bdg_202302.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Bdg_202303.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Bdg_202304.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Medan_202203.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Medan_202204.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Medan_202205.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'SOREFERENCE3', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Medan_202206.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PICK TIME', 'PICKER', 'SOREFERENCE3', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo', 'Consignee ZIP']
Outbound+Report Medan_202207.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'SOREFERENCE3', 'PRIORITY', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report Medan_202208.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PICK TIME', 'PICKER', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'REGION CODE', 'Exp Date', 'BatchNo', 'Consignee ZIP']
Outbound+Report Medan_202209.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'Exp Date', 'BatchNo', 'QTY PICKED']
Outbound+Report Medan_202210.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Medan_202211.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Medan_202212.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Medan_202301.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Medan_202302.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Medan_202303.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report Medan_202304.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'SALESMAN CODE']
['WAVE NO', 'QTY PICKED', 'LINE STATUS', 'SOREFERENCE3', 'BOE', 'RPU FLAG', 'ADD TIME', 'Exp Date', 'BatchNo', 'TS Location']
Outbound+Report_202106.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'WAREHOUSING DATE']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound+Report_202109.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound+Report_202110.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound+Report_202111.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound+Report_202112.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report_202201.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report_202202 1-24 Feb.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report_202202.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report_202203(1).xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report_202203.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT']
['WAVE NO', 'LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE', 'Exp Date', 'BatchNo']
Outbound+Report_TA Medan_202108.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'WAREHOUSING DATE']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
Outbound+Report_TC Medan_202107.xlsx
Tokped 1
Column beda
['CUBIC', 'GROSS WEIGHT', 'WAREHOUSING DATE']
['LINE STATUS', 'PRIORITY', 'BOE', 'RPU FLAG', 'SOREFERENCE3', 'REGION CODE']
~$Outbound new 1 Juni - 31 Juli 2021.xlsx
~$Outbound Report_202106 sd 29 Jun.xlsx

In [11]:
## for backup

wms_tokped_cp = wms_tokped.copy()
wms_tokped2_cp = wms_tokped2.copy()
wms_tokped3_cp = wms_tokped3.copy()

In [44]:
## for backup

wms_tokped = wms_tokped_cp.copy()
wms_tokped2 = wms_tokped2_cp.copy()
wms_tokped3 = wms_tokped3_cp.copy()

In [12]:
### run 8
# Process Fulfilment Data
print('== Process Fulfilment Data ==')

wms_tokped = wms_tokped.groupby(['WAREHOUSE ID', 'SOREFERENCE2', 'SO STATUS', 'SKU', 'Source'])['QTY SHIPPED'].sum().reset_index()
wms_short = wms_tokped[['WAREHOUSE ID', 'SOREFERENCE2', 'SO STATUS', 'SKU', 'QTY SHIPPED']]
if len(wms_tokped2) != 0:
    wms_tokped2['Ftd Reason'] = wms_tokped2['Ftd Reason'].astype(str).str.extract(r'(INV\S+)')
    wms_tokped2 = wms_tokped2.rename(columns = {'Tenant Name' : 'WAREHOUSE ID', 'Ftd Reason' : 'SOREFERENCE2', 'Status':'SO STATUS', 'Sku Variant' : 'SKU', 'Num Item' : 'QTY SHIPPED'})
    wms_short2 = wms_tokped2[['WAREHOUSE ID', 'SOREFERENCE2', 'SO STATUS', 'SKU', 'QTY SHIPPED']]

wms_tokped3['Reason'] = wms_tokped3['Reason'].astype(str).str.extract(r'(INV\S+)')
wms_tokped3 = wms_tokped3.rename(columns = {'Tenant' : 'WAREHOUSE ID', 'Reason' : 'SOREFERENCE2', 'WMS Order Status':'SO STATUS', 'Item SKU' : 'SKU', 'Tot Item' : 'QTY SHIPPED'})
wms_short3 = wms_tokped3[['WAREHOUSE ID', 'SOREFERENCE2', 'SO STATUS', 'SKU', 'QTY SHIPPED']]

if len(wms_tokped2) != 0:
    wms_short = wms_short.append(wms_short2, ignore_index = True, sort = False).append(wms_short3, ignore_index = True, sort = False)
else :
    wms_short = wms_short.append(wms_short3, ignore_index = True, sort = False)

wms_short = wms_short.rename(columns = {'WAREHOUSE ID' : 'WH', 'QTY SHIPPED' : 'Warehouse Quantity', 'SKU' : 'SKU WH'})
wms_short = wms_short.drop_duplicates(['WH', 'SOREFERENCE2', 'SO STATUS', 'SKU WH'])

wms_tokped = wms_tokped.append(wms_tokped2, ignore_index = True, sort = False).append(wms_tokped3, ignore_index = True, sort = False)
wms_tokped = wms_tokped.rename(columns = {'WAREHOUSE ID' : 'WH', 'QTY SHIPPED' : 'Warehouse Quantity', 'SKU' : 'SKU WH'})

wms_short_ori = wms_short.copy()
wms_short['SKU WH'] = wms_short['SKU WH'].astype(str).str.replace('.0', '', regex = False)

# Unbundling Fulfilment Data
print('== Unbundling Fulfilment Data ==')

selcen_sku['Product ID'] = selcen_sku['Product ID'].astype(str).str.replace('.0', '', regex = False)
#########disini ada merge
wms_short = wms_short.merge(selcen_sku[selcen_sku['Bundle Name'].isnull()].groupby(['Invoice', 'Product ID'])['Real SKU'].first().reset_index(), how = 'left', left_on = ['SOREFERENCE2', 'SKU WH'], right_on = ['Invoice', 'Product ID'])

list_col = ['SKU'] + data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Organik 7')+1].to_list()

data_SKU['SKU'] = data_SKU['SKU'].astype(str)
#########disini ada merge
wms_short = wms_short.merge(data_SKU[list_col].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU')
list_pcs = [x for x in wms_short.columns if 'PCS' in x]
for i in list_pcs:
    wms_short[i] = wms_short[i] * wms_short['Warehouse Quantity']

print("Unbundling")
data_bundle1 = wms_short[~wms_short['Produk 1'].isnull()]
data_bundle1['Real SKU'] = data_bundle1['SKU Produk 1']
data_bundle1['Warehouse Quantity'] = data_bundle1['PCS Produk 1']

data_bundle2 = wms_short[~wms_short['Produk 2'].isnull()]
data_bundle2['Real SKU'] = data_bundle2['SKU Produk 2']
data_bundle2['Warehouse Quantity'] = data_bundle2['PCS Produk 2']

data_bundle3 = wms_short[~wms_short['Produk 3'].isnull()]
data_bundle3['Real SKU'] = data_bundle3['SKU Produk 3']
data_bundle3['Warehouse Quantity'] = data_bundle3['PCS Produk 3']

data_bundle4 = wms_short[~wms_short['Produk 4'].isnull()]
data_bundle4['Real SKU'] = data_bundle4['SKU Produk 4']
data_bundle4['Warehouse Quantity'] = data_bundle4['PCS Produk 4']

data_bundle5 = wms_short[~wms_short['Produk 5'].isnull()]
data_bundle5['Real SKU'] = data_bundle5['SKU Produk 5']
data_bundle5['Warehouse Quantity'] = data_bundle5['PCS Produk 5']

data_bundle6 = wms_short[~wms_short['Produk 6'].isnull()]
data_bundle6['Real SKU'] = data_bundle6['SKU Produk 6']
data_bundle6['Warehouse Quantity'] = data_bundle6['PCS Produk 6']

data_bundle7 = wms_short[~wms_short['Produk 7'].isnull()]
data_bundle7['Real SKU'] = data_bundle7['SKU Produk 7']
data_bundle7['Warehouse Quantity'] = data_bundle7['PCS Produk 7']

data_bundle = data_bundle1.append([data_bundle2, data_bundle3, data_bundle4, data_bundle5, data_bundle6, data_bundle7], ignore_index = True, sort = False)




# Merging with Fulfilment Data
print('== Merging with Fulfilment Data ==')

wms_short = wms_short_ori.copy()
for_wms = selcen_sku.copy()

for_wms['Invoice'] = for_wms['Invoice'].astype(str)
wms_short['SOREFERENCE2'] = wms_short['SOREFERENCE2'].astype(str)

for_wms['Product ID'] = for_wms['Product ID'].astype(str).str.replace('.0', '', regex = False)
wms_short['SKU WH'] = wms_short['SKU WH'].astype(str).str.replace('.0', '', regex = False)

#########disini ada merge
for_wms = for_wms.merge(wms_short.drop_duplicates(['SOREFERENCE2', 'SKU WH']), how = 'left', left_on = ['Invoice', 'Product ID'], right_on = ['SOREFERENCE2', 'SKU WH'])

for_wms_unbundle = for_wms[for_wms['Bundle Name'].notnull()]

for_wms_unbundle['SKU WH'] = for_wms_unbundle['SKU WH'].astype(str)
data_bundle['SKU WH'] = data_bundle['SKU WH'].astype(str)
for_wms_unbundle = for_wms_unbundle.merge(data_bundle[['Invoice', 'Real SKU', 'WH','SKU WH', 'SO STATUS', 'Warehouse Quantity']].drop_duplicates(['Invoice', 'Real SKU', 'SKU WH']), how = 'left', on = ['Invoice', 'Real SKU', 'SKU WH']).set_index(for_wms_unbundle.index)

for_wms['SO STATUS'][for_wms_unbundle.index] = for_wms_unbundle['SO STATUS_y']
for_wms['WH'][for_wms_unbundle.index] = for_wms_unbundle['WH_y']
for_wms['Warehouse Quantity'][for_wms_unbundle.index] = for_wms_unbundle['Warehouse Quantity_y']

# Checking if No Unmerged Data
print('== Checking if No Unmerged Data ==')
for_wms[(for_wms['Invoice'].isin(wms_short['SOREFERENCE2'])) & 
        (for_wms['SO STATUS'].isnull())].groupby(['Product Name','Real SKU', 'Bundle Name', 'Real Nama Produk', 'SKU WH'], dropna = False)['Invoice'].first().reset_index()

== Process Fulfilment Data ==
== Unbundling Fulfilment Data ==
Unbundling
== Merging with Fulfilment Data ==
== Checking if No Unmerged Data ==

,Product Name,Real SKU,Bundle Name,Real Nama Produk,SKU WH,Invoice
0,(Near ED) HiLo Active Caramel Latte 500g,(E)2101478180,Buy 1 Get 1 FREE HiLo Active Caramel Latte 500...,(Near ED) HiLo Active Caramel Latte 500g,NaN,INV/20230117/MPL/2982681376
1,(PBI) HiLo School RTD Cotton Candy 200ml,(B)2HF1403250,Kartu Ucapan - Bisa Dikirim sebagai Hadiah,(PBI) HiLo School RTD Cotton Candy 200ml,NaN,INV/20230404/MPL/3154014143
2,Buy 1 Get 1 FREE HiLo Active Caramel Latte 500...,(E)2101478180P2,NaN,HiLo Active Caramel Latte 500g Near ED x 2 pcs,NaN,INV/20230117/MPL/2982681376
3,HiLo Active Chocolate 750gr,2101452190,Twin Pack: HiLo Active Chocolate 750gr - Susu ...,HiLo Active Chocolate 750gr,NaN,INV/20230104/MPL/2950574705
4,HiLo School 3+ Soya Vanilla Malt 400g,2HF0112021,Twin Pack: HiLo School 3+ Soya Multigrain Vani...,HiLo School 3+ Soya Vanilla Malt 400g,NaN,INV/20230112/MPL/2972529148
...,...,...,...,...,...,...
100,Twin Pack: L-Men Gain Mass Klepon Latte 500gr ...,2LD0905181P2,NaN,Buy 1 Get 1 - L-Men Gain Mass Klepon Latte,NaN,INV/20230101/MPL/2943328503
101,Twin Pack: L-Men Gain Mass Taro 500gr - Suplem...,2304008180P2,NaN,L-Men Gain Mass Taro 500g x 2 pcs,NaN,INV/20230101/MPL/2943258936
102,Twin Pack: Tropicana Slim Avocado Coffee (10 S...,2104115110P2,NaN,Twin Pack - Tropicana Slim Avocado Coffee 10 S...,NaN,INV/20230102/MPL/2946311898
103,Twin Pack: Tropicana Slim Low Fat Korean Straw...,2105028180P2,NaN,Twin Pack - Tropicana Slim Low Fat Milk Korean...,NaN,INV/20230101/MPL/2943637388
104,Twin Pack: Tropicana Slim Mint Cocoa (10 Sch) ...,2104148024P2,NaN,Tropicana Slim Mint Cocoa 10 Sachet x 2 pcs,NaN,INV/20230113/MPL/2973453195

In [13]:
### run 9 harus se kosong mungkin
selcen_null[(selcen_null['ID Produk'].isnull())&(selcen_null['Product Name']!='Kartu Ucapan & Kemasan - Kirim sebagai Hadiah')][['Product Name','SKU']].drop_duplicates()#.to_excel('prod id tokped missing.xlsx',index=False)

                                      Product Name         SKU
95238   Kartu Ucapan - Bisa Dikirim sebagai Hadiah    PH76B110
108589  Kartu Ucapan - Bisa Dikirim sebagai Hadiah  2305551161

# WMS

In [14]:
### run 10

# import pandas as pd
# import numpy as np
import pypyodbc

conn = pypyodbc.connect('Driver={SQL Server};'
                        'Server=NFI-DB-01;'
                        'Database=gudang;'
                        # 'UID=andra.miftah;'
                        # 'PWD=24nutrifoodindonesia21;'
                         'Trusted_Connection=yes;'
                )

cursor = conn.cursor()
wms_telkom = pd.read_sql(r"""SELECT t1.id, t1.order_id,t1.status, t1.quantity, t1.product_id, t2.id,  t2.order_number, t2.invoice_number, t2.channel, t2.order_date, t3.id, t3.sku, t3.name
  FROM [gudang].[dbo].[outbound_items] as t1
  left join orders as t2
  on t1.order_id = t2.id
  left join products as t3
  on t1.product_id = t3.id
  where t2.channel = 'Tokopedia'""", conn)

In [28]:
## run 10 alternative
wms_telkom=pd.read_excel(r"D:\Downloads\Data Gudang 20221122 (1).xlsx")
wms_telkom=wms_telkom[wms_telkom['channel']=='Tokopedia']

In [15]:
### run 11

# import pandas as pd
# import numpy as np
# import pypyodbc

# conn = pypyodbc.connect('Driver={SQL Server};'
#                 'Server=NFI-DB-01;'
#                 'Database=gudang;'
#                 'UID=andra.miftah;'
#                 'PWD=24nutrifoodindonesia21;'
#                 )

# cursor = conn.cursor()
# wms_telkom = pd.read_sql(r"""SELECT t1.id, t1.order_id,t1.status, t1.quantity, t1.product_id, t2.id,  t2.order_number, t2.invoice_number, t2.channel, t2.order_date, t3.id, t3.sku, t3.name
#   FROM [gudang].[dbo].[outbound_items] as t1
#   left join orders as t2
#   on t1.order_id = t2.id
#   left join products as t3
#   on t1.product_id = t3.id
#   where t2.channel = 'Tokopedia'""", conn)

# wms_telkom=pd.read_excel(r"D:\settlement\Code\Settlement Project\Manual\backup wms\data_wms_telkom Juli 2022.xlsx")

# wms_telkom=wms_telkom[wms_telkom['channel']=='Tokopedia']

# outbound_items = pd.read_csv(r'Backup Gudang 4 Sept 2021 Gudang Baru/outbound_items.csv', sep = ';')
# orders = pd.read_csv(r'Backup Gudang 4 Sept 2021 Gudang Baru/orders.csv', sep = ';')
# products = pd.read_csv(r'Backup Gudang 4 Sept 2021 Gudang Baru/products.csv', sep = ';')

# wms_telkom2 = outbound_items[['id', 'order_id','status', 'quantity', 'product_id']].merge(
#     orders[['id',  'order_number', 'invoice_number', 'channel', 'order_date']], how = 'left', left_on = 'order_id', right_on = 'id'
# ).merge(
#     products[['id', 'sku', 'name']], how = 'left', left_on = 'product_id', right_on = 'id'
# )
# wms_telkom2 = wms_telkom2[wms_telkom2['channel'].isin(['Tokopedia'])]
if 'STATUS' in wms_telkom.columns:
    wms_telkom = wms_telkom.rename(columns = {'STATUS':'status'})
wms_telkom = wms_telkom[['invoice_number', 'sku', 'status', 'quantity']].drop_duplicates()
wms_telkom_pure = wms_telkom.copy()
# wms_telkom2 = wms_telkom2[['invoice_number', 'sku', 'status', 'quantity']].drop_duplicates()
# wms_telkom = wms_telkom.append(wms_telkom2, ignore_index = True, sort = False)

# wms_telkom = wms_telkom.groupby(['invoice_number', 'sku', 'status'])['quantity'].sum().reset_index()

wms_telkom['WH'] = 'Telkom'
wms_telkom = wms_telkom.rename(columns = {'invoice_number' : 'SOREFERENCE2', 'status':'SO STATUS', 'sku' : 'SKU WH', 'quantity' : 'Warehouse Quantity'})

colname = wms_telkom.columns.to_list()
wms_telkom_all = wms_telkom.merge(j_conv, how = 'left', left_on = ['SKU WH'], right_on = ['Real SKU'])
wms_j = wms_telkom_all[wms_telkom_all['SKU Produk'].notnull()]

wms_j['SKU WH'] = wms_j['SKU Produk']
wms_j['Warehouse Quantity'] = wms_j['Warehouse Quantity'] * wms_j['Konversi ke UOM'].astype(float)

wms_telkom = wms_telkom.append(wms_j, ignore_index = True, sort = False)
wms_telkom = wms_telkom[colname]

temp_telkom = for_wms[for_wms['Invoice'].isin(wms_telkom['SOREFERENCE2'])]

temp_telkom = temp_telkom.drop(['WH', 'SOREFERENCE2', 'SO STATUS', 'SKU WH', 'Warehouse Quantity'], axis = 1)
temp_telkom['Invoice'] = temp_telkom['Invoice'].astype(str)
wms_telkom['SOREFERENCE2'] = wms_telkom['SOREFERENCE2'].astype(str)

temp_telkom['Real SKU'] = temp_telkom['Real SKU'].astype(str).str.replace('.0', '', regex = False)
wms_telkom['SKU WH'] = wms_telkom['SKU WH'].astype(str)

temp_telkom = temp_telkom.merge(wms_telkom.drop_duplicates(['SOREFERENCE2', 'SKU WH']), how = 'left', left_on = ['Invoice', 'Real SKU'], right_on = ['SOREFERENCE2', 'SKU WH']).set_index(temp_telkom.index)

temp_telkom['Warehouse Quantity'] = temp_telkom['Warehouse Quantity'] * temp_telkom['Qty. Invoiced']/temp_telkom.groupby(['Invoice', 'Real Nama Produk'])['Qty. Invoiced'].transform('sum')

temp_telkom_bundle = temp_telkom[temp_telkom['Brand'] == 'Bundle']

temp_buat_bundle = temp_telkom[temp_telkom['Warehouse Quantity'].notnull()].groupby(['Invoice', 'Bundle Name']).agg({'WH' : 'first', 'SO STATUS' : 'first', 'Warehouse Quantity' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Warehouse Quantity'] = temp_buat_bundle['Warehouse Quantity']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

temp_telkom_bundle = temp_telkom_bundle.merge(temp_buat_bundle.drop_duplicates(['Invoice', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Product Name'], right_on = ['Invoice', 'Bundle Name']).set_index(temp_telkom_bundle.index)
temp_telkom_bundle['Warehouse Quantity_y'] = temp_telkom_bundle['Warehouse Quantity_y']*temp_telkom_bundle['Qty. Invoiced']

temp_telkom['SO STATUS'][temp_telkom_bundle.index] = temp_telkom_bundle['SO STATUS_y']
temp_telkom['WH'][temp_telkom_bundle.index] = temp_telkom_bundle['WH_y']
temp_telkom['Warehouse Quantity'][temp_telkom_bundle.index] = temp_telkom_bundle['Warehouse Quantity_y']

for_wms = for_wms[~for_wms['Invoice'].isin(wms_telkom['SOREFERENCE2'])]
for_wms = for_wms.append(temp_telkom, ignore_index = True, sort = False)

for_wms_null = for_wms[(for_wms['Invoice'].isin(wms_telkom['SOREFERENCE2'])) & 
        (for_wms['SO STATUS'].isnull())]

temp_telkom = for_wms_null[for_wms_null['Invoice'].isin(wms_telkom['SOREFERENCE2'])]
wms_telkom2 = wms_telkom.copy()

wms_telkom2['SKU WH'] = wms_telkom2['SKU WH'].astype(str).str.replace('2309005305', '2309005300')

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '1101930453'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(R)1101930453'

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '1101155250'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(E)1101155250'

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '2101846355'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(E)2101846355'

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '2101484302'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(E)2101484302'

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '1101155250'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(E)1101155250'

temp_telkom = temp_telkom.drop(['WH', 'SOREFERENCE2', 'SO STATUS', 'SKU WH', 'Warehouse Quantity'], axis = 1)
temp_telkom['Invoice'] = temp_telkom['Invoice'].astype(str)
wms_telkom2['SOREFERENCE2'] = wms_telkom2['SOREFERENCE2'].astype(str)

temp_telkom['Real SKU'] = temp_telkom['Real SKU'].astype(str).str.replace('.0', '', regex = False)
wms_telkom2['SKU WH'] = wms_telkom2['SKU WH'].astype(str)

temp_telkom = temp_telkom.merge(wms_telkom2.drop_duplicates(['SOREFERENCE2', 'SKU WH']), how = 'left', left_on = ['Invoice', 'Real SKU'], right_on = ['SOREFERENCE2', 'SKU WH']).set_index(temp_telkom.index)
temp_telkom['Warehouse Quantity'] = temp_telkom['Warehouse Quantity'] * temp_telkom['Qty. Invoiced']/temp_telkom.groupby(['Invoice', 'Real Nama Produk'])['Qty. Invoiced'].transform('sum')

temp_telkom_bundle = temp_telkom[temp_telkom['Brand'] == 'Bundle']

temp_buat_bundle = temp_telkom[temp_telkom['Warehouse Quantity'].notnull()].groupby(['Invoice', 'Bundle Name']).agg({'WH' : 'first', 'SO STATUS' : 'first', 'Warehouse Quantity' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Warehouse Quantity'] = temp_buat_bundle['Warehouse Quantity']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

temp_telkom_bundle = temp_telkom_bundle.merge(temp_buat_bundle.drop_duplicates(['Invoice', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Product Name'], right_on = ['Invoice', 'Bundle Name']).set_index(temp_telkom_bundle.index)
temp_telkom_bundle['Warehouse Quantity_y'] = temp_telkom_bundle['Warehouse Quantity_y']*temp_telkom_bundle['Qty. Invoiced']

temp_telkom['SO STATUS'][temp_telkom_bundle.index] = temp_telkom_bundle['SO STATUS_y']
temp_telkom['WH'][temp_telkom_bundle.index] = temp_telkom_bundle['WH_y']
temp_telkom['Warehouse Quantity'][temp_telkom_bundle.index] = temp_telkom_bundle['Warehouse Quantity_y']

for_wms['SO STATUS'][temp_telkom.index] = temp_telkom['SO STATUS']
for_wms['WH'][temp_telkom.index] = temp_telkom['WH']
for_wms['Warehouse Quantity'][temp_telkom.index] = temp_telkom['Warehouse Quantity']

In [16]:
### run 12
sku_dups = wms_telkom.groupby(['SOREFERENCE2', 'SKU WH'])['WH'].count().reset_index()
sku_dups = sku_dups[sku_dups['WH'] > 1]['SOREFERENCE2'].unique()

wms_telkom_grouped = wms_telkom.groupby(['SOREFERENCE2', 'SKU WH', 'SO STATUS', 'WH'])['Warehouse Quantity'].sum().reset_index()
temp_telkom = for_wms[for_wms['Invoice'].isin(sku_dups)]

temp_telkom = temp_telkom.drop(['WH', 'SOREFERENCE2', 'SO STATUS', 'SKU WH', 'Warehouse Quantity'], axis = 1)
temp_telkom['Invoice'] = temp_telkom['Invoice'].astype(str)
wms_telkom_grouped['SOREFERENCE2'] = wms_telkom_grouped['SOREFERENCE2'].astype(str)

temp_telkom['Real SKU'] = temp_telkom['Real SKU'].astype(str).str.replace('.0', '', regex = False)
wms_telkom_grouped['SKU WH'] = wms_telkom_grouped['SKU WH'].astype(str)

temp_telkom = temp_telkom.merge(wms_telkom_grouped.drop_duplicates(['SOREFERENCE2', 'SKU WH']), how = 'left', left_on = ['Invoice', 'Real SKU'], right_on = ['SOREFERENCE2', 'SKU WH']).set_index(temp_telkom.index)
temp_telkom['Warehouse Quantity'] = temp_telkom['Warehouse Quantity'] * temp_telkom['Qty. Invoiced']/temp_telkom.groupby(['Invoice', 'Real Nama Produk'])['Qty. Invoiced'].transform('sum')

temp_telkom_bundle = temp_telkom[temp_telkom['Brand'] == 'Bundle']

temp_buat_bundle = temp_telkom[temp_telkom['Warehouse Quantity'].notnull()].groupby(['Invoice', 'Bundle Name']).agg({'WH' : 'first', 'SO STATUS' : 'first', 'Warehouse Quantity' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Warehouse Quantity'] = temp_buat_bundle['Warehouse Quantity']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

temp_telkom_bundle = temp_telkom_bundle.merge(temp_buat_bundle.drop_duplicates(['Invoice', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Product Name'], right_on = ['Invoice', 'Bundle Name']).set_index(temp_telkom_bundle.index)
temp_telkom_bundle['Warehouse Quantity_y'] = temp_telkom_bundle['Warehouse Quantity_y']*temp_telkom_bundle['Qty. Invoiced']

temp_telkom['SO STATUS'][temp_telkom_bundle.index] = temp_telkom_bundle['SO STATUS_y']
temp_telkom['WH'][temp_telkom_bundle.index] = temp_telkom_bundle['WH_y']
temp_telkom['Warehouse Quantity'][temp_telkom_bundle.index] = temp_telkom_bundle['Warehouse Quantity_y']

for_wms['SO STATUS'][temp_telkom.index] = temp_telkom['SO STATUS']
for_wms['WH'][temp_telkom.index] = temp_telkom['WH']
for_wms['Warehouse Quantity'][temp_telkom.index] = temp_telkom['Warehouse Quantity']

In [27]:
for_wms[(for_wms['Invoice'].isin(wms_telkom['SOREFERENCE2'])) & 
        (for_wms['SO STATUS'].isnull())].groupby(['Product Name','Product ID','Real SKU', 'Real Nama Produk','Bundle Name', 'SKU WH'], dropna = False)['Invoice'].first().reset_index()

,Product Name,Product ID,Real SKU,Real Nama Produk,Bundle Name,SKU WH,Invoice
0,(FREE) L-Men Protein Crunch BBQ Beef (20gr),1744101727,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),L-Men Platinum Choco Latte 800gr FREE L-Men Pr...,NaN,INV/20220806/MPL/2551420739
1,(FREE) L-Men Protein Crunch BBQ Beef (20gr),1744134650,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),L-Men Whey Advanced Cappuccino 250gr FREE L-Me...,NaN,INV/20220807/MPL/2554771342
2,(FREE) L-Men Protein Crunch BBQ Beef (20gr),2747653959,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),Free 3 Protein Crunch - L-Men Platinum Kacang ...,NaN,INV/20220806/MPL/2552407074
3,(FREE) L-Men Protein Crunch BBQ Beef (20gr),2747681015,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),Free 3 Protein Crunch - L-Men Platinum Ketan H...,NaN,INV/20220807/MPL/2553045153
4,(Near ED) L-MEN PROTEIN CRUNCH BBQ BEEF 20BX20G,1681720928,(E)2309005305,(Near ED) L-MEN PROTEIN CRUNCH BBQ BEEF 20BX20G,L-Men Protein Crunch BBQ Beef 20gr (1 Carton /...,NaN,INV/20230222/MPL/3064582415
5,(PBS) L-Men Hi Protein 2 Go Chocolate,2596160549,(B)2307061250,(PBS) L-Men Hi Protein 2 Go Chocolate,Free L-Men 2 Go - L-Men Protein Bar Crunchy Ch...,NaN,INV/20220304/MPL/2100383716
6,(PBS) L-Men Hi Protein 2 Go Chocolate,2596429036,(B)2307061250,(PBS) L-Men Hi Protein 2 Go Chocolate,Free 2 Pcs L-Men 2 Go - L-Men Lose Weight Avoc...,NaN,INV/20220207/MPL/2020735692
7,(PBS) L-Men Hi Protein 2 Go Chocolate,2596441319,(B)2307061250,(PBS) L-Men Hi Protein 2 Go Chocolate,Free 2 Pcs L-Men 2 Go - L-Men Plant Protein ra...,NaN,INV/20220307/MPL/2109179183
8,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4880563929,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Daily Popcorn Cara...,NaN,INV/20220806/MPL/2550953970
9,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4880981740,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Daily Dark Chocola...,NaN,INV/20220808/MPL/2558728708
10,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4881036859,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Gain Mass Chocolat...,NaN,INV/20220807/MPL/2554504320
11,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4881052714,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Gain Mass Taro 500gr,NaN,INV/20220802/MPL/2540735531
12,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4881083814,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Lose Weight Chocol...,NaN,INV/20220807/MPL/2554626272
13,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4881096342,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Lose Weight Avocad...,NaN,INV/20220806/MPL/2552562106
14,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4881108279,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Lose Weight Mango ...,NaN,INV/20220806/MPL/2552671860
15,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4899698030,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Plant Protein Ogur...,NaN,INV/20220806/MPL/2551751098
16,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4899742721,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Platinum Choco Lat...,NaN,INV/20220807/MPL/2554392497
17,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4899843681,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Protein Bar Crunch...,NaN,INV/20220809/MPL/2560456297
18,(PBS) L-Men Protein Crunch BBQ Beef 20BX20G,4899952917,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),FREE Protein Crunch - L-Men Advanced Choco Van...,NaN,INV/20220806/MPL/2551899391
19,Gift - Kartu Pantun by HiLo Teen,3100809600,(G)71210222,Gift - Kartu Pantun by HiLo Teen,Buy1 Get 1 FREE HiLo Teen Biscuit Caramel 500g...,NaN,INV/20220314/MPL/2132523957
20,Gift - Masker Nature Republic,4701672303,(G)71210267,Gift - Masker Nature Republic,FREE Sheet Mask - Triple Pack: Tropicana Slim ...,NaN,INV/20220804/MPL/2547908422
21,Gift - Tas Serut HiLo PRJ,6147353279,(G)71210292,Gift - Tas Serut HiLo PRJ,Free Tas - HiLo Milky Vanilla Cookies Ready to...,NaN,INV/20220917/MPL/2662440475
22,Gift Tokopedia - Freemir Wheat Straw Plate,5451044584,(G)71210290,Gift Tokopedia - Freemir Wheat Straw Plate,FREE Wheat Straw Plate - Tropicana Slim Minyak...,NaN,INV/20220916/MPL/2660657894
23,HiLo School Original 400g,7215512339,2HF0114021,HiLo School Original 400g,Buy 1 Get 1 FREE - HiLo School Chocolate 500gr...,NaN,INV/20221223/MPL/2921615497
24,HiLo School RTD Vanila Vegiberi 200ml,1551068729,2HF1401250,HiLo School RTD Vanila Vegiberi 200ml,HiLo School Vanilla Vegiberi 200ml (24 Pack) -...,NaN,INV/20220202/MPL/2005295806
25,HiLo School RTD Vanila Vegiberi 200ml,1734287863,2HF1401250,HiLo School RTD Vanila Vegiberi 200ml,HiLo School Vanilla Vegiberi 200ml - Ready to ...,NaN,INV/20220805/MPL/2550181337
26,HiLo School Vanilla Vegiberi 200ml (24 Pack) -...,1551068729,21014281P24,Hilo School Vanilla Vegiberi Ready To Drink Su...,NaN,NaN,INV/20220202/MPL/2005295806
27,HiLo School Vanilla Vegiberi 200ml - Ready to ...,1734287863,21014281P4,Hilo School Vanilla Vegiberi Ready To Drink Su...,NaN,NaN,INV/20220805/MPL/2550181337
28,L-Men Platinum Choco Latte Box (6 Sch) - 25 gr...,1053561784,2305551161,L-Men Platinum Chocolate Dus 6 sch 38.5 gr,NaN,NaN,INV/20220727/MPL/2524154751
29,L-Men Platinum Chocolate Dus 6 sch 38.5 gr,1053667417,2305551161,L-Men Platinum Chocolate Dus 6 sch 38.5 gr,Twin Pack: L-Men Platinum Choco Latte Box (6 S...,NaN,INV/20220729/MPL/2528871371
30,L-Men Platinum Chocolate Dus 6 sch 38.5 gr,1139774270,2305551161,L-Men Platinum Chocolate Dus 6 sch 38.5 gr,Triple Pack: L-Men Platinum Choco Latte Box (6...,NaN,INV/20220914/MPL/2656560472
31,L-Men Protein Crunch BBQ Beef (20gr),1395719416,2309005305,L-Men Protein Crunch BBQ Beef (20gr),NaN,NaN,INV/20220903/MPL/2625576480
32,L-Men Protein Crunch BBQ Beef (20gr),1681720928,2309005305,L-Men Protein Crunch BBQ Beef (20gr),L-Men Protein Crunch BBQ Beef 20gr (1 Carton /...,NaN,INV/20220401/MPL/2184390331
33,L-Men Protein Crunch BBQ Beef 20gr (1 Carton /...,1681720928,(E)2309005305P20,Special Promo : L-Men Protein Crunch BBQ Beef ...,NaN,NaN,INV/20230222/MPL/3064582415
34,L-Men Protein Crunch BBQ Beef 20gr (1 Carton /...,1681720928,2309005305P20,L-Men Protein Crunch BBQ Beef (20gr) (1 Karton...,NaN,NaN,INV/20220401/MPL/2184390331
35,L-Men Whey Daily Dark Chocolate 250gr,2596045780,2300551155,L-Men Whey Daily Dark Chocolate 250gr,Free L-Men 2 Go - Twin Pack L-Men Daily Dark C...,NaN,INV/20220329/MPL/2176774513
36,Near ED - HiLo Almond Milk Coconut 200gr,2253461882,(E)2101487148,Near ED - HiLo Almond Milk Coconut 200gr,Twin Pack: HiLo Almond Milk Coconut 200gr - Su...,NaN,INV/20221104/MPL/2792287952
37,NutriSari Florida Orange (40 Sch),652277609,1101907331,Nutrisari Florida Orange (40 Sch),NaN,NaN,INV/20220213/MPL/2040819167
38,Triple Pack: L-Men Platinum Choco Latte Box (6...,1139774270,2305551161P3,L-Men Platinum Chocolate Dus 6 sch 38.5 gr x 3...,NaN,NaN,INV/20220914/MPL/2656560472
39,Tropicana Slim Cookies Nutty Chocolate,22346632,2152051110,Tropicana Slim Nutty Chocolate Cookies 200gr,NaN,NaN,INV/20220304/MPL/2099861640
40,Tropicana Slim Milk Skim Coffee 500gr,590865803,2101150180,Tropicana Slim Milk Skim Coffee 500gr,Twin Pack: Tropicana Slim Non Fat Skim Milk Fi...,NaN,INV/20221007/MPL/2716867437
41,Tropicana Slim Minyak Kanola 946ml,618142203,2104405,Tropicana Slim Minyak Kanola 946ml,Twin Pack: Tropicana Slim Minyak Kanola 946ml,NaN,INV/20220314/MPL/2133343567
42,Twin Pack: HiLo Almond Milk Coconut 200gr - Su...,2253461882,(E)2101487148P2,Near ED - HiLo Almond Milk Coconut 200gr x 2pcs,NaN,NaN,INV/20221104/MPL/2792287952
43,Twin Pack: L-Men Platinum Choco Latte Box (6 S...,1053667417,2305551161P2,L-Men Platinum Chocolate Dus 6 sch x 2 pcs,NaN,NaN,INV/20220729/MPL/2528871371
44,Twin Pack: Tropicana Slim Minyak Kanola 946ml,618142203,2104405P2,Twin Pack: Tropicana Slim Minyak Kanola 946ml,NaN,NaN,INV/20220314/MPL/2133343567
45,Twin Pack: Tropicana Slim Non Fat Skim Milk Fi...,590865803,2101150180P2,Twin Pack: Tropicana Slim Skim Milk Coffee 500gr,NaN,NaN,INV/20221007/MPL/2716867437

In [35]:
wms_telkom_pure[wms_telkom_pure['invoice_number']=='INV/20220729/MPL/2528871371']#kalau gk ada disini gk kekirim berarti

                    invoice_number         sku     status  quantity
43434  INV/20220729/MPL/2528871371  2305551106  confirmed         2

# Settlement

In [17]:
## run 13

import pandas as pd
import os
import numpy as np

pd.options.mode.chained_assignment = None

set_raw = pd.DataFrame()
for i in os.listdir(r'Settlement Project\Tokopedia\Settlement Tokped'):
    if 'xls' in i and '$' not in i:
        print(i)
        temp = pd.read_excel(r'Settlement Project\Tokopedia\Settlement Tokped/' + str(i))
        if 'Description' not in temp.columns: ### dr sini 
            temp = pd.read_excel(r'Settlement Project\Tokopedia\Settlement Tokped/' + str(i), header = 6)
            if 'Description' not in temp.columns:
                print('Break')
                break
        temp['File Name'] = str(i)
        true_col = ['Date', 'Description', 'Nominal (Rp)', 'Balance (Rp)', 'File Name']
        if temp.columns.to_list() == true_col :
            print('Column sama')
        else:
            print('Column beda')
            print([x for x in true_col if x not in temp.columns.to_list()])
            print([x for x in temp.columns.to_list() if x not in true_col])
        if "Description" in set_raw.columns:
            temp=temp[~temp['Description'].isin(set_raw['Description'].unique())]
        if 'Mutation (Debit/Credit)' in temp.columns:
            # temp['Nominal (Rp)']=temp['Nominal (Rp)'].astype(int)
            temp.loc[temp['Mutation (Debit/Credit)']=='Debit','Nominal (Rp)']=temp['Nominal (Rp)']*-1
        set_raw = set_raw.append(temp, ignore_index = True, sort = False) #sampai sini geser kiri

202012-Deposit_29_12_2020_06_01_2021.xls
Column sama
202101-Deposit_05_01_2021_14_01_2021.xls
Column sama
202101-Deposit_12_01_2021_20_01_2021.xls
Column sama
202101-Deposit_20_01_2021_27_01_2021.xls
Column sama
202101-Deposit_26_01_2021_05_02_2021.xls
Column sama
202102-Deposit_05_02_2021_10_02_2021.xls
Column sama
202102-Deposit_10_02_2021_24_02_2021.xls
Column sama
202102-Deposit_24_02_2021_03_03_2021.xls
Column sama
202103-Deposit_03_03_2021_10_03_2021.xls
Column sama
202103-Deposit_10_03_2021_17_03_2021.xls
Column sama
202103-Deposit_17_03_2021_25_03_2021.xls
Column sama
202103-Deposit_24_03_2021_30_03_2021.xls
Column sama
202104-Deposit_07_04_2021_15_04_2021.xls
Column sama
202104-Deposit_13_04_2021_21_04_2021.xls
Column sama
202104-Deposit_20_04_2021_28_04_2021.xls
Column sama
202104-Deposit_30_03_2021_07_04_2021.xls
Column sama
202105-Deposit_05_05_2021_12_05_2021.xlsx
Column sama
202105-Deposit_12_05_2021_19_05_2021.xls
Column sama
202105-Deposit_19_05_2021_28_05_2021.xls
Column sama
202105-Deposit_28_04_2021_05_05_2021.xls
Column sama
202105-Deposit_28_05_2021_02_06_2021.xls
Column sama
202106-Deposit_02_06_2021_04_06_2021.xls
Column sama
202106-Deposit_04_06_2021_09_06_2021.xls
Column sama
202106-Deposit_09_06_2021_11_06_2021.xls
Column sama
202106-Deposit_11_06_2021_16_06_2021.xls
Column sama
202106-Deposit_16_06_2021_23_06_2021.xls
Column sama
202106-Deposit_23_06_2021_26_06_2021.xls
Column sama
202106-Deposit_26_06_2021_30_06_2021.xls
Column sama
202107-Deposit_07_07_2021_14_07_2021.xls
Column sama
202107-Deposit_14_07_2021_21_07_2021.xls
Column sama
202107-Deposit_20_07_2021_30_07_2021.xls
Column sama
202107-Deposit_30_06_2021_07_07_2021.xls
Column sama
202107-Deposit_30_07_2021_02_08_2021.xls
Column sama
202108-Deposit_01_08_2021_10_08_2021.xls
Column sama
202108-Deposit_10_08_2021_23_08_2021.xls
Column sama
202108-Deposit_23_08_2021_30_08_2021.xls
Column sama
202108-Deposit_30_08_2021_01_09_2021.xls
Column sama
Deposit_01_09_2021_08_09_2021.xls
Column sama
Deposit_01_11_2021_09_11_2021.xls
Column sama
Deposit_02_08_2021_04_08_2021.xls
Column sama
Deposit_02_08_2021_07_08_2021.xls
Column sama
Deposit_03_02_2022_05_02_2022.xls
Column sama
Deposit_04_04_2022_05_04_2022.xls
Column sama
Deposit_04_04_2022_09_04_2022.xls
Column sama
Deposit_04_12_2021_08_12_2021.xls
Column sama
Deposit_05_02_2022_12_02_2022.xls
Column sama
Deposit_06_10_2021_13_10_2021.xls
Column sama
Deposit_07_01_2022_10_01_2022.xls
Column sama
Deposit_07_03_2022_09_03_2022.xls
Column sama
Deposit_08_09_2021_13_09_2021.xls
Column sama
Deposit_08_12_2021_12_12_2021.xls
Column sama
Deposit_09_03_2022_14_03_2022.xls
Column sama
Deposit_09_04_2022_14_04_2022.xls
Column sama
Deposit_09_11_2021_11_11_2021.xls
Column sama
Deposit_1046470_09_01_2023_23_01_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_1069435_23_01_2023_30_01_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_10_01_2022_17_01_2022.xls
Column sama
Deposit_1192930_30_01_2023_27_02_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_11_11_2021_17_11_2021.xls
Column sama
Deposit_1230200_27_02_2023_06_03_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_12651_22_04_2022_27_04_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_12_02_2022_16_02_2022.xls
Column sama
Deposit_12_12_2021_22_12_2021.xls
Column sama
Deposit_1322996_06_03_2023_30_03_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_13_09_2021_27_09_2021.xls
Column sama
Deposit_13_10_2021_21_10_2021.xls
Column sama
Deposit_1409111_30_03_2023_15_04_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_1415506_15_04_2023_27_04_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_14_03_2022_23_03_2022.xls
Column sama
Deposit_14_04_2022_20_04_2022.xls
Column sama
Deposit_158936_30_05_2022_09_06_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_159781_09_06_2022_21_06_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_16_02_2022_22_02_2022.xls
Column sama
Deposit_170658_21_06_2022_24_06_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_17_01_2022_24_01_2022.xls
Column sama
Deposit_17_11_2021_26_11_2021.xls
Column sama
Deposit_187040_24_06_2022_29_06_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_20_04_2022_22_04_2022.xls
Column sama
Deposit_219408_29_06_2022_06_07_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_21_10_2021_25_10_2021.xls
Column sama
Deposit_22_02_2022_24_02_2022.xls
Column sama
Deposit_22_12_2021_29_12_2021.xls
Column sama
Deposit_238821_06_07_2022_12_07_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_23_03_2022_28_03_2022.xls
Column sama
Deposit_24_01_2022_26_01_2022.xls
Column sama
Deposit_24_02_2022_25_02_2022.xls
Column sama
Deposit_25_02_2022_28_02_2022.xls
Column sama
Deposit_25_10_2021_01_11_2021.xls
Column sama
Deposit_25_10_2021_27_10_2021.xls
Column sama
Deposit_26_01_2022_30_01_2022.xls
Column sama
Deposit_26_11_2021_29_11_2021.xls
Column sama
Deposit_27_09_2021_06_10_2021.xls
Column sama
Deposit_28_02_2022_07_03_2022.xls
Column sama
Deposit_28_03_2022_04_04_2022.xls
Column sama
Deposit_296008_12_07_2022_27_07_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_29_11_2021_04_12_2021.xls
Column sama
Deposit_29_12_2021_07_01_2022.xls
Column sama
Deposit_30_01_2022_03_02_2022.xls
Column sama
Deposit_30_07_2021_02_08_2021.xls
Column sama
Deposit_35323_27_04_2022_12_05_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_35323_27_04_2022_12_05_2022.xlsx
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_41105_12_05_2022_17_05_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_419287_27_07_2022_10_08_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_419400_10_08_2022_29_08_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_51868_17_05_2022_20_05_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_578603_29_08_2022_28_09_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_63290_20_05_2022_25_05_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_664509_28_09_2022_09_10_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_709481_09_10_2022_16_10_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_709489_16_10_2022_23_10_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_709490_23_10_2022_31_10_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_737224_31_10_2022_07_11_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_74916_25_05_2022_30_05_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_762098_07_11_2022_12_11_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_788396_12_11_2022_19_11_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_823768_19_11_2022_23_11_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_824702_23_11_2022_29_11_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_865023_29_11_2022_07_12_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_880478_07_12_2022_12_12_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_906287_12_12_2022_19_12_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_991652_19_12_2022_31_12_2022.xls
Column beda
[]
['Mutation (Debit/Credit)']
Deposit_991730_31_12_2022_09_01_2023.xls
Column beda
[]
['Mutation (Debit/Credit)']

In [24]:
## run 14
set_jan = set_raw.copy()

set_jan = set_jan.drop_duplicates(['Date', 'Description', 'Nominal (Rp)'])

set_jan = set_jan[~set_jan['Description'].astype(str).str.isnumeric()]
set_jan['order_id'] = set_jan['Description'].astype(str).str.extract(r'(INV\S+)')

set_jan['Negatif'] = np.nan
negatif = pd.read_excel(r'Settlement Project/Tokopedia/Settlement Converter Tokopedia.xlsx', sheet_name = 'Negatif')
for i in range(len(negatif)):
    keyword = negatif['Keyword'][i]
    value = negatif['Negatif'][i]
    indeks = set_jan[set_jan['Description'].astype(str).str.contains(keyword, case = False)].index.to_list()
    set_jan['Negatif'][indeks] = value
    print(i,keyword,value)
    
set_jan['Negatif'] = set_jan['Negatif'].fillna('Positif')
indeks = set_jan[set_jan['Negatif'] == 'Positif'].index.to_list()
set_jan['Nominal (Rp)'][indeks] = set_jan['Nominal (Rp)'][indeks].abs()

indeks = set_jan[set_jan['Negatif'] == 'Negatif'].index.to_list()
set_jan['Nominal (Rp)'][indeks] = set_jan['Nominal (Rp)'][indeks].abs() * -1

set_jan['Kategori New'] = np.nan

kategori = pd.read_excel(r'Settlement Project/Tokopedia/Settlement Converter Tokopedia.xlsx', sheet_name = 'Kategori')
for i in range(len(kategori)):
    keyword = kategori['Keyword'][i]
    value = kategori['Kategori'][i]
    indeks = set_jan[set_jan['Description'].astype(str).str.contains(keyword, case = False)].index.to_list()
    set_jan['Kategori New'][indeks] = value
    
order_id = pd.read_excel(r'Settlement Project/Tokopedia/Settlement Converter Tokopedia.xlsx', sheet_name = 'order_id')
for i in range(len(order_id)):
    keyword = order_id['Keyword'][i]
    value = order_id['order_id'][i]
    indeks = set_jan[(set_jan['Description'].astype(str).str.contains(keyword, case = False)) & (set_jan['order_id'].isnull())].index.to_list()
    set_jan['order_id'][indeks] = value

0 [System] Pengembalian biaya kirim retur Negatif
1 Barang tidak dapat dikirim Negatif
2 Dipotong karena Negatif
3 Dipotong karena Solusi dari Resolusi Negatif
4 Ganti Kurir Negatif
5 Kekurangan barang Negatif
6 Kendala order Negatif
7 Pemotongan Biaya Admin Dilayani Tokopedia Negatif
8 Pemotongan Biaya Dilayani Tokopedia untuk Pelengkap Negatif
9 Pemotongan biaya jaminan Negatif
10 Pemotongan biaya kirim Negatif
11 Pemotongan Biaya Layanan Regular Merchant Negatif
12 Pemotongan biaya proteksi Negatif
13 Pemotongan biaya TokoCabang untuk Invoice Negatif
14 Pemotongan cashback untuk Voucher Toko Negatif
15 Pemotongan Dana Negatif
16 Pemotongan Ongkir Negatif
17 Pemotongan penalti Negatif
18 Pemotongan Selisih Ongkir Negatif
19 Pemotongan selisih premi asuransi pengiriman Negatif
20 Pemotongan untuk Asuransi dengan Tokopedia Negatif
21 Pemotongan untuk Service Fee Official Store Negatif
22 Pemotongan untuk Subsidi Voucher Negatif
23 Pemotongan Voucher Negatif
24 Penarikan biaya Negatif
25 Penarikan Subsidi Ongkir dari transaksi yang tidak memenuhi Negatif
26 Penggantian biaya Negatif
27 Penggantian biaya kirim awal di Pusat Resolusi Negatif
28 Penggunaan Saldo Tokopedia Negatif
29 Penyesuaian asuransi non TM menjadi TM Negatif
30 Penyesuaian Pengembalian dana ongkos kirim Negatif
31 Penyesuaian solusi Negatif
32 Resi Invalid Negatif
33 selisih ongkir akibat kardus Positif
34 selisih ongkir karena kardus tokocabang Negatif
35 Selisih ongkir karena kardus tokocabang atas Negatif
36 Selisih ongkir karena kardus tokocabang atas Positif
37 selisih ongkir karena kardus tokocabang atas invoice Positif
38 Selisih ongkir karena penggunaan dus TokoCabang Positif
39 selisih ongkos kirim akibat kardus Positif
40 Tidak ada konfirmasi dari penjual Negatif
41 Virtual bundling handling discount Positif
42 Withdrawal Negatif
43 Penyesuaian dana atas transaksi Negatif
44 Kompensasi atas pembatalan order  Positif
45 Pemotongan Biaya Jasa Transaksi Official Store Negatif
46 Penarikan otomatis Saldo Tokopedia penjual untuk melunasi tagihan biaya penyimpanan Dilayani Tokopedia Negatif
47 Komisi Affiliate untuk transaksi yang berhasil Negatif
48 Pengembalian Biaya Layanan Official Store Positif
49 Penarikan saldo untuk campaign Dipromosikan Affiliate Negatif
50 Pengembalian Pemotongan Rp1 Dipromosikan Affiliate untuk NutriMart Positif

In [25]:
### harus kosong
set_jan[(set_jan['Kategori New'].isnull())]['Description'].unique()#['Negatif'].unique()
# set_jan.to_csv('Rekap Settlement Tokopedia 2021-2022.csv',sep=';',index=False)

array([], dtype=object)

In [23]:
cek=pd.read_excel(r"D:\desktop\06. Settlement Tokopedia 2022.xlsx",sheet_name="Unpaid Dec 22",skiprows=6)

In [41]:
# set_jan[set_jan['order_id']=='INV/20220424/MPL/2263268732']
harusnyapaid=cek[cek['Tanggal Settlement Gabungan'].notnull()]['Invoice'].unique()
setlookup=set_jan[set_jan['order_id'].isin(harusnyapaid)][['File Name','order_id','Negatif','Kategori New','Date','Description']].rename(columns={'order_id':'Invoice'})#['Kategori New'].unique()
print(len(cek))
cekfinal=cek.merge(setlookup,how='left',on='Invoice')
# cekfinal[cekfinal['File Name'].notnull()]
cekfinal.to_excel('Settlement Tokopedia 2022.xlsx',index=False)

4164

In [23]:
set_raw[set_raw['Description'].str.contains('Rp1 Dipromosikan Affiliate')]

,Date,Description,Nominal (Rp),Balance (Rp),File Name,Mutation (Debit/Credit)
1522502,2023-03-31 09:30:29,Pengembalian Pemotongan Rp1 Dipromosikan Affil...,12,52688202,Deposit_1409111_30_03_2023_15_04_2023.xls,Credit

In [26]:
## run 15
for_wms['Paid'] = np.nan

paid = set_jan[set_jan['Kategori New'] == 'Produk+Ongkir']['order_id'].unique()
indeks = for_wms[for_wms['Invoice'].astype(str).isin(paid)].index.to_list()
for_wms['Paid'][indeks] = 'Paid'

refund = set_jan[set_jan['Kategori New'] == "Bi Komplain"]['order_id'].unique()
indeks = for_wms[for_wms['Invoice'].astype(str).isin(refund)].index.to_list()
for_wms['Paid'][indeks] = 'Refund'

for_wms['Paid'] = for_wms['Paid'].fillna('Unpaid')

set_pivot = pd.pivot_table(set_jan, values = 'Nominal (Rp)', index = 'order_id', columns = 'Kategori New', aggfunc=np.sum).reset_index()

set_pivot['Total Produk'] = 0

for i in set_pivot.columns:
    if 'Bi Kirim' in i:
        set_pivot['Total Produk'] = set_pivot['Total Produk'] + set_pivot[i].fillna(0).astype(int)

set_pivot['Total Produk'] = set_pivot['Total Produk'] + set_pivot['Asuransi'].fillna(0).astype(int) + set_pivot['Bi Marketing'].fillna(0).astype(int) + set_pivot['Produk+Ongkir'].fillna(0).astype(int) + set_pivot['Bi Selisih Dus'].fillna(0).astype(int) + set_pivot['Bi Komplain'].fillna(0).astype(int)

bundling = for_wms[for_wms['Bundle Name'].notnull()]
real_trx = for_wms[for_wms['Bundle Name'].isnull()]

real_trx['Invoice'] = real_trx['Invoice'].astype(str)
set_pivot['order_id'] = set_pivot['order_id'].astype(str)

real_trx = real_trx.merge(set_pivot[['order_id', 'Total Produk', 'Fullfee', 'Comfee', 'Tokopedia Ads']], how = 'left', left_on = 'Invoice', right_on = 'order_id')

non_prop = real_trx[real_trx['Brand'].isin(['Bonus Produk', 'Gimmick'])]
real_trx = real_trx[~real_trx['Brand'].isin(['Bonus Produk', 'Gimmick'])]

real_trx['Total Produk Prop'] = real_trx['Total Produk'].fillna(0) * real_trx['Total Net Before PPN']/real_trx.groupby(['Invoice'])['Total Net Before PPN'].transform('sum')
real_trx['Fullfee Prop'] = real_trx['Fullfee'].fillna(0) * real_trx['Qty. Invoiced']/real_trx.groupby(['Invoice'])['Qty. Invoiced'].transform('sum')
real_trx['Comfee Prop'] = real_trx['Comfee'].fillna(0) * real_trx['Total Net Before PPN']/real_trx.groupby(['Invoice'])['Total Net Before PPN'].transform('sum')

non_prop['Total Produk Prop'] = 0
non_prop['Fullfee Prop'] = 0
non_prop['Comfee Prop'] = 0

real_trx = real_trx.append(non_prop, ignore_index = True, sort = False)

bundling['Invoice'] = bundling['Invoice'].astype(str)

bundling = bundling.merge(real_trx[['Invoice', 'Product Name', 'Total Produk Prop', 'Comfee Prop', 'Fullfee Prop']].drop_duplicates(['Invoice', 'Product Name']), how = 'left', left_on = ['Invoice', 'Bundle Name'], right_on = ['Invoice', 'Product Name'])

non_prop = bundling[bundling['Brand'].isin(['Bonus Produk', 'Gimmick'])]
bundling = bundling[~bundling['Brand'].isin(['Bonus Produk', 'Gimmick'])]

bundling['Total Produk Prop'] = bundling['Total Produk Prop'].fillna(0) * bundling['Total Net Before PPN']/bundling.groupby(['Invoice', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundling['Fullfee Prop'] = bundling['Fullfee Prop'].fillna(0) * bundling['Qty. Invoiced']/bundling.groupby(['Invoice', 'Bundle Name'])['Qty. Invoiced'].transform('sum')
bundling['Comfee Prop'] = bundling['Comfee Prop'].fillna(0) * bundling['Total Net Before PPN']/bundling.groupby(['Invoice', 'Bundle Name'])['Total Net Before PPN'].transform('sum')

non_prop['Total Produk Prop'] = 0
non_prop['Fullfee Prop'] = 0
non_prop['Comfee Prop'] = 0

bundling = bundling.append(non_prop, ignore_index = True, sort = False)

# real_trx = real_trx.drop(['SKU_y', 'Real SKU_y', 'SKU_y'], axis = 1)
# real_trx = real_trx.rename(columns = {'SKU_x' : 'SKU'})

bundling = bundling.drop(['Product Name_y'], axis = 1)
bundling = bundling.rename(columns = {'Product Name_x' : 'Product Name'})

total_trx = real_trx.append(bundling, ignore_index = True, sort = False)

In [27]:
## run 16
total_trx['Total Selcen'] = total_trx['Price (Rp.)']

In [28]:
## run 17
indeks = total_trx[(total_trx['Paid'] == 'Paid') &
      (total_trx['Warehouse Origin'] == 'Shop Location') &
      (total_trx['SO STATUS'].isnull()) &
      (total_trx['Payment Date'] > '2021-07-28') &
       (total_trx['Payment Date'] < '2021-09-06')
      ].index.to_list()
total_trx['SO STATUS'][indeks] = 'confirmed'
total_trx['Warehouse Quantity'][indeks] = total_trx['Qty. Invoiced'][indeks]

unpaid = total_trx[total_trx['Paid'] == 'Unpaid']
total_trx = total_trx[total_trx['Paid'] != 'Unpaid']

unpaid['Total Produk Prop'] = unpaid['Total Selcen']

unpaid['Comfee'] = unpaid['Total Selcen'] * 4.25 / 100
# unpaid['Comfee'] = unpaid['Total Selcen']/1.11 * 4.25 / 100

unpaid['Fullfee'] = np.nan

unpaid_real = unpaid[unpaid['Bundle Name'].isnull()]
unpaid_bundle = unpaid[unpaid['Bundle Name'].notnull()]
indeks = unpaid_real[unpaid_real['WH'] == 'Titip Aja'].index.to_list()
unpaid_real['Fullfee'][indeks] = unpaid_real['Qty. Invoiced'][indeks] * 3000

unpaid_bundle['Fullfee'] = unpaid_bundle.merge(unpaid_real[['Invoice', 'Product Name', 'Fullfee']].drop_duplicates(['Invoice', 'Product Name']), how = 'left', left_on = ['Invoice', 'Bundle Name'], right_on = ['Invoice', 'Product Name']).set_index(unpaid_bundle.index)['Fullfee_y']
unpaid_bundle['Fullfee'] = unpaid_bundle['Fullfee'].fillna(0) * unpaid_bundle['Qty. Invoiced']/unpaid_bundle.groupby(['Invoice', 'Bundle Name'])['Qty. Invoiced'].transform('sum')

unpaid = unpaid_real.append(unpaid_bundle, ignore_index = True, sort = False)
unpaid['Fullfee Prop'] = unpaid['Fullfee']
unpaid['Comfee Prop'] = unpaid['Comfee']

total_trx = total_trx[total_trx['Paid'] != 'Unpaid']
total_trx = total_trx.append(unpaid, ignore_index = True, sort = False)

total_trx['BTL Cost'] = (total_trx['Total Produk Prop']) - total_trx['Total Net Before PPN']

total_trx.columns.to_list()

['Order ID',
 'Invoice',
 'Payment Date',
 'Order Status',
 'Product ID',
 'Product Name',
 'Qty. Invoiced',
 'SKU',
 'Notes',
 'Price (Rp.)',
 'Discount Amount (Rp.)',
 'Subsidi Amount (Rp.)',
 'Customer Name',
 'Customer Phone',
 'Recipient',
 'Recipient Number',
 'Recipient Address',
 'Courier',
 'Shipping Price + fee (Rp.)',
 'Insurance (Rp.)',
 'Total Shipping Fee (Rp.)',
 'Total Amount (Rp.)',
 'AWB',
 'Jenis Layanan',
 'Bebas Ongkir',
 'Warehouse Origin',
 'Campaign Name',
 'Source',
 'Date',
 'Month',
 'Year',
 'true datetime',
 'Pemilik Budget',
 'Real SKU',
 'Real Nama Produk',
 'Brand',
 'Sub Brand',
 'Produk 1',
 'SKU Produk 1',
 'PCS Produk 1',
 'Price List NFI 1',
 'Subtotal Produk 1',
 'Harga Display 1',
 'Harga Cost 1',
 'Harga Organik 1',
 'Produk 2',
 'SKU Produk 2',
 'PCS Produk 2',
 'Price List NFI 2',
 'Subtotal Produk 2',
 'Harga Display 2',
 'Harga Cost 2',
 'Harga Organik 2',
 'Produk 3',
 'SKU Produk 3',
 'PCS Produk 3',
 'Price List NFI 3',
 'Subtotal Produk 3',
 'Harga Display 3',
 'Harga Cost 3',
 'Harga Organik 3',
 'Produk 4',
 'SKU Produk 4',
 'PCS Produk 4',
 'Price List NFI 4',
 'Subtotal Produk 4',
 'Harga Display 4',
 'Harga Cost 4',
 'Harga Organik 4',
 'Produk 5',
 'SKU Produk 5',
 'PCS Produk 5',
 'Price List NFI 5',
 'Subtotal Produk 5',
 'Harga Display 5',
 'Harga Cost 5',
 'Harga Organik 5',
 'Produk 6',
 'SKU Produk 6',
 'PCS Produk 6',
 'Price List NFI 6',
 'Subtotal Produk 6',
 'Harga Display 6',
 'Harga Cost 6',
 'Harga Organik 6',
 'Produk 7',
 'SKU Produk 7',
 'PCS Produk 7',
 'Price List NFI 7',
 'Subtotal Produk 7',
 'Harga Display 7',
 'Harga Cost 7',
 'Harga Organik 7',
 'Bundle Name',
 'Price List NFI',
 'Total Net',
 'Bundle Flag',
 'Parent Item',
 'Parent SKU',
 'Harga Cost',
 'Total Harga Cost',
 'Total Net Before PPN',
 'WH',
 'SOREFERENCE2',
 'SO STATUS',
 'SKU WH',
 'Warehouse Quantity',
 'Paid',
 'order_id',
 'Total Produk',
 'Fullfee',
 'Comfee',
 'Tokopedia Ads',
 'Total Produk Prop',
 'Fullfee Prop',
 'Comfee Prop',
 'Total Selcen',
 'BTL Cost']

In [29]:
## run 18
total_trx['Total Produk Prop Adj'] = total_trx['Total Produk Prop']/1.11
total_trx['BTL Cost'] = (total_trx['Total Produk Prop Adj']) - total_trx['Total Net Before PPN']

In [30]:
## run 19
indeks = total_trx[total_trx['Warehouse Origin'] == 'Shop Location'].index.to_list()
total_trx['WH'][indeks] = 'Telkom'

In [31]:
## run 20
tambah_unpaid = pd.read_excel(r'Settlement Project/unpaid order to Andra.xlsx', sheet_name = 'Unpaid to cancel or not found')

tambah_unpaid['Order #'] = tambah_unpaid['Order #'].astype(str)
indeks = total_trx[total_trx['Invoice'].isin(tambah_unpaid['Order #'])].index.to_list()
print(len(indeks))
total_trx['Order Status'][indeks] = 'Cancel'
total_trx['Paid'][indeks] = 'Cancel'

0

In [32]:
## run 21
from datetime import date
total_trx.to_csv(r'Settlement Project\Backup\Realisasi Apr 2023\Final Result\Before Compare/Tokped Testing by Selcen v3 rev.csv', sep = ';', index = False)

#### ======A======

In [ ]:
total_trx_merge = total_trx.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Fullfee Prop' , 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['Invoice', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Fullfee Prop_y' , 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                 'Fullfee Prop_x' : 'Fullfee Prop' , 'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Fullfee Prop' , 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Fullfee Prop_y'][total_trx_null.index] = total_trx_null['Fullfee Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

source2 = source.copy()

source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
source2['Real SKU'][indeks] = '(U)2101809250'

# indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# source2['Real SKU'][indeks] = '2101941250P4'

# indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# source2['Real SKU'][indeks] = '2101809250P4'

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Fullfee Prop_y' , 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                 'Fullfee Prop_x' : 'Fullfee Prop' , 'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Fullfee Prop' , 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Fullfee Prop_y'][total_trx_null.index] = total_trx_null['Fullfee Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

In [ ]:
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

In [ ]:
total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']

In [ ]:
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']

In [ ]:
total_trx_merge['Delta Fullfee Prop'] = total_trx_merge['Fullfee Prop by Selcen'] - total_trx_merge['Fullfee Prop Real Jan']

In [ ]:
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

In [ ]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Tokped Testing by Selcen Compare v2.csv', sep = ';', index = False)

In [ ]:
ord_id = 'INV/20220122/MPL/1970377165'

In [ ]:
selcen_sku[selcen_sku['Invoice'] == ord_id]

In [ ]:
wms_tokped[wms_tokped['SOREFERENCE2'] == ord_id]

# Tokped Cek WMS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Tokped Testing by Selcen Compare v2.csv', sep = ';')

In [ ]:
data[['Year','Month']].drop_duplicates()

In [ ]:
data[['Payment Date', 'Month']].drop_duplicates('Month')

In [ ]:
data['New Date'] = np.nan
data['New Month'] = np.nan
data['New Year'] = np.nan

indeks = data[pd.to_datetime(data['Payment Date']).dt.strftime('%d').astype(int) <= 12].index.to_list()
data['New Date'][indeks] = pd.to_datetime(pd.to_datetime(data['Payment Date'][indeks]).dt.strftime('%Y-%d-%m %H:%M')).dt.day
data['New Month'][indeks] = pd.to_datetime(pd.to_datetime(data['Payment Date'][indeks]).dt.strftime('%Y-%d-%m %H:%M')).dt.month_name()
data['New Year'][indeks] = pd.to_datetime(pd.to_datetime(data['Payment Date'][indeks]).dt.strftime('%Y-%d-%m %H:%M')).dt.year

non_indeks = [x for x in data.index if x not in indeks]
data['New Date'][non_indeks] = pd.to_datetime(data['Payment Date'][non_indeks]).dt.day
data['New Month'][non_indeks] = pd.to_datetime(data['Payment Date'][non_indeks]).dt.month_name()
data['New Year'][non_indeks] = pd.to_datetime(data['Payment Date'][non_indeks]).dt.year

In [ ]:
data[['New Month', 'New Year']].drop_duplicates()

In [ ]:
data[(data[['Invoice', 'Real Nama Produk']].duplicated(keep = False)) & (data['Warehouse Origin'] == 'Shop Location')]

In [ ]:
data[data['Invoice'] == 'INV/20220120/MPL/1964134658'][['Invoice', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Warehouse Quantity', 'Warehouse Origin']]

In [ ]:
pd.options.display.max_columns = 150

In [ ]:
selcen[selcen['Source'] == 'Outbound Report_202201.xlsx']

In [ ]:
selcen

In [ ]:
import pandas as pd

In [ ]:
total_trx = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Tokped Testing by Selcen v3.csv", sep = ';')

In [ ]:
total_trx_full = total_trx.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_full['Invoice'] = total_trx_full['Invoice'].astype(str)

In [ ]:
source#['Invoice'].unique()

### ++++++A+++++++

In [33]:
### run 22
import pandas as pd
total_trx=pd.read_csv(r"Settlement Project\Backup\Realisasi Apr 2023\Final Result\Before Compare\Tokped Testing by Selcen v3 rev.csv", sep = ';')
total_trx.loc[(total_trx['Bundle Name']=='Free L-Men 2 Go - Twin Pack L-Men Daily Dark Chocolate 250gr')&
                    (total_trx['SKU'].isin(['2300542155',2300542155])),'Real Nama Produk']='L-Men Whey Daily Dark Chocolate 250gr'
total_trx.loc[(total_trx['Bundle Name']=='Free L-Men 2 Go - Twin Pack L-Men Daily Dark Chocolate 250gr')&
                    (total_trx['SKU'].isin(['2300542155',2300542155])),'Product Name']='L-Men Whey Daily Dark Chocolate 250gr'
total_trx.loc[(total_trx['Bundle Name']=='Free L-Men 2 Go - Twin Pack L-Men Daily Dark Chocolate 250gr')&
                    (total_trx['SKU'].isin(['2300542155',2300542155])),'Real SKU']='2300551155'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (54,62,70,77,85,93,97,105,108) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [42]:
## run 23
source = pd.read_csv(r"Settlement Project\Backup\Realisasi Mar 2023\Final Result\Raw Unpivoted\CSV\Runningan Tokopedia Mar 23 rev.csv", sep = ';')
# source=pd.read_excel(r"Settlement Project\Backup\Realisasi Mar 2023\Final Result\Raw Unpivoted\Excel\Runningan Tokopedia Mar 23.xlsx")
source=source.rename(columns={'Payment Date':'True datetime'})
source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021)]

# selcen_sku['Order ID'] = selcen_sku['OrderId'].astype(str)
source['Order #'] = source['Invoice'].astype(str)

source['Order #'] = source['Order #'].astype(str)
source['Real SKU'] = source['Real SKU'].astype(str)

# selcen_old = selcen_sku[selcen_sku['OrderId'].isin(source['Order #'])]

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (7,13,15,34,47,54,55,62,63,70,71,78,79,86,87,94,98,106,109,120) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [43]:
## run 24 , ganti prev month
import numpy as np
total_trx_merge = total_trx.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid March','Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Fullfee Prop' , 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['Invoice', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Fullfee Prop_y' , 'Comfee Prop_y','Paid March'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                 'Fullfee Prop_x' : 'Fullfee Prop' , 'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Paid March','Total Net', 'Total Produk Prop', 'Fullfee Prop' , 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Fullfee Prop_y'][total_trx_null.index] = total_trx_null['Fullfee Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid March'][total_trx_null.index] = total_trx_null['Paid March']


total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

source2 = source.copy()

source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
source2['Real SKU'][indeks] = '(U)2101809250'

# indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# source2['Real SKU'][indeks] = '2101941250P4'

# indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# source2['Real SKU'][indeks] = '2101809250P4'

total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Fullfee Prop_y' , 'Comfee Prop_y', 'Paid March'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                 'Fullfee Prop_x' : 'Fullfee Prop' , 'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name','Paid March', 'Total Net', 'Total Produk Prop', 'Fullfee Prop' , 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['Invoice', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Fullfee Prop_y'][total_trx_null.index] = total_trx_null['Fullfee Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid March'][total_trx_null.index] = total_trx_null['Paid March']

In [44]:
### run 25
total_trx_merge['Paid Beda'] = np.nan

indeks = total_trx_merge[total_trx_merge['Paid'] != total_trx_merge['Paid March']].index.to_list()
total_trx_merge['Paid Beda'][indeks] = 'Beda'

total_trx_merge['Paid Beda'] = total_trx_merge['Paid Beda'].fillna('Sama')
# total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'][['Order #','Brand','Real SKU','Month', 'Paid_x', 'Paid_y', 'Paid Beda']]
total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'].groupby(['Year','Month', 'Paid', 'Paid March'], dropna = False)['Invoice'].nunique()

Year    Month     Paid    Paid March
2023.0  April     Paid    NaN           13766
                  Refund  NaN               1
                  Unpaid  NaN             606
        February  Refund  Unpaid            1
        January   Paid    Unpaid            1
        March     Paid    Unpaid         3126
                  Refund  Unpaid            4
Name: Invoice, dtype: int64

In [47]:
# total_trx_merge[(total_trx_merge['Paid Beda'] == 'Beda')&(total_trx_merge['Month']=='July')][['Invoice','SKU','Brand','Paid January']]
# set_jan[set_jan['order_id']=='INV/20220701/MPL/2451912087']

In [45]:
### run 26
total_trx_merge = total_trx_merge.rename(columns = {'Paid' : 'Paid April'})

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})
total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_merge = total_trx_merge.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_merge['Invoice'] = total_trx_merge['Invoice'].astype(str)

In [ ]:
total_trx_merge.head(10)

In [46]:
### run 27
print('start export')
total_trx_merge[total_trx_merge['Year']>2022].to_excel(r"Settlement Project\Backup\Realisasi Apr 2023\Final Result\Raw Unpivoted\Excel\Runningan Tokopedia Apr 23 rev.xlsx", index = False)
print('excel sudah')
total_trx_merge.to_csv(r"Settlement Project\Backup\Realisasi Apr 2023\Final Result\Raw Unpivoted\CSV\Runningan Tokopedia Apr 23 rev.csv", sep = ';', index = False)
# from datetime import date

start export
excel sudah

In [ ]:
### selesai :) ###

In [39]:
total_trx_merge['Pemilik Budget']

0              NaN
1              NaN
2         Internal
3              NaN
4              NaN
            ...
175965         NaN
175966         NaN
175967         NaN
175968         NaN
175969         NaN
Name: Pemilik Budget, Length: 175970, dtype: object

In [61]:
total_trx_merge['Year'].min()

2022.0

In [49]:
total_trx_merge[total_trx_merge['Year']>2022].to_excel(r"Settlement Project\Backup\Realisasi Mar 2023\Final Result\Raw Unpivoted\Excel\Runningan Tokopedia Mar 23 rev1.xlsx", index = False)

In [8]:
df=pd.read_excel("D:\settlement\Code\Settlement Project\Backup\Realisasi Dec 2022\Final Result\Raw Unpivoted\Excel\Runningan Tokopedia Dec 22.xlsx")

In [9]:
df.to_csv("D:\settlement\Code\Settlement Project\Backup\Realisasi Dec 2022\Final Result\Raw Unpivoted\CSV\Runningan Tokopedia Dec 22 backup.csv",sep=';',index=False)

In [93]:
total_trx_merge[(total_trx_merge['Paid July']=='Paid')&(total_trx_merge['Brand'].isin(['HiLo','L-Men','NS','TS',"W'dank"]))].groupby(['Year','Month'])[['Warehouse Quantity','Qty. Invoiced']].sum().reset_index()

     Year     Month  Warehouse Quantity  Qty. Invoiced
0  2022.0     April            112279.5       112367.0
1  2022.0  February             98323.0        98781.0
2  2022.0   January            107804.0       107790.0
3  2022.0      July             66268.0        66259.0
4  2022.0      June             98649.5        98643.5
5  2022.0     March            109034.5       108978.5
6  2022.0       May             92014.0        92004.0

In [54]:
# 
total_trx_merge[total_trx_merge['Invoice']=="INV/20220722/MPL/2507831325"][['Warehouse Origin','Real SKU','Real Nama Produk','Qty. Invoiced','Warehouse Quantity']]

,Warehouse Origin,Real SKU,Real Nama Produk,Qty. Invoiced,Warehouse Quantity
230271,Bandung Soetta,PT40T49T60T61,Tropicana Slim Cookies Package 4 Varian (@5 Sch),2.0,NaN
358532,Bandung Soetta,2104523105,Tropicana Slim Hokkaido Cheese Cookies,2.0,NaN
370726,Bandung Soetta,2104508105,Tropicana Slim Korean Garlic Butter Cookies 5 Sch,2.0,NaN
375179,Bandung Soetta,2104543105,Tropicana Slim Korean Goguma Cookies (5 Sch),2.0,NaN
378194,Bandung Soetta,2104589105,Tropicana Slim Klepon Cookies (5 Sch),2.0,NaN

In [ ]:
import pandas as pd

In [ ]:
total_trx=pd.read_excel("D:\settlement\Code\Settlement Project\Backup\Runningan Tokped By Selcen Jan 2022 - Mar 2022 Rev 3 Add Duplicate Columns.xlsx",sheet_name='Sheet1')

In [ ]:
import requests
import os
data_SKU = pd.read_excel(r"D:\Masterdata\SKU_File\data_SKU.xlsx")

s = requests.Session()
s.get("https://tatanama.pythonanywhere.com")
s.post("https://tatanama.pythonanywhere.com", data = {'username' : 'ecommerce', 'password' : 'ecommerce'})
r = s.get("https://tatanama.pythonanywhere.com/download")

with open(r"D:\Masterdata\SKU_File\Master tatanama.xlsx", 'wb') as output:
    output.write(r.content)

if os.path.isfile(r"D:\Masterdata\SKU_File\Master tatanama.xlsx") :    
    SKU_append = pd.read_excel(r"D:\Masterdata\SKU_File\Master tatanama.xlsx")
    SKU_append.columns = [x.replace('_', ' ') for x in SKU_append.columns]
    data_SKU = data_SKU[~data_SKU['SKU'].astype(str).isin(SKU_append['SKU'].astype(str))]
    data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)

In [ ]:
data_SKU=SKU_append

data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')
# data_SKU['Price List NFI']=data_SKU['Price List NFI']/1.11
data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)#.str.replace('(S)', '', regex = False)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)

In [ ]:
total_trx['Price List NFI'] = total_trx['Price List NFI'].astype(float).astype('int64')
# total_trx['Price List NFI']=total_trx['Price List NFI']/1.11
total_trx['Real SKU'] = total_trx['Real SKU'].astype(str)#.str.replace('(S)', '', regex = False)
# total_trx['Real Nama Produk'] = total_trx['Nama Produk'].astype(str)

In [ ]:
temp2 = total_trx.copy()

print(temp2[temp2['Real SKU'].isnull()]['Real Nama Produk'].nunique())#[['Real Nama Produk', 'Real SKU']]

# list_alias = []
# list_alias_name = []
# for colname in data_SKU.columns:
#     if 'Alias SKU' in colname:
#         list_alias.append(colname)
#     if 'Alias Nama' in colname:
#         list_alias_name.append(colname)

# indeks = temp2[~temp2['SKU'].astype(str).isin(data_SKU['SKU'].astype(str))].index.to_list()


# for i in indeks:
#     for j in list_alias:
#         if str(temp2['SKU'][i]) in data_SKU[j].astype(str).values:
#             idx = data_SKU[str(temp2['SKU'][i]) == data_SKU[j].astype(str)].index.to_list()
#             for k in idx:
#                 if str(temp2['Product Name'][i]) == data_SKU[j.replace('SKU', 'Nama')][k]:
#                     temp2['SKU'][i] = data_SKU['SKU'][k]

# indeks = temp2[~temp2['SKU'].astype(str).isin(data_SKU['SKU'].astype(str))].index.to_list()

# for i in indeks:
#     for j in list_alias_name:
#         if str(temp2['Product Name'][i]).lower() in data_SKU[j].astype(str).str.lower().values:
#             temp2['SKU'][i] = data_SKU['SKU'].loc[str(temp2['Product Name'][i]).lower() == data_SKU[j].astype(str).str.lower()].values[0]

# indeks = temp2[~temp2['SKU'].astype(str).isin(data_SKU['SKU'].astype(str))].index.to_list()

# for i in indeks:
#     if str(temp2['Product Name'][i]).lower() in data_SKU['Nama Produk'].astype(str).str.lower().values:
#         temp2['SKU'][i] = data_SKU['SKU'].loc[str(temp2['Product Name'][i]).lower() == data_SKU['Nama Produk'].astype(str).str.lower()].values[0]


temp2 = temp2.drop(['Price List NFI', 'Total Net', 'Total Net Before PPN', 'Harga Cost'], axis = 1)
data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')

data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)
    
list_col = ['Real SKU', 'Price List NFI', 'Harga Cost']

print(temp2[temp2['Real SKU'].isnull()]['Real Nama Produk'].nunique())

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)

for i in list_col:
    if i == 'Real SKU':
        # temp2[i] = temp_merge[str(i) + '_y']
        pass
    else :
        temp2[i] = temp_merge[str(i)]
    
temp2['Price List NFI'] = pd.to_numeric(temp2['Price List NFI']).astype(int)
temp2['Harga Cost'] = pd.to_numeric(temp2['Harga Cost']).astype(int)
temp2['Qty. Invoiced'] = pd.to_numeric(temp2['Qty. Invoiced']).astype(int)

print(temp2[temp2['Real SKU'].isnull()]['Real Nama Produk'].nunique())

temp2['Total Net'] = temp2['Price List NFI'] * temp2['Qty. Invoiced']
temp2['Total Harga Cost'] = temp2['Harga Cost'] * temp2['Qty. Invoiced']
temp2['Total Net Before PPN'] = temp2['Total Net']/1.11

In [ ]:
temp2[temp2['Real SKU'].isnull()]['Real Nama Produk']#[['Real Nama Produk', 'Real SKU']]

In [ ]:
temp_merge[temp_merge['Price List NFI'].isnull()][['Real SKU', 'Real SKU_y']]

In [ ]:
data_SKU[data_SKU['Real SKU'] == '2104508105']

In [ ]:
temp_merge[['Real SKU_x', 'Real SKU_y']]

# Read Seller Centre