In [1]:
### run 1
import pandas as pd
import os
import numpy as np

selcen = pd.DataFrame()
folder = 'Settlement Project/Shopee/Seller Center/'

for i in os.listdir(folder):
    if r'$' not in i:
        temp = pd.read_excel(folder + str(i))
        temp['Source'] = i
        if len(selcen) != 0:
            temp = temp[~temp['No. Pesanan'].isin(selcen['No. Pesanan'])]
        selcen = selcen.append(temp, ignore_index = True, sort = False)
        print(i)
        true_col = ['No. Pesanan', 'Status Pesanan', 'Alasan Pembatalan',
       'Status Pembatalan/ Pengembalian', 'No. Resi', 'Opsi Pengiriman',
       'Antar ke counter/ pick-up',
       'Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan)',
       'Status Pengiriman', 'Jasa Kirim yang Digunakan',
       'Waktu Pesanan Dibuat', 'Waktu Pengiriman Diatur',
       'Waktu Pembayaran Dilakukan', 'Tanggal Outbound',
       'Tanggal Pesanan Sampai', 'Tanggal Pelepasan Dana Diverifikasi',
       'Waktu Pesanan Selesai', 'Tanggal Pembatalan Selesai',
       'Pesanan yang Dikelola Shopee', 'SKU Induk', 'Nama Produk',
       'Nomor Referensi SKU', 'Nama Variasi', 'Harga Awal',
       'Harga Setelah Diskon', 'Jumlah', 'Total Harga Produk', 'Total Diskon',
       'Diskon Dari Penjual', 'Diskon Dari Shopee', 'Berat Produk',
       'Jumlah Produk di Pesan', 'Total Berat', 'Voucher Ditanggung Penjual',
       'Cashback Koin', 'Voucher Ditanggung Shopee', 'Paket Diskon',
       'Paket Diskon (Diskon dari Shopee)',
       'Paket Diskon (Diskon dari Penjual)', 'Potongan Koin Shopee',
       'Diskon Kartu Kredit', 'Ongkos Kirim Dibayar oleh Pembeli',
       'Ongkos Kirim Pengembalian Barang', 'Total Pembayaran',
       'Perkiraan Ongkos Kirim', 'Catatan dari Pembeli', 'Catatan',
       'Username (Pembeli)', 'Nama Penerima', 'No. Telepon',
       'Alamat Pengiriman', 'Kota/Kabupaten', 'Provinsi', 'Source']
        if temp.columns.to_list() == true_col:
            print('Column Sama')
        else :
            print('Column Beda')
            print([x for x in true_col if x not in temp.columns.to_list()])
            print([x for x in temp.columns.to_list() if x not in true_col])

selcen

Order.all.20211201_20211231_part_1_of_6.xlsx
Column Sama
Order.all.20211201_20211231_part_2_of_6.xlsx
Column Sama
Order.all.20211201_20211231_part_3_of_6.xlsx
Column Sama
Order.all.20211201_20211231_part_4_of_6.xlsx
Column Sama
Order.all.20211201_20211231_part_5_of_6.xlsx
Column Sama
Order.all.20211201_20211231_part_6_of_6.xlsx
Column Sama
Order.all.20220101_20220131_part_1_of_4.xlsx
Column Sama
Order.all.20220101_20220131_part_2_of_4.xlsx
Column Sama
Order.all.20220101_20220131_part_3_of_4.xlsx
Column Sama
Order.all.20220101_20220131_part_4_of_4.xlsx
Column Sama
Order.all.20220201_20220223_part_1_of_4.xlsx
Column Sama
Order.all.20220201_20220223_part_2_of_4.xlsx
Column Sama
Order.all.20220201_20220223_part_3_of_4.xlsx
Column Sama
Order.all.20220201_20220223_part_4_of_4.xlsx
Column Sama
Order.all.20220201_20220228_part_1_of_4.xlsx
Column Sama
Order.all.20220201_20220228_part_2_of_4.xlsx
Column Sama
Order.all.20220201_20220228_part_3_of_4.xlsx
Column Sama
Order.all.20220201_20220228_part_4_of_4.xlsx
Column Sama
Order.all.20220301_20220331_part_1_of_7.xlsx
Column Sama
Order.all.20220301_20220331_part_2_of_7.xlsx
Column Sama
Order.all.20220301_20220331_part_3_of_7.xlsx
Column Sama
Order.all.20220301_20220331_part_4_of_7.xlsx
Column Sama
Order.all.20220301_20220331_part_5_of_7.xlsx
Column Sama
Order.all.20220301_20220331_part_6_of_7.xlsx
Column Sama
Order.all.20220301_20220331_part_7_of_7.xlsx
Column Sama
Order.all.20220401_20220425_part_1_of_7.xlsx
Column Sama
Order.all.20220401_20220425_part_2_of_7.xlsx
Column Sama
Order.all.20220401_20220425_part_3_of_7.xlsx
Column Sama
Order.all.20220401_20220425_part_4_of_7.xlsx
Column Sama
Order.all.20220401_20220425_part_5_of_7.xlsx
Column Sama
Order.all.20220401_20220425_part_6_of_7.xlsx
Column Sama
Order.all.20220401_20220425_part_7_of_7.xlsx
Column Sama
Order.all.20220501_20220524_part_1_of_4.xlsx
Column Sama
Order.all.20220501_20220524_part_2_of_4.xlsx
Column Sama
Order.all.20220501_20220524_part_3_of_4.xlsx
Column Sama
Order.all.20220501_20220524_part_4_of_4.xlsx
Column Sama
Order.all.20220525_20220531_part_1_of_2.xlsx
Column Sama
Order.all.20220525_20220531_part_2_of_2.xlsx
Column Sama
Order.all.20220601_20220626_part_1_of_4.xlsx
Column Sama
Order.all.20220601_20220626_part_2_of_4.xlsx
Column Sama
Order.all.20220601_20220626_part_3_of_4.xlsx
Column Sama
Order.all.20220601_20220626_part_4_of_4.xlsx
Column Sama
Order.all.20220701_20220722_part_1_of_5.xlsx
Column Sama
Order.all.20220701_20220722_part_2_of_5.xlsx
Column Sama
Order.all.20220701_20220722_part_3_of_5.xlsx
Column Sama
Order.all.20220701_20220722_part_4_of_5.xlsx
Column Sama
Order.all.20220701_20220722_part_5_of_5.xlsx
Column Sama
Order.all.20220701_20220722_part_6_of_5.xlsx
Column Sama
Order.all.20230301_20230323_part_1_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230301_20230323_part_2_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230301_20230323_part_3_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230301_20230323_part_4_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230301_20230323_part_5_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230301_20230331_part_6_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230301_20230331_part_7_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230423_part_1_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230423_part_2_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230423_part_3_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230423_part_4_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230423_part_5_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230430_part_1_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230430_part_2_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230430_part_3_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230430_part_4_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230430_part_5_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.20230401_20230430_part_6_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Aug2022_part_1_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Aug2022_part_2_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Aug2022_part_3_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Aug2022_part_4_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Aug2022_part_5_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Aug2022_part_6_of_7.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Aug2022_part_7_of_7.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Des 2022_part_1_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Des 2022_part_2_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Des 2022_part_3_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Des 2022_part_4_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Feb2023_part_1_of_3.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Feb2023_part_2_of_3.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Feb2023_part_3_of_3.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Feb2023_part_4_of_3.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Jan 2023_part_1_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Jan 2023_part_2_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Jan 2023_part_3_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Jan 2023_part_4_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Jan 2023_part_5_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mar2023_part_1_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mar2023_part_2_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mar2023_part_3_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mar2023_part_4_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mar2023_part_5_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mei2023_part_1_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mei2023_part_2_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mei2023_part_3_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Mei2023_part_4_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Nov2022_part_1_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Nov2022_part_2_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Nov2022_part_3_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Nov2022_part_4_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Nov2022_part_5_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Oct2022_part_1_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Oct2022_part_2_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Oct2022_part_3_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Oct2022_part_4_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Oct2022_part_5_of_4.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.order_creation_date.20220426_20220430.xlsx
Column Sama
Order.all.order_creation_date.20220627_20220630.xlsx
Column Sama
Order.all.Sept2022_part_1_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Sept2022_part_2_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Sept2022_part_3_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Sept2022_part_4_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Sept2022_part_5_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']
Order.all.Sept2022_part_6_of_5.xlsx
Column Beda
[]
['Dimiliki Shopee']

,No. Pesanan,Status Pesanan,Alasan Pembatalan,Status Pembatalan/ Pengembalian,No. Resi,Opsi Pengiriman,Antar ke counter/ pick-up,Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan),Status Pengiriman,Jasa Kirim yang Digunakan,...,Catatan dari Pembeli,Catatan,Username (Pembeli),Nama Penerima,No. Telepon,Alamat Pengiriman,Kota/Kabupaten,Provinsi,Source,Dimiliki Shopee
0,211218FCUV0C7P,Selesai,NaN,NaN,002847646906,Reguler (Cashless)-SiCepat REG,Pickup,2021-12-24 19:21,Sudah Dikirim,Paket diterima oleh [ratmi - (YBS) Yang Bersan...,...,NaN,NaN,elisistikomah13,M******I,******56,De******,KAB. TEGAL,JAWA TENGAH,Order.all.20211201_20211231_part_1_of_6.xlsx,NaN
1,211218FD5VGCDX,Selesai,NaN,NaN,SPXID01163129196C,Reguler (Cashless)-Shopee Express Standard,Pickup,2021-12-24 19:26,Sudah Dikirim,[Daan Mogot Hub] Paket anda telah diterima [Li...,...,NaN,NaN,adisti_santoso,L******),******61,Jl******,KOTA JAKARTA BARAT,DKI JAKARTA,Order.all.20211201_20211231_part_1_of_6.xlsx,NaN
2,211218FD5VGCDX,Selesai,NaN,NaN,SPXID01163129196C,Reguler (Cashless)-Shopee Express Standard,Pickup,2021-12-24 19:26,Sudah Dikirim,[Daan Mogot Hub] Paket anda telah diterima [Li...,...,NaN,NaN,adisti_santoso,L******),******61,Jl******,KOTA JAKARTA BARAT,DKI JAKARTA,Order.all.20211201_20211231_part_1_of_6.xlsx,NaN
3,211218FD6T2V5B,Selesai,NaN,NaN,002847645474,Reguler (Cashless)-SiCepat REG,Pickup,2021-12-24 19:26,Sudah Dikirim,Paket telah diterima Mahdalena,...,NaN,NaN,mahdalena030,m******a,******99,KO******,KAB. BANJAR,KALIMANTAN SELATAN,Order.all.20211201_20211231_part_1_of_6.xlsx,NaN
4,211218FD6T2V5B,Selesai,NaN,NaN,002847645474,Reguler (Cashless)-SiCepat REG,Pickup,2021-12-24 19:26,Sudah Dikirim,Paket telah diterima Mahdalena,...,NaN,NaN,mahdalena030,m******a,******99,KO******,KAB. BANJAR,KALIMANTAN SELATAN,Order.all.20211201_20211231_part_1_of_6.xlsx,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628251,220902Q5HQ1G6X,Selesai,NaN,NaN,SPXID029821519579,Hemat-Shopee Xpress Hemat,Pickup,2022-09-06 12:37,Sudah Dikirim,Paket telah diterima Nur Sulasmana Yang bersan...,...,NaN,NaN,mr.deadpool,N******a,******87,Jl******,KOTA BEKASI,JAWA BARAT,Order.all.Sept2022_part_6_of_5.xlsx,False
628252,220902Q5MBW638,Selesai,NaN,NaN,SPXID024328627269,Reguler (Cashless)-Shopee Xpress Standard,Pickup,2022-09-06 12:39,Sudah Dikirim,Paket telah diterima Helen Chou Yang bersangku...,...,NaN,NaN,blanjeonline,H******u,******60,"VILLA MELATI MAS JL. HELICONIA V Blok H5 No.2,...",KOTA TANGERANG SELATAN,BANTEN,Order.all.Sept2022_part_6_of_5.xlsx,False
628253,220902Q5NE6ABV,Selesai,NaN,NaN,SPXID025758287119,Reguler (Cashless)-Shopee Xpress Standard,Pickup,2022-09-06 12:40,Sudah Dikirim,Paket telah diterima Ayang Indriawan Yang bers...,...,NaN,NaN,ayang231,A******n,******19,Kp******,KAB. TASIKMALAYA,JAWA BARAT,Order.all.Sept2022_part_6_of_5.xlsx,False
628254,220902Q5TAJHDW,Selesai,NaN,NaN,SPXID020723459359,Reguler (Cashless)-Shopee Xpress Standard,Pickup,2022-09-06 12:42,Sudah Dikirim,Paket telah diterima Gustiany Yang bersangkutan.,...,NaN,NaN,utiansky,G******y,******08,Lu******,KOTA JAKARTA TIMUR,DKI JAKARTA,Order.all.Sept2022_part_6_of_5.xlsx,False
628255,220902Q5UPGVEM,Selesai,NaN,NaN,SPXID025493321639,Reguler (Cashless)-Shopee Xpress Standard,Pickup,2022-09-06 12:43,Sudah Dikirim,Paket telah diterima Ulfa Agustin Wulandari Ya...,...,NaN,NaN,ulfa_rezky2219,U******i,******88,Jl Wonokitri VIII/59a ( Blakang MallCiputra)( ...,KOTA SURABAYA,JAWA TIMUR,Order.all.Sept2022_part_6_of_5.xlsx,False

In [2]:
# for backup
selcen_cp=selcen.copy()

In [ ]:
# for backup
selcen=selcen_cp.copy()

In [3]:
# selcen[selcen['No. Pesanan']=='2301138G87N9MU']

In [4]:
## for display only
pd.options.display.max_columns = 150

In [5]:
## run 2
selcen = selcen.rename(columns = {'SKU Induk' : 'SKU', 'Jumlah' : 'Qty. Invoiced'})
selcen['Total Pembayaran'] = selcen['Total Pembayaran'].astype(str).str.replace('Rp', '').str.replace('.', '', regex = False)

indeks = selcen[selcen['Waktu Pembayaran Dilakukan'] == '-'].index.to_list()
selcen['Waktu Pembayaran Dilakukan'][indeks] = np.nan

selcen_bayar = selcen[selcen['Waktu Pembayaran Dilakukan'].notnull()]
selcen_batal = selcen[selcen['Waktu Pembayaran Dilakukan'].isnull()]

selcen_bayar['Waktu Pembayaran Dilakukan'] = pd.to_datetime(selcen_bayar['Waktu Pembayaran Dilakukan'], format = '%Y-%m-%d %H:%M', errors='coerce')
selcen_bayar['Year'] = selcen_bayar['Waktu Pembayaran Dilakukan'].dt.year.astype(int)
selcen_bayar['Month'] = selcen_bayar['Waktu Pembayaran Dilakukan'].dt.month_name()

selcen_batal['Waktu Pesanan Dibuat'] = pd.to_datetime(selcen_batal['Waktu Pesanan Dibuat'], format = '%Y-%m-%d', errors='coerce')
selcen_batal['Year'] = selcen_batal['Waktu Pesanan Dibuat'].dt.year.astype(int)
selcen_batal['Month'] = selcen_batal['Waktu Pesanan Dibuat'].dt.month_name()

selcen_new = selcen_bayar.append(selcen_batal, ignore_index = True, sort = False)


## tambahan timo 25 april 2023
selcen_new['true datetime']=pd.to_datetime(selcen_new['Waktu Pesanan Dibuat'])#.dt.strftime('%Y-%d-%m %H:%M')

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [8]:
### run 3
selcen_new = selcen_new[selcen_new['Year'] > 2022]

In [9]:
### run 4 must null
#cek kosong
temp = selcen_new.groupby(['No. Pesanan', 'SKU', 'Nama Produk'], dropna = False)['Source'].nunique().gt(1).reset_index()
temp = temp[temp['Source'] == True]
selcen_new[selcen_new['No. Pesanan'].isin(temp['No. Pesanan'])][['No. Pesanan', 'SKU', 'Nama Produk', 'Qty. Invoiced', 'Source']].sort_values('No. Pesanan')

Empty DataFrame
Columns: [No. Pesanan, SKU, Nama Produk, Qty. Invoiced, Source]
Index: []

In [11]:
### run 5
# cek hanya gift & cek beneran duplicate di 1 file di selcen web tidak
temp = selcen_new.groupby(['No. Pesanan', 'SKU', 'Nama Produk'], dropna = False)['Source'].nunique().gt(1).reset_index()
temp = temp[temp['Source'] == True]

cek=selcen_new[~(selcen_new['No. Pesanan'].isin(temp['No. Pesanan'])) &
          (selcen_new[['No. Pesanan', 'SKU', 'Nama Produk']].duplicated(keep = False)) &
          (selcen_new['SKU'].notnull())&~(selcen_new['Nama Produk'].isin(['[GIFT] - HiLo School Chocolate Ready To Drink 200ml (ED  < 6 bulan)',
                                                                          '[GIFT] - HiLo School Chocolate Ready To Drink 200ml',
                                                                          'HADIAH - HiLo School Cotton Candy 200 ml','HADIAH - L-Men Protein Crunch 20g (12g protein) - Camilan Tinggi Protein Bebas Laktosa']))][['No. Pesanan', 'Status Pesanan','SKU', 'Nama Produk', 'Qty. Invoiced', 'Source']]#.sort_values('No. Pesanan')['Nama Produk'].unique()

print(f'dups :{len(cek)}')
selcennewdup=selcen_new[selcen_new['No. Pesanan'].isin(cek['No. Pesanan'].unique())]
selcen_new=selcen_new[~selcen_new['No. Pesanan'].isin(cek['No. Pesanan'].unique())].append(selcennewdup.drop_duplicates())


cek=selcen_new[~(selcen_new['No. Pesanan'].isin(temp['No. Pesanan'])) &
          (selcen_new[['No. Pesanan', 'SKU', 'Nama Produk']].duplicated(keep = False)) &
          (selcen_new['SKU'].notnull())&~(selcen_new['Nama Produk'].isin(['[GIFT] - HiLo School Chocolate Ready To Drink 200ml (ED  < 6 bulan)',
                                                                          '[GIFT] - HiLo School Chocolate Ready To Drink 200ml',
                                                                          'HADIAH - HiLo School Cotton Candy 200 ml','HADIAH - L-Men Protein Crunch 20g (12g protein) - Camilan Tinggi Protein Bebas Laktosa']))][['No. Pesanan', 'Status Pesanan','SKU', 'Nama Produk', 'Qty. Invoiced', 'Source']]
print(f'dups skrng:{len(cek)}')
cek['Nama Produk'].unique()

dups :0
dups skrng:0

array([], dtype=object)

In [12]:
## run 6
import numpy as np

indeks = selcen_new[selcen_new['SKU'].isnull()].index.to_list()

selcen_new['SKU'] = selcen_new['SKU'].astype(str).str.replace('.0', '', regex = False)
selcen_new['SKU'][indeks] = np.nan

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [13]:
## run 7
cek_dups = selcen_new[(selcen_new[['No. Pesanan', 'SKU']].duplicated(keep = False)) & (selcen_new['SKU'].notnull())].groupby('SKU')['Nama Produk'].unique().reset_index()
( cek_dups.join( pd.DataFrame(cek_dups['Nama Produk'].to_list())
                 .add_prefix('array_') )
        .drop('Nama Produk', axis = 1) ).values

# selcen_new[(selcen_new[['No. Pesanan', 'SKU']].duplicated(keep = False)) & (selcen_new['SKU'].notnull())].groupby(['No. Pesanan','SKU'])['Nama Produk'].unique().reset_index()
# selcen_new[selcen_new['No. Pesanan']=='220125QB27VYSH']
# selcen_new[selcen_new['SKU']=='(B)2HF1403250'][['SKU','Nama Produk']].drop_duplicates()

array([['(B)2309005305',
        'HADIAH - L-Men Protein Crunch 20g (12g protein) - Camilan Tinggi Protein Bebas Laktosa']],
      dtype=object)

In [14]:
## run 8
indeks = selcen_new[selcen_new['Nama Produk'] == "Hilo Swiss Chocolate 10's"].index.to_list()
selcen_new['SKU'][indeks] = '2101891443'

indeks = selcen_new[selcen_new['Nama Produk'] == "NutriSari Milky Orange 40 sachet - Minuman Buah Vitamin C & Vitamin D"].index.to_list()
selcen_new['SKU'][indeks] = '1101588453'

indeks = selcen_new[selcen_new['Nama Produk'] == "W'Dank Bandrek - Ginger Palm Sugar - 10 sachet Renceng"].index.to_list()
selcen_new['SKU'][indeks] = '1101677318'

indeks = selcen_new[selcen_new['Nama Produk'] == "GRATIS L-Men 2 GO - L-Men Lose Weight Avocado Coffee 300g"].index.to_list()
selcen_new['SKU'][indeks] = 'PL25B103'

indeks = selcen_new[selcen_new['Nama Produk'] == "Triple Pack - Tropicana Slim Hokkaido Cheese Cookies (5 Sch) - Snack Bebas Gula, 100 Kalori"].index.to_list()
selcen_new['SKU'][indeks] = '2104523105P3'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [15]:
## run 9
temp2 = selcen_new.copy()

import time
import pandas as pd
import numpy as np
import math

import smtplib 
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import smtplib
import sys
import requests
import os
    
data_SKU = pd.read_excel(r"D:\1. Masterdata\SKU_File\data_SKU.xlsx")

s = requests.Session()
s.get("https://tatanama.pythonanywhere.com")
s.post("https://tatanama.pythonanywhere.com", data = {'username' : 'ecommerce', 'password' : 'ecommerce'})
r = s.get("https://tatanama.pythonanywhere.com/download")

with open(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx", 'wb') as output:
    output.write(r.content)

if os.path.isfile(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx") :    
    SKU_append = pd.read_excel(r"D:\1. Masterdata\SKU_File\Master tatanama.xlsx")
    SKU_append.columns = [x.replace('_', ' ') for x in SKU_append.columns]
    data_SKU = data_SKU[~data_SKU['SKU'].astype(str).isin(SKU_append['SKU'].astype(str))]
    data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)

to_excel = data_SKU.to_excel(r"D:\1. Masterdata\SKU_File\data_SKU.xlsx", index = False)

data_SKU = SKU_append.copy()

In [16]:
## run 10
list_alias = []
list_alias_name = []
for colname in data_SKU.columns:
    if 'Alias SKU' in colname:
        list_alias.append(colname)
    if 'Alias Nama' in colname:
        list_alias_name.append(colname)


for i in indeks:
    for j in list_alias:
        if str(selcen_new['SKU'][i]) in data_SKU[j].astype(str).values:
            idx = data_SKU[str(selcen_new['SKU'][i]) == data_SKU[j].astype(str)].index.to_list()
            for k in idx:
                if str(selcen_new['Nama Produk'][i]) == data_SKU[j.replace('SKU', 'Nama')][k]:
                    selcen_new['SKU'][i] = data_SKU['SKU'][k]

indeks = selcen_new[~selcen_new['SKU'].astype(str).isin(data_SKU['SKU'].astype(str))].index.to_list()

for i in indeks:
    for j in list_alias_name:
        if str(selcen_new['Nama Produk'][i]).lower() in data_SKU[j].astype(str).str.lower().values:
            selcen_new['SKU'][i] = data_SKU['SKU'].loc[str(selcen_new['Nama Produk'][i]).lower() == data_SKU[j].astype(str).str.lower()].values[0]

indeks = selcen_new[~selcen_new['SKU'].astype(str).isin(data_SKU['SKU'].astype(str))].index.to_list()

for i in indeks:
    if str(selcen_new['Nama Produk'][i]).lower() in data_SKU['Nama Produk'].astype(str).str.lower().values:
        selcen_new['SKU'][i] = data_SKU['SKU'].loc[str(selcen_new['Nama Produk'][i]).lower() == data_SKU['Nama Produk'].astype(str).str.lower()].values[0]

In [17]:
### run 11
sku_shopee = pd.read_excel(r"Settlement Project\Shopee\shopee_sku_mapping.xlsx")

selcen_null = selcen_new[(selcen_new['SKU'].isnull()) |
                     (~selcen_new['SKU'].astype(str).isin(data_SKU['SKU'].astype(str)))]
selcen_null = selcen_null.merge(sku_shopee[['item', 'real sku']].drop_duplicates('item'), how = 'left', left_on = 'Nama Produk', right_on = 'item').set_index(selcen_null.index)
selcen_new['SKU'][selcen_null.index] = selcen_null['real sku']

selcen_new_null = selcen_new[(selcen_new['SKU'].isnull()) |
                     (~selcen_new['SKU'].astype(str).isin(data_SKU['SKU'].astype(str)))]
selcen_new_not = selcen_new[(selcen_new['SKU'].notnull()) &
                     (selcen_new['SKU'].astype(str).isin(data_SKU['SKU'].astype(str)))]
selcen_new_null = selcen_new_null.merge(selcen_new_not[['SKU', 'Nama Produk']].drop_duplicates('Nama Produk'), how = 'left', on = 'Nama Produk').set_index(selcen_new_null.index)
selcen_new['SKU'][selcen_new_null.index] = selcen_new_null['SKU_y']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
## run 12
sku_shopee = pd.read_excel(r'Settlement Project/Shopee/SKU Blank.xlsx')

selcen_new_null = selcen_new[(selcen_new['SKU'].isnull()) |
                     (~selcen_new['SKU'].astype(str).isin(data_SKU['SKU'].astype(str)))]
selcen_new_null = selcen_new_null.merge(sku_shopee[['Real SKU', 'Nama Produk']].drop_duplicates('Nama Produk'), how = 'left', on = 'Nama Produk').set_index(selcen_new_null.index)
selcen_new['SKU'][selcen_new_null.index] = selcen_new_null['Real SKU']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [19]:
### run 12.5 - yang sku variasi jadi sku utama
selcen_new.loc[(selcen_new['SKU'].isnull())&(selcen_new['Nomor Referensi SKU'].notnull()),'SKU']=selcen_new['Nomor Referensi SKU']

In [20]:
## run 13 - harus null ya 
selcen_new[(selcen_new['SKU'].isnull()) |
                     (~selcen_new['SKU'].astype(str).isin(data_SKU['SKU'].astype(str)))].groupby(['SKU', 'Nama Produk'], dropna = False)['No. Pesanan'].first().reset_index().values

array([], shape=(0, 3), dtype=object)

In [21]:
### run 13.1

from datetime import datetime,timedelta
listjanjian=requests.get('http://event.l-men.com/apiv1?type=janjian')
for i in listjanjian.json():
    sku=i['realsku']
    print(sku)
    start=datetime.fromtimestamp(int(i['startdate']/1000)).replace(hour=0)
    end=datetime.fromtimestamp(int(i['enddate']/1000)).replace(hour=23)
    print(i['notes'])
    selcen_new.loc[(selcen_new['SKU']==sku)&(selcen_new['true datetime']>=start)&(selcen_new['true datetime']<end),'Pemilik Budget']=i['notes']
    print('=====')
    # print(str(datetime.fromtimestamp(int(i['enddate']/1000)).replace(hour=0)))

2T00803164
Launching tahap 2
=====
2T00803164P3
Launching tahap 2
=====
2T02703229P2
Launching
=====
PT25T74
Launching
=====
2T02703229
Launching tahap 2
=====
2104115110
Launching tahap 2
=====
2104115110P2
Launching tahap 2
=====
2104148024
Launching tahap 2
=====
2104148024P2
Launching tahap 2
=====
1N01402250P24
Marketing
=====
1N01402250P4
Marketing
=====
2104010270
Marketing
=====
1101909331
Marketing
=====
2T00803164P2
Marketing
=====
2T00803164P3
Marketing
=====
2HF0114021
Launching tahap 2
=====
2101751112
Marketing
=====
2101751112P2
Marketing
=====
2101700166P2
Marketing
=====
2101700166
Marketing
=====
2101384106
Internal
=====
2101384106P3
Internal
=====
2105055180P2
Internal
=====
2104523105P3
Internal
=====
2104508105P3
Internal
=====
2104543105P3
Internal
=====
2104589105P3
Internal
=====
2104241210P2
Internal
=====
2106386249P24
Internal
=====
2101000195
Internal
=====
2101151180
Internal
=====
2101150180
Internal
=====
2101200180
Internal
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102500125P2
Internal
=====
2102500130P2
Internal
=====
2102900125
Internal
=====
2102900130
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2309005305P20
Marketing
=====
2T01813126P2
Launching
=====
PH22T17
Marketing
=====
PH22T41
Marketing
=====
PH19H22
Launching
=====
PH22H95G277
Marketing
=====
1101685360
Marketing
=====
1101656360
Marketing
=====
2101847360
Marketing
=====
2101845360
Marketing
=====
2101819360
Marketing
=====
2101888360
Marketing
=====
PH19H103
Launching
=====
PH35H103
Launching
=====
2305551028
Launching
=====
2HF0113021
Launching tahap 2
=====
2HF0112021
Launching tahap 2
=====
1N01402250P4
Internal
=====
1N01402250P24
Internal
=====
2T00803164
Internal
=====
2T00803164P2
Internal
=====
2T00803164P3
Internal
=====
1101686318
Marketing
=====
1101694318
Marketing
=====
1N01402250P4
Marketing
=====
2T00803164
Marketing
=====
1N01402250P24
Marketing
=====
2T00803164P2
Marketing
=====
2T00803164P3
Marketing
=====
1101618318P2
Marketing
=====
1101618318
Marketing
=====
2309005305
Marketing
=====
2309005305P5
Marketing
=====
2309005305P10
Marketing
=====
2101700166
Marketing
=====
2101700166
Marketing
=====
2101700166P2
Marketing
=====
2101700166P2
Marketing
=====
2309005305P20
Marketing
=====
2309005305P20
Marketing
=====
(E)2101469180
Marketing
=====
1N01402250P4
Marketing
=====
1N01402250P24
Marketing
=====
2T01402249P4
Launching
=====
2T01402249P24
Launching
=====
1100534034
Launching
=====
2HC0109021
Launching tahap 2
=====
2305551028
Launching tahap 2
=====
PH19H22
Marketing
=====
PH22T41
Marketing
=====
PH22T17
Marketing
=====
(E)2101487148
Marketing
=====
(E)2101487148
Marketing
=====
2T01813126
Launching tahap 2
=====
2T01813126P2
Launching tahap 2
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102500125P2
Internal
=====
2102900125
Internal
=====
2102500130P2
Internal
=====
2102900130
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2101150180
Internal
=====
2101151180
Internal
=====
2101200180
Internal
=====
2101000195
Internal
=====
2101000195P2
Internal
=====
2101150180P2
Internal
=====
2101151180P2
Internal
=====
2101200180P2
Internal
=====
2304097159
Internal
=====
2104394210P2
Internal
=====
2104394210
Internal
=====
PT26T54
Internal
=====
2T01705164P2
Launching
=====
2305551028
Launching tahap 2
=====
PH22H95G277
Marketing
=====
1101665318
Marketing
=====
1101677318
Marketing
=====
1101653318
Marketing
=====
1101618318
Marketing
=====
2HH0813443P2
Launching
=====
2HF0114021P2
Marketing
=====
2LL1402249P4
Launching
=====
2LL1402249P24
Launching
=====
2LM0801029
Launching
=====
PL32L33
Launching
=====
2HF0114021
Marketing
=====
2101651195
Marketing
=====
2101651195P2
Marketing
=====
2101453195
Marketing
=====
2305551028
Internal
=====
2101453195P2
Marketing
=====
2101486195
Marketing
=====
2101486195P2
Marketing
=====
2309005305P20
Marketing
=====
(E)1101505453
Internal
=====
2304051180
Internal
=====
2LD0905181
Internal
=====
2304008180
Internal
=====
2TA0102180
Launching tahap 2
=====
2102500125
Internal
=====
2102500130
Internal
=====
2102900125
Internal
=====
2102000180
Internal
=====
2102500125P2
Internal
=====
2102500130P2
Internal
=====
2102900125P2
Internal
=====
2102900130P2
Internal
=====
2102000180P2
Internal
=====
2102900130
Internal
=====
2304558112
Internal
=====
2304515112
Internal
=====
2304576112
Internal
=====
2304558112P2
Internal
=====
2304515112C2
Internal
=====
2304576112P2
Internal
=====
2304051180P2
Internal
=====
2LD0905181P2
Internal
=====
2304008180P2
Internal
=====
1N03301456
Launching
=====
2T01402249P24
Launching tahap 2
=====
2LM0801029
Launching tahap 2
=====
1101685360
Marketing
=====
1101656360
Marketing
=====
2T01402249P24
Internal
=====
2106386249P24
Internal
=====
2106386249P12
Internal
=====
2101888360
Marketing
=====
2101819360
Marketing
=====
2101845360
Marketing
=====
2101847360
Marketing
=====
2305551028P3
Internal
=====
2305551028
Internal
=====
2305507288
Internal
=====
2305545288
Internal
=====
2305559288
Internal
=====
2305584288
Internal
=====
2105028180P2
Internal
=====
1N01402250P24
Internal
=====
2LM0801029P2
Marketing
=====
PT25T41
Internal
=====
2104228230P2
Internal
=====
2104251230P2
Internal
=====
2T01402249P12
Internal
=====

In [ ]:
selcen_new[selcen_new['Pemilik Budget'].notnull()][['No. Pesanan','SKU','Waktu Pesanan Dibuat','true datetime','Pemilik Budget']]

In [22]:
## run 14
for i in ['Harga Awal','Harga Setelah Diskon', 'Total Harga Produk', 'Total Diskon',
          'Diskon Dari Penjual', 'Diskon Dari Shopee','Voucher Ditanggung Penjual',
       'Cashback Koin', 'Voucher Ditanggung Shopee','Paket Diskon (Diskon dari Shopee)',
       'Paket Diskon (Diskon dari Penjual)','Diskon Kartu Kredit', 'Ongkos Kirim Dibayar oleh Pembeli',
       'Ongkos Kirim Pengembalian Barang', 'Total Pembayaran',
       'Perkiraan Ongkos Kirim']:
    selcen_new[i] = selcen_new[i].astype(str).str.replace('Rp', '').str.replace('.', '', regex = False).str.strip().astype(float)

In [23]:
## run 15
temp2 = selcen_new.copy()
temp2['SKU']=temp2['SKU'].astype(str)###tambahan 30 mei
temp2 = temp2.rename(columns = {'Nama Produk' : 'Product Name'})

data_SKU.loc[data_SKU['Price List NFI'].isin(['-']), 'Price List NFI'] = 0
data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')

data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)

list_col = ['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand']

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)
for i in list_col:
    temp2[i] = temp_merge[str(i)]
    
list_col = ['SKU'] + data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Cost 7')+1].to_list()
temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['SKU']), how = 'left', left_on = 'Real SKU', right_on = 'SKU').set_index(temp2.index)
list_pcs = [x for x in temp_merge.columns if 'PCS' in x]
for i in list_pcs:
    temp_merge[i] = temp_merge[i] * temp_merge['Qty. Invoiced']

list_col = data_SKU.columns[data_SKU.columns.get_loc('Produk 1'):data_SKU.columns.get_loc('Harga Cost 7')+1].to_list()    
for i in list_col:
    temp2[i] = temp_merge[str(i)]
    
list_col = ['Real SKU', 'Price List NFI', 'Harga Cost']

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)
for i in list_col:
    if i == 'Real SKU':
        temp2[i] = temp_merge[str(i) + '_y']
    else :
        temp2[i] = temp_merge[str(i)]
    
temp2['Price List NFI'] = pd.to_numeric(temp2['Price List NFI']).astype(int)
temp2['Harga Cost'] = pd.to_numeric(temp2['Harga Cost']).astype(int)
temp2['Qty. Invoiced'] = pd.to_numeric(temp2['Qty. Invoiced']).astype(int)

temp2['Total Net'] = temp2['Price List NFI'] * temp2['Qty. Invoiced']
temp2['Total Harga Cost'] = temp2['Harga Cost'] * temp2['Qty. Invoiced']
temp2['Total Net Before PPN'] = temp2['Total Net']/1.11

temp2['Voucher Ditanggung Penjual'] = temp2['Voucher Ditanggung Penjual'] * temp2['Total Net Before PPN']/temp2.groupby(['No. Pesanan'])['Total Net Before PPN'].transform('sum')
temp2['Total Pembayaran'] = temp2['Total Pembayaran'] * temp2['Total Net Before PPN']/temp2.groupby(['No. Pesanan'])['Total Net Before PPN'].transform('sum')
temp2['Perkiraan Ongkos Kirim'] = temp2['Perkiraan Ongkos Kirim'] * temp2['Total Net Before PPN']/temp2.groupby(['No. Pesanan'])['Total Net Before PPN'].transform('sum')

    
print("Unbundling")
data_bundle1 = temp2[~temp2['Produk 1'].isnull()]
data_bundle1['Bundle Name'] = data_bundle1['Product Name']
data_bundle1['Product Name'] = data_bundle1['Produk 1']
data_bundle1['SKU'] = data_bundle1['SKU Produk 1']
data_bundle1['Qty. Invoiced'] = data_bundle1['PCS Produk 1']
data_bundle1['Price List NFI'] = data_bundle1['Price List NFI 1']
data_bundle1['Total Net'] = data_bundle1['Price List NFI 1']
data_bundle1['Bundle Flag'] = np.nan

data_bundle2 = temp2[~temp2['Produk 2'].isnull()]
data_bundle2['Bundle Name'] = data_bundle2['Product Name']
data_bundle2['Product Name'] = data_bundle2['Produk 2']
data_bundle2['SKU'] = data_bundle2['SKU Produk 2']
data_bundle2['Qty. Invoiced'] = data_bundle2['PCS Produk 2']
data_bundle2['Price List NFI'] = data_bundle2['Price List NFI 2']
data_bundle2['Total Net'] = data_bundle2['Price List NFI 2'] 
data_bundle2['Bundle Flag'] = np.nan

data_bundle3 = temp2[~temp2['Produk 3'].isnull()]
data_bundle3['Bundle Name'] = data_bundle3['Product Name']
data_bundle3['Product Name'] = data_bundle3['Produk 3']
data_bundle3['SKU'] = data_bundle3['SKU Produk 3']
data_bundle3['Qty. Invoiced'] = data_bundle3['PCS Produk 3']
data_bundle3['Price List NFI'] = data_bundle3['Price List NFI 3']
data_bundle3['Total Net'] = data_bundle3['Price List NFI 3'] 
data_bundle3['Bundle Flag'] = np.nan

data_bundle4 = temp2[~temp2['Produk 4'].isnull()]
data_bundle4['Bundle Name'] = data_bundle4['Product Name']
data_bundle4['Product Name'] = data_bundle4['Produk 4']
data_bundle4['SKU'] = data_bundle4['SKU Produk 4']
data_bundle4['Qty. Invoiced'] = data_bundle4['PCS Produk 4']
data_bundle4['Price List NFI'] = data_bundle4['Price List NFI 4']
data_bundle4['Total Net'] = data_bundle4['Price List NFI 4'] 
data_bundle4['Bundle Flag'] = np.nan

data_bundle5 = temp2[~temp2['Produk 5'].isnull()]
data_bundle5['Bundle Name'] = data_bundle5['Product Name']
data_bundle5['Product Name'] = data_bundle5['Produk 5']
data_bundle5['SKU'] = data_bundle5['SKU Produk 5']
data_bundle5['Qty. Invoiced'] = data_bundle5['PCS Produk 5']
data_bundle5['Price List NFI'] = data_bundle5['Price List NFI 5']
data_bundle5['Total Net'] = data_bundle5['Price List NFI 5']
data_bundle5['Bundle Flag'] = np.nan

data_bundle6 = temp2[~temp2['Produk 6'].isnull()]
data_bundle6['Bundle Name'] = data_bundle6['Product Name']
data_bundle6['Product Name'] = data_bundle6['Produk 6']
data_bundle6['SKU'] = data_bundle6['SKU Produk 6']
data_bundle6['Qty. Invoiced'] = data_bundle6['PCS Produk 6']
data_bundle6['Price List NFI'] = data_bundle6['Price List NFI 6']
data_bundle6['Total Net'] = data_bundle6['Price List NFI 6']
data_bundle6['Bundle Flag'] = np.nan

data_bundle7 = temp2[~temp2['Produk 7'].isnull()]
data_bundle7['Bundle Name'] = data_bundle7['Product Name']
data_bundle7['Product Name'] = data_bundle7['Produk 7']
data_bundle7['SKU'] = data_bundle7['SKU Produk 7']
data_bundle7['Qty. Invoiced'] = data_bundle7['PCS Produk 7']
data_bundle7['Price List NFI'] = data_bundle7['Price List NFI 7']
data_bundle7['Total Net'] = data_bundle7['Price List NFI 7']
data_bundle7['Bundle Flag'] = np.nan

data_bundle = data_bundle1.append([data_bundle2, data_bundle3, data_bundle4, data_bundle5, data_bundle6, data_bundle7], ignore_index = True, sort = False)
data_bundle['SKU'] = data_bundle['SKU'].astype(str)
data_bundle['SKU'] = data_bundle['SKU'].str.replace('\.0$', '', regex = True)
data_bundle[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']] = data_bundle.merge(data_SKU[['Real SKU', 'Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU')[['Real SKU_y', 'Nama Produk', 'Brand_y', 'Sub Brand_y', 'Parent Item', 'Parent SKU']]

list_col = ['Real SKU', 'Price List NFI', 'Harga Cost']

data_bundle = data_bundle.drop(['Price List NFI', 'Harga Cost'], axis = 1)

temp_merge = data_bundle.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(data_bundle.index)
for i in list_col:
    if i == 'Real SKU':
        data_bundle[i] = temp_merge[str(i) + '_y']
    else :
        data_bundle[i] = temp_merge[str(i)]

data_bundle['Price List NFI'] = pd.to_numeric(data_bundle['Price List NFI']).astype(int)
data_bundle['Harga Cost'] = pd.to_numeric(data_bundle['Harga Cost']).astype(int)
data_bundle['Qty. Invoiced'] = pd.to_numeric(data_bundle['Qty. Invoiced']).astype(int)

data_bundle['Total Net'] = data_bundle['Price List NFI'] * data_bundle['Qty. Invoiced']
data_bundle['Total Harga Cost'] = data_bundle['Harga Cost'] * data_bundle['Qty. Invoiced']
data_bundle['Total Net Before PPN'] = data_bundle['Total Net']/1.11

for i in ['Harga Awal',
   'Harga Setelah Diskon', 'Total Harga Produk', 'Total Diskon',
   'Diskon Dari Penjual', 'Diskon Dari Shopee','Voucher Ditanggung Penjual',
   'Cashback Koin', 'Voucher Ditanggung Shopee','Paket Diskon (Diskon dari Shopee)',
   'Paket Diskon (Diskon dari Penjual)','Diskon Kartu Kredit', 'Ongkos Kirim Dibayar oleh Pembeli',
   'Ongkos Kirim Pengembalian Barang', 'Total Pembayaran',
   'Perkiraan Ongkos Kirim']:
    data_bundle[i] = data_bundle[i].fillna(0) * data_bundle['Total Net Before PPN']/data_bundle.groupby(['No. Pesanan', 'Bundle Name'])['Total Net Before PPN'].transform('sum')

print("Pricing")
temp2 = temp2.append(data_bundle, ignore_index = True, sort = False)

temp2['Price List NFI'] = pd.to_numeric(temp2['Price List NFI']).astype(int)
temp2['Harga Cost'] = pd.to_numeric(temp2['Harga Cost']).astype(int)
temp2['Qty. Invoiced'] = pd.to_numeric(temp2['Qty. Invoiced']).astype(int)

temp2['Total Net'] = temp2['Price List NFI'] * temp2['Qty. Invoiced']
temp2['Total Harga Cost'] = temp2['Harga Cost'] * temp2['Qty. Invoiced']
temp2['Total Net Before PPN'] = temp2['Total Net']/1.11

Unbundling

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:97: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:100: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:101: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Pricing

In [24]:
## run 16 harus null
temp2[temp2['Price List NFI'].isnull()]

Empty DataFrame
Columns: [No. Pesanan, Status Pesanan, Alasan Pembatalan, Status Pembatalan/ Pengembalian, No. Resi, Opsi Pengiriman, Antar ke counter/ pick-up, Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan), Status Pengiriman, Jasa Kirim yang Digunakan, Waktu Pesanan Dibuat, Waktu Pengiriman Diatur, Waktu Pembayaran Dilakukan, Tanggal Outbound, Tanggal Pesanan Sampai, Tanggal Pelepasan Dana Diverifikasi, Waktu Pesanan Selesai, Tanggal Pembatalan Selesai, Pesanan yang Dikelola Shopee, SKU, Product Name, Nomor Referensi SKU, Nama Variasi, Harga Awal, Harga Setelah Diskon, Qty. Invoiced, Total Harga Produk, Total Diskon, Diskon Dari Penjual, Diskon Dari Shopee, Berat Produk, Jumlah Produk di Pesan, Total Berat, Voucher Ditanggung Penjual, Cashback Koin, Voucher Ditanggung Shopee, Paket Diskon, Paket Diskon (Diskon dari Shopee), Paket Diskon (Diskon dari Penjual), Potongan Koin Shopee, Diskon Kartu Kredit, Ongkos Kirim Dibayar oleh Pembeli, Ongkos Kirim Pengembalian Barang, Total Pembayaran, Perkiraan Ongkos Kirim, Catatan dari Pembeli, Catatan, Username (Pembeli), Nama Penerima, No. Telepon, Alamat Pengiriman, Kota/Kabupaten, Provinsi, Source, Dimiliki Shopee, Year, Month, true datetime, Pemilik Budget, Real SKU, Real Nama Produk, Brand, Sub Brand, Produk 1, SKU Produk 1, PCS Produk 1, Price List NFI 1, Subtotal Produk 1, Harga Display 1, Harga Cost 1, Produk 2, SKU Produk 2, PCS Produk 2, Price List NFI 2, Subtotal Produk 2, Harga Display 2, Harga Cost 2, Produk 3, SKU Produk 3, PCS Produk 3, Price List NFI 3, Subtotal Produk 3, Harga Display 3, Harga Cost 3, Produk 4, SKU Produk 4, PCS Produk 4, Price List NFI 4, Subtotal Produk 4, Harga Display 4, Harga Cost 4, Produk 5, SKU Produk 5, PCS Produk 5, Price List NFI 5, Subtotal Produk 5, Harga Display 5, Harga Cost 5, Produk 6, SKU Produk 6, ...]
Index: []

In [25]:
### run 17
selcen_sku = temp2.copy()

In [26]:
### run 18 must null
temp = selcen_sku.groupby(['No. Pesanan', 'SKU', 'Product Name'], dropna = False)['Source'].nunique().gt(1).reset_index()
temp = temp[temp['Source'] == True]

selcen_sku[(selcen_sku['No. Pesanan'].isin(temp['No. Pesanan'])) &
           (selcen_sku['Bundle Name'].isnull()) &
          (selcen_sku[['No. Pesanan', 'SKU', 'Product Name']].duplicated(keep = False)) &
          (selcen_sku['SKU'].notnull())][['No. Pesanan', 'Status Pesanan','SKU', 'Product Name', 'Qty. Invoiced', 'Source']].sort_values('No. Pesanan')

Empty DataFrame
Columns: [No. Pesanan, Status Pesanan, SKU, Product Name, Qty. Invoiced, Source]
Index: []

In [42]:

# temp = selcen_sku.groupby(['No. Pesanan', 'SKU', 'Product Name'], dropna = False)['Source'].nunique().gt(1).reset_index()
# temp = temp[temp['Source'] == True]

# dups = selcen_sku[selcen_sku['No. Pesanan'].isin(temp['No. Pesanan'])]
# non_dups = selcen_sku[selcen_sku['No. Pesanan'].isin(temp['No. Pesanan'])]

# dups = dups.drop_duplicates(['No. Pesanan', 'SKU', 'Product Name'], keep = 'last')

# temp = dups.groupby(['No. Pesanan', 'SKU', 'Product Name'], dropna = False)['Source'].nunique().gt(1).reset_index()
# temp = temp[temp['Source'] == True]
# print(temp)

# if (len(temp) == 0):
#     selcen_sku = non_dups.append(dups, ignore_index= True, sort = False)
    
#     temp = selcen_sku.groupby(['No. Pesanan', 'SKU', 'Product Name'], dropna = False)['Source'].nunique().gt(1).reset_index()
#     temp = temp[temp['Source'] == True]

#     selcen_sku[(selcen_sku['No. Pesanan'].isin(temp['No. Pesanan'])) &
#                (selcen_sku['Bundle Name'].isnull()) &
#               (selcen_sku[['No. Pesanan', 'SKU', 'Product Name']].duplicated(keep = False)) &
#               (selcen_sku['SKU'].notnull())][['No. Pesanan', 'Status Pesanan','SKU', 'Product Name', 'Qty. Invoiced', 'Source']].sort_values('No. Pesanan')

In [27]:
### run 19
j_conv = pd.read_excel("Settlement Project\Rumus Realisasi.xlsx", sheet_name = 'Paket Brand')
j_conv = j_conv.iloc[:,:5]
j_conv = j_conv.rename(columns = {'SKU' : 'Real SKU', 'SKU.1' : 'SKU Produk'})
j_conv = j_conv[j_conv['Real SKU'].notnull()]
j_conv['SKU Produk'] = j_conv['SKU Produk'].astype(str).str.replace('.0', '',regex = False)

temp_all = selcen_sku.copy()

temp_all['Real SKU'] = temp_all['Real SKU'].astype(str)
j_conv['Real SKU'] = j_conv['Real SKU'].astype(str)

temp_all = temp_all.merge(j_conv, how = 'left', on = 'Real SKU')

paket_j = temp_all[temp_all['SKU Produk'].notnull()]

paket_j['Bundle Name'] = paket_j['Product Name']
paket_j['Product Name'] = paket_j['Name']
paket_j['SKU'] = paket_j['SKU Produk']
paket_j['Qty. Invoiced'] = paket_j['Qty. Invoiced'] * paket_j['Konversi ke UOM'].astype(float)
paket_j['Bundle Flag'] = np.nan

# import time
# import pandas as pd
# import numpy as np
# import math

# import smtplib 
# from email.mime.text import MIMEText
# from email.mime.application import MIMEApplication
# from email.mime.multipart import MIMEMultipart
# from smtplib import SMTP
# import smtplib
# import sys
# import requests
# import os
    

# print('A')
# data_SKU = pd.read_excel(r'C:\Users\andra.miftah\Demo 9\SKU_File/data_SKU.xlsx')
# print('A')
# s = requests.Session()
# s.get("https://tatanama.pythonanywhere.com")
# s.post("https://tatanama.pythonanywhere.com", data = {'username' : 'ecommerce', 'password' : 'ecommerce'})
# r = s.get("https://tatanama.pythonanywhere.com/download")

# with open(r'C:\Users\andra.miftah\Demo 9\SKU_File/Master tatanama.xlsx', 'wb') as output:
#     output.write(r.content)

# if os.path.isfile(r'C:\Users\andra.miftah\Demo 9\SKU_File/Master tatanama.xlsx') :    
#     SKU_append = pd.read_excel(r'C:\Users\andra.miftah\Demo 9\SKU_File/Master tatanama.xlsx')
#     SKU_append.columns = [x.replace('_', ' ') for x in SKU_append.columns]
#     data_SKU = data_SKU[~data_SKU['SKU'].astype(str).isin(SKU_append['SKU'].astype(str))]
#     data_SKU = data_SKU.append(SKU_append, ignore_index = True, sort = False)
    
data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)
if 'Real SKU_y' in paket_j.columns:
    paket_j = paket_j.drop('Real SKU_y', axis = 1)
paket_j['SKU'] = paket_j['SKU'].astype(str)
paket_j[['Real SKU', 'Real Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU', 'Price List NFI']] = paket_j.merge(data_SKU[['Real SKU', 'Nama Produk', 'Brand', 'Sub Brand', 'Parent Item', 'Parent SKU', 'Price List NFI']].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(paket_j.index)[['Real SKU_y', 'Nama Produk', 'Brand_y', 'Sub Brand_y', 'Parent Item_y', 'Parent SKU_y', 'Price List NFI_y']]

paket_j['Total Net'] = paket_j['Price List NFI'] * paket_j['Qty. Invoiced']

for i in ['Harga Awal',
   'Harga Setelah Diskon', 'Total Harga Produk', 'Total Diskon',
   'Diskon Dari Penjual', 'Diskon Dari Shopee','Voucher Ditanggung Penjual',
   'Cashback Koin', 'Voucher Ditanggung Shopee','Paket Diskon (Diskon dari Shopee)',
   'Paket Diskon (Diskon dari Penjual)','Diskon Kartu Kredit', 'Ongkos Kirim Dibayar oleh Pembeli',
   'Ongkos Kirim Pengembalian Barang', 'Total Pembayaran',
   'Perkiraan Ongkos Kirim']:
    paket_j[i] = paket_j[i] * paket_j['Total Net']/paket_j.groupby(['No. Pesanan', 'Bundle Name'])['Total Net'].transform('sum')

paket_j = paket_j.drop(['Nama Paket', 'SKU Produk', 'Name', 'Konversi ke UOM'], axis = 1)
selcen_sku = selcen_sku.append(paket_j, ignore_index = True, sort = False)
indeks = selcen_sku[selcen_sku['Product Name'].isin(paket_j['Bundle Name'])].index.to_list()
selcen_sku['Brand'][indeks] = 'Bundle'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [28]:
## run for check, jika ingin di unbundling isi rumus realisasi xlsx sheet paket brand
selcen_sku[(selcen_sku['Real SKU'].str.contains('J'))&~(selcen_sku['Real SKU'].isin(j_conv['Real SKU'].unique()))][['Real SKU','Real Nama Produk']].drop_duplicates()

Empty DataFrame
Columns: [Real SKU, Real Nama Produk]
Index: []

In [29]:
### run 20
indeks = selcen_sku[(selcen_sku['Real SKU'].astype(str).str.contains('^\(B\)', regex = True)) &
      (~selcen_sku['Brand'].isin(['Bonus Produk', 'Gimmick']))].index.to_list()

selcen_sku['Brand'][indeks] = 'Bonus Produk'

indeks = selcen_sku[(selcen_sku['Real SKU'].astype(str).str.contains('^\(U\)', regex = True)) &
      (~selcen_sku['Brand'].isin(['Bonus Produk', 'Gimmick']))].index.to_list()

selcen_sku['Brand'][indeks] = 'Bonus Produk'

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [46]:
# selcen_sku[selcen_sku['No. Pesanan'] == '2205230ABVF4VX'][['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Price List NFI','Qty. Invoiced','Total Net']]

# Old NFI

In [30]:
### run 21
source = pd.read_csv("Settlement Project\Backup\Realisasi Jan 2022\Runningan Shopee Jan 2021 - Jan 2022 Rev 1.csv", sep = ';')

source['True datetime'] = pd.to_datetime(source['True datetime'])
source = source[(source['Year'] > 2021) & (source['True datetime']<'2022-02-01')]

selcen_old = selcen_sku[selcen_sku['No. Pesanan'].isin(source['Order #'])]

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

selcen_old_merge = selcen_old.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Price List NFI', 'Qty. Invoiced']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']) 

selcen_old_null = selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()]

selcen_old_null = selcen_old_null.drop(['Order #', 'Price List NFI_y'], axis = 1)
selcen_old_null = selcen_old_null.rename(columns = {'Price List NFI_x' : 'Price List NFI'})

selcen_old_null = selcen_old_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Price List NFI']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name', 'Price List NFI']), how = 'left', left_on = ['No. Pesanan', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(selcen_old_null.index) 
selcen_old_merge['Price List NFI_y'][selcen_old_null.index] = selcen_old_null['Price List NFI_y']

selcen_old_null = selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()]

source2 = source.copy()

# source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# source2['Real SKU'][indeks] = '(U)2101809250'

# indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# source2['Real SKU'][indeks] = '2101941250P4'

# indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# source2['Real SKU'][indeks] = '2101809250P4'

selcen_old_null = selcen_old_null.drop(['Order #', 'Price List NFI_y'], axis = 1)
selcen_old_null = selcen_old_null.rename(columns = {'Price List NFI_x' : 'Price List NFI'})

selcen_old_null = selcen_old_null.merge(source2[['Order #', 'Real SKU', 'Bundle Name', 'Price List NFI']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(selcen_old_null.index) 

selcen_old_merge['Price List NFI_y'][selcen_old_null.index] = selcen_old_null['Price List NFI_y']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [31]:
# selcen_old_merge[selcen_old_merge['Price List NFI_y'].isnull()][['No. Pesanan','Product Name','Real Nama Produk', 'Real SKU','Bundle Name', 'Price List NFI_x', 'Price List NFI_y','Qty. Invoiced']].drop_duplicates('Real SKU')

In [32]:
### run 22
selcen_old_merge['Price List NFI_y'] = selcen_old_merge['Price List NFI_y'].fillna(selcen_old_merge['Price List NFI_x'])

selcen_old_merge = selcen_old_merge.drop(['Price List NFI_x', 'Order #'], axis = 1)
selcen_old_merge = selcen_old_merge.rename(columns = {'Price List NFI_y' : 'Price List NFI'})

selcen_old_merge['Price List NFI'] = pd.to_numeric(selcen_old_merge['Price List NFI']).astype(float)
selcen_old_merge['Qty. Invoiced'] = pd.to_numeric(selcen_old_merge['Qty. Invoiced']).astype(float)

selcen_old_merge['Total Net'] = selcen_old_merge['Price List NFI'] * selcen_old_merge['Qty. Invoiced']

selcen_sku = selcen_sku[~selcen_sku['No. Pesanan'].isin(selcen_old_merge['No. Pesanan'])]
selcen_sku = selcen_sku.append(selcen_old_merge, ignore_index = True, sort = False)

selcen_sku['Total Net Before PPN'] = selcen_sku['Total Net']/1.11

In [33]:
# selcen_sku

# Fulfillment

In [34]:
## run 23
selcen_sku['Outbound Qty'] = selcen_sku['Qty. Invoiced']

In [35]:
## run 24
shopee_merge = selcen_sku.copy()

In [36]:
## run 25
import pandas as pd
import numpy as np
import pypyodbc

conn = pypyodbc.connect('Driver={SQL Server};'
                        'Server=NFI-DB-01;'
                        'Database=gudang;'
                        # 'UID=andra.miftah;'
                        # 'PWD=24nutrifoodindonesia21;'
                        'Trusted_Connection=yes;'
                )

cursor = conn.cursor()
# wms_telkom = pd.read_sql(r"""SELECT t1.id, t1.order_id,t1.status, t1.quantity, t1.product_id, t2.id,  t2.order_number, t2.invoice_number, t2.channel, t2.order_date, t3.id, t3.sku, t3.name
#   FROM [gudang].[dbo].[outbound_items] as t1
#   left join orders as t2
#   on t1.order_id = t2.id
#   left join products as t3
#   on t1.product_id = t3.id""", conn)
                         
    
wms_telkom = pd.read_sql(r"""SELECT t1.id, t1.order_id, t1.product_id, t1.quantity, t2.id,  t2.status, t2.order_number, t2.invoice_number, t2.channel, t2.order_date, t3.id, t3.sku, t3.name
  FROM [gudang].[dbo].[order_products] as t1
  left join orders as t2
  on t1.order_id = t2.id
  left join products as t3
  on t1.product_id = t3.id""", conn)
# wms_telkom.to_csv(r'Backup WMS Telkom.csv', sep = ';', index = False)

In [37]:
## for backup
wms_telkom_cp = wms_telkom.copy()

In [ ]:
## for backup
wms_telkom = wms_telkom_cp.copy()

In [ ]:
#.nunique()

In [ ]:
# wms_telkom_cp[(wms_telkom_cp['invoice_number'].notnull())&(wms_telkom_cp['invoice_number']!=wms_telkom_cp['order_number'])][['channel','invoice_number','order_number']]

In [38]:
## run 26
wms_telkom = wms_telkom[wms_telkom['channel'].isin(['Shopee'])]
wms_telkom = wms_telkom.reset_index(drop = True)
wms_telkom = wms_telkom[['order_number','invoice_number', 'sku', 'status', 'quantity']].drop_duplicates()
wms_telkom['invoice_number'] = wms_telkom['invoice_number'].astype(str).str.replace('.0', '', regex = False)



min1 = wms_telkom[wms_telkom['order_number'].astype(str).str.contains('-1')]
min1['order_number'] = min1['order_number'].astype(str).str.replace('-1', '', regex = False)

temp_telkom = wms_telkom.merge(min1, how = 'left', on = ['order_number', 'sku'])
indeks = temp_telkom[temp_telkom['invoice_number_y'] == 'nan'].index.to_list()
temp_telkom['invoice_number_y'][indeks] = np.nan

indeks = temp_telkom[temp_telkom['invoice_number_y'].notnull()].index.to_list()
wms_telkom = wms_telkom.drop(indeks, axis = 0)
# wms_telkom = wms_telkom.drop('order_number', axis = 1)

wms_telkom['WH'] = 'Telkom'
wms_telkom = wms_telkom.rename(columns = {'order_number' : 'No. Pesanan', 'status':'Outbound Status', 'sku' : 'SKU WH', 'quantity' : 'Outbound Qty'})
wms_telkom.loc[wms_telkom['No. Pesanan'].str.len()==9,'No. Pesanan']=wms_telkom['invoice_number'] ### tambahan timo 20 aug

colname = wms_telkom.columns.to_list()
wms_telkom_all = wms_telkom.merge(j_conv, how = 'left', left_on = ['SKU WH'], right_on = ['Real SKU'])
wms_j = wms_telkom_all[wms_telkom_all['SKU Produk'].notnull()]

wms_j['SKU WH'] = wms_j['SKU Produk']
wms_j['Outbound Qty'] = wms_j['Outbound Qty'] * wms_j['Konversi ke UOM'].astype(float)

wms_telkom = wms_telkom.append(wms_j, ignore_index = True, sort = False)
wms_telkom = wms_telkom[colname]

wms_telkom = wms_telkom.groupby(['No. Pesanan','invoice_number', 'SKU WH', 'Outbound Status', 'WH'], dropna = False)['Outbound Qty'].sum().reset_index()


temp_telkom = shopee_merge[shopee_merge['Pesanan yang Dikelola Shopee'] == 'No'].copy()

temp_telkom = temp_telkom.drop(['Outbound Qty'], axis = 1)

cek=wms_telkom.copy()

temp_telkom['No. Pesanan'] = temp_telkom['No. Pesanan'].astype(str)
wms_telkom['No. Pesanan'] = wms_telkom['No. Pesanan'].astype(str)

temp_telkom['Real SKU'] = temp_telkom['Real SKU'].astype(str).str.replace('.0', '', regex = False)
wms_telkom['SKU WH'] = wms_telkom['SKU WH'].astype(str)

temp_telkom = temp_telkom.merge(wms_telkom.drop_duplicates(['No. Pesanan', 'SKU WH']), how = 'left', left_on = ['No. Pesanan', 'Real SKU'], right_on = ['No. Pesanan', 'SKU WH'])
cek2=temp_telkom.copy()
temp_telkom['Outbound Qty'] = temp_telkom['Outbound Qty'] * temp_telkom['Qty. Invoiced']/temp_telkom.groupby(['No. Pesanan', 'Real SKU'])['Qty. Invoiced'].transform('sum')

temp_telkom_bundle = temp_telkom[temp_telkom['Brand'] == 'Bundle']

temp_buat_bundle = temp_telkom.groupby(['No. Pesanan', 'Bundle Name']).agg({'WH' : 'first', 'Outbound Status' : 'first', 'Outbound Qty' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Outbound Qty'] = temp_buat_bundle['Outbound Qty']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

temp_telkom_bundle = temp_telkom_bundle.merge(temp_buat_bundle.drop_duplicates(['No. Pesanan', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Product Name'], right_on = ['No. Pesanan', 'Bundle Name']).set_index(temp_telkom_bundle.index)
temp_telkom_bundle['Outbound Qty_y'] = temp_telkom_bundle['Outbound Qty_y']*temp_telkom_bundle['Qty. Invoiced']

temp_telkom['Outbound Status'][temp_telkom_bundle.index] = temp_telkom_bundle['Outbound Status_y']
temp_telkom['WH'][temp_telkom_bundle.index] = temp_telkom_bundle['WH_y']
temp_telkom['Outbound Qty'][temp_telkom_bundle.index] = temp_telkom_bundle['Outbound Qty_y']


shopee_telkom = temp_telkom.copy()

temp_telkom = shopee_telkom[(shopee_telkom['No. Pesanan'].isin(wms_telkom['No. Pesanan'])) &
          (shopee_telkom['Outbound Status'].isnull())].copy()

wms_telkom2 = wms_telkom.copy()

wms_telkom2['SKU WH'] = wms_telkom2['SKU WH'].astype(str).str.replace('2309005305', '2309005300')

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '1101930453'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(R)1101930453'

indeks = wms_telkom2[wms_telkom2['SKU WH'] == '1101996453'].index.to_list()
wms_telkom2['SKU WH'][indeks] = '(E)1101996453'

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '2101846355'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(E)2101846355'

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '2101484302'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(E)2101484302'

# indeks = wms_telkom2[wms_telkom2['SKU WH'] == '1101155250'].index.to_list()
# wms_telkom2['SKU WH'][indeks] = '(E)1101155250'

temp_telkom = temp_telkom.drop(['Outbound Qty', 'Outbound Status', 'WH'], axis = 1)

temp_telkom['No. Pesanan'] = temp_telkom['No. Pesanan'].astype(str)
wms_telkom2['No. Pesanan'] = wms_telkom2['No. Pesanan'].astype(str)

temp_telkom['Real SKU'] = temp_telkom['Real SKU'].astype(str).str.replace('.0', '', regex = False)
wms_telkom2['SKU WH'] = wms_telkom2['SKU WH'].astype(str)

temp_telkom = temp_telkom.merge(wms_telkom2.drop_duplicates(['No. Pesanan', 'SKU WH']), how = 'left', left_on = ['No. Pesanan', 'Real SKU'], right_on = ['No. Pesanan', 'SKU WH']).set_index(temp_telkom.index)

temp_telkom_bundle = temp_telkom[temp_telkom['Brand'] == 'Bundle']

temp_buat_bundle = temp_telkom.groupby(['No. Pesanan', 'Bundle Name']).agg({'WH' : 'first', 'Outbound Status' : 'first', 'Outbound Qty' : 'max', 'Qty. Invoiced' : 'max'}).reset_index()
temp_buat_bundle['Outbound Qty'] = temp_buat_bundle['Outbound Qty']/temp_buat_bundle['Qty. Invoiced']
temp_buat_bundle = temp_buat_bundle.drop('Qty. Invoiced', axis = 1)

temp_telkom_bundle = temp_telkom_bundle.merge(temp_buat_bundle.drop_duplicates(['No. Pesanan', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Product Name'], right_on = ['No. Pesanan', 'Bundle Name']).set_index(temp_telkom_bundle.index)
temp_telkom_bundle['Outbound Qty_y'] = temp_telkom_bundle['Outbound Qty_y']*temp_telkom_bundle['Qty. Invoiced']

temp_telkom['Outbound Status'][temp_telkom_bundle.index] = temp_telkom_bundle['Outbound Status_y']
temp_telkom['WH'][temp_telkom_bundle.index] = temp_telkom_bundle['WH_y']
temp_telkom['Outbound Qty'][temp_telkom_bundle.index] = temp_telkom_bundle['Outbound Qty_y']

shopee_telkom['Outbound Status'][temp_telkom.index] = temp_telkom['Outbound Status']
shopee_telkom['WH'][temp_telkom.index] = temp_telkom['WH']
shopee_telkom['Outbound Qty'][temp_telkom.index] = temp_telkom['Outbound Qty']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [56]:
# shopee_telkom[shopee_telkom['No. Pesanan']=='2205230ABVF4VX']
# shopee_telkom[shopee_telkom['Outbound Qty'].notnull()]
# temp_telkom#[temp_telkom['invoice_number']=='2205230ABVF4VX']
display(cek[cek['invoice_number']=='2205230ABVF4VX'])
cek2[cek2['No. Pesanan']=='2205230ABVF4VX']

,No. Pesanan,invoice_number,SKU WH,Outbound Status,WH,Outbound Qty
59274,2205230ABVF4VX,2205230ABVF4VX,21014281,packing,Telkom,24.0
59275,2205230ABVF4VX,2205230ABVF4VX,2101656,packing,Telkom,24.0
59276,2205230ABVF4VX,2205230ABVF4VX,2101941250,packing,Telkom,24.0

,No. Pesanan,Status Pesanan,Alasan Pembatalan,Status Pembatalan/ Pengembalian,No. Resi,Opsi Pengiriman,Antar ke counter/ pick-up,Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan),Status Pengiriman,Jasa Kirim yang Digunakan,Waktu Pesanan Dibuat,Waktu Pengiriman Diatur,Waktu Pembayaran Dilakukan,Tanggal Outbound,Tanggal Pesanan Sampai,Tanggal Pelepasan Dana Diverifikasi,Waktu Pesanan Selesai,Tanggal Pembatalan Selesai,Pesanan yang Dikelola Shopee,SKU,Product Name,Nomor Referensi SKU,Nama Variasi,Harga Awal,Harga Setelah Diskon,Qty. Invoiced,Total Harga Produk,Total Diskon,Diskon Dari Penjual,Diskon Dari Shopee,Berat Produk,Jumlah Produk di Pesan,Total Berat,Voucher Ditanggung Penjual,Cashback Koin,Voucher Ditanggung Shopee,Paket Diskon,Paket Diskon (Diskon dari Shopee),Paket Diskon (Diskon dari Penjual),Potongan Koin Shopee,Diskon Kartu Kredit,Ongkos Kirim Dibayar oleh Pembeli,Ongkos Kirim Pengembalian Barang,Total Pembayaran,Perkiraan Ongkos Kirim,Catatan dari Pembeli,Catatan,Username (Pembeli),Nama Penerima,No. Telepon,Alamat Pengiriman,Kota/Kabupaten,Provinsi,Source,Dimiliki Shopee,Year,Month,true datetime,Pemilik Budget,Real SKU,Real Nama Produk,Brand,Sub Brand,Produk 1,SKU Produk 1,PCS Produk 1,Price List NFI 1,Subtotal Produk 1,Harga Display 1,Harga Cost 1,Produk 2,SKU Produk 2,PCS Produk 2,Price List NFI 2,Subtotal Produk 2,Harga Display 2,Harga Cost 2,Produk 3,SKU Produk 3,PCS Produk 3,Price List NFI 3,Subtotal Produk 3,Harga Display 3,Harga Cost 3,Produk 4,SKU Produk 4,PCS Produk 4,Price List NFI 4,Subtotal Produk 4,Harga Display 4,Harga Cost 4,Produk 5,SKU Produk 5,PCS Produk 5,Price List NFI 5,Subtotal Produk 5,Harga Display 5,Harga Cost 5,Produk 6,SKU Produk 6,PCS Produk 6,Price List NFI 6,Subtotal Produk 6,Harga Display 6,Harga Cost 6,Produk 7,SKU Produk 7,PCS Produk 7,Price List NFI 7,Subtotal Produk 7,Harga Display 7,Harga Cost 7,Price List NFI,Harga Cost,Total Net,Total Harga Cost,Total Net Before PPN,Bundle Name,Bundle Flag,Parent Item,Parent SKU,invoice_number,SKU WH,Outbound Status,WH,Outbound Qty
33040,2205230ABVF4VX,Selesai,NaN,NaN,JT11642430507,Kargo-JNE Trucking (JTR),Pickup,2022-05-25 20:19,Sudah Dikirim,Paket telah diterima Yang bersangkutan.,2022-05-23,2022-05-24 11:47,2022-05-23 20:19:00,NaN,2022-05-25,2022-05-30,2022-05-30 07:21,NaN,No,2101656P24,1 Karton - HiLo Teen Coffee Tiramisu Milk 200 ...,2101656P24,NaN,1896.0,1505.0,1.0,150500.0,391.0,391.0,0.0,4800 gr,3,14400 gr,0.0,0.0,0.0,N,0.0,0.0,0,0.0,350.0,0.0,164771.061453,121.229050,NaN,NaN,widiasr82,Widia,628128728792,NUSA Loka BSD the Savia Blok E2 no 10 sektor 1...,KOTA TANGERANG SELATAN,BANTEN,Order.all.20220501_20220524_part_1_of_4.xlsx,NaN,2022,May,2022-05-23,NaN,2101656P24,HILO Teen Coffee Tiramisu Ready To Drink Susu ...,Bundle,NaN,HiLo Teen RTD Coffee Tiramisu 200ml,2101656,24.0,6882.0,165168.0,189600.0,165168.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,165168.0,165168,165168.0,165168,148800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33041,2205230ABVF4VX,Selesai,NaN,NaN,JT11642430507,Kargo-JNE Trucking (JTR),Pickup,2022-05-25 20:19,Sudah Dikirim,Paket telah diterima Yang bersangkutan.,2022-05-23,2022-05-24 11:47,2022-05-23 20:19:00,NaN,2022-05-25,2022-05-30,2022-05-30 07:21,NaN,No,2101941250P24,1 Karton - HiLo Milky Brown Sugar Ready To Dri...,2101941250P24,NaN,1680.0,1350.0,1.0,135000.0,330.0,330.0,0.0,4800 gr,3,14400 gr,0.0,0.0,0.0,N,0.0,0.0,0,0.0,350.0,0.0,146167.877095,107.541899,NaN,NaN,widiasr82,Widia,628128728792,NUSA Loka BSD the Savia Blok E2 no 10 sektor 1...,KOTA TANGERANG SELATAN,BANTEN,Order.all.20220501_20220524_part_1_of_4.xlsx,NaN,2022,May,2022-05-23,NaN,2101941250P24,HiLo Milky Brown Sugar 200ml (24 Pcs),Bundle,NaN,Hilo RTD Milky Brown Sugar 200 ml,2101941250,24.0,6105.0,146520.0,172800.0,146520.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146520.0,146520,146520.0,146520,132000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33042,2205230ABVF4VX,Selesai,NaN,NaN,JT11642430507,Kargo-JNE Trucking (JTR),Pickup,2022-05-25 20:19,Sudah Dikirim,Paket telah diterima Yang bersangkutan.,2022-05-23,2022-05-24 11:47,2022-05-23 20:19:00,NaN,2022-05-25,2022-05-30,2022-05-30 07:21,NaN,No,21014281P24,1 Karton - HiLo School Vanilla Vegiberi Ready ...,21014281P24,NaN,1896.0,1505.0,1.0,150500.0,391.0,391.0,0.0,4800 gr,3,14400 gr,0.0,0.0,0.0,N,0.0,0.0,0,0.0,350.0,0.0,164771.061453,121.229050,NaN,NaN,widiasr82,Widia,628128728792,NUSA Loka BSD the Savia Blok E2 no 10 sektor 1...,KOTA TANGERANG SELATAN,BANTEN,Order.all.20220501_20220524_part_1_of_4.xlsx,NaN,2022,May,2022-05-23,NaN,21014281P24,Hilo School Vanilla Vegiberi Ready To Drink Su...,Bundle,NaN,HiLo School RTD Vanila Vegiberi 200ml,2HF1401250,24.0,6882.0,165168.0,189600.0,165168.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,165168.0,165168,165168.0,165168,148800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364177,2205230ABVF4VX,Selesai,NaN,NaN,JT11642430507,Kargo-JNE Trucking (JTR),Pickup,2022-05-25 20:19,Sudah Dikirim,Paket telah diterima Yang bersangkutan.,2022-05-23,2022-05-24 11:47,2022-05-23 20:19:00,NaN,2022-05-25,2022-05-30,2022-05-30 07:21,NaN,No,2101656,HiLo Teen RTD Coffee Tiramisu 200ml,2101656P24,NaN,1896.0,1505.0,24.0,150500.0,391.0,391.0,0.0,4800 gr,3,14400 gr,0.0,0.0,0.0,N,0.0,0.0,0,0.0,350.0,0.0,164771.061453,121.229050,NaN,NaN,widiasr82,Widia,628128728792,NUSA Loka BSD the Savia Blok E2 no 10 sektor 1...,KOTA TANGERANG SELATAN,BANTEN,Order.all.20220501_20220524_part_1_of_4.xlsx,NaN,2022,May,2022-05-23,NaN,2101656,HiLo Teen RTD Coffee Tiramisu 200ml,HiLo,HILO RTD,HiLo Teen RTD Coffee Tiramisu 200ml,2101656,24.0,6882.0,165168.0,189600.0,165168.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,6882.0,6882,165168.0,165168,148800.0,1 Karton - HiLo Teen Coffee Tiramisu Milk 200 ...,NaN,HiLo Teen RTD Tiramisu 200ml,NaN,2205230ABVF4VX,2101656,packing,Telkom,24.0
364178,2205230ABVF4VX,Selesai,NaN,NaN,JT11642430507,Kargo-JNE Trucking (JTR),Pickup,2022-05-25 20:19,Sudah Dikirim,Paket telah diterima Yang bersangkutan.,2022-05-23,2022-05-24 11:47,2022-05-23 20:19:00,NaN,2022-05-25,2022-05-30,2022-05-30 07:21,NaN,No,2101941250,Hilo RTD Milky Brown Sugar 200 ml,2101941250P24,NaN,1680.0,1350.0,24.0,135000.0,330.0,330.0,0.0,4800 gr,3,14400 gr,0.0,0.0,0.0,N,0.0,0.0,0,0.0,350.0,0.0,146167.877095,107.541899,NaN,NaN,widiasr82,Widia,628128728792,NUSA Loka BSD the Savia Blok E2 no 10 sektor 1...,KOTA TANGERANG SELATAN,BANTEN,Order.all.20220501_20220524_part_1_of_4.xlsx,NaN,2022,May,2022-05-23,NaN,2101941250,Hilo RTD Milky Brown Sugar 200 ml,HiLo,HILO RTD,Hilo RTD Milky Brown Sugar 200 ml,2101941250,24.0,6105.0,146520.0,172800.0,146520.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6105.0,6105,146520.0,146520,132000.0,1 Karton - HiLo Milky Brown Sugar Ready To Dri...,NaN,Hilo RTD Milky Brown Sugar 200 ml,NaN,2205230ABVF4VX,2101941250,packing,Telkom,24.0
364179,2205230ABVF4VX,Selesai,NaN,NaN,JT11642430507,Kargo-JNE Trucking (JTR),Pickup,2022-05-25 20:19,Sudah Dikirim,Paket telah diterima Yang bersangkutan.,2022-05-23,2022-05-24 11:47,2022-05-23 20:19:00,NaN,2022-05-25,2022-05-30,2022-05-30 07:21,NaN,No,2HF1401250,HiLo School RTD Vanila Vegiberi 200ml,21014281P24,NaN,1896.0,1505.0,24.0,150500.0,391.0,391.0,0.0,4800 gr,3,14400 gr,0.0,0.0,0.0,N,0.0,0.0,0,0.0,350.0,0.0,164771.061453,121.229050,NaN,NaN,widiasr82,Widia,628128728792,NUSA Loka BSD the Savia Blok E2 no 10 sektor 1...,KOTA TANGERANG SELATAN,BANTEN,Order.all.20220501_20220524_part_1_of_4.xlsx,NaN,2022,May,2022-05-23,NaN,2HF1401250,HiLo School RTD Vanila Vegiberi 200ml,HiLo,HILO RTD,HiLo School RTD Vanila Vegiberi 200ml,2HF1401250,24.0,6882.0,165168.0,189600.0,165168.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,6882.0,6882,165168.0,165168,148800.0,1 Karton - HiLo School Vanilla Vegiberi Ready ...,NaN,Hilo School RTD Vanilla Vegiberi 200ml,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
shopee_telkom[(shopee_telkom['No. Pesanan'].isin(wms_telkom['No. Pesanan'])) &
          (shopee_telkom['Outbound Status'].isnull())][['Real SKU', 'Real Nama Produk', 'Bundle Name', 'No. Pesanan']].drop_duplicates(['Real SKU', 'Real Nama Produk'])

,Real SKU,Real Nama Produk,Bundle Name,No. Pesanan
129,21014281P24,Hilo School Vanilla Vegiberi Ready To Drink Su...,NaN,220126T4BGKQVQ
1775,21014281P4,Hilo School Vanilla Vegiberi Ready To Drink Su...,NaN,220216JQ5XMGTY
10234,2101461P4,Hilo Teen Chocolate Ready To Drink Susu [4 pcs],NaN,220322HTX8R7CX
10235,PH21(2)G200,HiLo Teen Yoghurt Banana 250gr x 2 pcs Free Tu...,NaN,220322HTX8R7CX
34220,(R)1101588453P2,Nutrisari Milky Orange 20's,NaN,220504AYD1TSA3
342105,2HF1401250,HiLo School RTD Vanila Vegiberi 200ml,1 Karton - HiLo School Vanilla Vegiberi Ready ...,220126T4BGKQVQ
342434,2304515112,L-Men Lose Weight Avocado Coffee 300g,GRATIS L-Men 2 GO - L-Men Lose Weight Avocado ...,22013053052MRP
343397,2305559288,L-Men Platinum Bubble Gum 800 gram,GRATIS 3 RTD L-Men 2 Go - L-Men Platinum Bubb...,220218S5Q8VC1Y
349046,2101461,HiLo Teen RTD Coklat 200ml,4 Pack - HiLo Teen Chocolate Milk 200 ml x 4 p...,220322HTX8R7CX
349047,2101699155,HiLo Teen Yoghurt Banana 250gr,GRATIS Botol - HiLo Teen Yoghurt Banana 250g (...,220322HTX8R7CX
365295,(R)1101588453,NutriSari Milky Orange (Renceng),Nutrisari Milky Orange 20's,220504AYD1TSA3
467246,2104406,Tropicana Slim Sunflower Oil 946 ml,FREE Mint Cocoa - Twin Pack Tropicana Slim Min...,22090518VG8A5Q
482890,(G)71210225,Gift - Tumbler HiLo Teen 2022 (Warna Random),GRATIS Botol - HiLo Teen Yoghurt Banana 250g (...,220322HTX8R7CX
483359,(G)71210222,Gift - Kartu Pantun by HiLo Teen,BUY 1 GET 1 - HiLo Teen Biscuit Caramel 500 gr...,2203150JE6T6Q7
498249,(B)2309005305,(FREE) L-Men Protein Crunch BBQ Beef (20gr),Free 2 Protein Crunch - L-Men Gain Mass Mangga...,220808H7AVK953
523770,2101891443,HiLo Swiss Chocolate (10 sch) Renceng,"Paket HiLo Dessert - HiLo Es Ketan Hitam, Es T...",22052308VPQ0RP
537376,(E)2101492P24,(Near ED) HiLo School RTD Coklat 200ML x 24 pcs,NaN,220110DYJ0MM49
545203,(E)2101492,(Near ED) HiLo School RTD Coklat 200ML,SPESIAL PROMO - 1 Karton - HiLo School Chocola...,220110DYJ0MM49

In [39]:
### run 27
shopee_telkom['Status Pengiriman'] = shopee_telkom['Outbound Status']
shopee_telkom = shopee_telkom.drop('Outbound Status', axis = 1)

shopee_sbs = shopee_merge[shopee_merge['Pesanan yang Dikelola Shopee'] == 'Yes'].copy()
shopee_sbs['WH'] = 'Shopee Warehouse'

shopee_fulfill = shopee_sbs.append(shopee_telkom, ignore_index = True, sort = False)

In [40]:
## run 28
for_wms = shopee_fulfill.copy()

In [ ]:
for_wms[(for_wms['Year']==2022)&(for_wms['WH']!='Shopee Warehouse')&(for_wms['No. Pesanan']=='2205230ABVF4VX')][['No. Pesanan','Year','Month','Real SKU','Qty. Invoiced','Outbound Qty']]

In [ ]:
shopee_telkom[shopee_telkom['No. Pesanan']=='2205230ABVF4VX']

# Settlement

In [41]:
### run 29
import pandas as pd
import os
import numpy as np
set_shopee = pd.DataFrame()
folder = r'Settlement Project\Shopee\Settlement/'

for i in os.listdir(folder):
    temp = pd.read_csv(folder + str(i))
    if temp.columns[0] != 'Tanggal':
        header = temp[temp[temp.columns[0]] == 'Tanggal'].index[0]
        temp = pd.read_csv(folder + str(i), header = header+1)
    print(i)
    temp['Source'] = i
    if len(set_shopee) != 0:
        temp = temp[~temp['Deskripsi'].isin(set_shopee['Deskripsi'])]
    set_shopee = set_shopee.append(temp, ignore_index = True, sort = False)
    true_col = ['Tanggal', 'Penerima Dana', 'Jumlah Dana', 'Deskripsi', 'Status', 'Saldo', 'Source']
    if temp.columns.to_list() == true_col:
        print('Column Sama')
    else :
        print('Column Beda')
        print([x for x in true_col if x not in temp.columns.to_list()])
        print([x for x in temp.columns.to_list() if x not in true_col])
    
set_shopee

ShopeePay.ps_reports_wallet_all.20211211_20220110part_0_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20211211_20220110part_1_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20211211_20220110part_2_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20211211_20220110part_3_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20211211_20220110part_4_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220110_20220118.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220118_20220126.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220126_20220205part_0_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220126_20220205part_1_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220205_20220211.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220211_20220216.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220216_20220224.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220224_20220225.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220225_20220228.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220228_20220307part_0_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220228_20220307part_1_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220307_20220316part_0_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220307_20220316part_1_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220307_20220316part_2_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220307_20220316part_3_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220307_20220316part_4_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220316_20220323part_0_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220316_20220323part_1_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220323_20220405part_0_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220323_20220405part_1_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220323_20220405part_2_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220404_20220416part_0_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220404_20220416part_1_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220404_20220416part_2_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220404_20220416part_3_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220416_20220427part_0_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220416_20220427part_1_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220416_20220427part_2_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220427_20220512part_0_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220427_20220512part_1_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220427_20220512part_2_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220512_20220521part_0_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220512_20220521part_1_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220521_20220527.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220527_20220613part_0_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220527_20220613part_1_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220527_20220613part_2_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220613_20220624part_0_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220613_20220624part_1_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220624_20220628.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220626_20220712part_0_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220626_20220712part_1_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220626_20220712part_2_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220712_20220726part_0_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220712_20220726part_1_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220712_20220726part_2_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220726_20220826part_0_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220726_20220826part_1_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220726_20220826part_2_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220726_20220826part_3_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220726_20220826part_4_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220726_20220826part_5_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220826_20220927part_0_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220826_20220927part_1_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220826_20220927part_2_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220826_20220927part_3_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220826_20220927part_4_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220826_20220927part_5_of_6.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220927_20221026part_0_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220927_20221026part_1_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220927_20221026part_2_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20220927_20221026part_3_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221026_20221116part_0_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221026_20221116part_1_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221026_20221116part_2_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221026_20221116part_3_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221116_20221129part_0_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221116_20221129part_1_of_2.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221129_20230110part_0_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221129_20230110part_1_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221129_20230110part_2_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221129_20230110part_3_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20221129_20230110part_4_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230110_20230130part_0_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230110_20230130part_1_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230110_20230130part_2_of_3.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230130_20230225part_0_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230130_20230225part_1_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230130_20230225part_2_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230130_20230225part_3_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230225_20230328part_0_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230225_20230328part_1_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230225_20230328part_2_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230225_20230328part_3_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230225_20230328part_4_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230328_20230425part_0_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230328_20230425part_1_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230328_20230425part_2_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230328_20230425part_3_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230328_20230425part_4_of_5.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230425_20230529part_0_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230425_20230529part_1_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230425_20230529part_2_of_4.csv
Column Sama
ShopeePay.ps_reports_wallet_all.20230425_20230529part_3_of_4.csv
Column Sama

,Tanggal,Penerima Dana,Jumlah Dana,Deskripsi,Status,Saldo,Source
0,2022-01-10 09:24,Saldo Penjual,154300.0,Penghasilan dari Pesanan #2112241GWGSVTU,NaN,247935.0,ShopeePay.ps_reports_wallet_all.20211211_20220...
1,2022-01-10 09:23,Saldo Penjual,57035.0,Penghasilan dari Pesanan #2201089M3EFAV3,NaN,93635.0,ShopeePay.ps_reports_wallet_all.20211211_20220...
2,2022-01-10 09:23,Saldo Penjual,36600.0,Penghasilan dari Pesanan #220102QT3MBVP9,NaN,36600.0,ShopeePay.ps_reports_wallet_all.20211211_20220...
3,2022-01-10 09:14,Bank,-553710884.0,Penarikan Dana,Transaksi Selesai,0.0,ShopeePay.ps_reports_wallet_all.20211211_20220...
4,2022-01-10 09:13,Saldo Penjual,201880.0,Penghasilan dari Pesanan #211229D1X2FQGV,NaN,553710884.0,ShopeePay.ps_reports_wallet_all.20211211_20220...
...,...,...,...,...,...,...,...
394464,2023-04-25 11:37,Saldo Penjual,74353.0,Penghasilan dari Pesanan #230423UBDPT4G3,NaN,35740957.0,ShopeePay.ps_reports_wallet_all.20230425_20230...
394465,2023-04-25 11:32,Saldo Penjual,184846.0,Penghasilan dari Pesanan #230420JW3G1JG0,NaN,35666604.0,ShopeePay.ps_reports_wallet_all.20230425_20230...
394466,2023-04-25 11:31,Saldo Penjual,342555.0,Penghasilan dari Pesanan #230411TRWM61DP,NaN,35481758.0,ShopeePay.ps_reports_wallet_all.20230425_20230...
394467,2023-04-25 11:29,Saldo Penjual,85554.0,Penghasilan dari Pesanan #2304169GYKHNBM,NaN,35139203.0,ShopeePay.ps_reports_wallet_all.20230425_20230...
394468,2023-04-25 11:25,Saldo Penjual,455566.0,Penghasilan dari Pesanan #2304157043Q198,NaN,35053649.0,ShopeePay.ps_reports_wallet_all.20230425_20230...

In [ ]:
set_shopee.to_excel('sett shopee all.xlsx',index=False)

In [ ]:
cekshopee=pd.read_excel("D:\Downloads\case shopee.xlsx")
print(len(cekshopee['No. Pesanan'].unique()))
set_shopee[set_shopee['Order ID'].isin(canpaid['No. Pesanan'].unique())]['Deskripsi'].unique()#.to_excel('cash refund by shopee Aug 2022.xlsx',index=False)#.groupby(['Order ID'])[['Source']].nunique().sort_values('Source',ascending=False)#['Penerima Dana'].unique()
#220725DB5X69DH
# set_shopee[set_shopee['Order ID']=='220725DB5X69DH']

In [42]:
### run 30
set_shopee['Order ID'] = np.nan

indeks = set_shopee[set_shopee['Deskripsi'].astype(str).str.contains('#SN', regex = False)].index.to_list()
set_shopee['Order ID'][indeks] = set_shopee['Deskripsi'][indeks].astype(str).str.split('#SN', expand = True)[1].str.split(' ', expand = True)[0]

indeks = set_shopee[(set_shopee['Deskripsi'].astype(str).str.contains('#', regex = False)) &
                   (set_shopee['Order ID'].isnull())].index.to_list()
set_shopee['Order ID'][indeks] = set_shopee['Deskripsi'][indeks].astype(str).str.split('#', expand = True)[1].str.split(' ', expand = True)[0]

indeks = set_shopee[(set_shopee['Order ID'].isnull())].index.to_list()
set_shopee['Order ID'][indeks] = set_shopee['Deskripsi'][indeks].astype(str).str.split(' ',expand = True)[set_shopee['Deskripsi'][indeks].astype(str).str.split(' ',expand = True).columns[-1]]

converter = pd.read_excel(r'Settlement Project/Shopee/settlement shopee.xlsx')
for i in converter['Deskripsi'].values:
    i = str(i).replace('[', '\[').replace(']', '\]')
    indeks = set_shopee[(set_shopee['Deskripsi'].astype(str).str.contains(i, regex = True)) &
                   ((set_shopee['Order ID'].isnull()) | (set_shopee['Order ID'] == ''))].index.to_list()
    if len(indeks) != 0:
        set_shopee['Order ID'][indeks] = set_shopee['Deskripsi'][indeks].astype(str).str.split(i, expand = True)[1].str.strip()
    print(i)
    print(len(indeks))

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":

Penghasilan dari Pesanan
0

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Penarikan Dana
3
\[Pengurangan Wallet\] Pembeli Tidak Terima Barang Sebagian
33
\[Penambahan Wallet\] Penggantian Dana Penuh Barang Hilang
110
\[Penambahan Wallet\] Penggantian Dana Sebagian Barang Hilang
101
\[Penambahan Wallet\] Penggantian Dana Penuh Barang Rusak
375
\[Penambahan Wallet\] Penggantian Dana Sebagian Barang Rusak
39
Kompensasi Order #SN
0
Penarikan Otomatis
2
Kompensasi Order #SN
0
Penyesuaian untuk
32
\[Penambahan Wallet\] Pelepasan Dana
45
\[Penambahan Wallet\] Shopee Ongkir
3540
\[Pengurangan Wallet\] Pemotongan Biaya Pembayaran
6818
\[Pengurangan Wallet\] Pemotongan Biaya Administrasi Shopee Mall
6993
\[Pengurangan Wallet\] Pembeli Tidak Terima Barang
4
\[Pengurangan Wallet\] Pelepasan Dana Berlebih
9
Compensation for Order
0
Kompensasi kehilangan untuk paket
0

In [39]:
set_shopee[set_shopee['Order ID'].isin(['220625Q14P4AM7','2207213C6Y71X4',
                                        '220714E5MJ38CA','22071042NM3AAJ','2208011FJSYRF7'])]['Source'].values

array(['ShopeePay.ps_reports_wallet_all.20220826_20220927part_0_of_6.csv',
       'ShopeePay.ps_reports_wallet_all.20220826_20220927part_0_of_6.csv',
       'ShopeePay.ps_reports_wallet_all.20220826_20220927part_0_of_6.csv',
       'ShopeePay.ps_reports_wallet_all.20220826_20220927part_0_of_6.csv',
       'ShopeePay.ps_reports_wallet_all.20220826_20220927part_0_of_6.csv'],
      dtype=object)

In [46]:
### run 31
set_shopee['Kategori'] = np.nan
# set_shopee['Negatif'] = np.nan

converter = pd.read_excel(r'Settlement Project/Shopee/settlement shopee.xlsx')
converter.loc[converter['Deskripsi']=='[Pengurangan Wallet] Pelepasan Dana Berlebih','Kategori']='Bi Komplain'
for i in range(len(converter)):
    desc = converter['Deskripsi'][i]
    indeks = set_shopee[set_shopee['Deskripsi'].astype(str).str.contains(desc, regex = False)].index.to_list()
    set_shopee['Kategori'][indeks] = converter['Kategori'][i]
#     set_shopee['Negatif'][indeks] = converter['Posit/Negatif'][i]
    print(desc)

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

Penghasilan dari Pesanan
Penarikan Dana
[Pengurangan Wallet] Pembeli Tidak Terima Barang Sebagian
[Penambahan Wallet] Penggantian Dana Penuh Barang Hilang
[Penambahan Wallet] Penggantian Dana Sebagian Barang Hilang
[Penambahan Wallet] Penggantian Dana Penuh Barang Rusak
[Penambahan Wallet] Penggantian Dana Sebagian Barang Rusak
Kompensasi Order #SN
Penarikan Otomatis
Kompensasi Order #SN
Penyesuaian untuk
[Penambahan Wallet] Pelepasan Dana
[Penambahan Wallet] Shopee Ongkir
[Pengurangan Wallet] Pemotongan Biaya Pembayaran
[Pengurangan Wallet] Pemotongan Biaya Administrasi Shopee Mall
[Pengurangan Wallet] Pembeli Tidak Terima Barang
[Pengurangan Wallet] Pelepasan Dana Berlebih
Compensation for Order
Kompensasi kehilangan untuk paket
Isi Ulang Saldo Iklan/Koin Penjual

In [47]:
## run 32 must null
set_shopee[set_shopee['Kategori'].isnull()][['Deskripsi','Source']].values
# set_shopee[set_shopee['Deskripsi'].str.contains('Kompensasi kehilangan untuk paket',case=False)]

array([], shape=(0, 2), dtype=object)

In [48]:
## run 32
ord_id = set_shopee[set_shopee[set_shopee.columns[:-3]].duplicated(keep = 'first')]['Order ID'].unique()
for_wms[for_wms['No. Pesanan'].isin(ord_id)].groupby(['Year', 'Month'])['No. Pesanan'].nunique()

Series([], Name: No. Pesanan, dtype: int64)

In [49]:
## run 33 must null
temp = set_shopee[set_shopee['Kategori'].isnull()]
temp['Desc Group'] = [' '.join(map(str, l)) for l in temp['Deskripsi'].str.split().str[:-1]]
# temp['Order ID'] = temp['Deskripsi'].str.split().str[-1]
temp['Desc Group'].unique()

array([], dtype=float64)

In [50]:
## run 34 must null
np.unique([' '.join(map(str, l)) for l in set_shopee[set_shopee['Kategori'].isnull()]['Deskripsi'].str.split().str[:-1]])

array([], dtype=float64)

In [51]:
## run 35
set_fee = pd.DataFrame()
folder = 'Settlement Project/Shopee/Settlement Fee/'

for i in os.listdir(folder):
    colname = pd.ExcelFile(folder + str(i)).sheet_names
    colname = [x for x in colname if 'income' in x or "Income" in x]
    for j in colname:
        temp = pd.read_excel(folder + str(i), sheet_name = j)
        if temp.columns[1] != 'No. Pesanan':
            header = temp[temp[temp.columns[1]] == 'No. Pesanan'].index[0]
            temp = pd.read_excel(folder + str(i), header = header+1, sheet_name = j)
        print(i)
        print(j)
        temp = temp.rename(columns = {'Biaya Layanan (termasuk PPN 11%)' : 'Biaya Layanan (termasuk PPN 10%)',
                                      'Biaya Administrasi (termasuk PPN 11%)':'Biaya Administrasi (termasuk PPN 10%)'})
        true_col = ['No.', 'No. Pesanan', 'No. Pengajuan', 'Username (Pembeli)', 'Waktu Pesanan Dibuat', 'Tanggal Dana Dilepaskan', 'Harga Asli Produk', 'Total Diskon Produk', 'Jumlah Pengembalian Dana ke Pembeli', 'Diskon Produk dari Shopee', 'Diskon Voucher Ditanggung Penjual', 'Cashback Koin yang Ditanggung Penjual', 'Ongkir Dibayar Pembeli', 'Diskon Ongkir Ditanggung Jasa Kirim', 'Gratis Ongkir dari Shopee', 'Ongkir yang Diteruskan oleh Shopee ke Jasa Kirim', 'Ongkos Kirim Pengembalian Barang', 'Biaya Administrasi (termasuk PPN 10%)', 'Biaya Layanan (termasuk PPN 10%)', 'Biaya Transaksi', 'Bea Masuk, PPN & PPh', 'Total Penghasilan', 'Kode Voucher', 'Kompensasi', 'Unnamed: 24', 'Promo Gratis Ongkir dari Penjual', 'Jasa Kirim', 'Nama Kurir']
        if temp.columns.to_list() == true_col:
            print('Column Sama')
        else :
            print('Column Beda')
            print([x for x in true_col if x not in temp.columns.to_list()])
            print([x for x in temp.columns.to_list() if x not in true_col])
        temp['Source'] = i
        if len(set_fee) != 0:
            temp = temp[~temp['No. Pesanan'].isin(set_fee['No. Pesanan'])]
        set_fee = set_fee.append(temp, ignore_index = True, sort = False)
    
set_fee['Shipping Fee'] = set_fee['Ongkir Dibayar Pembeli'] + set_fee['Diskon Ongkir Ditanggung Jasa Kirim'] + set_fee['Gratis Ongkir dari Shopee'] + set_fee['Ongkir yang Diteruskan oleh Shopee ke Jasa Kirim']+set_fee['Ongkos Kirim Pengembalian Barang']
set_fee['ComFee'] = set_fee['Biaya Administrasi (termasuk PPN 10%)']
set_fee['Payment Fee'] = set_fee['Biaya Layanan (termasuk PPN 10%)']

Income.sudah dilepas.20211220_20211231.xls
income
Column Sama
Income.sudah dilepas.20220101_20220131.xls
income-1
Column Sama
Income.sudah dilepas.20220101_20220131.xls
income-2
Column Sama
Income.sudah dilepas.20220101_20220131.xls
income-3
Column Sama
Income.sudah dilepas.20220201_20220224.xls
income-1
Column Sama
Income.sudah dilepas.20220201_20220224.xls
income-2
Column Sama
Income.sudah dilepas.20220201_20220224.xls
income-3
Column Sama
Income.sudah dilepas.20220224_20220225.xls
income
Column Sama
Income.sudah dilepas.20220225_20220309.xls
income-1
Column Sama
Income.sudah dilepas.20220225_20220309.xls
income-2
Column Sama
Income.sudah dilepas.20220309_20220323.xls
income-1
Column Sama
Income.sudah dilepas.20220309_20220323.xls
income-2
Column Sama
Income.sudah dilepas.20220309_20220323.xls
income-3
Column Sama
Income.sudah dilepas.20220323_20220405.xls
income-1
Column Sama
Income.sudah dilepas.20220323_20220405.xls
income-2
Column Sama
Income.sudah dilepas.20220323_20220405.xls
income-3
Column Sama
Income.sudah dilepas.20220405_20220416.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220405_20220416.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220405_20220416.xls
income-3
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220405_20220416.xls
income-4
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220416_20220427.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220416_20220427.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220427_20220512.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220427_20220512.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220427_20220512.xls
income-3
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Unnamed: 25']
Income.sudah dilepas.20220512_20220521.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220512_20220521.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220521_20220527.xls
income
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220527_20220613.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220527_20220613.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220527_20220613.xls
income-3
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220613_20220624.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220613_20220624.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220624_20220628.xls
income
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220628_20220712.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220628_20220712.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220628_20220712.xls
income-3
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220712_20220726.xls
income-1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220712_20220726.xls
income-2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220712_20220726.xls
income-3
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220726_20220826.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220726_20220826.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220726_20220826.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220726_20220826.xls
income-4
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220726_20220826.xls
income-5
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220726_20220826.xls
income-6
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220826_20220927.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220826_20220927.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220826_20220927.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220826_20220927.xls
income-4
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220826_20220927.xls
income-5
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220826_20220927.xls
income-6
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Total berat sebenarnya per pesanan', 'Unnamed: 26']
Income.sudah dilepas.20220927_20221026.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20220927_20221026.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20220927_20221026.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20220927_20221026.xls
income-4
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20221026_20221116.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20221026_20221116.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20221026_20221116.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20221026_20221116.xls
income-4
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20221116_20221129.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20221116_20221129.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 27']
Income.sudah dilepas.20221129_20230110.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20221129_20230110.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20221129_20230110.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20221129_20230110.xls
income-4
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20221129_20230110.xls
income-5
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230110_20230130.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230110_20230130.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230110_20230130.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230130_20230225.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230130_20230225.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230130_20230225.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230130_20230225.xls
income-4
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230225_20230328.xls
income-1
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230225_20230328.xls
income-2
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230225_20230328.xls
income-3
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230225_20230328.xls
income-4
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230225_20230328.xls
income-5
Column Beda
['Biaya Transaksi', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Premi', 'Biaya Kartu Kredit', 'Biaya Kampanye', 'Total berat sebenarnya per pesanan', 'Unnamed: 28']
Income.sudah dilepas.20230328_20230425.xlsx
Income - 1
Column Beda
['Jumlah Pengembalian Dana ke Pembeli', 'Total Penghasilan', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Refund Amount to Buyer (Rp)', 'Premium', 'Biaya Kampanye', 'Total Released Amount (Rp)', 'Total berat sebenarnya per pesanan']
Income.sudah dilepas.20230328_20230425.xlsx
Income - 2
Column Beda
['Jumlah Pengembalian Dana ke Pembeli', 'Total Penghasilan', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Refund Amount to Buyer (Rp)', 'Premium', 'Biaya Kampanye', 'Total Released Amount (Rp)', 'Total berat sebenarnya per pesanan']
Income.sudah dilepas.20230328_20230425.xlsx
Income - 3
Column Beda
['Jumlah Pengembalian Dana ke Pembeli', 'Total Penghasilan', 'Unnamed: 24']
['Metode pembayaran pembeli', 'Refund Amount to Buyer (Rp)', 'Premium', 'Biaya Kampanye', 'Total Released Amount (Rp)', 'Total berat sebenarnya per pesanan']
Income.sudah dilepas.20230425_20230529.xlsx
Income - 1
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kampanye']
Income.sudah dilepas.20230425_20230529.xlsx
Income - 2
Column Beda
['Unnamed: 24']
['Metode pembayaran pembeli', 'Premium', 'Biaya Kampanye']

In [52]:
## run 35.1
set_fee=set_fee.fillna(0)  ### tambahan timo May 2023

In [54]:
### run 36
# set_shopee[set_shopee['Deskripsi'] == 'Penghasilan dari Pesanan #2112241GWGSVTU'].values
set_fee['Total Produk']=set_fee['Harga Asli Produk']+set_fee['Total Diskon Produk']## 30 mei 2022 
set_fee['Total Produk']=set_fee['Harga Asli Produk']+set_fee['Total Diskon Produk']+set_fee['Diskon Voucher Ditanggung Penjual'] ## 29 Juni 2022 
set_fee['Total Produk']=set_fee['Harga Asli Produk']+set_fee['Total Diskon Produk']+set_fee['Refund Amount to Buyer (Rp)']+set_fee['Diskon Produk dari Shopee']+set_fee['Diskon Voucher Ditanggung Penjual']+set_fee['Cashback Koin yang Ditanggung Penjual'] ## May 2023

In [56]:
### run 37 must null
set_shopee = set_shopee[(set_shopee[['Deskripsi', 'Source']].duplicated()) | (~set_shopee['Deskripsi'].duplicated())]

ord_id = set_shopee[set_shopee[set_shopee.columns[:-3]].duplicated(keep = 'first')]['Order ID'].unique()
for_wms[for_wms['No. Pesanan'].isin(ord_id)].groupby(['Year', 'Month'])['No. Pesanan'].nunique()

Series([], Name: No. Pesanan, dtype: int64)

In [57]:
### run 38
set_fee = set_fee[(set_fee[['No. Pesanan', 'Source']].duplicated()) | (~set_fee['No. Pesanan'].duplicated())]

In [ ]:
set_fee[set_fee['No. Pesanan'].duplicated(keep = False)]

In [ ]:
set_shopee

In [58]:
## run 39
set_pivot = pd.pivot_table(set_shopee, index = 'Order ID', columns = 'Kategori', values = 'Jumlah Dana', aggfunc = np.sum).reset_index()

set_pivot['Order ID'] = set_pivot['Order ID'].astype(str)
set_fee['No. Pesanan'] = set_fee['No. Pesanan'].astype(str)

set_pivot = set_pivot.merge(set_fee, how = 'left', left_on = 'Order ID', right_on = 'No. Pesanan')


# set_pivot['Total Transfer'] = set_pivot['Total Transfer'].fillna(0) + set_pivot['Bi Komplain'].fillna(0) ### ganti ke yang bawah 30 Mei 2022
set_pivot['Total Transfer'] = set_pivot['Total Produk'].fillna(0) + set_pivot['Bi Komplain'].fillna(0)

In [59]:
## run 40
for_wms['Paid'] = np.nan

paid = set_pivot[set_pivot['Bi Komplain'].isnull()]['Order ID'].unique()
indeks = for_wms[for_wms['No. Pesanan'].astype(str).isin(paid)].index.to_list()
for_wms['Paid'][indeks] = 'Paid'

refund = set_pivot[set_pivot['Bi Komplain'].notnull()]['Order ID'].unique()
indeks = for_wms[for_wms['No. Pesanan'].astype(str).isin(refund)].index.to_list()
for_wms['Paid'][indeks] = 'Refund'

for_wms['Paid'] = for_wms['Paid'].fillna('Unpaid')

set_pivot['Total Produk'] = set_pivot['Total Transfer']

bundling = for_wms[for_wms['Bundle Name'].notnull()]
real_trx = for_wms[for_wms['Bundle Name'].isnull()]

real_trx['No. Pesanan'] = real_trx['No. Pesanan'].astype(str)
set_pivot['Order ID'] = set_pivot['Order ID'].astype(str)

real_trx = real_trx.merge(set_pivot[['Order ID', 'Total Produk', 'ComFee', 'Shipping Fee', 'Payment Fee']], how = 'left', left_on = 'No. Pesanan', right_on = 'Order ID')

non_prop = real_trx[real_trx['Brand'].isin(['Bonus Produk', 'Gimmick'])]
real_trx = real_trx[~real_trx['Brand'].isin(['Bonus Produk', 'Gimmick'])]

real_trx['Total Produk Prop'] = real_trx['Total Produk'].fillna(0) * real_trx['Total Net Before PPN']/real_trx.groupby(['No. Pesanan'])['Total Net Before PPN'].transform('sum')
# real_trx['Fullfee Prop'] = real_trx['Fullfee'].fillna(0) * real_trx['Qty. Invoiced']/real_trx.groupby(['No. Pesanan'])['Qty. Invoiced'].transform('sum')
real_trx['Comfee Prop'] = real_trx['ComFee'].fillna(0) * real_trx['Total Net Before PPN']/real_trx.groupby(['No. Pesanan'])['Total Net Before PPN'].transform('sum')
real_trx['Payment Fee Prop'] = real_trx['Payment Fee'].fillna(0) * real_trx['Total Net Before PPN']/real_trx.groupby(['No. Pesanan'])['Total Net Before PPN'].transform('sum')
real_trx['Shipping Fee'] = real_trx['Shipping Fee'].fillna(0) * real_trx['Qty. Invoiced']/real_trx.groupby(['No. Pesanan'])['Qty. Invoiced'].transform('sum')

non_prop['Total Produk Prop'] = 0
# non_prop['Fullfee Prop'] = 0
non_prop['Comfee Prop'] = 0

real_trx = real_trx.append(non_prop, ignore_index = True, sort = False)

bundling['No. Pesanan'] = bundling['No. Pesanan'].astype(str)

bundling = bundling.merge(real_trx[['No. Pesanan', 'Product Name', 'Total Produk Prop', 'Comfee Prop', 'Shipping Fee', 'Payment Fee Prop']].drop_duplicates(['No. Pesanan', 'Product Name']), how = 'left', left_on = ['No. Pesanan', 'Bundle Name'], right_on = ['No. Pesanan', 'Product Name'])

non_prop = bundling[bundling['Brand'].isin(['Bonus Produk', 'Gimmick'])]
bundling = bundling[~bundling['Brand'].isin(['Bonus Produk', 'Gimmick'])]

bundling['Total Produk Prop'] = bundling['Total Produk Prop'].fillna(0) * bundling['Total Net Before PPN']/bundling.groupby(['No. Pesanan', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
# bundling['Fullfee Prop'] = bundling['Fullfee Prop'].fillna(0) * bundling['Qty. Invoiced']/bundling.groupby(['No. Pesanan', 'Bundle Name'])['Qty. Invoiced'].transform('sum')
bundling['Comfee Prop'] = bundling['Comfee Prop'].fillna(0) * bundling['Total Net Before PPN']/bundling.groupby(['No. Pesanan', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundling['Payment Fee Prop'] = bundling['Payment Fee Prop'].fillna(0) * bundling['Total Net Before PPN']/bundling.groupby(['No. Pesanan', 'Bundle Name'])['Total Net Before PPN'].transform('sum')
bundling['Shipping Fee'] = bundling['Shipping Fee'].fillna(0) * bundling['Qty. Invoiced']/bundling.groupby(['No. Pesanan', 'Bundle Name'])['Qty. Invoiced'].transform('sum')

non_prop['Total Produk Prop'] = 0
# non_prop['Fullfee Prop'] = 0
non_prop['Comfee Prop'] = 0
non_prop['Payment Fee Prop'] = 0
non_prop['Shipping Fee'] = 0

bundling = bundling.append(non_prop, ignore_index = True, sort = False)

# real_trx = real_trx.drop(['SKU_y', 'Real SKU_y', 'SKU_y'], axis = 1)
# real_trx = real_trx.rename(columns = {'SKU_x' : 'SKU'})

# bundling = bundling.drop(['SKU_y', 'Real SKU_y', 'SKU_y', 'Product Name_y'], axis = 1)
# bundling = bundling.rename(columns = {'SKU_x' : 'SKU', 'Product Name_x' : 'Product Name'})

total_trx = real_trx.append(bundling, ignore_index = True, sort = False)

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [60]:
### run 41
total_trx = real_trx.append(bundling, ignore_index = True, sort = False)

In [61]:
### run 42
tambah_unpaid = pd.read_excel(r'Settlement Project/unpaid order to Andra.xlsx', sheet_name = 'Unpaid to cancel or not found')
tambah_unpaid2 = pd.read_excel(r'Settlement Project/Unpaid Mar.xlsx', sheet_name = 'Shopee')

tambah_unpaid = tambah_unpaid.append(tambah_unpaid2, ignore_index = True, sort = False)
tambah_unpaid['No. Pesanan'] = tambah_unpaid['No. Pesanan'].astype(str)
indeks = total_trx[(total_trx['No. Pesanan'].isin(tambah_unpaid['No. Pesanan'])) & 
                  (total_trx['Paid'] == 'Unpaid')].index.to_list()
print(len(indeks))
total_trx['Status Pesanan'][indeks] = 'Cancel'
total_trx['Paid'][indeks] = 'Cancel'

rumus_status = pd.read_excel(r'Settlement Project/Rumus Status.xlsx', sheet_name = 'Shopee')
if len(rumus_status != 0):
    for i in range(len(rumus_status)):
        stat = rumus_status['Status Pesanan'][i]
        indeks = total_trx[(total_trx['Paid'] == 'Unpaid') &
                             (total_trx['Status Pesanan'].str.lower() == stat.lower())].index.to_list()
        total_trx['Status Pesanan'][indeks] = 'Cancel'
        total_trx['Paid'][indeks] = 'Cancel'

0

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [62]:
## run 43
total_trx['Product Name'] = total_trx['Product Name'].fillna(total_trx['Product Name_x'])

total_trx = total_trx.drop(['Product Name_x', 'Product Name_y'], axis = 1)

In [63]:
## run 44
total_trx['Total Net Before PPN'] = total_trx['Total Net']/1.11

In [64]:
## run 45
total_trx['Total Produk Prop Adj'] = total_trx['Total Produk Prop']/1.11
total_trx['BTL Cost'] = (total_trx['Total Produk Prop Adj']) - total_trx['Total Net Before PPN']

In [65]:
## run 46
total_trx['Total Selcen'] = total_trx['Total Pembayaran']

In [66]:
## run 47 ganti nama bulan/folder
total_trx.to_csv(r'Settlement Project\Backup\Realisasi May 2023\Final Result\Before Compare/Shopee May 2023.csv',sep=';',index=False)

In [67]:
### run 48
import pandas as pd

# total_trx = pd.read_csv('Settlement Project\Backup\Realisasi Apr 2023\Final Result\Before Compare/Shopee Apr 2023 rev 2.csv', sep = ';')
# total_trx['Total Produk Prop Adj'] = total_trx['Total Produk Prop']/1.11
# total_trx['BTL Cost'] = (total_trx['Total Produk Prop Adj']) - total_trx['Total Net Before PPN']

total_trx_full = total_trx.rename(columns = {'Total Produk Prop' : 'Total Produk Prop', 
                                                   'Total Net' : 'Total Net', 
                                                   'Fullfee Prop' : 'Fullfee Prop', 
                                                   'Comfee Prop' : 'Comfee Prop'})
# total_trx_full = total_trx.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
#                                                    'Total Net by Selcen' : 'Total Net', 
#                                                    'Fullfee Prop by Selcen' : 'Fullfee Prop', 
#                                                    'Comfee Prop by Selcen' : 'Comfee Prop'})


# total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
#        'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
#        'Delta Comfee Prop'], axis = 1)

total_trx_full['No. Pesanan'] = total_trx_full['No. Pesanan'].astype(str)

source = pd.read_csv(r"D:\6. settlement\Code\Settlement Project\Backup\Realisasi Apr 2023\Final Result\Raw Unpivoted\CSV\Runningan Shopee By Selcen Jan 2022 - Apr 2023 rev2.csv", sep = ';')
# source = source.rename(columns = {'Paid' : 'Paid March'})


# source['True datetime'] = pd.to_datetime(source['True datetime'])
# source = source[(source['Year'] > 2021) & (source['True datetime']<'2022-02-01')]

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

source['Order #'] = source['No. Pesanan'].astype(str)

total_trx_merge = total_trx_full.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid April','Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Paid April', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name','Paid April', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid April'][total_trx_null.index] = total_trx_null['Paid April']

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Paid April','Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Paid April','Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid April'][total_trx_null.index] = total_trx_null['Paid April']

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

source2 = source.copy()

source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# source2['Real SKU'][indeks] = '(U)2101809250'

# indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# source2['Real SKU'][indeks] = '2101941250P4'

# indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# source2['Real SKU'][indeks] = '2101809250P4'

total_trx_null = total_trx_null.drop(['Order #', 'Paid April','Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source2[['Order #', 'Real SKU', 'Bundle Name', 'Paid April','Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid April'][total_trx_null.index] = total_trx_null['Paid April']

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (3,4,6,7,8,9,11,12,13,14,15,16,19,22,46,56,57,61,62,68,69,75,76,82,83,89,90,96,97,103,115,117,120,121,122,124,135) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [82]:
total_trx_merge[(total_trx_merge['Total Net_y'].isnull()) & (total_trx_merge['No. Pesanan'].isin(source['Order #']))][['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']].drop_duplicates(['Real Nama Produk', 'Bundle Name'])

Empty DataFrame
Columns: [No. Pesanan, Real SKU, Real Nama Produk, Bundle Name, Qty. Invoiced]
Index: []

In [68]:
### run 49
import numpy as np
total_trx_merge['Paid Beda'] = np.nan

indeks = total_trx_merge[total_trx_merge['Paid'] != total_trx_merge['Paid April']].index.to_list()
total_trx_merge['Paid Beda'][indeks] = 'Beda'

total_trx_merge['Paid Beda'] = total_trx_merge['Paid Beda'].fillna('Sama')
# total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'][['Order #','Brand','Real SKU','Month', 'Paid_x', 'Paid_y', 'Paid Beda']]
total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'].groupby(['Year','Month', 'Paid', 'Paid April'], dropna  = False)['No. Pesanan'].nunique()

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Year  Month  Paid    Paid April
2023  April  Cancel  NaN             470
             Paid    Unpaid         1630
                     NaN            3011
             Unpaid  NaN               3
      May    Cancel  NaN            1967
             Paid    NaN           12265
             Unpaid  NaN            1230
Name: No. Pesanan, dtype: int64

In [69]:
## run 50
total_trx_merge = total_trx_merge.rename(columns = {'Paid' : 'Paid May'})

In [70]:
# total_trx_merge[(total_trx_merge['Paid January']=='Cancel')&
#                 (total_trx_merge['Paid']=='Paid')][['No. Pesanan']]#.unique()#[total_trx_merge['No. Pesanan']=='2205230ABVF4VX'][['Real SKU','Qty. Invoiced','Outbound Qty']]#[(total_trx_merge['Paid June'] == 'Paid') & (total_trx_merge['Paid']== 'Refund')]['No. Pesanan'].unique()
# total_trx[total_trx['No. Pesanan']=='220911GXJHCW0U']#['Paid']
total_trx_merge[(total_trx_merge['Year']>2022)&
                (total_trx_merge['Brand']!='Bundle')&
                (total_trx_merge['Paid April']=='Paid')].groupby(['Month'])[['Total Net Before PPN','Total Produk','Total Produk Prop Adj','BTL Cost','Payment Fee Prop']].sum().reset_index()

,Month,Total Net Before PPN,Total Produk,Total Produk Prop Adj,BTL Cost,Payment Fee Prop
0,April,1.832840e+09,2.314734e+09,1.580682e+09,-2.521575e+08,-3.158091e+07
1,February,2.365631e+09,2.680244e+09,2.039375e+09,-3.262560e+08,-4.073526e+07
2,January,2.932374e+09,3.313198e+09,2.438396e+09,-4.939779e+08,-4.870133e+07
3,March,3.273971e+09,4.018850e+09,2.945802e+09,-3.281689e+08,-1.083382e+08

In [71]:
## run 51
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_merge = total_trx_merge.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_merge['No. Pesanan'] = total_trx_merge['No. Pesanan'].astype(str)

In [72]:
## run 52
# finres=pd.read_excel("Settlement Project\Backup\Realisasi April 2022\Final Result\Ke Mbak May\Runningan Shopee Jan 2021 - Apr 2022 by Selcen Rev 1.xlsx",sheet_name='Runningan Shopee')
finres=pd.read_csv("Settlement Project\Backup\Realisasi April 2022\Final Result\Raw Unpivoted\CSV\Runningan Shopee By Selcen Jan 2022 - Apr 2022 Rev 1.csv", sep = ';')

C:\Users\timotius.giovandi\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3170: DtypeWarning: Columns (3,13,19,22,46,56,61,67,68,74,75,81,82,88,95,96,114,116,120,121,123,134,136) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [73]:
## run 53
finres['Pemilik Budget']=np.nan
colfin=finres.head(0).rename(columns={'Paid April':'Paid May','Paid March':'Paid April'})

In [74]:
### run 54
# finres2=colfin.head(0).append(total_trx_merge)
finres2=total_trx_merge[[x for x in total_trx_merge.columns if x in colfin.columns]]

In [75]:
### run 55
finres2.to_csv(r'Settlement Project\Backup\Realisasi May 2023\Final Result\Raw Unpivoted\CSV/Runningan Shopee By Selcen Jan 2022 - May 2023.csv', sep = ';', index = False)

In [76]:
### run 56
finres2[finres2['Year']>2022].to_excel(r'Settlement Project\Backup\Realisasi May 2023\Final Result\Raw Unpivoted\Excel/Runningan Shopee By Selcen Jan 2022 - May 2023.xlsx', index = False)

In [ ]:
### selesai yayyy ###

In [ ]:
source['Order #'].nunique()

In [ ]:
len(total_trx)

In [ ]:
len(selcen_sku)

In [ ]:
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_merge = total_trx_merge.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_merge['No. Pesanan'] = total_trx_merge['No. Pesanan'].astype(str)

total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Realisasi April 2022/Final Result/Runningan Shopee By Selcen Jan 2022 - Apr 2022.csv', sep = ';', index = False)

In [ ]:
temp = set_shopee.copy()
temp['Desc Group'] = [' '.join(map(str, l)) for l in temp['Deskripsi'].str.split().str[:-1]]
# temp['Order ID'] = temp['Deskripsi'].str.split().str[-1]
temp = temp[temp['Desc Group'].isin(['Penambahan Wallet] Shopee Ongkir',
'[Pengurangan Wallet] Pembeli Tidak Terima Barang',
'[Pengurangan Wallet] Pemotongan Biaya Administrasi Shopee Mall',
'[Pengurangan Wallet] Pemotongan Biaya Pembayaran'])]
temp

In [ ]:
total_trx_merge['Kategori Terlewat'] = np.nan
indeks = total_trx_merge[total_trx_merge['No. Pesanan'].isin(temp['Order ID'])].index.to_list()
len(indeks)
total_trx_merge['Kategori Terlewat'][indeks] = 'Ya'

In [ ]:
len(indeks)

In [ ]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Realisasi April 2022/Final Result/Runningan Shopee By Selcen Jan 2022 - Apr 2022 Rev 1.csv', sep = ';', index = False)

In [ ]:
# total_trx_merge = total_trx.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

# total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
#                                                   'Total Produk Prop_x' : 'Total Produk Prop',
#                                                   'Comfee Prop_x' : 'Comfee Prop'})

# total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
# total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

# total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
#                                                   'Total Produk Prop_x' : 'Total Produk Prop',
#                                                   'Comfee Prop_x' : 'Comfee Prop'})

# total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
# total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

# total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

# source2 = source.copy()

# source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# # indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# # source2['Real SKU'][indeks] = '(U)2101809250'

# # indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# # source2['Real SKU'][indeks] = '2101941250P4'

# # indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# # source2['Real SKU'][indeks] = '2101809250P4'

# total_trx_null = total_trx_null.drop(['Order #', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
# total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
#                                                   'Total Produk Prop_x' : 'Total Produk Prop',
#                                                   'Comfee Prop_x' : 'Comfee Prop'})

# total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
# total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
# total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
# total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']

In [ ]:
total_trx_merge[total_trx_merge['No. Pesanan'] == '220124N55HCVX6']

In [ ]:
total_trx_merge[(total_trx_merge['Total Net_y'].isnull()) & (total_trx_merge['No. Pesanan'].isin(source['Order #']))]

In [ ]:
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

In [ ]:
total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

In [ ]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Shopee Testing by Selcen Compare v3.csv', sep = ';', index = False)

In [ ]:
total_trx_merge[total_trx_merge['No. Pesanan'] == '2201173UQ6VKJ9'][['Real Nama Produk', 'Qty. Invoiced','Bundle Name','Comfee Prop by Selcen']]

In [ ]:
source[source['Order #'] == '2201173UQ6VKJ9'][['Real Nama Produk', 'Qty. Invoiced','Bundle Name','Comfee Prop']]

In [ ]:
set_fee[set_fee['No. Pesanan'] == '2201173UQ6VKJ9']

In [ ]:
set_shopee[set_shopee['Order ID'] == '220103TEWRMWRF']

In [ ]:
set_fee

In [ ]:
import pandas as pd

data = pd.read_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Shopee Testing by Selcen Compare.csv', sep = ';')

In [ ]:
data[(data[['No. Pesanan', 'Real Nama Produk']].duplicated(keep = False)) & (data['Pesanan yang Dikelola Shopee'] == 'No')
    & (data['Status Pesanan'] != 'Batal') &
    (data['Month'] == 'January')][['No. Pesanan', 'Status Pesanan', 'Real Nama Produk', 'Bundle Name']].drop_duplicates(['Real Nama Produk', 'Bundle Name'])

In [ ]:
data[data['No. Pesanan'] == '220101MWHHYATQ'][['No. Pesanan', 'Status Pesanan', 'Real Nama Produk', 'Bundle Name']]

In [ ]:
import pandas as pd

total_trx = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Shopee Testing by Selcen Compare v3.csv", sep = ';')

total_trx_full = total_trx.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
       'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
       'Delta Comfee Prop'], axis = 1)

total_trx_full['No. Pesanan'] = total_trx_full['No. Pesanan'].astype(str)

source = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Realisasi Februari 2022\Final Result\Runningan Shopee Jan 2021 - Feb 2022.csv", sep = ';')

source['True datetime'] = pd.to_datetime(source['True datetime'])
# source = source[(source['Year'] > 2021) & (source['True datetime']<'2022-02-01')]

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

total_trx_merge = total_trx_full.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid February','Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Paid February', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name','Paid February', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Paid February','Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Paid February','Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

source2 = source.copy()

source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# source2['Real SKU'][indeks] = '(U)2101809250'

# indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# source2['Real SKU'][indeks] = '2101941250P4'

# indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# source2['Real SKU'][indeks] = '2101809250P4'

total_trx_null = total_trx_null.drop(['Order #', 'Paid February','Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source2[['Order #', 'Real SKU', 'Bundle Name', 'Paid February','Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']

In [ ]:
total_trx_merge[(total_trx_merge['Total Net_y'].isnull()) & (total_trx_merge['No. Pesanan'].isin(source['Order #']))][['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']].drop_duplicates(['Real Nama Produk', 'Bundle Name'])

In [ ]:
total_trx_merge[total_trx_merge['No. Pesanan'] == '22013053052MRP'][['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced', 'Paid', 'Paid February']]

In [ ]:
source2[source2['Order #'] == '22013053052MRP'][['Order #', 'Real SKU', 'Real Nama Produk', 'Product Name','Bundle Name', 'Qty. Invoiced']]

In [ ]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Shopee Testing by Selcen Compare vPaid.csv', sep = ';', index = False)

In [ ]:
import pandas as pd

# total_trx = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Realisasi Maret 2022\Final Result\Runningan Shopee By Selcen Jan 2022 - Mar 2022 Rev 3 Drop Dups Order Repair PL.csv", sep = ';')

total_trx = temp2.copy()
total_trx_full = total_trx.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


# total_trx_full = total_trx_full.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
#        'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
#        'Delta Comfee Prop'], axis = 1)

total_trx_full = total_trx_full.drop(['Paid February', 'Paid Beda'], axis = 1)

total_trx_full['No. Pesanan'] = total_trx_full['No. Pesanan'].astype(str)

source = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Realisasi Februari 2022\Final Result\Runningan Shopee Jan 2021 - Feb 2022.csv", sep = ';')
source = source.rename(columns = {'Paid' : 'Paid February'})


source['True datetime'] = pd.to_datetime(source['True datetime'])
# source = source[(source['Year'] > 2021) & (source['True datetime']<'2022-02-01')]

source['Product Name'] = source['Product Name'].fillna(source['Real Nama Produk'])

total_trx_merge = total_trx_full.merge(source[['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Paid Beda', 'Paid February','Qty. Invoiced', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced']), how = 'left', left_on = ['No. Pesanan', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'], right_on = ['Order #', 'Real SKU', 'Real Nama Produk', 'Bundle Name', 'Qty. Invoiced'])

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Paid February', 'Paid Beda', 'Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Product Name', 'Bundle Name','Paid Beda', 'Paid February', 'Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Product Name', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Product Name',  'Bundle Name'], right_on = ['Order #', 'Product Name', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']
total_trx_merge['Paid Beda'][total_trx_null.index] = total_trx_null['Paid Beda']

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

total_trx_null = total_trx_null.drop(['Order #', 'Paid February','Paid Beda','Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net',
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source[['Order #', 'Real SKU', 'Bundle Name', 'Paid Beda','Paid February','Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']
total_trx_merge['Paid Beda'][total_trx_null.index] = total_trx_null['Paid Beda']

total_trx_null = total_trx_merge[total_trx_merge['Total Net_y'].isnull()]

source2 = source.copy()

source2['Real SKU'] = source2['Real SKU'].astype(str).str.replace('2309005305', '2309005300')

# indeks = source2[source2['Real SKU'] == '(B)2101809250'].index.to_list()
# source2['Real SKU'][indeks] = '(U)2101809250'

# indeks = source2[source2['Real SKU'] == 'PH48(3)B35'].index.to_list()
# source2['Real SKU'][indeks] = '2101941250P4'

# indeks = source2[source2['Real SKU'] == 'PH39(3)B17'].index.to_list()
# source2['Real SKU'][indeks] = '2101809250P4'

total_trx_null = total_trx_null.drop(['Order #', 'Paid Beda','Paid February','Total Net_y', 'Total Produk Prop_y', 'Comfee Prop_y'], axis = 1)
total_trx_null = total_trx_null.rename(columns = {'Total Net_x' : 'Total Net', 
                                                  'Total Produk Prop_x' : 'Total Produk Prop',
                                                  'Comfee Prop_x' : 'Comfee Prop'})

total_trx_null = total_trx_null.merge(source2[['Order #', 'Real SKU', 'Bundle Name', 'Paid February','Paid Beda','Total Net', 'Total Produk Prop', 'Comfee Prop']].drop_duplicates(['Order #', 'Real SKU', 'Bundle Name']), how = 'left', left_on = ['No. Pesanan', 'Real SKU',  'Bundle Name'], right_on = ['Order #', 'Real SKU', 'Bundle Name']).set_index(total_trx_null.index) 
total_trx_merge['Total Net_y'][total_trx_null.index] = total_trx_null['Total Net_y']
total_trx_merge['Total Produk Prop_y'][total_trx_null.index] = total_trx_null['Total Produk Prop_y']
total_trx_merge['Comfee Prop_y'][total_trx_null.index] = total_trx_null['Comfee Prop_y']
total_trx_merge['Paid February'][total_trx_null.index] = total_trx_null['Paid February']
total_trx_merge['Paid Beda'][total_trx_null.index] = total_trx_null['Paid Beda']

In [ ]:
total_trx_merge['Paid Beda'] = np.nan

indeks = total_trx_merge[total_trx_merge['Paid'] != total_trx_merge['Paid January']].index.to_list()
total_trx_merge['Paid Beda'][indeks] = 'Beda'

total_trx_merge['Paid Beda'] = total_trx_merge['Paid Beda'].fillna('Sama')
# total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'][['Order #','Brand','Real SKU','Month', 'Paid_x', 'Paid_y', 'Paid Beda']]
total_trx_merge[total_trx_merge['Paid Beda'] == 'Beda'].groupby(['Month', 'Paid', 'Paid January'], dropna  = False)['No. Pesanan'].nunique()

In [ ]:
total_trx_merge = total_trx_merge.rename(columns = {'Paid' : 'Paid February'})

In [ ]:
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop_x' : 'Total Produk Prop by Selcen', 
                                                   'Total Produk Prop_y' : 'Total Produk Prop Real Jan',
                                                   'Total Net_x' : 'Total Net by Selcen', 
                                                   'Total Net_y' : 'Total Net Real Jan',
                                                   'Fullfee Prop_x' : 'Fullfee Prop by Selcen', 
                                                   'Fullfee Prop_y' : 'Fullfee Prop Real Jan',
                                                   'Comfee Prop_x' : 'Comfee Prop by Selcen', 
                                                   'Comfee Prop_y' : 'Comfee Prop Real Jan'})

total_trx_merge['Delta Total Net'] = total_trx_merge['Total Net by Selcen'] - total_trx_merge['Total Net Real Jan']
total_trx_merge['Delta Total Produk Prop'] = total_trx_merge['Total Produk Prop by Selcen'] - total_trx_merge['Total Produk Prop Real Jan']
total_trx_merge['Delta Comfee Prop'] = total_trx_merge['Comfee Prop by Selcen'] - total_trx_merge['Comfee Prop Real Jan']

In [ ]:
total_trx_merge = total_trx_merge.rename(columns = {'Total Produk Prop by Selcen': 'Total Produk Prop', 
                                                   'Total Net by Selcen' : 'Total Net', 
                                                   'Fullfee Prop by Selcen' : 'Fullfee Prop', 
                                                   'Comfee Prop by Selcen' : 'Comfee Prop'})


# total_trx_merge = total_trx_merge.drop(['Order #', 'Total Net Real Jan', 'Total Produk Prop Real Jan',
#        'Comfee Prop Real Jan', 'Delta Total Net', 'Delta Total Produk Prop',
#        'Delta Comfee Prop'], axis = 1)

total_trx_merge['No. Pesanan'] = total_trx_merge['No. Pesanan'].astype(str)

In [ ]:
total_trx_merge.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Shopee Testing by Selcen Compare vPaid Beda.csv', sep = ';', index = False)

# Compare Realisasi Beda Feb

In [ ]:
import pandas as pd
import os
import numpy as np

selcen = pd.DataFrame()
folder = 'Settlement Project/Shopee/Seller Center/'

for i in os.listdir(folder):
    if r'$' not in i:
        temp = pd.read_excel(folder + str(i))
        temp['Source'] = i
        selcen = selcen.append(temp, ignore_index = True, sort = False)
        print(i)

selcen

In [ ]:
temp = selcen_new.groupby(['No. Pesanan', 'SKU', 'Nama Produk'], dropna = False)['Source'].nunique().gt(1).reset_index()
temp = temp[temp['Source'] == True]
selcen_new[selcen_new['No. Pesanan'].isin(temp['No. Pesanan'])][['No. Pesanan', 'SKU', 'Nama Produk', 'Qty. Invoiced', 'Source']].sort_values('No. Pesanan')

In [ ]:
selcen_new[(selcen_new[['No. Pesanan', 'SKU', 'Nama Produk']].duplicated(keep = False))][['No. Pesanan', 'SKU', 'Nama Produk', 'Qty. Invoiced', 'Source']]

In [ ]:
selcen_new[selcen_new['No. Pesanan'] == '220213CADHW4H0'][['No. Pesanan', 'SKU', 'Nama Produk', 'Qty. Invoiced', 'Source']]

In [ ]:
total_trx = pd.read_csv("D:\Backup\Backup 26 Mei\Settlement Project Backup\Realisasi Maret 2022\Final Result\Runningan Shopee By Selcen Jan 2022 - Mar 2022 No Dups Rev 1.csv", sep = ';')

In [ ]:
total_trx['Duplicated'] = np.nan
indeks = total_trx[total_trx['No. Pesanan'].isin(temp['No. Pesanan'])].index.to_list()

total_trx['Duplicated'][indeks] = 'Duplicated'

In [ ]:
total_trx[total_trx['No. Pesanan'].isin(temp['No. Pesanan'])]

In [ ]:
total_trx_merge['PL Selcen'] = total_trx_merge['Total Net by Selcen']/total_trx_merge['Qty. Invoiced']
total_trx_merge['PL Master'] = total_trx_merge['Total Net Real Jan']/total_trx_merge['Qty. Invoiced']
total_trx_merge['Delta PL'] =  total_trx_merge['PL Selcen'] - total_trx_merge['PL Master']

In [ ]:
temp2 = total_trx_merge[(total_trx_merge['Delta PL'].fillna(0) != 0) &
               (total_trx_merge['Brand'] != 'Bundle')].sort_values('Delta PL')[['No. Pesanan', 'SKU', 'Product Name', 'Qty. Invoiced', 'Source', 'PL Selcen', 'PL Master', 'Delta PL']].drop_duplicates('SKU')

In [ ]:
temp2['Percentage'] = temp2['Delta PL']/temp2['PL Selcen']
temp2.sort_values('Percentage')

In [ ]:
data_SKU[data_SKU['Real SKU'] == '2104115163']

In [ ]:
selcen_sku[selcen_sku['No. Pesanan'] == '220127VHFVJKS1'][['No. Pesanan', 'Product Name', 'Real SKU', 'Total Net', 'Qty. Invoiced']].drop_duplicates()

In [ ]:
total_trx.to_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Realisasi Maret 2022/Final Result/Runningan Shopee By Selcen Jan 2022 - Mar 2022 No Dups Rev 2 Add Duplicate Columns.csv', sep = ';', index = False)

In [ ]:
total_trx = pd.read_csv(r'D:\Backup\Backup 26 Mei\Settlement Project Backup/Realisasi Maret 2022/Final Result/Runningan Shopee By Selcen Jan 2022 - Mar 2022 No Dups Rev 2 Add Duplicate Columns.csv', sep = ';')

In [ ]:
temp2 = total_trx.copy()

list_alias = []
list_alias_name = []
for colname in data_SKU.columns:
    if 'Alias SKU' in colname:
        list_alias.append(colname)
    if 'Alias Nama' in colname:
        list_alias_name.append(colname)


for i in indeks:
    for j in list_alias:
        if str(temp2['SKU'][i]) in data_SKU[j].astype(str).values:
            idx = data_SKU[str(temp2['SKU'][i]) == data_SKU[j].astype(str)].index.to_list()
            for k in idx:
                if str(temp2['Product Name'][i]) == data_SKU[j.replace('SKU', 'Nama')][k]:
                    temp2['SKU'][i] = data_SKU['SKU'][k]

indeks = temp2[~temp2['SKU'].astype(str).isin(data_SKU['SKU'].astype(str))].index.to_list()

for i in indeks:
    for j in list_alias_name:
        if str(temp2['Product Name'][i]).lower() in data_SKU[j].astype(str).str.lower().values:
            temp2['SKU'][i] = data_SKU['SKU'].loc[str(temp2['Product Name'][i]).lower() == data_SKU[j].astype(str).str.lower()].values[0]

indeks = temp2[~temp2['SKU'].astype(str).isin(data_SKU['SKU'].astype(str))].index.to_list()

for i in indeks:
    if str(temp2['Product Name'][i]).lower() in data_SKU['Nama Produk'].astype(str).str.lower().values:
        temp2['SKU'][i] = data_SKU['SKU'].loc[str(temp2['Product Name'][i]).lower() == data_SKU['Nama Produk'].astype(str).str.lower()].values[0]


temp2 = temp2.drop(['Price List NFI', 'Total Net', 'Total Net Before PPN', 'Harga Cost'], axis = 1)
data_SKU['Price List NFI'] = data_SKU['Price List NFI'].astype(float).astype('int64')

data_SKU['Real SKU'] = data_SKU['SKU'].astype(str)
data_SKU['Real Nama Produk'] = data_SKU['Nama Produk'].astype(str)
    
list_col = ['Real SKU', 'Price List NFI', 'Harga Cost']

temp_merge = temp2.merge(data_SKU[list_col].drop_duplicates(['Real SKU']), how = 'left', left_on = 'SKU', right_on = 'Real SKU').set_index(temp2.index)
for i in list_col:
    if i == 'Real SKU':
        temp2[i] = temp_merge[str(i) + '_y']
    else :
        temp2[i] = temp_merge[str(i)]
    
temp2['Price List NFI'] = pd.to_numeric(temp2['Price List NFI']).astype(int)
temp2['Harga Cost'] = pd.to_numeric(temp2['Harga Cost']).astype(int)
temp2['Qty. Invoiced'] = pd.to_numeric(temp2['Qty. Invoiced']).astype(int)

temp2['Total Net'] = temp2['Price List NFI'] * temp2['Qty. Invoiced']
temp2['Total Harga Cost'] = temp2['Harga Cost'] * temp2['Qty. Invoiced']
temp2['Total Net Before PPN'] = temp2['Total Net']/1.11

In [ ]:
total_trx = temp2.copy()

In [ ]:
total_trx[total_trx['Duplicated'].notnull()][['No. Pesanan', 'Paid March','Total Net', 'Total Net Before PPN', 'Total Produk Prop', 'Total Produk Prop Adj', 'BTL Cost', 'Duplicated']]

In [ ]:
72150/1.11